force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/DependentLicense__c.field-meta.xml
<CustomField>
    <fullName>DependentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <inlineHelpText>The dependent license will be brought over from the application. Changes can be manually made here. This field is set with the Entity/Principal checkbox in the associated licenses section.</inlineHelpText>
    <label>Dependent License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>DependentLicenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV082219 - Created for PVL phase 1</description>
    <inlineHelpText>This denotes the Joint Venture.</inlineHelpText>
    <label>Parent</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Licenses (Parent)</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedListTreeViewerControllerTest.cls
@isTest
public with sharing class RelatedListTreeViewerControllerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createLicense();
    }
    public static testMethod void testGetChild1ObjectNameForNewRecord() {
        License__c record = [Select Id, DependentLicense__c from License__c where DependentLicense__c != null limit 1];
        RelatedListTreeViewerController.getChild1ObjectNameForNewRecord(record.DependentLicense__c, 'DependentLicenses__r');

    }
    public static testMethod void testGetData() {
        License__c record = [Select Id, DependentLicense__c from License__c where DependentLicense__c != null limit 1];
        RelatedListTreeViewerController.getData(record.DependentLicense__c, 'DependentLicenses__r', 'Licenses__r', 'Name', '', '', 10, 'Name', '');

    }
    public static testMethod void testGetChild1Columns(){
        License__c record = [Select Id, DependentLicense__c from License__c where DependentLicense__c != null limit 1];
        RelatedListTreeViewerController.getChild1Columns(record.DependentLicense__c, 'DependentLicenses__r', 'Licenses__r', 'Name', 'DependentLicense__c');
    }

    @IsTest
    static void testGetIdObjectName(){
        License__c record = [Select Id, DependentLicense__c from License__c where DependentLicense__c != null limit 1];
        RelatedListTreeViewerController.getIdObjectName(record.Id);
    }
}