force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <description>PacPoint-MV102119 - Created for PVL phase 1 to be able to search the License Records based on FEIN</description>
    <inlineHelpText>The Federal Employer Identification Number for entities.</inlineHelpText>
    <label>FEIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountRecordsSearchCreateTest.cls
@isTest
public with sharing class AccountRecordsSearchCreateTest {
    public static testMethod void testSearchAccountByBPID() {
        Account businessAcc = TestDataFactory.createBusinessAccount();
        insert businessAcc;
        AccountRecordsSearchCreate.searchAccountByBPID(null, 'Business Account', businessAcc.Name, businessAcc.FEIN__c);

    }
    public static testMethod void testLoadAccount() {
        Account businessAcc = TestDataFactory.createBusinessAccount();
        insert businessAcc;
        AccountRecordsSearchCreate.loadAccount(businessAcc.Id, 'PVL Business Account Layout');
    }
    public static testMethod void testGetFieldSet() {
        AccountRecordsSearchCreate.getFieldSet('WizardMatchingRecords', 'License__c');
    }
    public static testMethod void testCreateAccount() {
        Account businessAcc = TestDataFactory.createBusinessAccount();
        AccountRecordsSearchCreate.createAccount(JSON.serialize(businessAcc), 'BusinessAccount');
    }
}