force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint KN080819 - Created for PVL</description>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <description>PacPoint-MV102119 - Created for PVL phase 1 to be able to search the License Records based on FEIN</description>
    <inlineHelpText>The Federal Employer Identification Number for entities.</inlineHelpText>
    <label>FEIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LastTaxClearanceDate__c.field-meta.xml
<CustomField>
    <fullName>LastTaxClearanceDate__c</fullName>
    <description>PacPoint-KN02132020-Created for PVL Phase 1 Sprint 3</description>
    <inlineHelpText>The date of the most recent tax clearance.</inlineHelpText>
    <label>Last Tax Clearance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LastTaxClearanceStatus__c.field-meta.xml
<CustomField>
    <fullName>LastTaxClearanceStatus__c</fullName>
    <inlineHelpText>The most recent tax clearance status obtained from the Hawaii Department of Taxation API.</inlineHelpText>
    <label>Last Tax Clearance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved / Compliant</fullName>
            </value>
            <value>
                <fullName>Approved / Compliant. Entity name does not match DOTAX</fullName>
            </value>
            <value>
                <fullName>Denied / Not Compliant</fullName>
            </value>
            <value>
                <fullName>Tax Id was not found on record with DOTAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/Licensee__c.field-meta.xml
<CustomField>
    <fullName>Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The account that this license belongs too.</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseeNameFormula__c.field-meta.xml
<CustomField>
    <fullName>LicenseeNameFormula__c</fullName>
    <description>PacPoint FT112719 - Created for PVL</description>
    <formula>IF(LicenseTypeFormula__c = &quot;COLAX&quot;  || LicenseTypeFormula__c = &quot;COLA&quot;,  Licensee__r.Name  +  BR()  + &quot;C/O &quot; +  EmployeePrincipalEmployee__c, IF(LicenseTypeFormula__c &lt;&gt; &quot;COLAX&quot;  || LicenseTypeFormula__c &lt;&gt; &quot;COLA&quot;,
BLANKVALUE( Licensee__r.Name,
IF(ISBLANK(Licensee__r.MiddleName),
if(ISBLANK(Licensee__r.FirstName) ,&apos;&apos;, Licensee__r.FirstName+ &apos; &apos; ) + Licensee__r.LastName+ &apos; &apos; +   Licensee__r.Suffix  
,
Licensee__r.FirstName+ &apos; &apos; + Licensee__r.MiddleName+ &apos; &apos; + Licensee__r.LastName+ &apos; &apos; +   Licensee__r.Suffix 
)

), NULL))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Licensee Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
            <value>
                <fullName>ZI - Automatically Forfeited Due To Insurance Loss (60 Days to Restore)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/TaxEntityName__c.field-meta.xml
<CustomField>
    <fullName>TaxEntityName__c</fullName>
    <inlineHelpText>This is the entity name that is on file with the Hawaii Department of Tax</inlineHelpText>
    <label>Tax Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>Active / Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaxClearanceCheckBatch.cls
/*
 * -----------------------------------------------------------------------------------
 * Description
 * -----------------------------------------------------------------------------------
 * Covered by: TaxClearanceCheckBatchTest
 * -----------------------------------------------------------------------------------
 * PacPoint-CL08209022 - Created for case 00023037
 * -----------------------------------------------------------------------------------
 * Initial implementation
 *
 * @author chris.loyola@pacificpointcorp.com
 *
 * @created 08/09/2022
 * -----------------------------------------------------------------------------------
 * Changes
 * -----------------------------------------------------------------------------------
 */
public class TaxClearanceCheckBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts{

    private String licenseTypeId;

    private String query;

    private static Set<String> licenseStatusFilter = new Set<String>{
            'C - Current, Valid & In Good Standing',
            'CM - Current, Valid & In Good Standing/Maint. Requirement Due',
            'R - Valid Thru Expiration Date, Subject To Renewal',
            'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due',
            'Z - Current & Valid, But Subject To Disciplinary Requirement',
            'ZM - Current & Valid, But Subject To Disciplinary/Maintenance Requirement',
            'ZI - Automatically Forfeited Due To Insurance Loss (60 Days to Restore)'
            };

    public TaxClearanceCheckBatch(String parentLicenseTypeId) {
        licenseTypeId = parentLicenseTypeId;
        query = 'SELECT Id, ' +
                'LicenseeNameFormula__c, ' +
                'Licensee__r.BPID__c, ' +
                'Licensee__r.FEIN__c, ' +
                'Licensee__r.StateExciseTaxNumber__c ' +
                'FROM License__c ' +
                'WHERE LicenseType__c = :licenseTypeId ' +
                'AND Status__c IN :licenseStatusFilter ' +
                'AND LastTaxClearanceStatus__c != \'Approved / Compliant\' '+
                'AND ActiveInactive__c = \'Active\'';
    }

    public void execute(Database.BatchableContext bc, List<SObject> sObjects) {
        List<License__c> licenses = (List<License__c>) sObjects;

        TaxClearanceApiHelper.TaxClearanceResponse apiResponse = TaxClearanceApiHelper.runClearance(licenses);
        Map<String, TaxClearanceApiHelper.TaxClearanceResultResult> foundSsnsResultMap = new Map<String, TaxClearanceApiHelper.TaxClearanceResultResult>();
        Map<String, TaxClearanceApiHelper.TaxClearanceResultResult> foundFeinsResultMap = new Map<String, TaxClearanceApiHelper.TaxClearanceResultResult>();
        Map<String, TaxClearanceApiHelper.TaxClearanceResultResult> foundTaxIdsResultMap = new Map<String, TaxClearanceApiHelper.TaxClearanceResultResult>();

        if (apiResponse.ssns != null && !apiResponse.ssns.isEmpty()) {
            foundSsnsResultMap.putAll(mapResults(apiResponse.ssns));
        }

        if (apiResponse.feins != null && !apiResponse.feins.isEmpty()) {
            foundFeinsResultMap.putAll(mapResults(apiResponse.feins));
        }

        if (apiResponse.tax_ids != null && !apiResponse.tax_ids.isEmpty()) {
            foundTaxIdsResultMap.putAll(mapResults(apiResponse.tax_ids));
        }

        for (License__c l : licenses) {
            String bpId = l.Licensee__r.BPID__c;
            String fein = l.Licensee__r.FEIN__c;
            String taxId = l.Licensee__r.StateExciseTaxNumber__c;
            Boolean dFound = false;

            if (bpId != null && foundSsnsResultMap.containsKey(bpId)) {
                TaxClearanceApiHelper.TaxClearanceResultResult r = foundSsnsResultMap.get(bpId);
                if (r.status_code == 'Y') {
                    doYUpdate(l, r);
                    continue;
                } else if (r.status_code == 'D') {
                    dFound = true;
                }
            }

            if (fein != null && foundFeinsResultMap.containsKey(fein)) {
                TaxClearanceApiHelper.TaxClearanceResultResult r = foundFeinsResultMap.get(fein);
                if (r.status_code == 'Y') {
                    doYUpdate(l, r);
                    continue;
                } else if (r.status_code == 'D' && !dFound) {
                    dFound = true;
                }
            }

            if (taxId != null && foundTaxIdsResultMap.containsKey(taxId)) {
                TaxClearanceApiHelper.TaxClearanceResultResult r = foundTaxIdsResultMap.get(taxId);
                if (r.status_code == 'Y') {
                    doYUpdate(l, r);
                    continue;
                } else if (r.status_code == 'D' && !dFound) {
                    dFound = true;
                }
            }

            if (dFound) {
                l.LastTaxClearanceStatus__c = 'Denied / Not Compliant';
            } else {
                l.LastTaxClearanceStatus__c = 'Tax Id was not found on record with DOTAX';
            }
        }

        update licenses;
    }

    private void doYUpdate(License__c license, TaxClearanceApiHelper.TaxClearanceResultResult result) {
        String effectiveFrom = result.effective_from;
        List<String> splitDate = effectiveFrom.split('/');
        Date effectiveFromDate = Date.newInstance(Integer.valueOf(splitDate[2]),
                Integer.valueOf(splitDate[0]),
                Integer.valueOf(splitDate[1]));

        license.LastTaxClearanceDate__c = effectiveFromDate;
        license.TaxEntityName__c = result.name;

        String licenseNameFormula = TaxClearanceApiHelper.cleanClearanceResultName(license.LicenseeNameFormula__c);
        String clearanceResultName = TaxClearanceApiHelper.cleanClearanceResultName(result.name);

        if (licenseNameFormula == clearanceResultName) {
            license.LastTaxClearanceStatus__c = 'Approved / Compliant';
        } else {
            license.LastTaxClearanceStatus__c = 'Approved / Compliant. Entity name does not match DOTAX';
        }
    }

    private Map<String, TaxClearanceApiHelper.TaxClearanceResultResult> mapResults(List<TaxClearanceApiHelper.TaxClearanceResult> results) {
        Map<String, TaxClearanceApiHelper.TaxClearanceResultResult> ret = new Map<String, TaxClearanceApiHelper.TaxClearanceResultResult>();
        for (TaxClearanceApiHelper.TaxClearanceResult r : results) {
            if (r.id != null && r.results != null && !r.results.isEmpty()) {
                if (!ret.containsKey(r.id)) {
                    ret.put(r.id, r.results[0]);
                }
            }
        }

        return ret;
    }

    public void finish(Database.BatchableContext bc) {
        LicenseType__c lt = [SELECT Id, Name FROM LicenseType__c WHERE Id = :licenseTypeId];
        BatchJobFinishNotification notification = new BatchJobFinishNotification('TaxClearanceCheckBatch', lt.Name);
        notification.sendEmail();
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
}