force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/DependentLicense__c.field-meta.xml
<CustomField>
    <fullName>DependentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <inlineHelpText>The dependent license will be brought over from the application. Changes can be manually made here. This field is set with the Entity/Principal checkbox in the associated licenses section.</inlineHelpText>
    <label>Dependent License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>DependentLicenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseConditions__c.field-meta.xml
<CustomField>
    <fullName>LicenseConditions__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <inlineHelpText>This field is visible through MyPVL&apos;s Public License Search.</inlineHelpText>
    <label>License Conditions</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LicenseConditions__c/LicenseConditions__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>License Condition</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseConditions__c/fields/DependentLicense__c.field-meta.xml
<CustomField>
    <fullName>DependentLicense__c</fullName>
    <description>PacPoint-AZ112019 - Created for PVL phase 1.Used to populate the dependent license ID.</description>
    <formula>License__r.DependentLicense__c</formula>
    <label>Dependent License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseConditions__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>License Conditions</relationshipLabel>
    <relationshipName>LicenseConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LicenseConditions__c/fields/RMEandEntity__c.field-meta.xml
<CustomField>
    <fullName>RMEandEntity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-KN102219-Created for PVL Sprint 2 Phase 1</description>
    <inlineHelpText>Check this checkbox when the License Conditions listed on this Record apply to both the RME and Entity. Leave unchecked if the License Conditions only apply to the RME.</inlineHelpText>
    <label>RME and Entity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LicenseConditionTriggerTest.cls
@isTest
public with sharing class LicenseConditionTriggerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createLicense(); 
    }
    public static testMethod void testLicenseConditions() {
        License__c record = [Select Id from License__c where DependentLicense__c != null limit 1];
        LicenseConditions__c licenseCondition = new LicenseConditions__c();
        licenseCondition.License__c = record.Id;
        insert licenseCondition;
        licenseCondition.RMEandEntity__c = true;
        update licenseCondition;
        delete licenseCondition;

    }
    public static testMethod void testCreateRecord() {
        License__c record = [Select Id from License__c where DependentLicense__c != null limit 1];
        LicenseConditions__c licenseCondition = new LicenseConditions__c();
        licenseCondition.License__c = record.Id;
        licenseCondition.RMEandEntity__c = true;
        insert licenseCondition; 
        
    }
}