force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/OtherRenewalRequirements1__c.field-meta.xml
<CustomField>
    <fullName>OtherRenewalRequirements1__c</fullName>
    <description>PacPoint-FT111919 - Created for PVL phase 1</description>
    <label>Other Renewal Requirements 1</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/OtherRenewalRequirements2__c.field-meta.xml
<CustomField>
    <fullName>OtherRenewalRequirements2__c</fullName>
    <description>PacPoint FT111919 - Created for PVL</description>
    <label>Other Renewal Requirements 2</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PACIFICPOINT-AZ20200902 case 00009192</description>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RenewalNotificationControllerTest.cls
@isTest
private class RenewalNotificationControllerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.prepareAssociatedLicenses();
        
    }
    @isTest private static void testController() {
        List<License__c> records = [Select Id, LicenseType__r.OtherRenewalRequirements2__c, LicenseType__r.OtherRenewalRequirements1__c from License__c];
        LicenseType__c ltype = records.get(0).LicenseType__r;
        ltype.OtherRenewalRequirements1__c = 'test';
        ltype.OtherRenewalRequirements2__c = 'test';
        update ltype;
        List<String> idList = (List<String>)(new LicenseDomain(records)).getFieldValues('Id');
        String queryIds = String.join(idList, ',');
        Notification__c notification = NotificationService.generateNotificationForIdContain(queryIds, '');
        
        ApexPages.currentPage().getParameters().put('notificationIds', notification.Id);
        ApexPages.currentPage().getParameters().put('sortby', 'address');
        RenewalNotificationController cont = new RenewalNotificationController();

    }

    @isTest
    private static void testFormatAndNormalizeHelpers() {
        String input =
            '<p>RENEW ONLINE AT: <span style="font-size: 14px;">https://mypvl.example.com</span></p>' +
            '<font size="4">text</font><h2>Title</h2>INACTIVE STATUS?';

        String formatted = RenewalNotificationController.formatOtherRenewalRequirementsHtml(input);
        System.assert(formatted.contains('<div>'), 'p tags should convert to div');
        System.assert(!formatted.containsIgnoreCase('font-size'), 'font-size should be stripped');
        System.assert(!formatted.containsIgnoreCase('size="4"'), 'font size attr should be stripped');
        System.assert(formatted.contains('<div>Title</div>'), 'heading tags should convert to div');
        System.assert(formatted.contains('<strong>INACTIVE STATUS?</strong>'), 'bold phrase should wrap');

        System.assertEquals(null, RenewalNotificationController.normalizeRenewalRequirementsFontSize(null));
        System.assertEquals(
            '<span style=" color: red;">x</span>',
            RenewalNotificationController.normalizeRenewalRequirementsFontSize(
                '<span style="font-size: 13px; color: red;">x</span>'
            )
        );
    }
}