force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/BoardProgramName__c.field-meta.xml
<CustomField>
    <fullName>BoardProgramName__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <formula>LicenseType__r.BoardProgram__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Board Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseeNameFormula__c.field-meta.xml
<CustomField>
    <fullName>LicenseeNameFormula__c</fullName>
    <description>PacPoint FT112719 - Created for PVL</description>
    <formula>IF(LicenseTypeFormula__c = &quot;COLAX&quot;  || LicenseTypeFormula__c = &quot;COLA&quot;,  Licensee__r.Name  +  BR()  + &quot;C/O &quot; +  EmployeePrincipalEmployee__c, IF(LicenseTypeFormula__c &lt;&gt; &quot;COLAX&quot;  || LicenseTypeFormula__c &lt;&gt; &quot;COLA&quot;,
BLANKVALUE( Licensee__r.Name,
IF(ISBLANK(Licensee__r.MiddleName),
if(ISBLANK(Licensee__r.FirstName) ,&apos;&apos;, Licensee__r.FirstName+ &apos; &apos; ) + Licensee__r.LastName+ &apos; &apos; +   Licensee__r.Suffix  
,
Licensee__r.FirstName+ &apos; &apos; + Licensee__r.MiddleName+ &apos; &apos; + Licensee__r.LastName+ &apos; &apos; +   Licensee__r.Suffix 
)

), NULL))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Licensee Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/NotificationEmail__c.field-meta.xml
<CustomField>
    <fullName>NotificationEmail__c</fullName>
    <description>PacPoint-KN110719-Created for PVL Sprint 2 Phase 1</description>
    <inlineHelpText>The email that all email notifications will be delivered too.</inlineHelpText>
    <label>Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/License__c/fields/RenewalMailToCity__c.field-meta.xml
<CustomField>
    <fullName>RenewalMailToCity__c</fullName>
    <formula>CASE( RenewalMailToCode__c ,
&quot;B - Business Mailing/Business/Residence&quot;,
IF( IsMailingPopulated__c = &quot;Y&quot;,
MailingCity__c,
IF(IsBusinessPopulated__c = &quot;Y&quot;,
BusinessCity__c,
ResidenceCity__c)),


&quot;R - Residence Mailing/Residence&quot;,
IF( IsMailingPopulated__c = &quot;Y&quot;,
MailingCity__c,
IF(IsResidencePopulated__c = &quot;Y&quot;,
ResidenceCity__c,
null)),


&quot;E - Employer If licensee is inactive, licensee’s Mailing/Residence. Otherwise, c/o Employer’s Mailing/Business&quot;,
IF( 



OR (
TEXT(ActiveInactive__c) = &quot;Inactive&quot;,
IsEmployerAddressPopulated__c = &quot;N&quot;
),




IF( IsMailingPopulated__c = &quot;Y&quot;,
MailingCity__c,
IF(IsResidencePopulated__c = &quot;Y&quot;,
ResidenceCity__c,
null)),


EmployerCity__c

),



NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Mail To City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/RenewalMailToState__c.field-meta.xml
<CustomField>
    <fullName>RenewalMailToState__c</fullName>
    <formula>CASE( RenewalMailToCode__c ,
&quot;B - Business Mailing/Business/Residence&quot;,
IF( IsMailingPopulated__c = &quot;Y&quot;,
TEXT(MailingState__c),
IF(IsBusinessPopulated__c = &quot;Y&quot;,
TEXT(BusinessState__c),
ResidenceState__c)),


&quot;R - Residence Mailing/Residence&quot;,
IF( IsMailingPopulated__c = &quot;Y&quot;,
TEXT(MailingState__c),
IF(IsResidencePopulated__c = &quot;Y&quot;,
ResidenceStateCode__c,
null)),


&quot;E - Employer If licensee is inactive, licensee’s Mailing/Residence. Otherwise, c/o Employer’s Mailing/Business&quot;,
IF( 




OR (
TEXT(ActiveInactive__c) = &quot;Inactive&quot;,
IsEmployerAddressPopulated__c = &quot;N&quot;
),

IF( IsMailingPopulated__c = &quot;Y&quot;,
TEXT(MailingState__c),
IF(IsResidencePopulated__c = &quot;Y&quot;,
ResidenceStateCode__c,
null)),

TEXT(EmployerState__c)

),



NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Mail To State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/RenewalMailToStreet__c.field-meta.xml
<CustomField>
    <fullName>RenewalMailToStreet__c</fullName>
    <formula>CASE(  RenewalMailToCode__c  ,
&quot;B - Business Mailing/Business/Residence&quot;, 
	IF( IsMailingPopulated__c = &quot;Y&quot;,
	MailingStreet__c,
	IF(IsBusinessPopulated__c = &quot;Y&quot;,
	BusinessStreet__c,
	ResidenceStreet__c)),


&quot;R - Residence Mailing/Residence&quot;, 
	IF( IsMailingPopulated__c = &quot;Y&quot;,
	MailingStreet__c,
	IF(IsResidencePopulated__c = &quot;Y&quot;,
	ResidenceStreet__c,
	null)),


&quot;E - Employer If licensee is inactive, licensee’s Mailing/Residence. Otherwise, c/o Employer’s Mailing/Business&quot;, 
	IF(  



OR (
TEXT(ActiveInactive__c) = &quot;Inactive&quot;,
IsEmployerAddressPopulated__c = &quot;N&quot;
),


           IF( IsMailingPopulated__c = &quot;Y&quot;,
	   MailingStreet__c,
	   IF(IsResidencePopulated__c = &quot;Y&quot;,
           ResidenceStreet__c,
           null)),

           &quot;C/O &quot; + EmployerName__c &amp; BR() &amp;  EmployerStreet__c
           

),



NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Mail To Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/RenewalMailToZipCode__c.field-meta.xml
<CustomField>
    <fullName>RenewalMailToZipCode__c</fullName>
    <formula>CASE( RenewalMailToCode__c ,
&quot;B - Business Mailing/Business/Residence&quot;,
IF( IsMailingPopulated__c = &quot;Y&quot;,
MailingZipCode__c,
IF(IsBusinessPopulated__c = &quot;Y&quot;,
BusinessZipCode__c,
ResidenceZipCode__c)),

&quot;R - Residence Mailing/Residence&quot;,
IF( IsMailingPopulated__c = &quot;Y&quot;,
MailingZipCode__c,
IF(IsResidencePopulated__c = &quot;Y&quot;,
ResidenceZipCode__c,
null)),


&quot;E - Employer If licensee is inactive, licensee’s Mailing/Residence. Otherwise, c/o Employer’s Mailing/Business&quot;,
IF(

OR (
TEXT(ActiveInactive__c) = &quot;Inactive&quot;,
IsEmployerAddressPopulated__c = &quot;N&quot;
),

IF( IsMailingPopulated__c = &quot;Y&quot;,
MailingZipCode__c,
IF(IsResidencePopulated__c = &quot;Y&quot;,
ResidenceZipCode__c,
null)),

EmployerZipCode__c

),

NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Mail To Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/SendAMDInactivationEmail__c.field-meta.xml
<CustomField>
    <fullName>SendAMDInactivationEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send AMD Inactivation Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AMDInactivationLetterNoticeController.cls
/*
 * ___________________________________________________________________________________
 * AMD Inactivation Letter Notice Controller
 * For AMDInactivationLetterNotice Email Templates
 * Covered by:
 * __________________________________________________________________________________
 * PacPoint-EA02022024 - Created for Case 00033728
 * __________________________________________________________________________________
 * Initial implementation
 *
 * @author emel.l.agarao@pacificpointcorp.com
 *
 * @created 02/02/2024
 * __________________________________________________________________________________
 */
public class AMDInactivationLetterNoticeController {
    public License__c lic{get;set;}
    public String currentRecordId{get;set;}
    public String boardProgramName {set;get;}
    public String licenseeName {set;get;}
    public String renewalMailToStreet {set;get;}
    public String renewalMailToCity {set;get;}
    public String renewalMailToState {set;get;}
    public String renewalMailToZipCode {set;get;}
    
    public AMDInactivationLetterNoticeController(){
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        if(currentRecordId != null && String.isNotBlank(currentRecordId)){
            lic = [SELECT 
                Id, Name, LicenseeNameFormula__c, BoardProgramName__c, RenewalMailToStreet__c, 
                RenewalMailToCity__c, RenewalMailToState__c, RenewalMailToZipCode__c
                FROM License__c WHERE Id =:currentRecordId];
            this.boardProgramName = lic.BoardProgramName__c;
            this.renewalMailToCity = lic.RenewalMailToCity__c;
            this.licenseeName = lic.LicenseeNameFormula__c;
            this.renewalMailToStreet = lic.RenewalMailToStreet__c;
            this.renewalMailToState = lic.RenewalMailToState__c;
            this.renewalMailToZipCode = lic.RenewalMailToZipCode__c;
        }
    }

    //00033731
    @InvocableMethod(label='Process AMD Inactivation' description='Create Notifications, generate files and send emails for AMD Inactivation Letter Notice.' category='License')
    public static List <Results> processAMDInactivation(recordInfo[] licenseRecords){
        List<String> forUpdateLicenseIds = new List<String>();
        List<Results> results = new List<Results>();
        
        for(recordInfo record: licenseRecords) {
            Results res = new Results();
            res.operationOutcome = record.Id;
            results.add(res);
            forUpdateLicenseIds.add(record.Id);
        }
        List<License__c> forUpdateLicenses=[Select Id, NotificationEmail__c, SendAMDInactivationEmail__c from License__c where Id in:  forUpdateLicenseIds];
        List<Notification__c> notifications = (new LicenseDomain(forUpdateLicenses)).generateAMDInactivationNotifications(true);

        if(!notifications.isEmpty()){
            insert notifications;            
            Database.executeBatch(new AMDInactivationBatch(), 10);
        }

        return results;
    }

    public class recordInfo {
        @InvocableVariable
        public String Id;        
    }

    public class Results {
        @InvocableVariable(label='Records for Output' description='Output' required=true)
        public String operationOutcome;
    }
}