force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseRequirements__c/LicenseRequirements__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>License Requirements</label>
    <nameField>
        <label>License Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseRequirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseRequirements__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC073019- Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>LicenseRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseRequirements__c/fields/ParentLicenseRequirement__c.field-meta.xml
<CustomField>
    <fullName>ParentLicenseRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV080519- Created for PVL phase 1</description>
    <label>Parent License Requirement</label>
    <referenceTo>LicenseRequirements__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>LicenseRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseRequirements__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV082819 - Created for PVL phase 1</description>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>LicenseRequirements</relationshipLabel>
    <relationshipName>LicenseRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseRequirements__c/fields/RequirementLongDescription__c.field-meta.xml
<CustomField>
    <fullName>RequirementLongDescription__c</fullName>
    <description>PacPoint-MV082919 - Created for PVL phase 1</description>
    <label>Requirement Long Description</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LicenseRequirements__c/fields/RequirementShortDescription__c.field-meta.xml
<CustomField>
    <fullName>RequirementShortDescription__c</fullName>
    <description>PacPoint-MV080519 - Created for PVL phase 1</description>
    <label>Requirement Short Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LicenseRequirementsSelector.cls
/**** 
* ─────────────────────────────────────────────────────────
* class for selecting Data from the License Requirements
* ─────────────────────────────────────────────────────────
* PacPoint-CZ060819 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Chris Zhuang - PacificPointCorp 
* @created      2019-09-06
* ───────────────────────────────────────────────────────────
* Changes
*
*
* ───────────────────────────────────────────────────────────
*/
public with sharing class LicenseRequirementsSelector {
    public static List<LicenseRequirements__c> getLicenseRequirements(List<String> licenseIds) {
        return [Select Id, Name, Requirement__c, ParentLicenseRequirement__c, RequirementShortDescription__c, RequirementLongDescription__c from LicenseRequirements__c where License__c in: licenseIds];
    }
}