force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/AutoForfeitureStatus__c.field-meta.xml
<CustomField>
    <fullName>AutoForfeitureStatus__c</fullName>
    <description>PacPoint-KN081619 - Created for PVL Phase 1</description>
    <label>Auto Forfeiture Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LicenseStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suspense__c/Suspense__c.object-meta.xml
<CustomObject>
    <label>Suspense</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Suspense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspense</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Suspense__c/fields/Delete__c.field-meta.xml
<CustomField>
    <fullName>Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/Historical__c.field-meta.xml
<CustomField>
    <fullName>Historical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Historical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/InsuranceType__c.field-meta.xml
<CustomField>
    <fullName>InsuranceType__c</fullName>
    <description>PacPoint-KN08062020 - Created for PVL Phase 1 Sprint 6</description>
    <label>Insurance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Insurance_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Suspense</relationshipLabel>
    <relationshipName>Suspense</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/MaintenanceType__c.field-meta.xml
<CustomField>
    <fullName>MaintenanceType__c</fullName>
    <label>Maintenance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BA - FILE CHANGE OF BUSINESS ADDRESS</fullName>
            </value>
            <value>
                <fullName>BCHK - BOUNCED CHECK - GENERIC</fullName>
            </value>
            <value>
                <fullName>BCLF - BOUNCED CHECK - LICF</fullName>
            </value>
            <value>
                <fullName>BCNL - BOUNCED CHECK - NEW LICENSEE</fullName>
            </value>
            <value>
                <fullName>BCRN - BOUNCED CHECK - RENEWAL</fullName>
            </value>
            <value>
                <fullName>BCRS - BOUNCED CHECK - RESTORATION</fullName>
            </value>
            <value>
                <fullName>BCSF - BOUNCED CHECK SERVICE FEE</fullName>
            </value>
            <value>
                <fullName>BPLF - BOUNCED CHECK REPAYMENT - LICF</fullName>
            </value>
            <value>
                <fullName>BPRS - BOUNCED CHECK RNEW/RSTR, REPAYMENT RESTORATION</fullName>
            </value>
            <value>
                <fullName>BRDR - BOARD REVIEW AT SUSPENSE DATE</fullName>
            </value>
            <value>
                <fullName>CONT - PRINCIPAL MISSING CONTINUING ED REQUIREMENT</fullName>
            </value>
            <value>
                <fullName>CRSE - COURSE DUE</fullName>
            </value>
            <value>
                <fullName>CS - CLOSE OR EXTEND SITE OFFICE</fullName>
            </value>
            <value>
                <fullName>EC - EMPLOYER CLOSED</fullName>
            </value>
            <value>
                <fullName>FM - PROVE FAMILY MEMBER STATUS</fullName>
            </value>
            <value>
                <fullName>FRMR - EMPLOYER MUST RENEW</fullName>
            </value>
            <value>
                <fullName>IE - FILE INACTIVE OR NEW EMPLOYER</fullName>
            </value>
            <value>
                <fullName>IWBD - BOND DUE</fullName>
            </value>
            <value>
                <fullName>IWLI - LIABILITY DUE</fullName>
            </value>
            <value>
                <fullName>IWLP - LIABILITY/PROPERTY DAMAGE DUE</fullName>
            </value>
            <value>
                <fullName>IWSL - SELF-INSURED FOR W/C</fullName>
            </value>
            <value>
                <fullName>IWSW - WORKERS COMP THRU LEASING CO. DUE</fullName>
            </value>
            <value>
                <fullName>IWWC - WORKERS COMPENSATION DUE</fullName>
            </value>
            <value>
                <fullName>IZBD - BOND EXPIRED</fullName>
            </value>
            <value>
                <fullName>IZLI - LIABILITY EXPIRED</fullName>
            </value>
            <value>
                <fullName>IZLP - LIABILITY/PROPERTY DAMAGE EXPIRED</fullName>
            </value>
            <value>
                <fullName>IZSL - SELF-INSURED FOR W/C EXPIRED</fullName>
            </value>
            <value>
                <fullName>IZSW - WORKERS COMP THRU LEASING CO. EXPIRED</fullName>
            </value>
            <value>
                <fullName>IZWC - WORKERS COMPENSATION EXPIRED</fullName>
            </value>
            <value>
                <fullName>LCR1 - LICENSE CONDITIONAL REVIEW PAST DUE</fullName>
            </value>
            <value>
                <fullName>NFRM - RME WITHOUT EMPLOYMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/SuspenseDueDate__c.field-meta.xml
<CustomField>
    <fullName>SuspenseDueDate__c</fullName>
    <label>Suspense Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/SuspenseStatus__c.field-meta.xml
<CustomField>
    <fullName>SuspenseStatus__c</fullName>
    <description>PacPoint-KN08072020-Created for PVL Phase 1 Sprint 6</description>
    <label>Suspense Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LicenseStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Insurance_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BD - Bond</fullName>
    </customValue>
    <customValue>
        <fullName>BX - Bond Exemption (All Boards)</fullName>
    </customValue>
    <customValue>
        <fullName>D - Employee Dishonesty Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>EX - Exemption</fullName>
    </customValue>
    <customValue>
        <fullName>FS - Pre-Need Funeral Service Trust</fullName>
    </customValue>
    <customValue>
        <fullName>GM - Perpetual Care (Ground Maintenance) Trust</fullName>
    </customValue>
    <customValue>
        <fullName>LC - Line of Credit</fullName>
    </customValue>
    <customValue>
        <fullName>LI - Liability</fullName>
    </customValue>
    <customValue>
        <fullName>LP - Liability / Property Damage</fullName>
    </customValue>
    <customValue>
        <fullName>PI - Pre-Need Interment (Burial) Services Trust</fullName>
    </customValue>
    <customValue>
        <fullName>SI - Exclusion from Workers Comp.</fullName>
    </customValue>
    <customValue>
        <fullName>SL - Self-Insured for W/C (Entity OK&apos;d By Labor Dept)</fullName>
    </customValue>
    <customValue>
        <fullName>SM - No HI Employees - Submit Workers Comp Prior to Hiring</fullName>
    </customValue>
    <customValue>
        <fullName>SW - Workers Comp Thru Leasing Co.</fullName>
    </customValue>
    <customValue>
        <fullName>SX - Exemption No Longer Allowed</fullName>
    </customValue>
    <customValue>
        <fullName>T1 - Client Trust Account #1</fullName>
    </customValue>
    <customValue>
        <fullName>T2 - Client Trust Account #2</fullName>
    </customValue>
    <customValue>
        <fullName>T3 - Client Trust Account #3</fullName>
    </customValue>
    <customValue>
        <fullName>T4 - Client Trust Account #4</fullName>
    </customValue>
    <customValue>
        <fullName>T5 - Client Trust Account #5</fullName>
    </customValue>
    <customValue>
        <fullName>TC - Charter Tour</fullName>
    </customValue>
    <customValue>
        <fullName>WC - Workers Compensation</fullName>
    </customValue>
    <customValue>
        <fullName>WP - Submit Prior to Hiring Hi Empl - Evidence of WC Not Submitted</fullName>
    </customValue>
    <masterLabel>Insurance Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SuspenseSelector.cls
public with sharing class SuspenseSelector {
    public static List<Suspense__c> getSuspenseByIds(List<String> licenseIds) {
        return [
            Select Id, InsuranceType__c, SuspenseDueDate__c, License__c,License__r.LicenseType__r.Name from Suspense__c where License__c in: licenseIds
            and SuspenseDueDate__c >= Today
        ];
    }

    public static List<Suspense__c> getDueSuspenses(Set<String> licenseIds) {
        return [
            Select Id, InsuranceType__c, SuspenseDueDate__c, License__c,License__r.LicenseType__r.Name from Suspense__c where License__c in: licenseIds
            and SuspenseDueDate__c < Today and Delete__c = false and Historical__c = false
        ];
    }

    public static List<Suspense__c> getSuspenseByLicenseIds(List<String> licenseIds) {
        return [
            Select Id, InsuranceType__c,SuspenseStatus__c, SuspenseDueDate__c, 
            License__r.LicenseType__r.AutoForfeitureStatus__c,
            License__c, Historical__c, MaintenanceType__c,License__r.LicenseType__r.Name from Suspense__c 
            where License__c in: licenseIds and Historical__c = false AND License__r.LicenseType__r.Name NOT IN ('BAP', 'BEP', 'MAP') 
            order by CreatedDate
        ];
    }

    public static List<Suspense__c> getNFRMSuspenseByLicenseIds(List<String> licenseIds) {
        return [
            Select Id, InsuranceType__c,SuspenseStatus__c, SuspenseDueDate__c, License__c, Historical__c from Suspense__c 
            where License__c in: licenseIds and Historical__c = false and MaintenanceType__c = 'NFRM - RME WITHOUT EMPLOYMENT' 
            order by CreatedDate];
    }

    public static DataBase.QueryLocator getSuspenseQueryLocator(String objectType, String selectFields, String filterCriteria) {
        return Database.getQueryLocator(String.format('SELECT {0} FROM {1} WHERE {2} ', new List<String>{selectFields, objectType, filterCriteria}));
    }
}