force-app/main/default/objects/PVLErrorHandler__e/PVLErrorHandler__e.object-meta.xml
<CustomObject>
    <description>Used to handle errors</description>
    <label>PVL Error Handler</label>
    <pluralLabel>PVL Error Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/PVLErrorHandler__e/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <label>Debug Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PVLErrorHandler__e/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <label>Reference Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationLogService.cls
/****
 * Description: used to capture application logs.
 * 
 * ** */
public class ApplicationLogService {
    public static void logApplicationError(String type, String recordId, String info, String error) {
        PVLErrorHandler__e log = new PVLErrorHandler__e();
        log.Debug_Level__c = 'Error';
        log.Type__c = type;
        log.Reference_Id__c = recordId;
        log.Message__c = info;
        log.Stack_Trace__c = error;
        EventBus.publish(log);
    }
    
}