force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC101718 - Created for BREG phase 1</description>
    <label>Investigation</label>
    <nameField>
        <label>Investigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/SEBCase__c.field-meta.xml
<CustomField>
    <fullName>SEBCase__c</fullName>
    <description>PacPoint-IC101718 - Created for BREG phase 1</description>
    <label>SEB Case</label>
    <referenceTo>SEBCase__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/SEBCase__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC101218 - Created for BREG phase 1</description>
    <label>SEB Case</label>
    <nameField>
        <label>SEB Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEB Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvestigationCallsBatch.cls
global with sharing class InvestigationCallsBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public List<String> recordIds = new List<String>();  
    public String query = 'SELECT Id, Name, SEBCase__c FROM Investigation__c ';

    global InvestigationCallsBatch(String recordId) {
        this();
        this.recordIds.add(recordId);
        query += ' WHERE Id IN :recordIds AND SEBCase__c != NULL';
    }

    global InvestigationCallsBatch(List<String> recordIds) {
        this();
        this.recordIds = recordIds;
        query += ' WHERE Id IN :recordIds AND SEBCase__c != NULL';
    }

    global InvestigationCallsBatch() {  
        recordIds.clear();    
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Investigation__c> scope){
        Map<String, Blob> springcmFiles = new Map<String, Blob>();
        for(Investigation__c inv:scope){
            PageReference pdf = Page.InvestigationCallsTemplate;
            pdf.getParameters().put('id', inv.Id);
        
            Blob content;
            if(Test.isRunningTest()) {
                content = Blob.valueOf('test');
            } else {
                content = pdf.getContent();
            }

            //Save to SpringCM
            try{                    
                List<SpringCMDocument> result = SpringCMConnector.createFile(inv.Id, 'Calls for '+ inv.Name +'.pdf', content);
            }catch(Exception ex){
                System.debug('InvestigationCallsBatch: SpringCMConnector.createFile');
                System.debug(ex.getMessage());
            }
        }
    }

    global void finish(Database.BatchableContext BC) {}
}