force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC101718 - Created for BREG phase 1</description>
    <label>Investigation</label>
    <nameField>
        <label>Investigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/SEBCase__c.field-meta.xml
<CustomField>
    <fullName>SEBCase__c</fullName>
    <description>PacPoint-IC101718 - Created for BREG phase 1</description>
    <label>SEB Case</label>
    <referenceTo>SEBCase__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-IC101818 - Created for BREG phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appellate Court</fullName>
            </value>
            <value>
                <fullName>Circuit Court</fullName>
            </value>
            <value>
                <fullName>Commissioner’s Final Order</fullName>
            </value>
            <value>
                <fullName>Consent Agreement</fullName>
            </value>
            <value>
                <fullName>Consent Order</fullName>
            </value>
            <value>
                <fullName>Corrections by Attorney Required (L)</fullName>
            </value>
            <value>
                <fullName>Corrections Required</fullName>
            </value>
            <value>
                <fullName>Currently in Hearing</fullName>
            </value>
            <value>
                <fullName>Ex Parte Motion for Service by Publication</fullName>
            </value>
            <value>
                <fullName>Investigation in Progress</fullName>
            </value>
            <value>
                <fullName>Judgement Enforcing Commissioner’s Final Order</fullName>
            </value>
            <value>
                <fullName>Judgement Enforcing Commissioner’s Final Order (BOC)</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Ready to Serve</fullName>
            </value>
            <value>
                <fullName>Pending Hearing Date</fullName>
            </value>
            <value>
                <fullName>Pending Request for Hearing</fullName>
            </value>
            <value>
                <fullName>Preliminary Order to Cease and Desist</fullName>
            </value>
            <value>
                <fullName>Ready for Supervising Attorney Review</fullName>
            </value>
            <value>
                <fullName>Ready for Supervising Attorney Review (L)</fullName>
            </value>
            <value>
                <fullName>Ready for Supervisor Review</fullName>
            </value>
            <value>
                <fullName>Recommend Final Order</fullName>
            </value>
            <value>
                <fullName>Recommend Judgement</fullName>
            </value>
            <value>
                <fullName>Recommend Referral to Legal</fullName>
            </value>
            <value>
                <fullName>Recommend to Close</fullName>
            </value>
            <value>
                <fullName>Remand to Appellate Court</fullName>
            </value>
            <value>
                <fullName>Remand to Circuit Court</fullName>
            </value>
            <value>
                <fullName>Remand to Commissioner</fullName>
            </value>
            <value>
                <fullName>Report Approved</fullName>
            </value>
            <value>
                <fullName>Supreme Court</fullName>
            </value>
            <value>
                <fullName>Under Legal Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigation__c/recordTypes/Investigation.recordType-meta.xml
<RecordType>
    <fullName>Investigation</fullName>
    <active>true</active>
    <label>Investigation</label>
</RecordType>

force-app/main/default/objects/SEBCase__c/SEBCase__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC101218 - Created for BREG phase 1</description>
    <label>SEB Case</label>
    <nameField>
        <label>SEB Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEB Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEBCase__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-JB102318 - Created for BREG phase 1</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.SEBSEC__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SEB Cases</relationshipLabel>
    <relationshipName>SEB_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-RA101218 - Created for BREG phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
                <default>true</default>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/TotalSEBCaseExpenses__c.field-meta.xml
<CustomField>
    <fullName>TotalSEBCaseExpenses__c</fullName>
    <description>PacPoint-LC121318 - Created for BREG phase 1</description>
    <label>Total SEB Case Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/TotalSEBCaseHours__c.field-meta.xml
<CustomField>
    <fullName>TotalSEBCaseHours__c</fullName>
    <description>PacPoint-LC121318 - Created for BREG phase 1</description>
    <label>Total SEB Case Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StatusHistory__c/StatusHistory__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC100918 - Created for BREG phase 1</description>
    <label>Status History</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/StatusHistory__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-JB103118 - Created for BREG phase 1</description>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Status Histories</relationshipLabel>
    <relationshipName>StatusHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StatusHistory__c/fields/SEBCase__c.field-meta.xml
<CustomField>
    <fullName>SEBCase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC101218 - Created for BREG phase 1</description>
    <label>SEB Case</label>
    <referenceTo>SEBCase__c</referenceTo>
    <relationshipLabel>Status Histories</relationshipLabel>
    <relationshipName>StatusHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeandExpenseDetails__c/TimeandExpenseDetails__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Time and Expense Details</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time and Expenses Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeandExpenseDetails__c/fields/ExpenseAmount__c.field-meta.xml
<CustomField>
    <fullName>ExpenseAmount__c</fullName>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Expense Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TimeandExpenseDetails__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Hours</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeandExpenseDetails__c/fields/TimeandExpenseHeader__c.field-meta.xml
<CustomField>
    <fullName>TimeandExpenseHeader__c</fullName>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Time and Expense Header</label>
    <referenceTo>TimeandExpenseHeader__c</referenceTo>
    <relationshipLabel>Time and Expenses Details</relationshipLabel>
    <relationshipName>TimeandExpenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TimeandExpenseHeader__c/TimeandExpenseHeader__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Time and Expense Header</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time and Expense Header</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeandExpenseHeader__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TimeandExpenseHeader__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-IC102418 - Created for BREG phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvestigationAllHandlerTest.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for the InvestigationAll trigger and the InvestigationAllHandler class
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* PacPoint-LC010919 - Created for BREG Phase 1
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author       Lucian Ciobanu - PacificPointCorp 
* @created      2019-01-09
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest
public class InvestigationAllHandlerTest{
    
    private static testmethod void testHandler1(){
        
       
        Account acct = new Account(
            Name = 'Test Accont',
            SEBSEC__c = true
        );
        insert acct;
        
        SEBCase__c SEBCase = new SEBCase__c(
            Account__c = acct.Id
            
        );
        insert SEBCase;
        
        Investigation__c Investigation1 = new Investigation__c(
            SEBCase__c = SEBCase.Id,
            Name = 'Test Investigation'
        );
        insert Investigation1;
        
        Investigation__c Investigation2 = new Investigation__c(
            SEBCase__c = SEBCase.Id,
            Name = 'Test Investigation'
        );
        insert Investigation2;
        
        TimeandExpenseHeader__c Header1 = new TimeandExpenseHeader__c(
            Investigation__c = Investigation1.Id,
            Name = 'Test Assignment'
          //  AssignedTo__c = UserInfo.getUserId()
        );
        insert Header1;
        
            
        List<TimeandExpenseDetails__c> TimeExpenseList = new List<TimeandExpenseDetails__c>();    
        
        TimeandExpenseDetails__c TimeandExpense11 = new TimeandExpenseDetails__c(
            TimeandExpenseHeader__c = Header1.Id,
            ExpenseAmount__c = 20,
            Hours__c = 2
        );
        TimeExpenseList.add(TimeandExpense11);
        
        TimeandExpenseDetails__c TimeandExpense12 = new TimeandExpenseDetails__c(
            TimeandExpenseHeader__c = Header1.Id,
            ExpenseAmount__c = 30,
            Hours__c = 3
        );
        TimeExpenseList.add(TimeandExpense12);
        
        TimeandExpenseDetails__c TimeandExpense13 = new TimeandExpenseDetails__c(
            TimeandExpenseHeader__c = Header1.Id,
            ExpenseAmount__c = 40,
            Hours__c = 4
        );
        TimeExpenseList.add(TimeandExpense13);
        
        TimeandExpenseHeader__c Header2 = new TimeandExpenseHeader__c(
            Investigation__c = Investigation1.Id,
            Name = 'Test Assignment'
           // AssignedTo__c = UserInfo.getUserId()
        );
        insert Header2;
        
        TimeandExpenseDetails__c TimeandExpense21 = new TimeandExpenseDetails__c(
            TimeandExpenseHeader__c = Header2.Id,
            ExpenseAmount__c = 10,
            Hours__c = 1
        );
        TimeExpenseList.add(TimeandExpense21);
        
        TimeandExpenseDetails__c TimeandExpense22 = new TimeandExpenseDetails__c(
            TimeandExpenseHeader__c = Header2.Id,
            ExpenseAmount__c = 10,
            Hours__c = 1
        );
        TimeExpenseList.add(TimeandExpense22);
        
        TimeandExpenseDetails__c TimeandExpense23 = new TimeandExpenseDetails__c(
            TimeandExpenseHeader__c = Header2.Id,
            ExpenseAmount__c = 10,
            Hours__c = 1
        );
        TimeExpenseList.add(TimeandExpense23);

        Test.startTest();
            insert TimeExpenseList;
            
            SEBCase__c SEBCaseCheck = [SELECT Id, TotalSEBCaseExpenses__c, TotalSEBCaseHours__c FROM SEBCase__c WHERE Id =: SEBCase.Id LIMIT 1];
            System.assertEquals(120, SEBCaseCheck.TotalSEBCaseExpenses__c);
            System.assertEquals(12, SEBCaseCheck.TotalSEBCaseHours__c);
        Test.stopTest();     
    }
    
    public static testmethod void TestHistory() {
        Account acct = new Account(
            Name = 'Test Accont',
            SEBSEC__c = true
        );
        insert acct;
        
        SEBCase__c cs = new SEBCase__c();
        cs.Status__c = 'Intake';
        cs.Account__c = acct.Id;
        insert cs;
        
        Investigation__c ex = new Investigation__c();
        ex.SEBCase__c = cs.Id;
        ex.Status__c = 'Investigation in Progress';
        insert ex;
        
        Test.startTest();
        ex.Status__c = 'Ready for Supervisor Review';
        update ex;
        ex.Status__c = 'Ready for Supervising Attorney Review';
        update ex;
        Test.stopTest();
        
        System.assert([SELECT COUNT() FROM StatusHistory__c] >= 3, 'At this point, we should have at least 3 history records');
    }
    
}