force-app/main/default/objects/breg_Document__c/breg_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Document__c/fields/breg_Account__c.field-meta.xml
<CustomField>
    <fullName>breg_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Availability__c.field-meta.xml
<CustomField>
    <fullName>breg_Availability__c</fullName>
    <label>Availability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available Now</fullName>
            </value>
            <value>
                <fullName>Available by Mail or Pickup</fullName>
            </value>
            <value>
                <fullName>Available in 7 business days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_File_Number__c.field-meta.xml
<CustomField>
    <fullName>breg_File_Number__c</fullName>
    <label>File Number</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Is_Certificate_Of_Good_Standing__c.field-meta.xml
<CustomField>
    <fullName>breg_Is_Certificate_Of_Good_Standing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Certificate Of Good Standing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Is_Public__c.field-meta.xml
<CustomField>
    <fullName>breg_Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Transaction__c.field-meta.xml
<CustomField>
    <fullName>breg_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta BREG-3543</description>
    <label>BREG Transaction</label>
    <referenceTo>breg_Transaction__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>breg_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
                <default>true</default>
                <label>Digital</label>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/breg_Form_Configuration__c.object-meta.xml
<CustomObject>
    <label>Form Configuration</label>
    <nameField>
        <label>Form Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>breg_Entity_Type_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Suffix_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Suffix_Code__c</fullName>
    <inlineHelpText>Specifies code of the form, i.e. A1, C-5, etc</inlineHelpText>
    <label>Suffix Code</label>
    <length>99</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Transaction_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Transaction_Code__c</fullName>
    <label>Transaction Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>breg_Transaction_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/breg_Transaction__c.object-meta.xml
<CustomObject>
    <description>Aalta BREG-62</description>
    <label>BREG Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BREG Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Account__c.field-meta.xml
<CustomField>
    <fullName>breg_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta BREG-62</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>breg_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transactions (Case)</relationshipLabel>
    <relationshipName>breg_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>breg_Effective_Date__c</fullName>
    <description>Aalta BREG-62</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_File_Number__c.field-meta.xml
<CustomField>
    <fullName>breg_File_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Number (Deprecated)</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>breg_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Form_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Form_Code__c</fullName>
    <label>Form Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Form_Configuration__c.field-meta.xml
<CustomField>
    <fullName>breg_Form_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Configuration</label>
    <referenceTo>breg_Form_Configuration__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>breg_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Status__c.field-meta.xml
<CustomField>
    <fullName>breg_Status__c</fullName>
    <description>Aalta BREG-62</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Entered</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Received</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>Held</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Purged</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Delinquent</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>??? (I)</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Suspended</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Test</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>aMended</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Bounced Chk</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Transaction_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Transaction_Code__c</fullName>
    <label>Transaction Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>breg_Transaction_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-62</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
                <label>AC - Articles of Correction</label>
            </value>
            <value>
                <fullName>ADD</fullName>
                <label>ADD - Address Change</label>
            </value>
            <value>
                <fullName>ADMBX</fullName>
                <label>ADMBX - Certificate of Administrative Termination</label>
            </value>
            <value>
                <fullName>ADMT</fullName>
                <label>ADMT - Administrative Termination</label>
            </value>
            <value>
                <fullName>AFF</fullName>
                <label>AFF - Affadavit</label>
            </value>
            <value>
                <fullName>AGAD</fullName>
                <label>AGAD - Agent Address Change</label>
            </value>
            <value>
                <fullName>AGC</fullName>
                <label>AGC - Change of Registered Agent</label>
            </value>
            <value>
                <fullName>AGD</fullName>
                <label>AGD - Designation of Agent</label>
            </value>
            <value>
                <fullName>AGR</fullName>
                <label>AGR - Resignation of Agent</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>AM - Amendment</label>
            </value>
            <value>
                <fullName>AMBX</fullName>
                <label>AMBX - Amendment</label>
            </value>
            <value>
                <fullName>AMCN</fullName>
                <label>AMCN - Amendment / Cancellation LLP</label>
            </value>
            <value>
                <fullName>AMIN</fullName>
                <label>AMIN - Articles of Amendment / Increase</label>
            </value>
            <value>
                <fullName>AMNC</fullName>
                <label>AMNC - Articles of Amendment / Name Change</label>
            </value>
            <value>
                <fullName>AMRD</fullName>
                <label>AMRD - Articles of Amendment / Reduction</label>
            </value>
            <value>
                <fullName>AMRS</fullName>
                <label>AMRS - Amended / Restated</label>
            </value>
            <value>
                <fullName>AMRSX</fullName>
                <label>AMRSX - Amended / Restated</label>
            </value>
            <value>
                <fullName>ANN</fullName>
                <label>ANN - Annual Filing</label>
            </value>
            <value>
                <fullName>ANNBX</fullName>
                <label>ANNBX - Annual report/statement</label>
            </value>
            <value>
                <fullName>ART</fullName>
                <label>ART - Articles of Incorporation</label>
            </value>
            <value>
                <fullName>ARTBX</fullName>
                <label>ARTBX - Articles of Incorporation</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>AT - Articles of Termination</label>
            </value>
            <value>
                <fullName>ATBX</fullName>
                <label>ATBX - Articles of Termination</label>
            </value>
            <value>
                <fullName>BSX</fullName>
                <label>BSX - Back Scanned Document</label>
            </value>
            <value>
                <fullName>CC</fullName>
                <label>CC - Certificate of Correction</label>
            </value>
            <value>
                <fullName>CCLP</fullName>
                <label>CCLP - Certificate of Correction</label>
            </value>
            <value>
                <fullName>CERBX</fullName>
                <label>CERBX - Certificate</label>
            </value>
            <value>
                <fullName>CLSF</fullName>
                <label>CLSF - TM/SM Classification</label>
            </value>
            <value>
                <fullName>CMGBX</fullName>
                <label>CMGBX - LLC Merger/Consolidation/Name Change</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>CN - Application For Certificate of Cancellation</label>
            </value>
            <value>
                <fullName>RS</fullName>
                <label>RS - Restated Articles</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Form_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD-1</fullName>
    </customValue>
    <customValue>
        <fullName>ADD</fullName>
    </customValue>
    <customValue>
        <fullName>ADD-MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>ADD-TNTMSM</fullName>
    </customValue>
    <customValue>
        <fullName>AG-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-AG-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-CONS-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-DC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-DNP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FLLC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FLLP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FLP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-GP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-LLC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-LLP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-LP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-PC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-SBC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-SOLE-1</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CONS-1</fullName>
    </customValue>
    <customValue>
        <fullName>DC-1</fullName>
    </customValue>
    <customValue>
        <fullName>DC-10</fullName>
    </customValue>
    <customValue>
        <fullName>DC-12</fullName>
    </customValue>
    <customValue>
        <fullName>DC-13</fullName>
    </customValue>
    <customValue>
        <fullName>DC-2</fullName>
    </customValue>
    <customValue>
        <fullName>DC-3</fullName>
    </customValue>
    <customValue>
        <fullName>DC-4</fullName>
    </customValue>
    <customValue>
        <fullName>DC-5</fullName>
    </customValue>
    <masterLabel>Form Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BREGCaseStatusHandlerRestArtTest.cls
@isTest
private class BREGCaseStatusHandlerRestArtTest {
    @TestSetup
    static void setupData() {
        Id bregAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BREG_Account')?.getRecordTypeId();
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case')?.getRecordTypeId();

        Account entity = new Account(
            Name = 'Restated LLP Entity',
            RecordTypeId = bregAccRecordTypeId,
            breg_Entity_Type__c = 'K5',
            breg_Entity_Status__c = 'Active (A)'
        );
        insert entity;

        Account childGp = new Account(
            Name = 'Restated Child GP',
            RecordTypeId = bregAccRecordTypeId,
            ParentId = entity.Id,
            breg_Entity_Type__c = 'G5',
            breg_Entity_Status__c = 'Active (A)'
        );
        insert childGp;

        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            breg_Suffix_Code__c = 'DC-4',
            breg_Form_Code__c = 'DC-4',
            breg_Entity_Type__c = 'D1'
        );
        insert formConfig;

        Case c = new Case(
            Subject = 'Restated Articles Test Case',
            Status = 'New',
            Origin = 'Web',
            RecordTypeId = bregCaseRecordTypeId,
            breg_Form_Configuration__c = formConfig.Id,
            breg_Form_Code__c = 'DC-4',
            breg_Entity__c = entity.Id,
            breg_Effective_Date__c = Date.today(),
            breg_Name_of_the_Entity__c = 'Restated LLP Entity'
        );
        insert c;

        insert new breg_Document__c(
            Name = 'Approved Restated Doc',
            breg_Case__c = c.Id,
            breg_Is_Public__c = false,
            breg_Type__c = 'Digital',
            breg_Availability__c = 'Available Now',
            breg_Is_Certificate_Of_Good_Standing__c = false
        );
    }

    @isTest
    static void testHandleStatusChangeEmptyInputBranches() {
        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        handler.handleStatusChange(new List<Case>(), 'Pending Submission', true, false);
        handler.handleStatusChange(new List<Case>(), 'Rejected', true, false);
        handler.handleStatusChange(new List<Case>(), 'Approved', false, true);
        handler.handleStatusChange(new List<Case>(), 'Completed', false, true);
        Test.stopTest();

        Assert.isTrue(true, 'Restated Articles handler should execute empty-list branches without errors.');
    }

    @isTest
    static void testCompletedActionMakesDocumentsPublic() {
        Case c = [SELECT Id, breg_Form_Code__c FROM Case WHERE Subject = 'Restated Articles Test Case' LIMIT 1];
        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        try {
            handler.handleStatusChange(new List<Case>{ c }, 'Completed', false, true);
        } catch (Exception e) {
        }
        Test.stopTest();

        breg_Document__c doc = [SELECT Id, breg_Is_Public__c FROM breg_Document__c WHERE breg_Case__c = :c.Id LIMIT 1];
        Assert.areEqual(true, doc.breg_Is_Public__c, 'Approved/Rejected restated documents should be marked public on completion.');
    }

    @isTest
    static void testApprovedActionAndValidationWithLlpChildren() {
        Id bregAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BREG_Account')?.getRecordTypeId();
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case')?.getRecordTypeId();

        Account llpEntity = new Account(
            Name = 'Restated LLP Branch Entity',
            RecordTypeId = bregAccRecordTypeId,
            breg_Entity_Type__c = 'K5',
            breg_Entity_Status__c = 'Active (A)'
        );
        insert llpEntity;

        insert new Account(
            Name = 'Restated Branch GP Child',
            RecordTypeId = bregAccRecordTypeId,
            ParentId = llpEntity.Id,
            breg_Entity_Type__c = 'G5',
            breg_Entity_Status__c = 'Active (A)'
        );

        breg_Form_Configuration__c formConfig = [SELECT Id FROM breg_Form_Configuration__c WHERE breg_Form_Code__c = 'DC-4' LIMIT 1];
        Case c = new Case(
            Subject = 'Restated Approved Branch Case',
            Status = 'New',
            Origin = 'Web',
            RecordTypeId = bregCaseRecordTypeId,
            breg_Form_Configuration__c = formConfig.Id,
            breg_Form_Code__c = 'DC-4',
            breg_Entity__c = llpEntity.Id,
            breg_Name_of_the_Entity__c = llpEntity.Name,
            breg_Effective_Date__c = Date.today(),
            breg_Override_Payment__c = true
        );
        insert c;

        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        handler.handleStatusChange(new List<Case>{ c }, 'Approved', false, true);
        try {
            handler.handleStatusChange(new List<Case>{ c }, 'Approved', true, false);
        } catch (Exception e) {
            Assert.isNotNull(e.getMessage(), 'Approved validation branch should execute.');
        }
        Test.stopTest();

        List<breg_Transaction__c> transactions = [SELECT Id FROM breg_Transaction__c WHERE breg_File_Number__c = :c.Id];
        Assert.isNotNull(transactions, 'Approved action should exercise restated transaction creation paths.');
    }

    @isTest
    static void testRejectedValidationBranch() {
        Case c = [SELECT Id, breg_Form_Code__c FROM Case WHERE Subject = 'Restated Articles Test Case' LIMIT 1];
        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        try {
            handler.handleStatusChange(new List<Case>{ c }, 'Rejected', true, false);
        } catch (Exception e) {
            Assert.isNotNull(e.getMessage(), 'Rejected validation branch should execute even if org-specific rules apply.');
        }
        Test.stopTest();

        Assert.isNotNull(c.Id, 'Rejected validation branch should execute without breaking test context.');
    }

    @isTest
    static void testCompletedActionNoMatchingDocumentsBranch() {
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case')?.getRecordTypeId();
        breg_Form_Configuration__c formConfig = [SELECT Id FROM breg_Form_Configuration__c WHERE breg_Form_Code__c = 'DC-4' LIMIT 1];
        Account entity = [SELECT Id, Name FROM Account WHERE Name = 'Restated LLP Entity' LIMIT 1];

        Case c = new Case(
            Subject = 'Restated No Doc Match Case',
            Status = 'New',
            Origin = 'Web',
            RecordTypeId = bregCaseRecordTypeId,
            breg_Form_Configuration__c = formConfig.Id,
            breg_Form_Code__c = 'DC-4',
            breg_Entity__c = entity.Id,
            breg_Effective_Date__c = Date.today(),
            breg_Name_of_the_Entity__c = entity.Name,
            breg_Override_Payment__c = true
        );
        insert c;

        insert new breg_Document__c(
            Name = 'Non-Matching Restated Doc',
            breg_Case__c = c.Id,
            breg_Is_Public__c = false,
            breg_Type__c = 'Digital',
            breg_Availability__c = 'Available Now',
            breg_Is_Certificate_Of_Good_Standing__c = false
        );

        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        handler.handleStatusChange(new List<Case>{ c }, 'Completed', false, true);
        Test.stopTest();

        breg_Document__c doc = [SELECT breg_Is_Public__c FROM breg_Document__c WHERE breg_Case__c = :c.Id LIMIT 1];
        Assert.areEqual(false, doc.breg_Is_Public__c, 'Completed action should keep non-matching documents unchanged.');
    }

    @isTest
    static void testReceivedCreatesTransactionsForEntityAndChildGp() {
        Case c = [
            SELECT Id, breg_Entity__c, breg_Effective_Date__c, breg_Form_Code__c, breg_Received_Date_Formula__c
            FROM Case
            WHERE Subject = 'Restated Articles Test Case'
            LIMIT 1
        ];
        Account childGp = [SELECT Id FROM Account WHERE Name = 'Restated Child GP' LIMIT 1];
        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        handler.handleStatusChange(new List<Case>{ c }, 'Received', false, true);
        Test.stopTest();

        List<breg_Transaction__c> txnRecords = [
            SELECT Id, breg_Account__c, breg_Transaction_Code__c, breg_Case__c, breg_Status__c
            FROM breg_Transaction__c
            WHERE breg_Case__c = :c.Id AND breg_Transaction_Code__c = 'RS'
        ];

        Set<Id> accountIds = new Set<Id>();
        for (breg_Transaction__c txnRecord : txnRecords) {
            accountIds.add(txnRecord.breg_Account__c);
            Assert.areEqual('R', txnRecord.breg_Status__c, 'Restated Articles Received transactions should be in Received status.');
        }

        Assert.isTrue(accountIds.contains(c.breg_Entity__c), 'Entity RS transaction should be created.');
        Assert.isTrue(accountIds.contains(childGp.Id), 'Child GP RS transaction should be created for LLP entities.');
    }

    @isTest
    static void testReceivedCreatesOnlyEntityTransactionForNonLlp() {
        Id bregAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BREG_Account')?.getRecordTypeId();
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case')?.getRecordTypeId();
        breg_Form_Configuration__c formConfig = [SELECT Id FROM breg_Form_Configuration__c WHERE breg_Form_Code__c = 'DC-4' LIMIT 1];

        Account entity = new Account(
            Name = 'Restated Non LLP Entity',
            RecordTypeId = bregAccRecordTypeId,
            breg_Entity_Type__c = 'D1',
            breg_Entity_Status__c = 'Active (A)'
        );
        insert entity;

        Case c = new Case(
            Subject = 'Restated Non LLP Received Case',
            Status = 'New',
            Origin = 'Web',
            RecordTypeId = bregCaseRecordTypeId,
            breg_Form_Configuration__c = formConfig.Id,
            breg_Form_Code__c = 'DC-4',
            breg_Entity__c = entity.Id,
            breg_Effective_Date__c = Date.today(),
            breg_Name_of_the_Entity__c = entity.Name,
            breg_Override_Payment__c = true
        );
        insert c;

        BREGCaseStatusHandlerRestatedArticles handler = new BREGCaseStatusHandlerRestatedArticles();

        Test.startTest();
        handler.handleStatusChange(new List<Case>{ c }, 'Received', false, true);
        Test.stopTest();

        List<breg_Transaction__c> transactions = [
            SELECT Id, breg_Account__c, breg_Transaction_Code__c
            FROM breg_Transaction__c
            WHERE breg_Case__c = :c.Id AND breg_Transaction_Code__c = 'RS'
        ];

        Assert.areEqual(1, transactions.size(), 'Non-LLP restated cases should only create one entity RS transaction.');
        Assert.areEqual(entity.Id, transactions[0].breg_Account__c, 'RS transaction should be linked to the entity account.');
    }
}