force-app/main/default/objects/breg_Document__c/breg_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Document__c/fields/breg_Annotation__c.field-meta.xml
<CustomField>
    <fullName>breg_Annotation__c</fullName>
    <description>Contains annotation JSON information. The field is not to be manipulated outside of PDF Editor</description>
    <label>Annotation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Docusign_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>breg_Docusign_Document_Id__c</fullName>
    <externalId>true</externalId>
    <label>Docusign Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Document__c/fields/breg_Is_Public__c.field-meta.xml
<CustomField>
    <fullName>breg_Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BREGExternalAPIGetDocument.cls
@RestResource(urlMapping='/api/getBregDocument')
global with sharing class BREGExternalAPIGetDocument {
    global class GetDocumentResponse {
        public String base64Document { get; set; }
        public String errorMessage { get; set; }
        public String documentName { get; set; }
        public Boolean isPublic { get; set; }
        public String annotation { get; set; }
        public DateTime dateFiled { get; set; }
    }

    @HttpGet
    global static GetDocumentResponse getDocumentById() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        GetDocumentResponse response = new GetDocumentResponse();

        // Get documentId from query parameter
        Map<String, Object> requestBody = (Map<String, Object>) JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        if (requestBody.isEmpty()) {
            response.errorMessage = 'Missing required parameter: documentId';
            RestContext.response.statusCode = 500;
            return response;
        }

        String documentId = (String) requestBody.get('documentId');

        // Query breg_Document__c for DocuSign Document Id
        breg_Document__c doc;
        try {
            doc = [
                SELECT Id, Name, breg_Docusign_Document_Id__c, breg_Is_Public__c, breg_Annotation__c, breg_Case__r.breg_Submission_Date__c
                FROM breg_Document__c
                WHERE Id = :documentId
            ];
            response.documentName = doc.Name;
            response.isPublic = doc.breg_Is_Public__c;
            response.annotation = doc.breg_Annotation__c;
            response.dateFiled = doc.breg_Case__r?.breg_Submission_Date__c;
        } catch (Exception ex) {
            response.errorMessage = 'Failed to retrieve document from DocuSign. ' + ex.getMessage();
            RestContext.response.statusCode = 500;
            return response;
        }

        Blob documentBlob;
        try {
            // Get the document blob from DocuSignAPI
            documentBlob = Test.isRunningTest() ? Blob.valueOf('PDF content') : DocuSignAPI.getDocumentBlob(doc.breg_Docusign_Document_Id__c ,false);
        } catch (Exception ex) {
            response.errorMessage = 'Failed to retrieve document from DocuSign. ' + ex.getMessage();
            RestContext.response.statusCode = 500;
            return response;
        }

        try {
            // Encode blob to base64 string
            response.base64Document = EncodingUtil.base64Encode(documentBlob);
        } catch (Exception ex) {
            response.errorMessage = 'Failed to encode document to base64. ' + ex.getMessage();
            RestContext.response.statusCode = 500;
        }

        return response;
    }
}