force-app/main/default/objects/CollectionsAllocation__c/CollectionsAllocation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT012619 - Created for phase1</description>
    <label>Collections Allocation</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Collections Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsAllocation__c/fields/CutOffBatchDate__c.field-meta.xml
<CustomField>
    <fullName>CutOffBatchDate__c</fullName>
    <description>PacPoint-PH030819 - Created for phase 1</description>
    <label>Close Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT030319 - Created for phase 1</description>
    <label>Deposit</label>
    <referenceTo>Deposits__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/DepositDate__c.field-meta.xml
<CustomField>
    <fullName>DepositDate__c</fullName>
    <formula>Deposit__r.DepositDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deposit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/TransactionLine__c.field-meta.xml
<CustomField>
    <fullName>TransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction Line</label>
    <referenceTo>TransactionLine__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deposits__c/Deposits__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070318 - Created for phase 1</description>
    <label>Deposits</label>
    <nameField>
        <displayFormat>DEP-{00000}</displayFormat>
        <label>Deposit Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposits__c/fields/DepositDate__c.field-meta.xml
<CustomField>
    <fullName>DepositDate__c</fullName>
    <description>PacPoint-FT070218 - Created for phase 1</description>
    <label>Deposit Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deposits__c/fields/DepositNumber__c.field-meta.xml
<CustomField>
    <fullName>DepositNumber__c</fullName>
    <description>PacPoint-070218 - Created for phase 1</description>
    <label>Deposit Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/FiscalForm__c.object-meta.xml
<CustomObject>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA - Fiscal Forms CR - Creating to capture the Fiscal Form records.</description>
    <label>Fiscal Form</label>
    <nameField>
        <label>Fiscal Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FiscalForm__c/recordTypes/RECWKST.recordType-meta.xml
<RecordType>
    <fullName>RECWKST</fullName>
    <active>true</active>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA - Fiscal Forms CR - Creating to capture the Fiscal Form records.</description>
    <label>RECWKST</label>
</RecordType>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/WorkitemID__c.field-meta.xml
<CustomField>
    <fullName>WorkitemID__c</fullName>
    <label>Workitem ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/WorkitemID__c.field-meta.xml
<CustomField>
    <fullName>WorkitemID__c</fullName>
    <description>PacPoint-FT082218 - Created for phase 1

To be used by BREG to associate to records scanned into BRIMS</description>
    <label>Workitem ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentRecwkstCmpControllerTest.cls
@isTest
public with sharing class PaymentRecwkstCmpControllerTest {
    @TestSetup
    static void makeData(){
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Contact cnt = new Contact(LastName = 'TestCon', AccountId = acc.Id);
        insert cnt;
        
        
        date sd = Date.Today();
        
        Deposits__c xDeposit = new Deposits__c();
        xDeposit.DepositDate__c = sd;
        xDeposit.DepositNumber__c = '223322';
        xDeposit.DepositNumber__c = 'Draft';
        insert xDeposit;
        
        List<pymt__PaymentX__c> payments = new List<pymt__PaymentX__c>();
        
        pymt__PaymentX__c currentYearPayment1 = new pymt__PaymentX__c();
        currentYearPayment1.pymt__Status__c = 'Completed';
        currentYearPayment1.pymt__Date__c = Date.newInstance(sd.year(),1,12);
        currentYearPayment1.RemitToDCCA__c = 50; 
        currentYearPayment1.PPIFeeAmount__c = 100;
        currentYearPayment1.HIGETaxAmount__c = 150; 
        currentYearPayment1.DepositBatch__c = xDeposit.Id;
        currentYearPayment1.pymt__Payment_Type__c = 'Cash';
        payments.add(currentYearPayment1);

        pymt__PaymentX__c currentYearPayment2 = new pymt__PaymentX__c();
        currentYearPayment2.pymt__Status__c = 'Completed';
        currentYearPayment2.pymt__Date__c = Date.newInstance(sd.year(),1,12);
        currentYearPayment2.RemitToDCCA__c = 50; 
        currentYearPayment2.PPIFeeAmount__c = 100;
        currentYearPayment2.HIGETaxAmount__c = 150; 
        currentYearPayment2.DepositBatch__c = xDeposit.Id;
        currentYearPayment2.pymt__Payment_Type__c = 'Check or Money Order';
        payments.add(currentYearPayment2);
        
        pymt__PaymentX__c currentYearPayment3 = new pymt__PaymentX__c();
        currentYearPayment3.pymt__Status__c = 'Completed';
        currentYearPayment3.pymt__Date__c = Date.newInstance(sd.year(),1,12);
        currentYearPayment3.RemitToDCCA__c = 50; 
        currentYearPayment3.PPIFeeAmount__c = 100;
        currentYearPayment3.HIGETaxAmount__c = 150; 
        currentYearPayment3.DepositBatch__c = xDeposit.Id;
        currentYearPayment3.pymt__Payment_Type__c = 'Credit Card';
        payments.add(currentYearPayment3);
        
        insert payments;
        
        Transaction__c trns1 = new Transaction__c();
        trns1.Account__c = acc.Id;
        trns1.WorkitemID__c = '1';
        insert trns1;
        
        TransactionLine__c trLine = new TransactionLine__c();
        trLine.Transaction__c = trns1.Id;
        insert trLine;
        
        CollectionsAllocation__c alloc = new CollectionsAllocation__c();
        alloc.Deposit__c = xDeposit.Id;
        alloc.TransactionLine__c = trLine.Id;
        alloc.CutOffBatchDate__c = System.now();
        alloc.Payment__c = currentYearPayment1.Id;
        insert alloc;
    }
    public static testMethod void testReport() {
        PaymentRecwkstCmpController.runReport(Date.Today().addDays(-400));
        List<pymt__PaymentX__c> payments = [
            SELECT
                    Id,
                    pymt__Payment_Type__c,
                    pymt__Amount__c,
                    CreatedBy.Terminal__c
            FROM pymt__PaymentX__c];
        for(pymt__PaymentX__c record: payments) {
            record.pymt__Amount__c = 233.32;
        }
        PaymentRecwkstCmpController.RecwkstReport rec = new PaymentRecwkstCmpController.RecwkstReport(payments);
    }
    public static testMethod void testSaveAndCreateFile() {
        Schema.DescribeSObjectResult d = Schema.SObjectType.FiscalForm__c; 
        Map<String ,Schema.RecordTypeInfo> rtMapById = d.getRecordTypeInfosByName();
        String recordTypeId =  rtMapById.get('RECWKST').getRecordTypeId();
        String data = + '{"runningUser":{"attributes":{"type":"User"},"FirstName":"Alvin","LastName":"Zhou"},"batchDate":"2020-11-02","runningName":"Alvin Zhou","batchDate2":"2020-11-02","terminal3TotalCash":0,"terminal13TotalCash":0,'
        +' "terminal3TotalCoins":0,"terminal13TotalCoins":0,"terminal3TotalCheck":0,"terminal13TotalCheck":0,"tape1Check":0,"tape2Check":0,"tape3Check":0,"tape4Check":0,"tape5Check":0,"tape6Check":0,"tape1CheckTextarea":"",'
        +' "tape2CheckTextarea":"","tape3CheckTextarea":"","tape4CheckTextarea":"","tape5CheckTextarea":"","tape6CheckTextarea":"","moreTapesCheck":[],"calculatedValue":0,"gov3TotalCheck":0,"gov13TotalCheck":0,"totalDeposit":0,'
        +' "totalCash":0,"totalCoins":0,"totalReceipt":0,"depositNotesTextarea":""}';
        String recordId = PaymentRecwkstCmpController.saveAndCreateFile(null, data, recordTypeId);
        PaymentRecwkstCmpController.getCutOffDate(recordId);

    }
}