force-app/main/default/objects/InsuranceBond__c/InsuranceBond__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Insurance &amp; Bond</label>
    <nameField>
        <displayFormat>IB-{00000}</displayFormat>
        <label>Insurance / Bond Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance &amp; Bonds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InsuranceBond__c/fields/CurrentGapInInsurance__c.field-meta.xml
<CustomField>
    <fullName>CurrentGapInInsurance__c</fullName>
    <description>PacPoint-KN081519 - Created for PVL Phase 1</description>
    <label>Current Gap In Insurance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsuranceBond__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Insurance &amp; Bonds</relationshipLabel>
    <relationshipName>Insurance_Bonds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InsuranceBond__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BD - Bond</fullName>
            </value>
            <value>
                <fullName>BX - Bond Exemption (All Boards)</fullName>
            </value>
            <value>
                <fullName>D - Employee Dishonesty Insurance</fullName>
            </value>
            <value>
                <fullName>EX - Exemption</fullName>
            </value>
            <value>
                <fullName>FS - Pre-Need Funeral Service Trust</fullName>
            </value>
            <value>
                <fullName>GM - Perpetual Care (Ground Maintenance) Trust</fullName>
            </value>
            <value>
                <fullName>LC - Line of Credit</fullName>
            </value>
            <value>
                <fullName>LI - Liability</fullName>
            </value>
            <value>
                <fullName>LP - Liability / Property Damage</fullName>
            </value>
            <value>
                <fullName>PI - Pre-Need Interment (Burial) Services Trust</fullName>
            </value>
            <value>
                <fullName>SI - Exclusion from Workers Comp.</fullName>
            </value>
            <value>
                <fullName>SL - Self-Insured for W/C (Entity OK&apos;d By Labor Dept)</fullName>
            </value>
            <value>
                <fullName>SM - No HI Employees - Submit Workers Comp Prior to Hiring</fullName>
            </value>
            <value>
                <fullName>SW - Workers Comp Thru Leasing Co.</fullName>
            </value>
            <value>
                <fullName>SX - Exemption No Longer Allowed</fullName>
            </value>
            <value>
                <fullName>T1 - Client Trust Account #1</fullName>
            </value>
            <value>
                <fullName>T2 - Client Trust Account #2</fullName>
            </value>
            <value>
                <fullName>T3 - Client Trust Account #3</fullName>
            </value>
            <value>
                <fullName>T4 - Client Trust Account #4</fullName>
            </value>
            <value>
                <fullName>T5 - Client Trust Account #5</fullName>
            </value>
            <value>
                <fullName>TC - Charter Tour</fullName>
            </value>
            <value>
                <fullName>WC - Workers Compensation</fullName>
            </value>
            <value>
                <fullName>WP - Submit Prior to Hiring Hi Empl - Evidence of WC Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/CurrentGapInInsurance__c.field-meta.xml
<CustomField>
    <fullName>CurrentGapInInsurance__c</fullName>
    <description>PacPoint-KN081519 - Created for PVL Phase 1</description>
    <label>Current Gap In Insurance</label>
    <summarizedField>InsuranceBond__c.CurrentGapInInsurance__c</summarizedField>
    <summaryFilterItems>
        <field>InsuranceBond__c.Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>InsuranceBond__c.License__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/InsuranceBondTypesRequired__c.field-meta.xml
<CustomField>
    <fullName>InsuranceBondTypesRequired__c</fullName>
    <description>PacPoint-DN02042020 - Created for PVL Sprint 3 Phase 1</description>
    <label>Insurance/Bond Type(s) Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BD - Bond</fullName>
            </value>
            <value>
                <fullName>BX - Bond Exemption (All Boards)</fullName>
            </value>
            <value>
                <fullName>EX - Exemption</fullName>
            </value>
            <value>
                <fullName>FS - Pre-Need Funeral Service Trust</fullName>
            </value>
            <value>
                <fullName>GM - Perpetual Care (Ground Maintenance) Trust</fullName>
            </value>
            <value>
                <fullName>LC - Line of Credit</fullName>
            </value>
            <value>
                <fullName>LI - Liability</fullName>
            </value>
            <value>
                <fullName>LP - Liability / Property Damage</fullName>
            </value>
            <value>
                <fullName>PI - Pre-Need Interment (Burial) Services Trust</fullName>
            </value>
            <value>
                <fullName>SI - Exclusion from Workers Comp.</fullName>
            </value>
            <value>
                <fullName>SL - Self-Insured for W/C (Entity OK&apos;d By Labor Dept)</fullName>
            </value>
            <value>
                <fullName>SM - No HI Employees - Submit Workers Comp Prior to Hiring</fullName>
            </value>
            <value>
                <fullName>SW - Workers Comp Thru Leasing Co.</fullName>
            </value>
            <value>
                <fullName>SX - Exemption No Longer Allowed</fullName>
            </value>
            <value>
                <fullName>T1 - Client Trust Account #1</fullName>
            </value>
            <value>
                <fullName>T2 - Client Trust Account #2</fullName>
            </value>
            <value>
                <fullName>T3 - Client Trust Account #3</fullName>
            </value>
            <value>
                <fullName>T4 - Client Trust Account #4</fullName>
            </value>
            <value>
                <fullName>T5 - Client Trust Account #5</fullName>
            </value>
            <value>
                <fullName>TC - Charter Tour</fullName>
            </value>
            <value>
                <fullName>WC - Workers Compensation</fullName>
            </value>
            <value>
                <fullName>WP - Submit Prior to Hiring Hi Empl - Evidence of WC Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LicenseCheckInsuranceRequirementsTest.cls
@isTest
private class LicenseCheckInsuranceRequirementsTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.insertInsuranceBonds();
        
    }
    // @isTest
    // static void testCheckInsuranceRequirementException() {
    //     Test.startTest();
    //     String licenseIdErrorMessage;
    //     try{
    //         LicenseCheckInsuranceRequirements.checkInsuranceRequirements(new List<String>());
    //     } catch(LicenseCheckInsuranceRequirements.CustomFlowException ex) {
    //         licenseIdErrorMessage = ex.getMessage();
    //     }
    //     String errorMessage;
    //     try{
    //         LicenseCheckInsuranceRequirements.checkInsuranceRequirements(new List<String>{'test'});
    //     } catch(LicenseCheckInsuranceRequirements.CustomFlowException ex) {
    //         errorMessage = ex.getMessage();
    //     }
        
    //     Test.stopTest();
    //     System.assert(errorMessage != null);
    //     System.assert(licenseIdErrorMessage != null);
    // }

    @isTest
    static void testCheckInsuranceRequirementsTrue() {
        License__c record = [Select Id from License__c limit 1];
        List<InsuranceBond__c> bonds = [Select Id, Type__c,License__c, License__r.LicenseType__r.Id, License__r.LicenseType__r.InsuranceBondTypesRequired__c , CurrentGapInInsurance__c from InsuranceBond__c where License__c =: record.Id];
        Set<String> types = new Set<String>();
        LicenseType__c licenseType;
        for(InsuranceBond__c bond: bonds) {
            bond.CurrentGapInInsurance__c = 0;
            types.add(bond.Type__c);
            licenseType = bond.License__r.LicenseType__r;
        }
        List<String> typeList = new List<String>();
        typeList.addAll(types);
        String requiredTypes = String.join(typeList, ';');
        licenseType.InsuranceBondTypesRequired__c = requiredTypes;
        update licenseType;
        update bonds;

        

        Test.startTest();
        List<Boolean> results = LicenseCheckInsuranceRequirements.checkInsuranceRequirements(new List<String> {record.Id});
        Test.stopTest();
        System.assertEquals(results.get(0), true);
        
    }

    @isTest
    static void testCheckInsuranceRequirementsFalse() {
        List<InsuranceBond__c> bonds = [Select Id, Type__c,License__c, License__r.LicenseType__r.Id, License__r.LicenseType__r.InsuranceBondTypesRequired__c , CurrentGapInInsurance__c from InsuranceBond__c];
        String type;
        LicenseType__c licenseType;
        for(InsuranceBond__c bond: bonds) {
            bond.CurrentGapInInsurance__c = 0;
            type = bond.Type__c;
            licenseType = bond.License__r.LicenseType__r;
        }
        licenseType.InsuranceBondTypesRequired__c = type;
        update licenseType;
        update bonds;

        License__c record = [Select Id from License__c limit 1];


        Test.startTest();
        List<Boolean> results = LicenseCheckInsuranceRequirements.checkInsuranceRequirements(new List<String> {record.Id});
        Test.stopTest();
        System.assertEquals(results.get(0), false);
        
    }
    
}