force-app/main/default/objects/InsuranceBond__c/InsuranceBond__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Insurance &amp; Bond</label>
    <nameField>
        <displayFormat>IB-{00000}</displayFormat>
        <label>Insurance / Bond Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance &amp; Bonds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InsuranceBond__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Insurance &amp; Bonds</relationshipLabel>
    <relationshipName>Insurance_Bonds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/BreakinInsuranceCoverageAllowed__c.field-meta.xml
<CustomField>
    <fullName>BreakinInsuranceCoverageAllowed__c</fullName>
    <description>PacPoint-KN081519 - Created for PVL Phase 1</description>
    <inlineHelpText>In Days</inlineHelpText>
    <label>Break in Insurance Coverage Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/InsuranceBondTypesRequired__c.field-meta.xml
<CustomField>
    <fullName>InsuranceBondTypesRequired__c</fullName>
    <description>PacPoint-DN02042020 - Created for PVL Sprint 3 Phase 1</description>
    <label>Insurance/Bond Type(s) Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BD - Bond</fullName>
            </value>
            <value>
                <fullName>BX - Bond Exemption (All Boards)</fullName>
            </value>
            <value>
                <fullName>EX - Exemption</fullName>
            </value>
            <value>
                <fullName>FS - Pre-Need Funeral Service Trust</fullName>
            </value>
            <value>
                <fullName>GM - Perpetual Care (Ground Maintenance) Trust</fullName>
            </value>
            <value>
                <fullName>LC - Line of Credit</fullName>
            </value>
            <value>
                <fullName>LI - Liability</fullName>
            </value>
            <value>
                <fullName>LP - Liability / Property Damage</fullName>
            </value>
            <value>
                <fullName>PI - Pre-Need Interment (Burial) Services Trust</fullName>
            </value>
            <value>
                <fullName>SI - Exclusion from Workers Comp.</fullName>
            </value>
            <value>
                <fullName>SL - Self-Insured for W/C (Entity OK&apos;d By Labor Dept)</fullName>
            </value>
            <value>
                <fullName>SM - No HI Employees - Submit Workers Comp Prior to Hiring</fullName>
            </value>
            <value>
                <fullName>SW - Workers Comp Thru Leasing Co.</fullName>
            </value>
            <value>
                <fullName>SX - Exemption No Longer Allowed</fullName>
            </value>
            <value>
                <fullName>T1 - Client Trust Account #1</fullName>
            </value>
            <value>
                <fullName>T2 - Client Trust Account #2</fullName>
            </value>
            <value>
                <fullName>T3 - Client Trust Account #3</fullName>
            </value>
            <value>
                <fullName>T4 - Client Trust Account #4</fullName>
            </value>
            <value>
                <fullName>T5 - Client Trust Account #5</fullName>
            </value>
            <value>
                <fullName>TC - Charter Tour</fullName>
            </value>
            <value>
                <fullName>WC - Workers Compensation</fullName>
            </value>
            <value>
                <fullName>WP - Submit Prior to Hiring Hi Empl - Evidence of WC Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LicenseCheckInsuranceRequirements.cls
/****
 * Description: 27880
 * Created by: pacificpointcorpaz000027880
 * ******/
public class LicenseCheckInsuranceRequirements {
    public static final List<String> dedicatedStatus = new List<String>{'Active', 'Waived', 'Pending'};
    public class CustomFlowException extends Exception {}

    @InvocableMethod(label='License: Check Insurance Requirements' description='This method can be called from a flow.')
    public static List<Boolean> checkInsuranceRequirements(List<String> inputStrings) {
        List<String> insuranceType_S = new List<String>();
        // // Your method implementation will go here
        // // Assuming that the license Id has been attached.
        // if(inputStrings.isEmpty()) {
        //     throw new CustomFlowException('Please make sure the license Id can be attached.');
        // }

        //
        List<License__c> licenses = [Select Id, LicenseType__r.InsuranceBondTypesRequired__c, 
            LicenseType__r.BreakinInsuranceCoverageAllowed__c from License__c where Id in: inputStrings];
        Map<Id, License__c> licenseMap = new Map<Id, License__c>(licenses);
        // if(licenses.isEmpty()) {
        //     throw new CustomFlowException('Please make sure the license Id is valid.');
        // }
        List<String> licenseIds = (new LicenseDomain(licenses)).getIds();
        List<InsuranceBond__c> insuranceBonds = InsuranceBondSelector.getInsuranceBonds(licenseIds);
        Map<String, List<InsuranceBond__c>> insuranceBondsMap = (new InsuranceBondDomain(insuranceBonds)).getLicenseId2InsuranceBonds();
        List<Boolean> results = new List<Boolean>();
        for(String licenseId: inputStrings) {
            Boolean isValid = true;
            License__c record = licenseMap.get(licenseId);
            List<InsuranceBond__c> bonds = insuranceBondsMap.get(licenseId);
            if(bonds != null && !bonds.isEmpty() && record != null) {
                Set<String> typeSetRequired = (new InsuranceBondDomain(bonds)).getMissingRequiredTypes(record);
                if(!typeSetRequired.isEmpty()) isValid = false;
            }
            results.add(isValid);
        }
        // typeSetRequired is empty means all the required license types are met under the insurance bond type value.
        return results;
    }
}