force-app/main/default/objects/InsuranceBond__c/InsuranceBond__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Insurance &amp; Bond</label>
    <nameField>
        <displayFormat>IB-{00000}</displayFormat>
        <label>Insurance / Bond Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance &amp; Bonds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InsuranceBond__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Insurance &amp; Bonds</relationshipLabel>
    <relationshipName>Insurance_Bonds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InsuranceBond__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsuranceBond__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-KN081519 - Created for PVL Phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/InsurancePortalSubmission__c.object-meta.xml
<CustomObject>
    <label>Insurance Portal Submission</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Insurance Portal Submissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Portal Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/AdditionalComments__c.field-meta.xml
<CustomField>
    <fullName>AdditionalComments__c</fullName>
    <label>Additional Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/AuthorizedRepresentative__c.field-meta.xml
<CustomField>
    <fullName>AuthorizedRepresentative__c</fullName>
    <label>Authorized Representative</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/ErrorReason__c.field-meta.xml
<CustomField>
    <fullName>ErrorReason__c</fullName>
    <label>Error Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance</label>
    <referenceTo>InsuranceBond__c</referenceTo>
    <relationshipLabel>Insurance Portal Submissions</relationshipLabel>
    <relationshipName>Insurance_Portal_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/InsuranceType__c.field-meta.xml
<CustomField>
    <fullName>InsuranceType__c</fullName>
    <label>Insurance Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/InsurerAffordingCoverage__c.field-meta.xml
<CustomField>
    <fullName>InsurerAffordingCoverage__c</fullName>
    <label>Insurer Affording Coverage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Insurance Portal Submissions</relationshipLabel>
    <relationshipName>Insurance_Portal_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/LimitEachOccurrence__c.field-meta.xml
<CustomField>
    <fullName>LimitEachOccurrence__c</fullName>
    <label>Limit Each Occurrence</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyCancellationDate__c.field-meta.xml
<CustomField>
    <fullName>PolicyCancellationDate__c</fullName>
    <formula>DATEVALUE(PolicyCancellationDateYear__c &amp; &quot;-&quot; &amp; PolicyCancellationDateMonth__c &amp; &quot;-&quot; &amp; PolicyCancellationDateDay__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyCancellationDateDay__c.field-meta.xml
<CustomField>
    <fullName>PolicyCancellationDateDay__c</fullName>
    <label>Policy Cancellation Date Day</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyCancellationDateMonth__c.field-meta.xml
<CustomField>
    <fullName>PolicyCancellationDateMonth__c</fullName>
    <label>Policy Cancellation Date Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyCancellationDateYear__c.field-meta.xml
<CustomField>
    <fullName>PolicyCancellationDateYear__c</fullName>
    <label>Policy Cancellation Date Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>PolicyEffectiveDate__c</fullName>
    <formula>DATEVALUE(PolicyEffectiveDateYear__c &amp; &quot;-&quot; &amp; PolicyEffectiveDateMonth__c &amp; &quot;-&quot; &amp; PolicyEffectiveDateDay__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyEffectiveDateDay__c.field-meta.xml
<CustomField>
    <fullName>PolicyEffectiveDateDay__c</fullName>
    <label>Policy Effective Date Day</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyEffectiveDateMonth__c.field-meta.xml
<CustomField>
    <fullName>PolicyEffectiveDateMonth__c</fullName>
    <label>Policy Effective Date Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyEffectiveDateYear__c.field-meta.xml
<CustomField>
    <fullName>PolicyEffectiveDateYear__c</fullName>
    <label>Policy Effective Date Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>PolicyExpirationDate__c</fullName>
    <formula>DATEVALUE(PolicyExpirationDateYear__c &amp; &quot;-&quot; &amp; PolicyExpirationDateMonth__c &amp; &quot;-&quot; &amp; PolicyExpirationDateDay__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyExpirationDateDay__c.field-meta.xml
<CustomField>
    <fullName>PolicyExpirationDateDay__c</fullName>
    <label>Policy Expiration Date Day</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyExpirationDateMonth__c.field-meta.xml
<CustomField>
    <fullName>PolicyExpirationDateMonth__c</fullName>
    <label>Policy Expiration Date Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyExpirationDateYear__c.field-meta.xml
<CustomField>
    <fullName>PolicyExpirationDateYear__c</fullName>
    <label>Policy Expiration Date Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PVLLicenseNumber__c.field-meta.xml
<CustomField>
    <fullName>PVLLicenseNumber__c</fullName>
    <label>PVL License Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PVLLicenseType__c.field-meta.xml
<CustomField>
    <fullName>PVLLicenseType__c</fullName>
    <label>PVL License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/PVLPortalUser__c.field-meta.xml
<CustomField>
    <fullName>PVLPortalUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PVL Portal User</label>
    <referenceTo>PVL_Portal_User__c</referenceTo>
    <relationshipLabel>Insurance Portal Submissions</relationshipLabel>
    <relationshipName>Insurance_Portal_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePortalSubmission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Successfully Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Manually Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InsurancePortalSubmissionBatch.cls
global class InsurancePortalSubmissionBatch implements schedulable, Database.Batchable<SObject>, Database.Stateful {
    public String query ;
    public List<Id> allLicenseIds = new List<Id>();
    global InsurancePortalSubmissionBatch() {
        query = 'Select Id, AdditionalComments__c, AuthorizedRepresentative__c, Email__c, Insurance__c, '
            +'ErrorReason__c, InsuranceType__c, InsurerAffordingCoverage__c, License__c, LimitEachOccurrence__c, '
            +'PolicyCancellationDate__c, PolicyCancellationDateDay__c, PolicyCancellationDateMonth__c, PolicyCancellationDateYear__c,'
            +' PolicyEffectiveDate__c, PolicyEffectiveDateDay__c, PolicyEffectiveDateMonth__c, PolicyEffectiveDateYear__c, '
            +'PolicyExpirationDate__c, PolicyExpirationDateDay__c, PolicyExpirationDateMonth__c, PolicyExpirationDateYear__c, '
            +'PolicyNumber__c, PVLLicenseNumber__c, PVLLicenseType__c, PVLPortalUser__c, Status__c, SubmitterType__c,'
            +' TransactionType__c from InsurancePortalSubmission__c '
            + ' where Status__c = \'Submitted\' and ( SubmitterType__c = \'Licensed Insurance Agent\' ' 
            + ' or (SubmitterType__c = \'Not Admitted Insurer or Leasing Company\' and NonLicensedInsurerSubmittal_Approved__c = TRUE ))';
    }
    /* batch start class */
    global DataBase.QueryLocator Start(Database.BatchableContext context) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext context, List<SObject> scope) {
        LicenseService.disableUpdateAssociatedEntity = true;
        List<InsurancePortalSubmission__c> portalSubmissions = (List<InsurancePortalSubmission__c> )scope;
        List<InsurancePortalSubmission__c> filteredRecordsForInsurance = (new InsurancePortalSubmissionDomain(
            portalSubmissions)).filterInsurancePortalSubmissionForBondCreate();
        List<InsuranceBond__c> bonds = (new InsurancePortalSubmissionDomain(filteredRecordsForInsurance)).createInsuranceCoverage();

        // If the duplicate rule is an alert rule, we can try to bypass it
        Database.DMLOptions dml = new Database.DMLOptions(); 
        dml.DuplicateRuleHeader.AllowSave = true;
       
        List<Database.SaveResult> results = Database.insert(bonds, dml);
        for(Integer i= 0;i< results.size(); i++) {
            if(results.get(i).isSuccess()) {
                filteredRecordsForInsurance.get(i).Insurance__c = results.get(i).getId();
                filteredRecordsForInsurance.get(i).Status__c = 'Successfully Processed';
            } else {
                filteredRecordsForInsurance.get(i).Status__c = 'Error';
            }
        }
        


        List<InsurancePortalSubmission__c> recordsForCancellation = (new InsurancePortalSubmissionDomain(portalSubmissions)).filterInsurancePortalSubmissionForCancellation();
        List<String> licenseIds = (List<String>) (new InsurancePortalSubmissionDomain(recordsForCancellation)).getFieldValues('License__c');
        List<InsuranceBond__c> insuranceBondForCancellation = InsuranceBondSelector.getInsuranceBonds(licenseIds);
        Map<String, List<InsurancePortalSubmission__c>> insurancePortalSubmissionMap = (new InsurancePortalSubmissionDomain(
            recordsForCancellation)).convertLicenseIdToInsurancePortalSubmission();
        
        List<InsuranceBond__c> bondsForUpdate = (new InsuranceBondDomain(
                insuranceBondForCancellation)).updateInsuranceBondForCancellation(insurancePortalSubmissionMap);
        
        List<Database.SaveResult> updateResults = Database.update(bondsForUpdate, dml);
        
        Map<String, String> messageMap = new Map<String, String>();
        for(Database.SaveResult savedResult : updateResults) {
            if(savedResult.isSuccess()) {
                messageMap.put(savedResult.getId(), 'Successfully Processed');
            } else {
                messageMap.put(savedResult.getId(), 'Error');
            }
        }

        List<InsurancePortalSubmission__c> cancelledSubmissionsForUpdate = (new InsuranceBondDomain(insuranceBondForCancellation)).updateInsuranceSubmissionStatus(
            insurancePortalSubmissionMap, messageMap);
        List<String> cancelledSubmissionIds = (new InsurancePortalSubmissionDomain(cancelledSubmissionsForUpdate)).getIds();
        Set<String> cancelledSubmissionIdSet = new Set<String>();
        cancelledSubmissionIdSet.addAll(cancelledSubmissionIds);
        filteredRecordsForInsurance.addAll(cancelledSubmissionsForUpdate);
        /****** Set the InsurancePortalSubmission__c.Status__c = "Error"

Set the Error Reason = "Unable to find a matching Insurance Record" 
 */
        filteredRecordsForInsurance.addAll((new InsurancePortalSubmissionDomain(recordsForCancellation)).failRemainingCancelledInsurancePortalSubmission(cancelledSubmissionIdSet));
        update filteredRecordsForInsurance;
        allLicenseIds.addAll(licenseIds);

    }
    public void execute(System.SchedulableContext context) {
        Database.executeBatch(new InsurancePortalSubmissionBatch(), 50);
	}
	/* batch finish class */
    global void finish(Database.BatchableContext context) {
        if(!allLicenseIds.isEmpty()) {
            Database.executeBatch(new BatchUpdateActiveEmployeeLicenseNum(allLicenseIds), 50);
            allLicenseIds.clear();
        }
    }
}