force-app/main/default/objects/CaseTeamAssignment__c/CaseTeamAssignment__c.object-meta.xml
<CustomObject>
    <description>Many-to-many relationship between PUC Case and Case Team Member. When a record of this object is inserted, it gives access to a PUC Case based on CaseTeamMember.Access__c.</description>
    <label>Case Team Assignment</label>
    <nameField>
        <displayFormat>CTA-{000000}</displayFormat>
        <label>Case Team Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Team Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseTeamAssignment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Team</relationshipLabel>
    <relationshipName>CaseTeamAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EmailAlertTrigger__c/EmailAlertTrigger__c.object-meta.xml
<CustomObject>
    <description>to bypass limit of 5k apex email sends, insert records of this object to trigger email alerts</description>
    <label>Email Alert Trigger</label>
    <nameField>
        <label>Email Alert Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Alert Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailAlertTrigger__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Email Alert Triggers</relationshipLabel>
    <relationshipName>EmailAlertTriggers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTeamMemberAssignmentEmailController.cls
public without sharing class CaseTeamMemberAssignmentEmailController {
    
    public Id recordId { get; set; }

    private CaseTeamAssignment__c caseAssignment {
        get {
            try{
            if (caseAssignment == null) {
                //String className, String methodName, String message, String parameters, String stackTrace, Integer logLevel
                EmailAlertTrigger__c eat = (EmailAlertTrigger__c)EmailAlertTriggersSelector.INSTANCE.selectSObjectsById(new Set<Id>{recordId})[0];
                caseAssignment = (CaseTeamAssignment__c)CaseTeamAssignmentsSelector.INSTANCE.selectSObjectsById(new Set<Id>{eat.RelatedRecordId__c})[0];
            }} catch(Exception e) {
                CustomLogger.logException(e, 'CaseTeamMemberAssignmentEmailController', 'caseAssignment', recordId);
            }
            return caseAssignment;
        } set;
    }

    public String getCaseNumber() {
        return caseAssignment.Case__r.CaseNumber;
    }
    public String getAccount() {
        return caseAssignment.Case__r.AccountId;
    }
    public String getType() {
        return caseAssignment.Case__r.Type;
    }
    public String getUrl() {
        return Url.getSalesforceBaseUrl().toExternalForm() + '/lightning/r/Case__c/' + caseAssignment.Case__c + '/view';
    }

}