force-app/main/default/objects/CaseTeamAssignment__c/CaseTeamAssignment__c.object-meta.xml
<CustomObject>
    <description>Many-to-many relationship between PUC Case and Case Team Member. When a record of this object is inserted, it gives access to a PUC Case based on CaseTeamMember.Access__c.</description>
    <label>Case Team Assignment</label>
    <nameField>
        <displayFormat>CTA-{000000}</displayFormat>
        <label>Case Team Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Team Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseTeamAssignment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Team</relationshipLabel>
    <relationshipName>CaseTeamAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseTeamAssignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CaseTeamRoles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseTeamAssignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notEqual</operation>
            <value>PUC Customer Community</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notEqual</operation>
            <value>Consumer Advocate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CaseTeamAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTeamAssignmentsSelector.cls
public inherited sharing class CaseTeamAssignmentsSelector extends fflib_SObjectSelector {

    public static final CaseTeamAssignmentsSelector INSTANCE = (CaseTeamAssignmentsSelector)fflibe_Applicationimpl.SELECTOR.newInstance(CaseTeamAssignment__c.getSObjectType());

    public CaseTeamAssignmentsSelector() {
        super(false, false, false, false);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new Schema.SObjectField[] {
            CaseTeamAssignment__c.Id,
            CaseTeamAssignment__c.Role__c,
            CaseTeamAssignment__c.Case__c,
            CaseTeamAssignment__c.User__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return CaseTeamAssignment__c.getSObjectType();
    }

    public override SObject[] selectSObjectsById(Set<Id> recordIds) {
        return Database.query(
            newQueryFactory()
                .selectField('Case__r.OwnerId')
                .selectField('Case__r.Account.Name')
                .selectField('User__r.IsActive')
                .setCondition('Id IN :recordIds')
                .toSOQL()
        );
    }

    public CaseTeamAssignment__c[] selectByUserAndCase(Set<Id> userIds, Set<Id> caseIds) {
        return Database.query(
            newQueryFactory()
                .setCondition('User__c IN :userIds AND Case__c IN :caseIds')
                .toSOQL()
        );
    }

}