force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/DFIRegistration__c.object-meta.xml
<CustomObject>
    <description>PacPoint-MV021120 - Created for DFI phase 1. Used to be able to apply a payment when subscribing for an event</description>
    <label>DFI Registration</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DFI Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DFIRegistration__c/fields/Acknowledgementof35Fee__c.field-meta.xml
<CustomField>
    <fullName>Acknowledgementof35Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-MV021120 - Created for DFI phase 1.</description>
    <inlineHelpText>I acknowledge that there is a $35 fee that must be paid upon submission of this application and it is all inclusive of the event with lunch.</inlineHelpText>
    <label>Acknowledgement of $35 Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/fields/Areyouattending__c.field-meta.xml
<CustomField>
    <fullName>Areyouattending__c</fullName>
    <description>PacPoint-MV021120 - Created for DFI phase 1.</description>
    <label>Are you attending?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes, I am coming</fullName>
                <default>true</default>
                <label>Yes, I am coming</label>
            </value>
            <value>
                <fullName>Sorry, I cannot attend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <description>PacPoint-MV021120 - Created for DFI phase 1.</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/fields/Dietaryrestrictions__c.field-meta.xml
<CustomField>
    <fullName>Dietaryrestrictions__c</fullName>
    <description>PacPoint-MV021220 - Created for DFI phase 1.</description>
    <label>Dietary restrictions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Vegan</fullName>
            </value>
            <value>
                <fullName>Kosher</fullName>
            </value>
            <value>
                <fullName>Gluten-free</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <description>PacPoint-MV021220 - Created for DFI phase 1.</description>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>PacPoint-MV021220 - Created for DFI phase 1.</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DFIRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>PacPoint-MV021320 - Created for DFI phase 1.</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenericCommunityPaymentControllerTest.cls
/*
 * ___________________________________________________________________________________
 * Code coverage for GenericCommunityPaymentController
 * __________________________________________________________________________________
 * PacPoint-CL02132020 - Created for DFI Phase 1
 * __________________________________________________________________________________
 * Initial implementation
 * 
 * @author chris.loyola@pacificpointcorp.com
 * 
 * @created 2/13/2020
 * __________________________________________________________________________________
 */
@IsTest
private class GenericCommunityPaymentControllerTest {
    @TestSetup
    static void setup() {
        CashierCode__c cc = new CashierCode__c();
        cc.Name = '000 - Test';
        cc.CashierCode__c = 'EDX';
        cc.Division__c = 'DFI';
        insert cc;
        // Data setup
        Account acc = new Account();
        acc.Name = 'Test 398624';
        insert acc;

        Contact cnt = new Contact();
        cnt.AccountId = acc.Id;
        cnt.LastName = 'Test 375734';
        insert cnt;

        acc.Contact__c = cnt.Id;
        update acc;
    }

    @IsTest
    static void testCreateSObject() {
        String cashierId = [SELECT Id FROM CashierCode__c  limit 1].Id;
        String accountId = [SELECT Id FROM Account  limit 1 ].Id;
        String contactId = [SELECT Id FROM Contact limit 1].Id;

        DFIRegistration__c testObj = new DFIRegistration__c();
        testObj.FirstName__c = 'test';
        testObj.LastName__c = 'test';
        testObj.EmailAddress__c = 'test@test.test';
        testObj.CompanyName__c = 'test';
        testObj.Acknowledgementof35Fee__c = true;
        testObj.Areyouattending__c = 'Yes, I am coming';
        testObj.Dietaryrestrictions__c = 'Vegan';

        String cashierRecordStr = '{"Amount__c":23442,"CashierCode__c":"323","Id":"' + cashierId +
                '","SystemModstamp":"2019-06-09T05:01:12.000Z"}';
        String contactRecordStr = '{"AccountId":"' + accountId + '","Id":"' + contactId +
                '","SystemModstamp":"2019-06-05T17:34:56.000Z"}';
        String paymentId =
                GenericCommunityPaymentController.createSObject(testObj, contactRecordStr, cashierRecordStr, 'DFI',
                        'USD', 'DFIRegistration__c');
        List<pymt__PaymentX__c> payments = [Select Id from pymt__PaymentX__c where Id =: paymentId];
        System.assertEquals(payments.size(), 1);
    }

    @IsTest
    static void testCreateSObjectError() {
        String cashierId = [SELECT Id FROM CashierCode__c  limit 1].Id;
        String accountId = [SELECT Id FROM Account  limit 1 ].Id;
        String contactId = [SELECT Id FROM Contact limit 1].Id;

        DFIRegistration__c testObj = new DFIRegistration__c();
        testObj.put('EmailAddress__c', 'invalid email');

        String cashierRecordStr = '{"Amount__c":23442,"CashierCode__c":"323","Id":"' + cashierId +
                '","SystemModstamp":"2019-06-09T05:01:12.000Z"}';
        String contactRecordStr = '{"AccountId":"' + accountId + '","Id":"' + contactId +
                '","SystemModstamp":"2019-06-05T17:34:56.000Z"}';
        try {
            GenericCommunityPaymentController.createSObject(testObj, contactRecordStr, cashierRecordStr, 'DFI',
                    'USD', 'DFIRegistration__c');
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException);
        }
    }

    @IsTest
    static void testLoadGenericContact() {
        String contactId = [SELECT Id FROM Contact limit 1].Id;
        System.assert(GenericCommunityPaymentController.loadGenericContact(contactId).contains(contactId));
    }

    @IsTest
    static void testLoadCashierCode() {
        String cashierId = [SELECT Id FROM CashierCode__c].Id;
        System.assert(GenericCommunityPaymentController.loadCashierCode(cashierId).contains('EDX'));
    }

    @IsTest
    static void testCheckPaymentStatusNotComplete() {
        String cashierId = [SELECT Id FROM CashierCode__c  limit 1].Id;
        String accountId = [SELECT Id FROM Account  limit 1 ].Id;
        String contactId = [SELECT Id FROM Contact limit 1].Id;

        DFIRegistration__c testObj = new DFIRegistration__c();
        testObj.FirstName__c = 'test';
        testObj.LastName__c = 'test';
        testObj.EmailAddress__c = 'test@test.test';
        testObj.CompanyName__c = 'test';
        testObj.Areyouattending__c = 'Yes, I am coming';
        testObj.Dietaryrestrictions__c = 'Vegan';
        testObj.Acknowledgementof35Fee__c = true;

        String cashierRecordStr = '{"Amount__c":23442,"CashierCode__c":"323","Id":"' + cashierId +
                '","SystemModstamp":"2019-06-09T05:01:12.000Z"}';
        String contactRecordStr = '{"AccountId":"' + accountId + '","Id":"' + contactId +
                '","SystemModstamp":"2019-06-05T17:34:56.000Z"}';
        String paymentId =
                GenericCommunityPaymentController.createSObject(testObj, contactRecordStr, cashierRecordStr, 'DFI',
                        'USD', 'DFIRegistration__c');

        try {
            GenericCommunityPaymentController.checkPaymentStatus(paymentId);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException);
            System.assert(e.getMessage().contains('PAYMENT NOT COMPLETED'));
        }
    }

    @IsTest
    static void testCheckPaymentStatusNoPaymentIdNull() {
        try {
            GenericCommunityPaymentController.checkPaymentStatus(null);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException);
            System.assert(e.getMessage().contains('NO PAYMENT ID'));
        }
    }
}