force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cost Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/CollectionsAllocation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT012619 - Created for phase1</description>
    <label>Collections Allocation</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Collections Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsAllocation__c/fields/AmountAllocated__c.field-meta.xml
<CustomField>
    <fullName>AmountAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Amount Allocated from Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TransactionLine__r.CashierCodeCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashier Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT(TransactionLine__r.Transaction__r.Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/NetCollectionsafterFeesAllocated__c.field-meta.xml
<CustomField>
    <fullName>NetCollectionsafterFeesAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>IF( TrustAccount__c = TRUE, AmountAllocated__c, AmountAllocated__c - TotalFeesAllocated__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Collections after Fees Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TEXT(Payment__r.pymt__Payment_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Reconciliation_Batch__c.field-meta.xml
<CustomField>
    <fullName>Reconciliation_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CZ103019 - Created for 4GOV phase 1</description>
    <label>Reconciliation Batch</label>
    <referenceTo>Reconciliation_Batch__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/TransactionLine__c.field-meta.xml
<CustomField>
    <fullName>TransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction Line</label>
    <referenceTo>TransactionLine__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reconciliation_Batch__c/Reconciliation_Batch__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CZ101919 - Created for 4GOV phase 1.This object will house each batched Collection Allocation records.</description>
    <label>Reconciliation Batch</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Reconciliation Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliation Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reconciliation_Batch__c/fields/Batch_Time__c.field-meta.xml
<CustomField>
    <fullName>Batch_Time__c</fullName>
    <description>PacPoint-CZ101919 - Created for 4GOV phase 1</description>
    <label>Batch Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reconciliation_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CZ101919 - Created for 4GOV phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Sent To 4Gov</fullName>
                <label>Sent To GL</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
                <isActive>false</isActive>
                <label>Email Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reconciliation_Batch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <formula>CashierCode__r.CostCenter__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( CashierCode__r.Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RunReconciliationBatchController.cls
/*
* ─────────────────────────────────────────────────────────
* RunReconciliationBatchController Class
* 
* ─────────────────────────────────────────────────────────
* PacPoint-CZ171019 - Created for PVL 4Gov Integration
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Chris Zhuang - PacificPointCorp 
* @created      2019-10-17
* ───────────────────────────────────────────────────────────
* Changes
*
* ───────────────────────────────────────────────────────────
*/
public with sharing class RunReconciliationBatchController {
    //Apex properties or variables
    public Id Id { get; set; }
    public Reconciliation_Batch__c batchObject { get; set; }
    public Boolean isDisabled { get; set; }
    private ApexPages.standardController sc = null;

    //constructor to get the Reconciliation_Batch__c record
    public RunReconciliationBatchController(ApexPages.StandardController controller) {
        batchObject =  (Reconciliation_Batch__c) controller.getRecord();
        Id = batchObject.Id;
        sc = controller;
        isDisabled = false;
        if (String.isNotEmpty(Id)) {
            batchObject = [select Id, Name, Batch_Time__c, Status__c, Type__c from Reconciliation_Batch__c where id =: Id];
        }

        if (batchObject != null && batchObject.Status__c != 'Pending Review') {
            isDisabled = true;
        }
    }

    //Method that can is called from the Visual Force page action attribute
    public PageReference reRunBatchProcess() {
        if(batchObject?.Type__c == 'Payment'){            
            String query = 'SELECT Id,NetCollectionsafterFeesAllocated__c,PaymentType__c,Payment__r.RemitToDCCA__c,Transaction__r.Account__r.Name,Transaction__r.Name,Payment__r.pymt__Date__c,CashierCode__c,Payment__r.pymt__Memo__c,Payment__r.Division__c,TransactionLine__r.CostCenter__c,AmountAllocated__c, TransactionLine__r.CashierCode__r.FAMISSrcCode__c, TransactionLine__r.CashierCode__r.FundAccount__c';
            query += ' FROM CollectionsAllocation__c WHERE Reconciliation_Batch__c = \'' + batchObject.Id + '\' AND Payment__r.Division__c != \'PUC\'';
            List<sObject> sobjList = Database.query(query);

            ReconciliationBatchJob bj = new ReconciliationBatchJob();
            //Write each line of the csv file from the records in the CollectionsAllocation__c
            for(sObject s : sobjList) {
                CollectionsAllocation__c ca = (CollectionsAllocation__c)s;
                bj.getCSVFileDetails(ca);
            }
            bj.UpdateCSVFile(batchObject);
        } else if(batchObject?.Type__c == 'Adjustment'){
            // Run PaymentAdjustmentBatchJob
            Database.executeBatch(new PaymentAdjustmentBatchJob(batchObject.Id), 200);
        }

        PageReference pageRef = new PageReference('/'+Id);
        pageRef.setRedirect(true);
        return pageRef; 
    }
    
    public PageReference doCancel() {
        return sc.cancel();
    }
}