force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cost Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FAMISSrcCode__c.field-meta.xml
<CustomField>
    <fullName>FAMISSrcCode__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>FAMIS Src Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Fund Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/CollectionsAllocation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT012619 - Created for phase1</description>
    <label>Collections Allocation</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Collections Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsAllocation__c/fields/AmountAllocated__c.field-meta.xml
<CustomField>
    <fullName>AmountAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Amount Allocated from Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TransactionLine__r.CashierCodeCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashier Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT(TransactionLine__r.Transaction__r.Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/JVProcessed__c.field-meta.xml
<CustomField>
    <fullName>JVProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for the JV form created by Pacific Point</description>
    <label>JV Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/NetCollectionsafterFeesAllocated__c.field-meta.xml
<CustomField>
    <fullName>NetCollectionsafterFeesAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>IF( TrustAccount__c = TRUE, AmountAllocated__c, AmountAllocated__c - TotalFeesAllocated__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Collections after Fees Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/TransactionLine__c.field-meta.xml
<CustomField>
    <fullName>TransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction Line</label>
    <referenceTo>TransactionLine__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <formula>CashierCode__r.CostCenter__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( CashierCode__r.Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FAMISSrcCode__c.field-meta.xml
<CustomField>
    <fullName>FAMISSrcCode__c</fullName>
    <formula>CashierCode__r.FAMISSrcCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FAMIS Src Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <formula>CashierCode__r.FundAccount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fund Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollectionsAllocationDomain.cls
public with sharing class CollectionsAllocationDomain extends SObjectDomain{
    public CollectionsAllocationDomain(List<CollectionsAllocation__c> records) {
        super(records);
    }
    public Map<String, Decimal> summarizeAllocationRecordAmount(String paymentType) {
        Map<String, Decimal> cashierCodeAmount = new Map<String, Decimal>();
        for(CollectionsAllocation__c record : (List<CollectionsAllocation__c>) records) {
            String uniqueKey = record.TransactionLine__r.CashierCode__r.FundAccount__c +
                record.TransactionLine__r.CashierCode__r.FAMISSrcCode__c +
                record.TransactionLine__r.CashierCode__r.CostCenter__c;
            Decimal amount = 0;
            amount = record.AmountAllocated__c;
            if(paymentType == 'Credit Card') {
                amount = record.NetCollectionsafterFeesAllocated__c;
            }
            Decimal totalAmount = 0;
            if(cashierCodeAmount.containsKey(uniqueKey)) {
                totalAmount = cashierCodeAmount.get(uniqueKey);
            }
            if(amount == null) 
                amount = 0;
            totalAmount = amount + totalAmount;
            cashierCodeAmount.put(uniqueKey, totalAmount);
        }
        return cashierCodeAmount;
    }
    public void checkJVProcessed() {
        for(CollectionsAllocation__c record: (List<CollectionsAllocation__c>) records) {
            record.JVProcessed__c = true;
        }
    }

    public List<FiscalFormFeed.DataFeed> getDataFeeds(Map<String, Decimal> cashierCodeAmount, String year) {
        Set<String> cashierCodeSet = new Set<String>();
    
        List<FiscalFormFeed.DataFeed> dataFeeds = new List<FiscalFormFeed.DataFeed>();
        for(CollectionsAllocation__c record: (List<CollectionsAllocation__c>) records) {
            String uniqueKey = record.TransactionLine__r.CashierCode__r.FundAccount__c +
                record.TransactionLine__r.CashierCode__r.FAMISSrcCode__c +
                record.TransactionLine__r.CashierCode__r.CostCenter__c;

            if(cashierCodeSet.contains(uniqueKey)) {
                continue;
            }
            
            FiscalFormFeed.DataFeed feed = new FiscalFormFeed.DataFeed();
            
            feed.tcValue = '011';
            feed.recordId = record.Id;
            if(record.TransactionLine__r.CashierCode__r.FundAccount__c != null) {
                feed.sValue = record.TransactionLine__r.CashierCode__r.FundAccount__c.split('-')[0];
            }
            
            feed.yrValue = year;
            if(record.TransactionLine__r.CashierCode__r.FundAccount__c != null) 
                feed.appValue = record.TransactionLine__r.CashierCode__r.FundAccount__c.split('-')[1];
            // feed.dValue = record.TransactionLine__r.CashierCode__r.Division__c.substring(0, 1);
            feed.dValue = 'R';
            feed.sourceObjValue = record.TransactionLine__r.CashierCode__r.FAMISSrcCode__c;
            feed.costCenterValue = record.TransactionLine__r.CashierCode__r.CostCenter__c;
            if (String.isBlank(feed.costCenterValue)) {
                feed.costCenterValue = '0';
            }
            feed.amount = cashierCodeAmount.get(uniqueKey);
            dataFeeds.add(feed);
            cashierCodeSet.add(uniqueKey);
            
        }
        return dataFeeds;
    }
    public List<FiscalFormFeed.DataFeed> getJVFeeds(String year) {
        Map<String, List<CollectionsAllocation__c>> collectionAllocationMap = new Map<String, List<CollectionsAllocation__c>>();
        for(CollectionsAllocation__c record: (List<CollectionsAllocation__c>) records) {
            String transactionId = record.Transaction__c;
            List<CollectionsAllocation__c> allocations = new List<CollectionsAllocation__c>();
            if(collectionAllocationMap.containsKey(transactionId)) {
                allocations = collectionAllocationMap.get(transactionId);
            }
            allocations.add(record);
            collectionAllocationMap.put(transactionId, allocations);
        }
        Integer lastValue = 0;
        Integer index = 1;
        List<FiscalFormFeed.DataFeed> dataFeeds = new List<FiscalFormFeed.DataFeed>();
        for(String transactionId: collectionAllocationMap.keySet()) {
            List<CollectionsAllocation__c> allocations = collectionAllocationMap.get(transactionId);
            if((lastValue + allocations.size()) > 14 && allocations.size() <= 14) {
                for(Integer i = 0;i< (14 - lastValue); i++) {
                    FiscalFormFeed.DataFeed feed = new FiscalFormFeed.DataFeed();
                    feed.indexValue = '';
                    feed.tcValue = '';
                    feed.sValue = '';
                    feed.yrValue = '';
                    feed.appValue = '';
                    feed.dValue = '';
                    feed.sourceObjValue = '';
                    feed.costCenterValue = '';
                    dataFeeds.add(feed);
                }
                lastValue = allocations.size();

            } else {
                lastValue = lastValue + allocations.size();
            }
            for(CollectionsAllocation__c record: allocations) {
                String indexValue = '' + index;
                if(indexValue.length() == 1) {
                    indexValue = '0' + indexValue;
                }
                FiscalFormFeed.DataFeed feed = new FiscalFormFeed.DataFeed();
                feed.indexValue = indexValue;
                feed.tcValue = '011';
                feed.fValue = record.TransactionLine__r.CashierCode__r.FundAccount__c.split('-')[0];
                feed.yrValue = year;
                feed.appValue = record.TransactionLine__r.CashierCode__r.FundAccount__c.split('-')[1];
                // feed.dValue = record.TransactionLine__r.CashierCode__r.Division__c.substring(0, 1);
                feed.recordId = record.Id;
                feed.dValue = 'R';
                feed.sourceObjValue = record.TransactionLine__r.CashierCode__r.FAMISSrcCode__c;
                feed.costCenterValue = record.TransactionLine__r.CashierCode__r.CostCenter__c;
                feed.projectNumValue = record.TransactionLine__r.CashierCode__r.CashierCode__c;
                Decimal amount = record.AmountAllocated__c;
                System.debug('##########Payment Name##########' + record.Payment__r.Name + '#####Cashier Code####' + record.TransactionLine__r.CashierCode__r.CashierCode__c 
                    + '#####amount####' + amount + '#####recordId####' + record.Id);
                if(amount != null) {
                    amount = amount.abs();
                    feed.jVAmount1 = amount.intValue() + '';
                    String amount2 = ((amount - amount.intValue()) * 100 ).intValue() + '';
                    feed.jVAmount2 = amount2;
                }
                feed.transactionId = record.Transaction__c;
                dataFeeds.add(feed);
                index ++;
            }   
        }
        return dataFeeds;

    } 
}