force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cost Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FAMISSrcCode__c.field-meta.xml
<CustomField>
    <fullName>FAMISSrcCode__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>FAMIS Src Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FeeCode__c.field-meta.xml
<CustomField>
    <fullName>FeeCode__c</fullName>
    <description>PacPoint-FT082218 - Created for phase 1

Code used by BREG to associate Cashier Codes for transaction line items.</description>
    <label>Fee Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Fund Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/CollectionsAllocation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT012619 - Created for phase1</description>
    <label>Collections Allocation</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Collections Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsAllocation__c/fields/AmountAllocated__c.field-meta.xml
<CustomField>
    <fullName>AmountAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Amount Allocated from Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/AmountfromPayment__c.field-meta.xml
<CustomField>
    <fullName>AmountfromPayment__c</fullName>
    <formula>Payment__r.pymt__Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount from Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/AmountfromTransactionLine__c.field-meta.xml
<CustomField>
    <fullName>AmountfromTransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TransactionLine__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount from Transaction Line</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TransactionLine__r.CashierCodeCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashier Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/CutOffBatchDate__c.field-meta.xml
<CustomField>
    <fullName>CutOffBatchDate__c</fullName>
    <description>PacPoint-PH030819 - Created for phase 1</description>
    <label>Close Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT030319 - Created for phase 1</description>
    <label>Deposit</label>
    <referenceTo>Deposits__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT(TransactionLine__r.Transaction__r.Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/NetCollectionsafterFeesAllocated__c.field-meta.xml
<CustomField>
    <fullName>NetCollectionsafterFeesAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>IF( TrustAccount__c = TRUE, AmountAllocated__c, AmountAllocated__c - TotalFeesAllocated__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Collections after Fees Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TEXT(Payment__r.pymt__Payment_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/TransactionLine__c.field-meta.xml
<CustomField>
    <fullName>TransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction Line</label>
    <referenceTo>TransactionLine__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deposits__c/Deposits__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070318 - Created for phase 1</description>
    <label>Deposits</label>
    <nameField>
        <displayFormat>DEP-{00000}</displayFormat>
        <label>Deposit Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposits__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>PacPoint-FT070218 - Created for phase 1</description>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Deposits__c/fields/PUCDeposit__c.field-meta.xml
<CustomField>
    <fullName>PUCDeposit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-IC071819- Created for Phase 2</description>
    <label>PUC Deposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/FiscalForm__c.object-meta.xml
<CustomObject>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA - Fiscal Forms CR - Creating to capture the Fiscal Form records.</description>
    <label>Fiscal Form</label>
    <nameField>
        <label>Fiscal Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FiscalForm__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA Fiscal Form CR - Creating for capturing of forms</description>
    <inlineHelpText>Populate the End Date for pulling payments.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/fields/FundType__c.field-meta.xml
<CustomField>
    <fullName>FundType__c</fullName>
    <label>Fund Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Used to store the request data</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA Fiscal Form CR - Creating for capturing of forms</description>
    <inlineHelpText>Populate the Start Date of pulling payments,</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/recordTypes/TDR.recordType-meta.xml
<RecordType>
    <fullName>TDR</fullName>
    <active>true</active>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA - Fiscal Forms CR - Creating to capture the Fiscal Form records.</description>
    <label>TDR</label>
</RecordType>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <formula>CashierCode__r.CostCenter__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( CashierCode__r.Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FAMISSrcCode__c.field-meta.xml
<CustomField>
    <fullName>FAMISSrcCode__c</fullName>
    <formula>CashierCode__r.FAMISSrcCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FAMIS Src Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <formula>CashierCode__r.FundAccount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fund Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TDRFormController.cls
public with sharing class TDRFormController {
    public List<Map<String, Object>> allRecords {
        set;get;
    }
    public List<FiscalFormFeed> values {
        set;get;
    }
    public String copyStr {
        set;get;
    }
    public String userName{
        get;set;
    }
    public List<String> copies {
        set;get;
    }
    public TDRFormController() {
        userName = UserInfo.getName();
        values = new List<FiscalFormFeed>();

        String recordId = System.currentPageReference().getParameters().get('recordId');
        String copy = System.currentPageReference().getParameters().get('copy');
        if (copy == null) copyStr = 'COPY #1 - STATE TREASURY';
        if (copy == '1') copyStr = 'COPY #1 - STATE TREASURY';
        if (copy == '2') copyStr = 'COPY #2 - STATE COMPTROLLER';
        if (copy == '3') copyStr = 'COPY #3 - DEPARTMENT FISCAL OFFICE';
        if (copy == '4') copyStr = 'COPY #4 - DEPARTMENT FISCAL OFFICE (FOLLOW-UP COPY)';
        if (recordId != null) {
            FiscalForm__c record = [Select Id, StartDate__c, EndDate__c, Request__c
            from FiscalForm__c where Id =: recordId];
            String request = record.Request__c;
            values = (List<FiscalFormFeed>)JSON.deserialize(request, List<FiscalFormFeed>.class);
        } else {

            FiscalFormFeed formFeed = new FiscalFormFeed();
            formFeed.bankDeposit = '99.01';
            formFeed.electronicFundTransfer = '99.01';
            formFeed.creditCardProcessing = '99.01';
            formFeed.others = '99.01';
            formFeed.dateStr = '99/99/9999';
            formFeed.detailFund = 'detailFund REGISTRATION - CRF';
            formFeed.fundName = 'fundName';
            formFeed.remarks = '02/25.26.27 First Hawaii';
            formFeed.remarks = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis,';
            formFeed.totalDeposit = '99.01';
            formFeed.totalDeposit2 = '99.01';

            FiscalFormFeed.DataFeed dataFeed = new FiscalFormFeed.DataFeed();
            dataFeed.indexValue = '99';
            dataFeed.tcValue = '999';
            dataFeed.sValue = 'S';
            dataFeed.yrValue = '99';
            dataFeed.appValue = '999';
            dataFeed.dValue = 'P';
            dataFeed.sourceObjValue = '9999';
            dataFeed.costCenterValue = '9999';
            dataFeed.amount = 99.01;
            dataFeed.revValue = 'R';

            List<FiscalFormFeed.DataFeed> fundsList = new List<FiscalFormFeed.DataFeed>();
            FiscalFormFeed.DataFeed dataFeed2 = (FiscalFormFeed.DataFeed) dataFeed.clone();
            dataFeed2.amount = 99;
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed2);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);
            fundsList.add(dataFeed);

            formFeed.funds = fundsList;

            values.add(formFeed);
            values.add(formFeed);
        }

        this.copies = new List<String>{'COPY #1 - STATE TREASURY', 'COPY #2 - STATE COMPTROLLER',
            'COPY #3 - DEPARTMENT FISCAL OFFICE', 'COPY #4 - DEPARTMENT FISCAL OFFICE (FOLLOW-UP COPY)'};


    }

    @AuraEnabled(cacheable = true)
    public static List<Map<String, String>> getTdrDepositOptions() {
        List<Map<String, String>> result = new List<Map<String, String>>();

        for (Deposits__c deposit : [SELECT Id, Name FROM Deposits__c WHERE Notes__c = 'Pending TDR' AND PUCDeposit__c = false ORDER BY Name ASC]) {
            Map<String, String> opt = new Map<String, String>();
            opt.put('label', deposit.Name);
            opt.put('value', deposit.Id);
            result.add(opt);
        }

        return result;
    }

    @AuraEnabled
    public static void saveAsFile(String recordId) {
        Map<String, Blob> files = new Map<String, Blob>();
        for (Integer i = 1;i < 5; i++) {
            PageReference pageRef = Page.TDR;
            pageRef.getParameters().put('recordId', recordId);
            pageRef.getParameters().put('copy', i + '');
            Blob content = Test.isRunningTest() ? Blob.valueOf('test') : pageRef.getContent();
            String docName = 'TDRFile(COPY' + i + ').pdf';
            files.put(docName, content);
        }

        PageReference pageCopyRef = Page.TDRCopies;
        pageCopyRef.getParameters().put('recordId', recordId);
        Blob docCopyContent = Test.isRunningTest() ? Blob.valueOf('test') : pageCopyRef.getContent();
        files.put('TDRFile.pdf', docCopyContent);

        List<SpringCMDocument> result = SpringCMConnector.createFiles(recordId, files);


    }

    @AuraEnabled
    public static String submitForFile(String str, String recordId, String recordTypeId, String feedStr) {
        FiscalFormFeed.SearchFeed feed = (FiscalFormFeed.SearchFeed) JSON.deserialize(feedStr, FiscalFormFeed.SearchFeed.class);
        List<FiscalForm__c> records = new List<FiscalForm__c>();

        if (!String.isBlank(recordId)) {
            records = [Select Id, Request__c, PaymentType__c, FundType__c, StartDate__c, EndDate__c, Division__c from FiscalForm__c where Id =: recordId limit 1];
            for (FiscalForm__c record : records) {
                record.Request__c = str;
                recordId = record.Id;
                record.PaymentType__c = feed.paymentType;
                record.Division__c = feed.division;
                record.FundType__c = feed.fundType;
                record.StartDate__c = feed.startDate;
                record.EndDate__c = feed.cutOffDate;
            }
            update records;
        } else {
            FiscalForm__c record = new FiscalForm__c();
            record.RecordTypeId = recordTypeId;
            record.Request__c = str;
            record.PaymentType__c = feed.paymentType;
            record.Division__c = feed.division;
            record.FundType__c = feed.fundType;
            record.StartDate__c = feed.startDate;
            record.EndDate__c = feed.cutOffDate;
            insert record;
            recordId = record.Id;
        }


        return recordId;

    }

    @AuraEnabled
    public static string searchData(String feedStr) {
        FiscalFormFeed.SearchFeed feed = (FiscalFormFeed.SearchFeed) JSON.deserialize(feedStr, FiscalFormFeed.SearchFeed.class);
        DateTime cutOffDate;
        DateTime startDate;
        String division;
        Boolean isCreditCard = feed.paymentType == 'Credit Card';
        List<String> paymentTypes = new List<String>();
        Set<String> excludedUserIds = new Set<String>();

        String query = 'Select Id, CutOffBatchDate__c, NetCollectionsafterFeesAllocated__c,  TransactionLine__r.CashierCode__c, AmountAllocated__c, AmountfromTransactionLine__c, AmountfromPayment__c, ' +
            ' TransactionLine__r.CashierCode__r.CostCenter__c, TransactionLine__r.CashierCode__r.FundAccount__c, ' +
            ' TransactionLine__r.CashierCode__r.Division__c, TransactionLine__r.CashierCode__r.FAMISSrcCode__c, ' +
            ' TransactionLine__r.CashierCode__r.FeeCode__c, PaymentType__c from CollectionsAllocation__c ' +
            ' where Payment__r.pymt__Status__c IN (\'Completed\',\'BCF\') ';

        if (isCreditCard) {
            query += ' AND (Payment__r.pymt__Transaction_Type__c = \'Payment\' OR Payment__r.pymt__Transaction_Type__c = \'Refund\') ';
        } else {
            query += ' AND Payment__r.pymt__Transaction_Type__c = \'Payment\' ';
        }

        if (String.isNotBlank(feed.paymentType) && feed.paymentType == 'Cash') {
            for (PermissionSetAssignment psa : [
                SELECT
                    Id,
                    AssigneeId
                FROM PermissionSetAssignment
                WHERE PermissionSet.Name = 'ExcludeFromFiscalTDRForm'
            ]) {
                excludedUserIds.add(psa.AssigneeId);
            }

            query += ' AND Payment__r.CreatedById NOT IN :excludedUserIds ';
        }

        DateTime serviceDateTime = System.now();
        Integer offsetHours = UserInfo.getTimeZone().getOffset(serviceDateTime) / 1000 / 60 / 60;

        if (feed.cutOffDate != null) {
            cutOffDate = feed.cutOffDate;
            cutOffDate = cutOffDate.addDays(1);
            cutOffDate = cutOffDate.addHours(-(offsetHours));

            query += ' and CutOffBatchDate__c <: cutOffDate ';
        }

        if (feed.startDate != null) {
            startDate = feed.startDate;
            startDate = startDate.addHours(-(offsetHours));
            query += ' and CutOffBatchDate__c >=: startDate ';
        }

        if (!String.isBlank(feed.division)) {
            division = feed.division;
            if (division == 'PUC') {
                query += ' AND Division__c = :division ';
            } else {
                query += ' AND Division__c <> \'PUC\' ';
            }
        } else {
            query += ' AND Division__c <> \'PUC\' ';
        }

        List<String> trustAccountFilter;
        String tempFilterFundAccount = feed.fundAccounts;
        if (String.isNotBlank(feed.fundType)) {
            if (feed.fundType != 'Trust') {
                query += ' and TransactionLine__r.CashierCode__r.FundAccount__c = :tempFilterFundAccount';
            } else {
                trustAccountFilter = (List<String>) JSON.deserialize(tempFilterFundAccount, List<String>.class);
                query += ' and TransactionLine__r.CashierCode__r.FundAccount__c IN :trustAccountFilter';
            }
        }

        Boolean hasPaymentTypeFilter = false;
        List<String> depositIds;
        if (!String.isBlank(feed.paymentType)) {
            hasPaymentTypeFilter = true;
            if (isCreditCard) {
                paymentTypes.add('Credit Card');
                paymentTypes.add('ECheck');

                if (String.isNotBlank(feed.selectedDeposits)) {
                    depositIds = (List<String>) JSON.deserialize(feed.selectedDeposits, List<String>.class);
                    query += ' and Deposit__c IN :depositIds ';
                }

            } else if (feed.paymentType == 'Cash') {
                paymentTypes.add('Cash');
                paymentTypes.add('Money Order');
                paymentTypes.add('Cashier\'s Check');
                paymentTypes.add('Check');
            } else if (feed.paymentType == 'EFT') {
                paymentTypes.add('Electronic Funds Transfer');
            }
            query += ' and PaymentType__c in: paymentTypes ';

            if (!isCreditCard) {
                query += ' AND AmountAllocated__c >= 0 ';
            }
        }

        query += ' ORDER BY TransactionLine__r.CashierCode__r.FundAccount__c';

        List<CollectionsAllocation__c> collectionAllocations = Database.query(query);

        if (!hasPaymentTypeFilter) {
            collectionAllocations = removeNegativeAllocation(collectionAllocations);
        }

        List<String> cRecordIds = new List<String>();

        Map<String, Decimal> cashierCodeAmount = (new CollectionsAllocationDomain(collectionAllocations))
            .summarizeAllocationRecordAmount(feed.paymentType);

        String yearStr = '00';
        if ((cutOffDate != null || isCreditCard) && feed.fundType != 'General') {
            cutOffDate = cutOffDate == null ? System.today() : cutOffDate;
            Integer month = cutOffDate.month();
            Integer year = cutOffDate.year();
            if (month > 6) {
                year++;
            }
            yearStr = '' + year;
            yearStr = yearStr.substring(2, 4);
        }

        List<FiscalFormFeed.DataFeed> feeds = (new CollectionsAllocationDomain(collectionAllocations)).getDataFeeds(cashierCodeAmount, yearStr);
        feeds.sort();

        Integer index = 1;
        for (FiscalFormFeed.DataFeed f : feeds) {
            String indexValue = '' + index;

            if (indexValue.length() == 1) {
                indexValue = '0' + indexValue;
            }

            f.indexValue = indexValue;
            f.elemKey = f.appValue;
            index++;
            if (index == 15) {
                index = 1;
            }
        }
        return JSON.serialize(feeds);
    }

    //case 00028187
    private static List<CollectionsAllocation__c> removeNegativeAllocation(List<CollectionsAllocation__c> collectionsAllocations) {
        List<CollectionsAllocation__c> result = new List<CollectionsAllocation__c>();
        for (collectionsAllocation__c c : collectionsAllocations) {
            if (c.PaymentType__c != 'Credit Card' && c.AmountAllocated__c < 0) {
                continue;
            }

            result.add(c);
        }

        return result;
    }
}