force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Fund Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/CollectionsAllocation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT012619 - Created for phase1</description>
    <label>Collections Allocation</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Collections Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsAllocation__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TransactionLine__r.CashierCodeCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashier Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/CutOffBatchDate__c.field-meta.xml
<CustomField>
    <fullName>CutOffBatchDate__c</fullName>
    <description>PacPoint-PH030819 - Created for phase 1</description>
    <label>Close Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT030319 - Created for phase 1</description>
    <label>Deposit</label>
    <referenceTo>Deposits__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/DepositDate__c.field-meta.xml
<CustomField>
    <fullName>DepositDate__c</fullName>
    <formula>Deposit__r.DepositDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deposit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT(TransactionLine__r.Transaction__r.Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TEXT(Payment__r.pymt__Payment_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/TransactionLine__c.field-meta.xml
<CustomField>
    <fullName>TransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction Line</label>
    <referenceTo>TransactionLine__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deposits__c/Deposits__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070318 - Created for phase 1</description>
    <label>Deposits</label>
    <nameField>
        <displayFormat>DEP-{00000}</displayFormat>
        <label>Deposit Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deposits__c/fields/DepositDate__c.field-meta.xml
<CustomField>
    <fullName>DepositDate__c</fullName>
    <description>PacPoint-FT070218 - Created for phase 1</description>
    <label>Deposit Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Deposits__c/fields/DepositNumber__c.field-meta.xml
<CustomField>
    <fullName>DepositNumber__c</fullName>
    <description>PacPoint-070218 - Created for phase 1</description>
    <label>Deposit Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/FiscalForm__c.object-meta.xml
<CustomObject>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA - Fiscal Forms CR - Creating to capture the Fiscal Form records.</description>
    <label>Fiscal Form</label>
    <nameField>
        <label>Fiscal Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FiscalForm__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FiscalForm__c/recordTypes/TDR.recordType-meta.xml
<RecordType>
    <fullName>TDR</fullName>
    <active>true</active>
    <description>PacPoint-AC081120 - Case# 10552 - Created for DCCA - Fiscal Forms CR - Creating to capture the Fiscal Form records.</description>
    <label>TDR</label>
</RecordType>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/WorkitemID__c.field-meta.xml
<CustomField>
    <fullName>WorkitemID__c</fullName>
    <label>Workitem ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( CashierCode__r.Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <formula>CashierCode__r.FundAccount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fund Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/WorkitemID__c.field-meta.xml
<CustomField>
    <fullName>WorkitemID__c</fullName>
    <description>PacPoint-FT082218 - Created for phase 1

To be used by BREG to associate to records scanned into BRIMS</description>
    <label>Workitem ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TDRFormControllerTest.cls
@IsTest
public with sharing class TDRFormControllerTest {
    @TestSetup
    static void makeData() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Contact cnt = new Contact(LastName = 'TestCon', AccountId = acc.Id);
        insert cnt;

        date sd = Date.Today();

        Deposits__c xDeposit = new Deposits__c();
        xDeposit.DepositDate__c = sd;
        xDeposit.DepositNumber__c = '223322';
        xDeposit.DepositNumber__c = 'Draft';
        insert xDeposit;

        List<pymt__PaymentX__c> payments = new List<pymt__PaymentX__c>();

        pymt__PaymentX__c currentYearPayment1 = new pymt__PaymentX__c();
        currentYearPayment1.pymt__Status__c = 'Completed';
        currentYearPayment1.pymt__Date__c = Date.newInstance(sd.year(), 1, 12);
        currentYearPayment1.RemitToDCCA__c = 50;
        currentYearPayment1.PPIFeeAmount__c = 100;
        currentYearPayment1.HIGETaxAmount__c = 150;
        currentYearPayment1.DepositBatch__c = xDeposit.Id;
        currentYearPayment1.pymt__Payment_Type__c = 'Cash';
        payments.add(currentYearPayment1);

        pymt__PaymentX__c currentYearPayment2 = new pymt__PaymentX__c();
        currentYearPayment2.pymt__Status__c = 'Completed';
        currentYearPayment2.pymt__Date__c = Date.newInstance(sd.year(), 1, 12);
        currentYearPayment2.RemitToDCCA__c = 50;
        currentYearPayment2.PPIFeeAmount__c = 100;
        currentYearPayment2.HIGETaxAmount__c = 150;
        currentYearPayment2.DepositBatch__c = xDeposit.Id;
        currentYearPayment2.pymt__Payment_Type__c = 'Check or Money Order';
        payments.add(currentYearPayment2);

        pymt__PaymentX__c currentYearPayment3 = new pymt__PaymentX__c();
        currentYearPayment3.pymt__Status__c = 'Completed';
        currentYearPayment3.pymt__Date__c = Date.newInstance(sd.year(), 1, 12);
        currentYearPayment3.RemitToDCCA__c = 50;
        currentYearPayment3.PPIFeeAmount__c = 100;
        currentYearPayment3.HIGETaxAmount__c = 150;
        currentYearPayment3.DepositBatch__c = xDeposit.Id;
        currentYearPayment3.pymt__Payment_Type__c = 'Credit Card';
        payments.add(currentYearPayment3);

        insert payments;

        Transaction__c trns1 = new Transaction__c();
        trns1.Account__c = acc.Id;
        trns1.WorkitemID__c = '1';
        insert trns1;

        TransactionLine__c trLine = new TransactionLine__c();
        trLine.Transaction__c = trns1.Id;
        insert trLine;

        CollectionsAllocation__c alloc = new CollectionsAllocation__c();
        alloc.Deposit__c = xDeposit.Id;
        alloc.TransactionLine__c = trLine.Id;
        alloc.CutOffBatchDate__c = System.now();
        alloc.Payment__c = currentYearPayment1.Id;
        insert alloc;
    }

    @IsTest
    static void testSearchMethod() {
        List<CollectionsAllocation__c> records = [Select Id, CutOffBatchDate__c,
        TransactionLine__r.CashierCode__r.Division__c, TransactionLine__r.CashierCode__r.FundAccount__c,
        PaymentType__c from CollectionsAllocation__c];
        String division = records.get(0).TransactionLine__r.CashierCode__r.Division__c;
        String paymentType = records.get(0).PaymentType__c;
        String fundAccount = records.get(0).TransactionLine__r.CashierCode__r.FundAccount__c;
        Date cutOffDate = Date.valueOf(records.get(0).CutOffBatchDate__c);
        FiscalFormFeed.SearchFeed feed = new FiscalFormFeed.SearchFeed();
        feed.cutOffDate = cutOffDate;
        feed.paymentType = paymentType;
        feed.fundType = fundAccount;
        feed.division = division;
        feed.startDate = cutOffDate.addDays(-5);
        List<Map<String, Object>> m = (new TDRFormController()).allRecords;
        String results = TDRFormController.searchData(JSON.serialize(feed));
    }

    @IsTest
    static void testSearchMethod2() {
        List<CollectionsAllocation__c> records = [
            SELECT
                Id,
                CutOffBatchDate__c,
                TransactionLine__r.CashierCode__r.Division__c,
                TransactionLine__r.CashierCode__r.FundAccount__c,
                PaymentType__c
            FROM CollectionsAllocation__c
        ];
        String division = records.get(0).TransactionLine__r.CashierCode__r.Division__c;
        String paymentType = records.get(0).PaymentType__c;
        Date cutOffDate = Date.valueOf(records.get(0).CutOffBatchDate__c);
        FiscalFormFeed.SearchFeed feed = new FiscalFormFeed.SearchFeed();
        feed.cutOffDate = cutOffDate;
        feed.paymentType = paymentType;
        feed.fundType = 'Trust';
        feed.fundAccounts = '[]';
        feed.division = division;
        feed.startDate = cutOffDate.addDays(-5);
        String results = TDRFormController.searchData(JSON.serialize(feed));
        feed.paymentType = null;
        String results2 = TDRFormController.searchData(JSON.serialize(feed));
    }

    @IsTest
    static void testController2() {
        ApexPages.currentPage().getParameters().put('copy', '2');
        TDRFormController ctrl = new TDRFormController();
    }

    @IsTest
    static void testController() {
        Schema.DescribeSObjectResult d = Schema.SObjectType.FiscalForm__c;
        Map<String, Schema.RecordTypeInfo> rtMapById = d.getRecordTypeInfosByName();
        String recordTypeId = rtMapById.get('TDR').getRecordTypeId();
        String str = '[{"fundName":"SPECIAL","detailFund":"BUSINESS REGISTRATION - PVL","dateStr":"11/02/2020","remarks":"02/25.26.27 First Hawaii","totalDeposit":"1306.57","bankDeposit":"1306.57","electronicFundTransfer":"",' +
            '"creditCardProcessing":"","others":"","totalDeposit2":"1306.57","funds":[{"indexValue":"01","tcValue":"011","sValue":"S","yrValue":"21","appValue":"305","dValue":"R","sourceObjValue":"0159","costCenterValue":"0092",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":"1306.57"},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"",' +
            '"tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"",' +
            '"venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"",' +
            '"gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"",' +
            '"tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"",' +
            '"venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"",' +
            '"gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"",' +
            '"tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"",' +
            '"venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"",' +
            '"gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null}]}]';

        String feedStr = '{"fundType":"Special","paymentType":"Credit Card","cutOffDate":"2020-11-01","startDate":"2019-10-29","division":"PVL"}"';

        String recordId ;
        recordId = TDRFormController.submitForFile(str, recordId, recordTypeId, feedStr);
        ApexPages.currentPage().getParameters().put('recordId', recordId);
        ApexPages.currentPage().getParameters().put('copy', '1');
        TDRFormController ctrl = new TDRFormController();

    }

    @IsTest
    static void testSaveAsFile() {
        Schema.DescribeSObjectResult d = Schema.SObjectType.FiscalForm__c;
        Map<String, Schema.RecordTypeInfo> rtMapById = d.getRecordTypeInfosByName();
        String recordTypeId = rtMapById.get('TDR').getRecordTypeId();
        String str = '[{"fundName":"SPECIAL","detailFund":"BUSINESS REGISTRATION - PVL","dateStr":"11/02/2020","remarks":"02/25.26.27 First Hawaii","totalDeposit":"1306.57","bankDeposit":"1306.57","electronicFundTransfer":"",' +
            '"creditCardProcessing":"","others":"","totalDeposit2":"1306.57","funds":[{"indexValue":"01","tcValue":"011","sValue":"S","yrValue":"21","appValue":"305","dValue":"R","sourceObjValue":"0159","costCenterValue":"0092",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":"1306.57"},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"",' +
            '"tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"",' +
            '"venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"",' +
            '"gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"",' +
            '"tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"",' +
            '"venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"",' +
            '"gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"",' +
            '"tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"",' +
            '"venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"",' +
            '"gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"","dValue":"","sourceObjValue":"","costCenterValue":"",' +
            '"projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null},{"indexValue":"","tcValue":"","sValue":"","yrValue":"","appValue":"",' +
            '"dValue":"","sourceObjValue":"","costCenterValue":"","projectNumValue":"","projectPhValue":"","deptActValue":"","gLActValue":"","sLActValue":"","venterNumValue":"","venterSFXValue":"","amount":null}]}]';

        String feedStr = '{"fundType":"Special","paymentType":"Credit Card","cutOffDate":"2020-11-01","startDate":"2019-10-29","division":"PVL"}"';

        String recordId ;
        recordId = TDRFormController.submitForFile(str, recordId, recordTypeId, feedStr);
        Test.startTest();
        TDRFormController.saveAsFile(recordId);
        TDRFormController.submitForFile(str, recordId, recordTypeId, feedStr);
    }
}