force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionGroup__c.field-meta.xml
<CustomField>
    <fullName>TransactionGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082618 - Created for phase 1</description>
    <label>Transaction Group</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Grouped Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PaymentReceiptPdfExtControllerTest.cls
/*
 * Created on 9/5/2018.
 * Author chris.loyola@pacificpointcorp.com
 */
@IsTest
private class PaymentReceiptPdfExtControllerTest {
    private static testmethod void testSetPaymentRecord() {
        RecordTypeInfo accountBusinessAccount = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('BusinessAccount');
        Account dummyAccount = new Account();
        dummyAccount.Name = 'Dummy Account Incorporation Incorporated';
        dummyAccount.RecordTypeId = accountBusinessAccount.getRecordTypeId();
        insert dummyAccount;

        CashierCode__c dummyCashierCode = new CashierCode__c();
        dummyCashierCode.Name = 'Dummy Cashier Code Name - TestTestTestTestTestTestTestTestTestTest';
        dummyCashierCode.Amount__c = 10.00;
        dummyCashierCode.CashierCode__c = 'DUM';
        insert dummyCashierCode;

        Transaction__c dummyTrans = new Transaction__c();
        dummyTrans.Account__c = dummyAccount.Id;
        dummyTrans.TransactionType__c = 'Payment';
        insert dummyTrans;

        TransactionLine__c dummyTL = new TransactionLine__c();
        dummyTL.Transaction__c = dummyTrans.Id;
        dummyTL.CashierCode__c = dummyCashierCode.Id;
        dummyTL.Account__c = dummyAccount.Id;
        insert dummyTL;

        pymt__PaymentX__c dummyPayment = new pymt__PaymentX__c();
        dummyPayment.Name = '123131';
        dummyPayment.Transaction__c = dummyTrans.Id;
        insert dummyPayment;  
        Test.startTest();
        PaymentReceiptPdfExtController extCtrl = new PaymentReceiptPdfExtController();
        extCtrl.setPaymentRecord(dummyPayment);
    }

    @IsTest
    static void controllerTest() {
        RecordTypeInfo accountBusinessAccount = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('BusinessAccount');
        Account dummyAccount = new Account();
        dummyAccount.Name = 'Dummy Account Incorporation Incorporated';
        dummyAccount.RecordTypeId = accountBusinessAccount.getRecordTypeId();
        insert dummyAccount;

        CashierCode__c dummyCashierCode = new CashierCode__c();
        dummyCashierCode.Name = 'Dummy Cashier Code Name - TestTestTestTestTestTestTestTestTestTest';
        dummyCashierCode.Amount__c = 10.00;
        dummyCashierCode.CashierCode__c = 'DUM';
        insert dummyCashierCode;

        Transaction__c dummyTrans = new Transaction__c();
        dummyTrans.Account__c = dummyAccount.Id;
        dummyTrans.TransactionType__c = 'Payment';
        insert dummyTrans;

        TransactionLine__c dummyTL = new TransactionLine__c();
        dummyTL.Transaction__c = dummyTrans.Id;
        dummyTL.CashierCode__c = dummyCashierCode.Id;
        dummyTL.Account__c = dummyAccount.Id;
        insert dummyTL;

        pymt__PaymentX__c dummyPayment = new pymt__PaymentX__c();
        dummyPayment.Name = '123131';
        dummyPayment.Transaction__c = dummyTrans.Id;
        insert dummyPayment;
        Test.startTest();
        PageReference pg = Page.PaymentReceiptPdf;
        Test.setCurrentPage(pg);
        pg.getParameters().put('Id', String.valueOf(dummyPayment.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(dummyPayment);
        PaymentReceiptPdfExtController extCtrl = new PaymentReceiptPdfExtController(sc);
        System.assert(!extCtrl.getTransactionLines().isEmpty());
        System.assert(extCtrl.getTransactionAccounts().isEmpty());

        Transaction__c dummyTrans2 = new Transaction__c();
        dummyTrans2.Account__c = dummyAccount.Id;
        dummyTrans2.TransactionType__c = 'Group';
        insert dummyTrans2;

        Transaction__c dummyTrans3 = new Transaction__c();
        dummyTrans3.Account__c = dummyAccount.Id;
        dummyTrans3.TransactionType__c = 'Payment';
        dummyTrans3.TransactionGroup__c = dummyTrans2.Id;
        insert dummyTrans3;

        pymt__PaymentX__c dummyPayment2 = new pymt__PaymentX__c();
        dummyPayment2.Name = '123131';
        dummyPayment2.Transaction__c = dummyTrans2.Id;
        insert dummyPayment2;

        TransactionLine__c dummyTL2 = new TransactionLine__c();
        dummyTL2.Transaction__c = dummyTrans2.Id;
        dummyTL2.CashierCode__c = dummyCashierCode.Id;
        dummyTL2.Account__c = dummyAccount.Id;
        insert dummyTL2;

        TransactionLine__c dummyTL3 = new TransactionLine__c();
        dummyTL3.Transaction__c = dummyTrans3.Id;
        dummyTL3.CashierCode__c = dummyCashierCode.Id;
        dummyTL3.Account__c = dummyAccount.Id;
        insert dummyTL3;
        
        PageReference pg2 = Page.PaymentReceiptPdf;
        Test.setCurrentPage(pg2);
        pg.getParameters().put('Id', String.valueOf(dummyPayment2.Id));
        ApexPages.StandardController sc2 = new ApexPages.StandardController(dummyPayment2);
        PaymentReceiptPdfExtController extCtrl2 = new PaymentReceiptPdfExtController(sc2);
        
        System.assert(!extCtrl2.getGroupedTransactionLines().isEmpty());
    }
}