force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cost Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FAMISSrcCode__c.field-meta.xml
<CustomField>
    <fullName>FAMISSrcCode__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>FAMIS Src Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Fund Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/CollectionsAllocation__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT012619 - Created for phase1</description>
    <label>Collections Allocation</label>
    <nameField>
        <displayFormat>C-{0000000}</displayFormat>
        <label>Collections Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsAllocation__c/fields/AmountAllocated__c.field-meta.xml
<CustomField>
    <fullName>AmountAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Amount Allocated from Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>TransactionLine__r.CashierCodeCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashier Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/NetCollectionsafterFeesAllocated__c.field-meta.xml
<CustomField>
    <fullName>NetCollectionsafterFeesAllocated__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <formula>IF( TrustAccount__c = TRUE, AmountAllocated__c, AmountAllocated__c - TotalFeesAllocated__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Collections after Fees Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsAllocation__c/fields/TransactionLine__c.field-meta.xml
<CustomField>
    <fullName>TransactionLine__c</fullName>
    <description>PacPoint-FT012619 - Created for phase 1</description>
    <label>Transaction Line</label>
    <referenceTo>TransactionLine__c</referenceTo>
    <relationshipLabel>Collections Allocations</relationshipLabel>
    <relationshipName>Collections_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <formula>CashierCode__r.CostCenter__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FAMISSrcCode__c.field-meta.xml
<CustomField>
    <fullName>FAMISSrcCode__c</fullName>
    <formula>CashierCode__r.FAMISSrcCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FAMIS Src Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/FundAccount__c.field-meta.xml
<CustomField>
    <fullName>FundAccount__c</fullName>
    <formula>CashierCode__r.FundAccount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fund Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/PaidStatus__c.field-meta.xml
<CustomField>
    <fullName>PaidStatus__c</fullName>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Paid Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BCF</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Chargeback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082718 - Created for phase 1</description>
    <label>Payment</label>
    <referenceTo>pymt__PaymentX__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollectionsAllocationDomainTest.cls
/*
 * -----------------------------------------------------------------------------------
 * Description
 *
 * -----------------------------------------------------------------------------------
 * Covered by: CollectionsAllocationDomainTestTest
 * -----------------------------------------------------------------------------------
 * PacPoint-CL03202023 - Created for
 * -----------------------------------------------------------------------------------
 * Initial implementation
 *
 * @author chris.loyola@pacificpointcorp.com
 *
 * @created 03/20/2023
 * -----------------------------------------------------------------------------------
 * Changes
 * -----------------------------------------------------------------------------------
 */
@IsTest
private class CollectionsAllocationDomainTest {
    @TestSetup
    static void setup() {
        Account a = new Account(Name = 'Test');
        insert a;

        Contact c = new Contact(LastName = 'Test', AccountId = a.Id);
        insert c;

        Transaction__c t = new Transaction__c(Account__c = a.Id);
        insert t;

        CashierCode__c cc = new CashierCode__c(Description__c = 'Test',
            Amount__c = 1.00,
            FAMISSrcCode__c = '1-1',
            CostCenter__c = '1',
            FundAccount__c = '1-1',
            CashierCode__c = '1-1');
        insert cc;

        TransactionLine__c tl = new TransactionLine__c(
            PaidStatus__c = 'Paid',
            Transaction__c = t.Id,
            CashierCode__c = cc.Id
        );
        insert tl;

        pymt__PaymentX__c payment = new pymt__PaymentX__c();
        payment.pymt__Status__c = 'Completed';
        payment.pymt__Payment_Type__c = 'Credit Card';
        insert payment;

        CollectionsAllocation__c col = new CollectionsAllocation__c();
        col.Payment__c = payment.Id;
        col.TransactionLine__c = tl.Id;
        col.AmountAllocated__c = 1;
        insert col;
    }

    @IsTest
    static void SummarizeAllocationRecordAmountTest() {
        CollectionsAllocation__c ca = new CollectionsAllocation__c();
        List<CollectionsAllocation__c> cas = [
            SELECT
                Id,
                AmountAllocated__c,
                NetCollectionsafterFeesAllocated__c,
                TransactionLine__r.CashierCode__r.FAMISSrcCode__c,
                TransactionLine__r.CashierCode__r.FundAccount__c,
                TransactionLine__r.CashierCode__r.CostCenter__c,
                TransactionLine__r.CashierCode__r.CashierCode__c,
                Transaction__c
            FROM CollectionsAllocation__c
        ];
        (new CollectionsAllocationDomain(cas)).summarizeAllocationRecordAmount('Credit Card');
    }

    @IsTest
    static void getDataFeedsTest() {
        CollectionsAllocation__c ca = new CollectionsAllocation__c();
        List<CollectionsAllocation__c> cas = [
            SELECT
                Id,
                AmountAllocated__c,
                NetCollectionsafterFeesAllocated__c,
                TransactionLine__r.CashierCode__r.FAMISSrcCode__c,
                TransactionLine__r.CashierCode__r.FundAccount__c,
                TransactionLine__r.CashierCode__r.CostCenter__c,
                TransactionLine__r.CashierCode__r.CashierCode__c,
                Transaction__c
            FROM CollectionsAllocation__c
        ];

        (new CollectionsAllocationDomain(cas)).getDataFeeds(new Map<String, Decimal>{
        '1-1-1-11'=> 1
        }, String.valueOf(Date.today().year()));
    }

    @IsTest
    static void getJVFeedsTest() {
        CollectionsAllocation__c ca = new CollectionsAllocation__c();
        List<CollectionsAllocation__c> cas = [
            SELECT
                Id,
                AmountAllocated__c,
                NetCollectionsafterFeesAllocated__c,
                TransactionLine__r.CashierCode__r.FAMISSrcCode__c,
                TransactionLine__r.CashierCode__r.FundAccount__c,
                TransactionLine__r.CashierCode__r.CostCenter__c,
                TransactionLine__r.CashierCode__r.CashierCode__c,
                Transaction__c,
                Payment__r.Name
            FROM CollectionsAllocation__c
        ];

        (new CollectionsAllocationDomain(cas)).getJVFeeds(String.valueOf(Date.today().year()));
    }

    @IsTest
    static void checkJVProcessedTest() {
        CollectionsAllocation__c ca = new CollectionsAllocation__c();
        List<CollectionsAllocation__c> cas = new List<CollectionsAllocation__c>{ca};
        (new CollectionsAllocationDomain(cas)).checkJVProcessed();
    }
}