force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NotificationDeletionBatch.cls
/*
 * -----------------------------------------------------------------------------------
 * Description
 * -----------------------------------------------------------------------------------
 * Covered by: NotificationDeletionBatchTest
 * -----------------------------------------------------------------------------------
 * PacPoint-CL05182022 - Created for PVL Case 00021633
 * -----------------------------------------------------------------------------------
 * Initial implementation
 *
 * @author chris.loyola@pacificpointcorp.com
 *
 * @created 05/18/2022
 * -----------------------------------------------------------------------------------
 * Changes
 * -----------------------------------------------------------------------------------
 */
public class NotificationDeletionBatch implements Schedulable, Database.Batchable<SObject>{

    public String query;

    public NotificationDeletionBatch() {
        query = 'SELECT Id ' +
                'FROM Notification__c ' +
                'WHERE (Status__c = \'Failed\' OR Status__c = \'Cancelled\') ' +
                'AND CreatedDate < LAST_N_DAYS:7';
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Notification__c> notifications = (List<Notification__c>) scope;
        delete notifications;
    }

    public void finish(Database.BatchableContext bc) {
    }

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator(query);
    }

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new NotificationDeletionBatch());
    }
}