force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/DocumentTemplateName__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateName__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Document Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/FailedReason__c.field-meta.xml
<CustomField>
    <fullName>FailedReason__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Fire__c.field-meta.xml
<CustomField>
    <fullName>Fire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to run the doc generator process.
PacPoint: AZ00008158PVL2</description>
    <label>Fire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/ScheduledTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledTime__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Scheduled Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/TimeDelivered__c.field-meta.xml
<CustomField>
    <fullName>TimeDelivered__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Time Delivered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/TimeSent__c.field-meta.xml
<CustomField>
    <fullName>TimeSent__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Time Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduledGenerateFiles.cls
global with sharing class ScheduledGenerateFiles implements schedulable, Database.Batchable<SObject>, Database.Stateful,Database.AllowsCallouts {
    public String query ='Select Id, Name, RecordId__c, Status__c,FailedReason__c,DocumentTemplateName__c, Fire__c, TimeDelivered__c, ScheduledTime__c, '
            +' TimeSent__c from Notification__c where ( Status__c = \'Failed\'  or Status__c =\'Scheduled\') and Scheduled__c = true';
    global DataBase.QueryLocator Start(Database.BatchableContext context) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext context, List<SObject> scope) {
        List<Notification__c> records = (List<Notification__c>) scope;
        (new NotificationDomain(records)).fireNotifications();
        // update records;
    }
    public void execute(System.SchedulableContext context) {
		Database.executeBatch(new ScheduledGenerateFiles(), 10);
	}
	/* batch finish class */
    global void finish(Database.BatchableContext context) {
        Database.executeBatch(new SendLetterToPrinterBatchJob(), 10);
    }
}