force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC100518 - Created for BREG phase 1</description>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/AssistantExaminer__c.field-meta.xml
<CustomField>
    <fullName>AssistantExaminer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC101018 - Created for BREG phase 1</description>
    <label>Assistant Examiner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exams1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/fields/SkipCustomEditValidation__c.field-meta.xml
<CustomField>
    <fullName>SkipCustomEditValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-CL02032022 - Created for case 00018526 Bypass Assistant Examiner/Owner edit validation</description>
    <label>SkipCustomEditValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FileDetails__c/FileDetails__c.object-meta.xml
<CustomObject>
    <description>PacPoint-JB103118 - Created for BREG phase 1:  Stores file header information</description>
    <label>File Details</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>File Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FileDetails__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-JB111618 - Created for BREG phase 1</description>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>File Details</relationshipLabel>
    <relationshipName>File_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FileDetails__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-JB111618 - Created for BREG phase 1</description>
    <label>Filing</label>
    <referenceTo>Filing__c</referenceTo>
    <relationshipLabel>File Details</relationshipLabel>
    <relationshipName>File_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FileDetails__c/fields/Locked__c.field-meta.xml
<CustomField>
    <fullName>Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-DL103121 for BREG Support Case2411. Referenced by automation to trigger creating or deleting a share record for granting or removing access to a File Detail record (example: grant/remove share for SEC users to edit an Exam record when Owner or Assistant Examiner field is populated; or edit a Filing record when Reviewer field is populated.</description>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Filing__c/Filing__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC100518 - Created for BREG phase 1</description>
    <label>Filing</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Filing__c/fields/AllowUserToPerformReviewer__c.field-meta.xml
<CustomField>
    <fullName>AllowUserToPerformReviewer__c</fullName>
    <description>(Reviewer__r.Email == &quot;cshimoda@dcca.hawaii.gov&quot;) &amp;&amp;  ($User.Email == &quot;byoshimura@dcca.hawaii.gov&quot; || $User.Email == &quot;yumi.hasegawa@pacificpointcorp.com&quot; )


(Reviewer__r.Email == &quot;tokuda@dcca.hawaii.gov.invalid&quot;) &amp;&amp;  ($User.Email == &quot;byoshimura@dcca.hawaii.gov.invalid&quot; || $User.Email == &quot;yumi.hasegawa+dccadev22@pacificpointcorp.com&quot; )</description>
    <formula>(Reviewer__r.Email == &quot;cshimoda@dcca.hawaii.gov&quot;) &amp;&amp;  ($User.Email == &quot;byoshimura@dcca.hawaii.gov&quot; || $User.Email == &quot;yumi.hasegawa@pacificpointcorp.com&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allow User To Perform Reviewer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <description>PacPoint-JB102418 - Created for BREG phase 1For display on page</description>
    <formula>CASE( RecordType.DeveloperName, &apos;Brokerdealer&apos;, &apos;Broker Dealer&apos;, &apos;ByQualification&apos;, &apos;By Qualification&apos;, &apos;Franchise&apos;, &apos;Franchise&apos;, &apos;IssuerDealer&apos;, &apos;Issuer-Dealer&apos;, &apos;InvestmentAdvisor&apos;, &apos;Investment Advisor&apos;, &apos;ModelAccreditedInvestor&apos;, &apos;Model Accredited Investor&apos;, &apos;MutualFund&apos;, &apos;Mutual Fund&apos;, &apos;RegulationA&apos;, &apos;Regulation A&apos;, &apos;RegulationD&apos;, &apos;Regulation D&apos;, &apos;SmallCompanyOfferingRegistrationSCOR&apos;, &apos;Small Company Offering Registration (SCOR)&apos;, &apos;Unknown&apos;)</formula>
    <label>Filing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-RA0101218 - Created for BREG phase 1</description>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Filings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/SkipReviewerEditValidation__c.field-meta.xml
<CustomField>
    <fullName>SkipReviewerEditValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-CL11242021 - Created for case 00018526</description>
    <label>SkipReviewerEditValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FileDetailSelector.cls
public class FileDetailSelector {
    public static List<FileDetails__c> getFileDetails(List<String> recordIds) {
        return [
                SELECT
                        Id,
                        OwnerId,
                        Locked__c,
                        Exam__c,
                        Exam__r.OwnerId,
                        Exam__r.AssistantExaminer__c,
                        Exam__r.SkipCustomEditValidation__c,
                        Filing__r.AllowUserToPerformReviewer__c,
                        Filing__r.OwnerId,
                        Filing__r.Reviewer__c,
                        Filing__r.SkipReviewerEditValidation__c,
                        Filing__c
                FROM FileDetails__c
                WHERE Id IN: recordIds
        ];
    }
}