force-app/main/default/objects/Earned_Continuing_Education__c/Earned_Continuing_Education__c.object-meta.xml
<CustomObject>
    <description>PacPoint-KN08312020-Created for CE and INS Portal</description>
    <label>Earned Continuing Education</label>
    <nameField>
        <displayFormat>CE-{00000}</displayFormat>
        <label>Earned Continuing Education Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Earned Continuing Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Earned_Continuing_Education__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-KN08312020-Created for CE and INS Portal</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Earned Continuing Education</relationshipLabel>
    <relationshipName>Earned_Continuing_Education</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/CoreCreditsThisLicensePeriod__c.field-meta.xml
<CustomField>
    <fullName>CoreCreditsThisLicensePeriod__c</fullName>
    <label>Core Credits - This License Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/License__c/fields/ElectiveCreditsThisLicensePeriod__c.field-meta.xml
<CustomField>
    <fullName>ElectiveCreditsThisLicensePeriod__c</fullName>
    <label>Elective Credits - This License Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduledClearEarnedCEBatch.cls
/**
 * ScheduledClearEarnedCEBatch
 * Author: Alvin Zhou
 * Date: December 5, 2023
 * 
 * Description:
 * This global class implements Salesforce's Schedulable, Batchable, and Stateful interfaces.
 * It's designed for batch processing of License__c records to update associated Earned_Continuing_Education__c records.
 * The class handles batch execution and can maintain state across transactions. It's also scheduled to run
 * as per Salesforce's scheduling framework.
 * It is supposed to run annually 1/1
 */

// Declares a global class that implements Schedulable, Batchable, and Stateful interfaces. 
// This class is designed to process records in batches and can maintain state across transactions.
global class ScheduledClearEarnedCEBatch implements Schedulable, Database.Batchable<SObject>, Database.Stateful {

    // Query to select License records with non-zero Core or Elective Credits.
    // Also fetches the first related Earned Continuing Education record for each License.
    global String query = 'Select Id, (Select Id, Name from Earned_Continuing_Education__r limit 1) from License__c where CoreCreditsThisLicensePeriod__c > 0 or ElectiveCreditsThisLicensePeriod__c > 0 ';
    
    // Start method of the batch class. It prepares the query locator for the batch process.
    global DataBase.QueryLocator Start(Database.BatchableContext context) {
        return Database.getQueryLocator(query);
    }

    // Execute method called for each batch of records processed. 
    // It updates Earned Continuing Education records associated with each License record.
    global void execute(Database.BatchableContext context, List<SObject> scope) {   
        List<License__c> records = (List<License__c>) scope;
        List<Earned_Continuing_Education__c> earnedRecords = new List<Earned_Continuing_Education__c>();
        
        // Iterates through each License record and accumulates associated Earned Continuing Education records.
        for(License__c record: records) {
            if(record.Earned_Continuing_Education__r != null)
                earnedRecords.addAll(record.Earned_Continuing_Education__r);
        }
        
        // Updates Earned Continuing Education records. This triggers automation to update License credit fields.
        if(!earnedRecords.isEmpty())
            update earnedRecords;
    }

    // Execute method for Schedulable context. It schedules the batch job with a batch size of 100.
    public void execute(System.SchedulableContext context) {
        Database.executeBatch(new ScheduledClearEarnedCEBatch(), 100);
    }
    
    // Finish method of the batch class. Currently, it does not perform any operations.
    global void finish(Database.BatchableContext context) {}
}