force-app/main/default/objects/breg_Account_Affiliation__c/breg_Account_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Aalta BREG-59</description>
    <label>Account Affiliation</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Account Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Address_Street_2__c.field-meta.xml
<CustomField>
    <fullName>breg_Address_Street_2__c</fullName>
    <description>Additional Street field for the Address field</description>
    <label>Address Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta Breg-59</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>BREG Case</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Account Affiliations</relationshipLabel>
    <relationshipName>Account_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Entity_Name__c</fullName>
    <label>Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_First_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Role__c.field-meta.xml
<CustomField>
    <fullName>breg_Role__c</fullName>
    <description>Aalta Breg-59</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Assignor</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>New Applicant</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>General Partner</fullName>
            </value>
            <value>
                <fullName>Incorporator</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Officer</fullName>
            </value>
            <value>
                <fullName>Officer/Director</fullName>
            </value>
            <value>
                <fullName>Organizer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Registrant</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Transferee</fullName>
            </value>
            <value>
                <fullName>Merging Entity</fullName>
            </value>
            <value>
                <fullName>Surviving Entity</fullName>
            </value>
            <value>
                <fullName>Recipient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Status__c.field-meta.xml
<CustomField>
    <fullName>breg_Status__c</fullName>
    <description>Aalta BREG-2367</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_TN_TM_SM__c.field-meta.xml
<CustomField>
    <fullName>breg_TN_TM_SM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TN/TM/SM</label>
    <referenceTo>breg_TN_TM_SM__c</referenceTo>
    <relationshipLabel>Account Affiliations</relationshipLabel>
    <relationshipName>breg_Account_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-59</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
                <label>Commercial Registered Agent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/breg_TN_TM_SM__c.object-meta.xml
<CustomObject>
    <label>TN/TM/SM</label>
    <nameField>
        <label>TN/TM/SM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TN/TM/SM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Cert_Number__c.field-meta.xml
<CustomField>
    <fullName>breg_Cert_Number__c</fullName>
    <description>Aalta BREG-61</description>
    <label>CERT #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>breg_Expiration_Date__c</fullName>
    <description>Aalta BREG-61</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Status__c.field-meta.xml
<CustomField>
    <fullName>breg_Status__c</fullName>
    <description>Aalta BREG-61</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Revoked</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_TM_SM_Category__c.field-meta.xml
<CustomField>
    <fullName>breg_TM_SM_Category__c</fullName>
    <description>Aalta BREG-61</description>
    <label>TM/SM Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TNTMSM_Classifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-61</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Name</fullName>
            </value>
            <value>
                <fullName>Trademark</fullName>
            </value>
            <value>
                <fullName>Service Mark</fullName>
            </value>
            <value>
                <fullName>Publicity Rights Name</fullName>
            </value>
            <value>
                <fullName>TNTMSM Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TNTMSM_Classifications.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0 - NO CATEGORY SELECTED</fullName>
    </customValue>
    <customValue>
        <fullName>1 - Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>2 - Paints</fullName>
    </customValue>
    <customValue>
        <fullName>3 - Cosmetics and Cleaning Preparations</fullName>
    </customValue>
    <customValue>
        <fullName>4 - Lubricants and Fuels</fullName>
    </customValue>
    <customValue>
        <fullName>5 - Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>6 - Metal Goods</fullName>
    </customValue>
    <customValue>
        <fullName>7 - Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>8 - Hand Tools</fullName>
    </customValue>
    <customValue>
        <fullName>9 - Electrical and Scientific Apparatus</fullName>
    </customValue>
    <customValue>
        <fullName>10 - Medical Apparatus</fullName>
    </customValue>
    <customValue>
        <fullName>11 - Environmental Control Apparatus</fullName>
    </customValue>
    <customValue>
        <fullName>12 - Vehicles</fullName>
    </customValue>
    <customValue>
        <fullName>13 - Firearms</fullName>
    </customValue>
    <customValue>
        <fullName>14 - Jewelry</fullName>
    </customValue>
    <customValue>
        <fullName>15 - Musical Instruments</fullName>
    </customValue>
    <customValue>
        <fullName>16 - Paper Goods and Printed Matter</fullName>
    </customValue>
    <customValue>
        <fullName>17 - Rubber Goods</fullName>
    </customValue>
    <customValue>
        <fullName>18 - Leather Goods</fullName>
    </customValue>
    <customValue>
        <fullName>19 - Nonmetallic Building Materials</fullName>
    </customValue>
    <customValue>
        <fullName>20 - Furniture and Articles Not Otherwise Classified</fullName>
    </customValue>
    <customValue>
        <fullName>21 - Houseware and Glass</fullName>
    </customValue>
    <customValue>
        <fullName>22 - Cordage and Fibers</fullName>
    </customValue>
    <customValue>
        <fullName>23 - Yarns and Threads</fullName>
    </customValue>
    <customValue>
        <fullName>24 - Fabrics</fullName>
    </customValue>
    <customValue>
        <fullName>25 - Clothing</fullName>
    </customValue>
    <customValue>
        <fullName>26 - Fancy Goods</fullName>
    </customValue>
    <customValue>
        <fullName>27 - Floor Coverings</fullName>
    </customValue>
    <customValue>
        <fullName>28 - Toys and Sporting Goods</fullName>
    </customValue>
    <customValue>
        <fullName>29 - Meats and Processed Foods</fullName>
    </customValue>
    <masterLabel>TNTMSM Classifications</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BREGCaseStatusHandlerTNTMSMRenewal.cls
/**
 * Handler for the TNTMSM Renewal forms (T-1, T-2, T-3)
 */
public with sharing class BREGCaseStatusHandlerTNTMSMRenewal extends BREGCaseStatusHandlerBase {
    public override void handleStatusChange(List<Case> cases, String newStatus, Boolean performValidation, Boolean performActions) {
        system.debug('BREGCaseStatusHandlerTNTMSMRenewal: ' + cases);
        if (performValidation) {
            super.handleStatusChange(cases, newStatus, true, false);
            performValidation(cases, newStatus);
        }

        if (performActions) {
            super.handleStatusChange(cases, newStatus, false, true);
            performActions(cases, newStatus);
        }
    }

    private void performValidation(List<Case> cases, String newStatus) {
        switch on newStatus {
            when 'Pending Submission' {
                checkDateOfTheFirstUse(cases);
            }
            when 'Approved' {
                checkTNTMSMIsLinked(cases);
            }
            when else {
                // do nothing
            }
        }
    }

    private void checkTNTMSMIsLinked(List<Case> cases) {
        String errorMessage = 'TN/TM/SM is required to approve a TN/TM/SM Renewal filing.';
        for (Case caseRecord : cases) {
            if (caseRecord.breg_TNTMSM_Registration_Type__c == 'Renewal' && caseRecord.breg_TN_TM_SM__c == null) {
                addErrorMessage(caseRecord, 'breg_TN_TM_SM__c', errorMessage);
            }
        }
    }

    private void checkDateOfTheFirstUse(List<Case> cases) {
        system.debug('TNTMSMRenewal:' + cases);
        String errorMessage = 'The date of first use cannot be a future date.';
        for (Case caseRecord : cases) {
            if (caseRecord.breg_TNTMSM_First_Used_Anywhere__c > Date.today() || caseRecord.breg_TNTMSM_First_Used_Hawaii__c > Date.today()) {
                addErrorMessage(caseRecord, '', errorMessage);
            }
        }
    }

    private void performActions(List<Case> cases, String newStatus) {
        // add specific actions for different statuses
        switch on newStatus {
            when 'Approved' {
                updateExpirationDate(cases);
            }
            when 'Completed' {
                updateTNTMSMs(cases);
            }
            when else {
                // do nothing
            }
        }
    }

    private void updateExpirationDate(List<Case> cases) {
        Map<Id, Date> previousExpirationDateByCaseId = getPreviousExpirationDateByCaseId(cases);
        List<Case> casesToUpdate = new List<Case>();
        for (Case c : cases) {
            Case cToUpdate = new Case();
            cToUpdate.Id = c.Id;

            Date baseExpirationDate = previousExpirationDateByCaseId.get(c.Id);
            if (baseExpirationDate != null) {
                cToUpdate.breg_Expiration_Date__c = baseExpirationDate.addYears(5);
            } else {
                // Add 5 years to the effective date to set the expiration date for new registrations.
                cToUpdate.breg_Expiration_Date__c = c.breg_Effective_Date__c != null ? c.breg_Effective_Date__c.addYears(5).addDays(-1) : null;
            }
            casesToUpdate.add(cToUpdate);
        }
        if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        }
    }

    private Map<Id, Date> getPreviousExpirationDateByCaseId(List<Case> cases) {
        Map<Id, Date> previousExpirationDateByCaseId = new Map<Id, Date>();
        Map<Id, String> lookupKeyByCaseId = new Map<Id, String>();
        Set<String> descriptions = new Set<String>();
        Set<String> certificates = new Set<String>();

        for (Case c : cases) {
            if (
                c.breg_TNTMSM_Registration_Type__c != 'Renewal' ||
                String.isBlank(c.breg_TNTMSM_Description__c) ||
                String.isBlank(c.breg_TNTMSM_Certificate__c)
            ) {
                continue;
            }

            lookupKeyByCaseId.put(c.Id, buildDescriptionCertificateKey(c.breg_TNTMSM_Description__c, c.breg_TNTMSM_Certificate__c));
            descriptions.add(c.breg_TNTMSM_Description__c);
            certificates.add(c.breg_TNTMSM_Certificate__c);
        }

        if (lookupKeyByCaseId.isEmpty()) {
            return previousExpirationDateByCaseId;
        }

        Map<String, Date> previousExpirationDateByLookupKey = new Map<String, Date>();

        for (breg_TN_TM_SM__c tntmsm : [
            SELECT Id, Name, breg_Cert_Number__c, breg_Expiration_Date__c
            FROM breg_TN_TM_SM__c
            WHERE Name IN :descriptions
                AND breg_Cert_Number__c IN :certificates
                AND breg_Expiration_Date__c != NULL
            ORDER BY breg_Expiration_Date__c DESC, CreatedDate DESC
        ]) {
            String lookupKey = buildDescriptionCertificateKey(tntmsm.Name, tntmsm.breg_Cert_Number__c);
            if (!previousExpirationDateByLookupKey.containsKey(lookupKey)) {
                previousExpirationDateByLookupKey.put(lookupKey, tntmsm.breg_Expiration_Date__c);
            }
        }

        for (Id caseId : lookupKeyByCaseId.keySet()) {
            Date previousExpirationDate = previousExpirationDateByLookupKey.get(lookupKeyByCaseId.get(caseId));
            if (previousExpirationDate != null) {
                previousExpirationDateByCaseId.put(caseId, previousExpirationDate);
            }
        }

        return previousExpirationDateByCaseId;
    }

    private String buildDescriptionCertificateKey(String description, String certificate) {
        return description + '|' + certificate;
    }

    private void updateTNTMSMs(List<Case> cases) {
        List<breg_TN_TM_SM__c> tnTmSmsToUpdate = new List<breg_TN_TM_SM__c>();
        Map<Id, breg_TN_TM_SM__c> tnTmSmsMap = getTNTMSMMap(getTNTMSMIds(cases));
        Map<Id, breg_Account_Affiliation__c> caseIdToAccAffsMap = getCaseIdToAccAffsMap(getCaseIds(cases));
        for (Case c : cases) {
            breg_Account_Affiliation__c accAff = caseIdToAccAffsMap.get(c.Id);
            if (tnTmSmsMap.containsKey(c.breg_TN_TM_SM__c)) {
                breg_TN_TM_SM__c tnTmSm = tnTmSmsMap.get(c.breg_TN_TM_SM__c);
                tnTmSm.breg_Expiration_Date__c = c.breg_Expiration_Date__c;
                if (c.breg_TNTMSM_Registration_Type__c == 'Renewal' || c.breg_Is_Renewal__c) {
                    if (tnTmSm.breg_Status__c == 'E') {
                        tnTmSm.breg_Status__c = 'A';
                    }
                }
                if (accAff != null) {
                    tnTmSm.breg_Mailing_Address__City__s = accAff.breg_Address__City__s;
                    tnTmSm.breg_Mailing_Address__StateCode__s = accAff.breg_Address__StateCode__s;
                    tnTmSm.breg_Mailing_Address__Street__s = accAff.breg_Address__Street__s;
                    tnTmSm.breg_Mailing_Address__PostalCode__s = accAff.breg_Address__PostalCode__s;
                    tnTmSm.breg_Mailing_Address__CountryCode__s = accAff.breg_Address__CountryCode__s;
                }
                if (c.breg_TNTMSM_Classification__c != null) {
                    tnTmSm.breg_TM_SM_Category__c = c.breg_TNTMSM_Classification__c;
                }
                tnTmSmsToUpdate.add(tnTmSm);
            }
        }
        if (!tnTmSmsToUpdate.isEmpty()) {
            update tnTmSmsToUpdate;
        }
    }

    private Map<Id, breg_TN_TM_SM__c> getTNTMSMMap(Set<Id> ids) {
        return new Map<Id, breg_TN_TM_SM__c>(
            [
                SELECT Id, breg_Expiration_Date__c, breg_Status__c
                FROM breg_TN_TM_SM__c
                WHERE Id IN :ids
            ]
        );
    }

    private Set<Id> getTNTMSMIds(List<Case> cases) {
        Set<Id> ids = new Set<Id>();
        for (Case c : cases) {
            if (c.breg_TN_TM_SM__c != null) {
                ids.add(c.breg_TN_TM_SM__c);
            }
        }
        return ids;
    }

    private Map<Id, breg_Account_Affiliation__c> getCaseIdToAccAffsMap(Set<Id> caseIds) {
        Map<Id, breg_Account_Affiliation__c> caseIdToAccAffsMap = new Map<Id, breg_Account_Affiliation__c>();

        List<breg_Account_Affiliation__c> accAffs = [
            SELECT
                Id,
                breg_Type__c,
                breg_Entity_Name__c,
                breg_First_Name__c,
                breg_Last_Name__c,
                breg_Role__c,
                breg_Case__c,
                breg_Address__CountryCode__s,
                breg_Address__StateCode__s,
                breg_Address__City__s,
                breg_Address__Street__s,
                breg_Address__PostalCode__s,
                breg_Address_Street_2__c
            FROM breg_Account_Affiliation__c
            WHERE breg_Case__c IN :caseIds AND (breg_Role__c = 'Applicant' OR breg_Role__c = 'New Applicant')
        ];

        for (breg_Account_Affiliation__c accAff : accAffs) {
            if (!caseIdToAccAffsMap.containsKey(accAff.breg_Case__c)) {
                caseIdToAccAffsMap.put(accAff.breg_Case__c, accAff);
            }
        }
        return caseIdToAccAffsMap;
    }
}