force-app/main/default/objects/breg_Account_Affiliation__c/breg_Account_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Aalta BREG-59</description>
    <label>Account Affiliation</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Account Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta Breg-59</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>BREG Case</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Account Affiliations</relationshipLabel>
    <relationshipName>Account_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Entity_Type__c</fullName>
    <description>Aalta BREG-369</description>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>breg_Entity_Type_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_First_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Role__c.field-meta.xml
<CustomField>
    <fullName>breg_Role__c</fullName>
    <description>Aalta Breg-59</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Assignor</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>New Applicant</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>General Partner</fullName>
            </value>
            <value>
                <fullName>Incorporator</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Officer</fullName>
            </value>
            <value>
                <fullName>Officer/Director</fullName>
            </value>
            <value>
                <fullName>Organizer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Registrant</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Transferee</fullName>
            </value>
            <value>
                <fullName>Merging Entity</fullName>
            </value>
            <value>
                <fullName>Surviving Entity</fullName>
            </value>
            <value>
                <fullName>Recipient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Status__c.field-meta.xml
<CustomField>
    <fullName>breg_Status__c</fullName>
    <description>Aalta BREG-2367</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_To_Remove__c.field-meta.xml
<CustomField>
    <fullName>breg_To_Remove__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To Remove</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-59</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
                <label>Commercial Registered Agent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/breg_Form_Configuration__c.object-meta.xml
<CustomObject>
    <label>Form Configuration</label>
    <nameField>
        <label>Form Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Business_Location__c.field-meta.xml
<CustomField>
    <fullName>breg_Business_Location__c</fullName>
    <label>Business Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Foreign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Business_Process__c.field-meta.xml
<CustomField>
    <fullName>breg_Business_Process__c</fullName>
    <label>Business Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Name Reservation</fullName>
            </value>
            <value>
                <fullName>Name Registration</fullName>
            </value>
            <value>
                <fullName>Annual Report</fullName>
            </value>
            <value>
                <fullName>Business Filing</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Business_Structure__c.field-meta.xml
<CustomField>
    <fullName>breg_Business_Structure__c</fullName>
    <label>Business Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cooperative</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Days_After_Submission_hold_Approval__c.field-meta.xml
<CustomField>
    <fullName>breg_Days_After_Submission_hold_Approval__c</fullName>
    <description>Aalta BREG-3564</description>
    <label>Days After Submission to hold Approval</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>breg_Entity_Type_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Form_Instruction_URL__c.field-meta.xml
<CustomField>
    <fullName>breg_Form_Instruction_URL__c</fullName>
    <label>Form Instruction URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Form_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Is_Expeditable__c.field-meta.xml
<CustomField>
    <fullName>breg_Is_Expeditable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Expeditable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Profit_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Profit_Type__c</fullName>
    <label>Profit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Profit</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Name</fullName>
            </value>
            <value>
                <fullName>Trademark</fullName>
            </value>
            <value>
                <fullName>Service Mark</fullName>
            </value>
            <value>
                <fullName>Publicity Rights Name</fullName>
            </value>
            <value>
                <fullName>TNTMSM Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Suffix_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Suffix_Code__c</fullName>
    <inlineHelpText>Specifies code of the form, i.e. A1, C-5, etc</inlineHelpText>
    <label>Suffix Code</label>
    <length>99</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_What_is_this_form__c.field-meta.xml
<CustomField>
    <fullName>breg_What_is_this_form__c</fullName>
    <inlineHelpText>This field is used to specify text message that is displayed in the &quot;What is this form&quot; component</inlineHelpText>
    <label>What is this form?</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration__c/fields/breg_Withdrawal_Range__c.field-meta.xml
<CustomField>
    <fullName>breg_Withdrawal_Range__c</fullName>
    <description>Time range (in hours) to accept submitted filing withdrawal</description>
    <inlineHelpText>In hours</inlineHelpText>
    <label>Withdrawal Range</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/breg_Form_Configuration_Item__c/breg_Form_Configuration_Item__c.object-meta.xml
<CustomObject>
    <label>Form Configuration Item</label>
    <nameField>
        <displayFormat>FCI-{00000}</displayFormat>
        <label>Form Configuration Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Configuration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Form_Configuration_Item__c/fields/breg_Form_Configuration__c.field-meta.xml
<CustomField>
    <fullName>breg_Form_Configuration__c</fullName>
    <label>Form Configuration</label>
    <referenceTo>breg_Form_Configuration__c</referenceTo>
    <relationshipLabel>Form Configuration Items</relationshipLabel>
    <relationshipName>breg_Form_Configuration_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BREG_Setting__c/BREG_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global settings for BREG Portal</description>
    <label>BREG Setting</label>
</CustomObject>

force-app/main/default/objects/BREG_Setting__c/fields/Home_Warning_Banner_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Home_Warning_Banner_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the Notice of Extension warning banner is displayed on the BREG portal home page.</description>
    <inlineHelpText>Show the Notice of Extension warning banner on the portal home page.</inlineHelpText>
    <label>Home Warning Banner Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BREGPortalUtilsTest.cls
@isTest
public class BREGPortalUtilsTest {

    @TestSetup
    static void setupTestData() {
        BREGTestDataFactory.createCommunityUser();
    }

    @isTest
    static void testIsHomeWarningBannerEnabled() {
        Assert.isFalse(BREGPortalUtils.isHomeWarningBannerEnabled(), 'Banner should be hidden when setting is not configured.');

        insert new BREG_Setting__c(SetupOwnerId = UserInfo.getOrganizationId(), Home_Warning_Banner_Enabled__c = true);

        Test.startTest();
        Boolean enabled = BREGPortalUtils.isHomeWarningBannerEnabled();
        Test.stopTest();

        Assert.isTrue(enabled, 'Banner should be visible when setting is enabled.');
    }

    @isTest
    static void testGetGp1FormUsReturnsG5Record() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'GP-1',
            breg_Suffix_Code__c = 'G5'
        );
        insert formConfig;

        Test.startTest();
        Id resultId = BREGPortalUtils.getGP1Form('US');
        Test.stopTest();

        Assert.areEqual(formConfig.Id, resultId, 'US country should return the G5 GP-1 form record.');
    }

    @isTest
    static void testGetGp1FormNonUsReturnsG6Record() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'GP-1',
            breg_Suffix_Code__c = 'G6'
        );
        insert formConfig;

        Test.startTest();
        Id resultId = BREGPortalUtils.getGP1Form('CA');
        Test.stopTest();

        Assert.areEqual(formConfig.Id, resultId, 'Non-US country should return the G6 GP-1 form record.');
    }

    @isTest
    static void testGetGp1FormNoRecordThrowsAuraHandledException() {
        Test.startTest();
        try {
            BREGPortalUtils.getGP1Form('US');
            Assert.fail('Expected AuraHandledException when no GP-1 record exists.');
        } catch (AuraHandledException ex) {
            Assert.isTrue(ex.getMessage() != null, 'Exception message should be present.');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetFormConfigurationByIdIncludesElements() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'CFG-ID',
            breg_Form_Instruction_URL__c = 'https://example.test/instructions',
            breg_What_is_this_Form__c = 'Read this: /{instructionURL}',
            breg_Days_After_Submission_hold_Approval__c = 5,
            breg_Suffix_Code__c = 'S1'
        );
        insert formConfig;

        BREGPortalUtils.FormConfiguration result;
        Test.startTest();
        System.runAs(BREGTestDataFactory.getTestCommunityUser()) {
            result = BREGPortalUtils.getFormConfiguration(formConfig.Id);
        }
        Test.stopTest();

        Assert.isNotNull(result, 'Form configuration should be returned for a valid Id.');
        Assert.areEqual(formConfig.Id, result.id, 'Returned config Id should match.');
        Assert.isTrue(result.whatIsThisForm.contains('https://example.test/instructions'), 'Instruction URL token should be replaced.');
        Assert.areEqual(5, result.daysAfterSubmissionHoldApproval, 'Days field should be mapped as Integer.');
        Assert.isNotNull(result.elements, 'Elements list should always be initialized.');
    }

    @isTest
    static void testGetFormConfigurationByCriteriaAndNoMatch() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'CFG-CRITERIA',
            breg_Suffix_Code__c = 'A1'
        );
        insert formConfig;

        BREGPortalUtils.FormConfiguration matched;
        BREGPortalUtils.FormConfiguration noMatch;
        Test.startTest();
        System.runAs(BREGTestDataFactory.getTestCommunityUser()) {
            matched = BREGPortalUtils.getFormConfiguration(
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            );
            noMatch = BREGPortalUtils.getFormConfiguration(
                'NON_EXISTENT_ID',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            );
        }
        Test.stopTest();

        Assert.isNotNull(matched, 'Configuration should be returned when all filter fields are null and record matches.');
        Assert.areEqual(formConfig.Id, matched.id, 'Matched Id should be the inserted record.');
        Assert.areEqual(null, noMatch, 'No match should return null.');
    }

    @isTest
    static void testGetUserInfoInternalUserShape() {
        Test.startTest();
        Map<String, Object> userInfo = BREGPortalUtils.getUserInfo();
        Test.stopTest();

        Assert.areEqual(false, (Boolean) userInfo.get('isGuest'), 'Current test-running user should not be guest.');
        Assert.isTrue(userInfo.containsKey('id'), 'User map should include id for internal user.');
    }

    @isTest
    static void testGetSsoUrlDoesNotReturnBlank() {
        Test.startTest();
        String ssoUrl;
        Exception captured;
        try {
            ssoUrl = BREGPortalUtils.getSSOUrl(null);
        } catch (Exception ex) {
            captured = ex;
        }
        Test.stopTest();

        Assert.isTrue(String.isNotBlank(ssoUrl), 'SSO URL should not be blank.');
    }

    @isTest
    static void testGetCaseWithRelationsNullIdThrows() {
        Test.startTest();
        try {
            BREGPortalUtils.getCaseWithRelations(null);
            Assert.fail('Expected AuraHandledException when case id is null.');
        } catch (AuraHandledException ex) {
            Assert.isTrue(String.isNotBlank(ex.getMessage()), 'Exception should include a message.');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetCaseWithRelationsValidIdReturnsCase() {
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case').getRecordTypeId();
        Case testCase = new Case(Subject = 'Portal Utils Test', Status = 'New', RecordTypeId = bregCaseRecordTypeId);
        insert testCase;

        Test.startTest();
        Case result = BREGPortalUtils.getCaseWithRelations(testCase.Id);
        Test.stopTest();

        Assert.isNotNull(result, 'Case should be returned for a valid case id.');
        Assert.areEqual(testCase.Id, result.Id, 'Returned case id should match inserted case id.');
    }

    @isTest
    static void testGetCaseWithRelationsExcludesAffiliationsMarkedToRemove() {
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case').getRecordTypeId();
        Case testCase = new Case(Subject = 'Portal Utils Test', Status = 'New', RecordTypeId = bregCaseRecordTypeId);
        insert testCase;

        breg_Account_Affiliation__c keptOfficer = new breg_Account_Affiliation__c(
            breg_Case__c = testCase.Id,
            breg_Role__c = 'Officer',
            breg_Type__c = 'Individual',
            breg_Status__c = 'A',
            breg_First_Name__c = 'Jane',
            breg_Last_Name__c = 'Kept'
        );
        breg_Account_Affiliation__c removedOfficer = new breg_Account_Affiliation__c(
            breg_Case__c = testCase.Id,
            breg_Role__c = 'Officer',
            breg_Type__c = 'Individual',
            breg_Status__c = 'A',
            breg_First_Name__c = 'John',
            breg_Last_Name__c = 'Removed',
            breg_To_Remove__c = true
        );
        insert new List<breg_Account_Affiliation__c>{ keptOfficer, removedOfficer };

        Test.startTest();
        Case result = BREGPortalUtils.getCaseWithRelations(testCase.Id);
        Test.stopTest();

        Set<Id> returnedAffiliationIds = new Set<Id>();
        for (breg_Account_Affiliation__c aff : result.Account_Affiliations__r) {
            returnedAffiliationIds.add(aff.Id);
        }

        Assert.isTrue(returnedAffiliationIds.contains(keptOfficer.Id), 'Active officer should still be returned.');
        Assert.isFalse(returnedAffiliationIds.contains(removedOfficer.Id), 'Officer marked to remove should not be returned when reloading a draft.');
    }

    @isTest
    static void testGetCaseForWithdrawalNullIdThrows() {
        Test.startTest();
        try {
            BREGPortalUtils.getCasesForWithdrawal(null);
            Assert.fail('Expected AuraHandledException when case id is null.');
        } catch (AuraHandledException ex) {
            Assert.isTrue(String.isNotBlank(ex.getMessage()), 'Exception should include a message.');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetCaseForWithdrawalValidIdReturnsWrapper() {
        Id bregCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('BREG_Case').getRecordTypeId();

        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'CASE-CFG',
            breg_Entity_Type__c = 'D1',
            breg_Suffix_Code__c = 'D1',
            breg_Form_Code__c = 'DC-1',
            breg_Form_Name__c = 'Articles of Incorporation',
            breg_Business_Process__c = 'New Business',
            breg_Is_Expeditable__c = true,
            breg_Withdrawal_Range__c = 24
        );
        insert formConfig;

        Case testCase = new Case(
            Subject = 'Withdrawal Test',
            RecordTypeId = bregCaseRecordTypeId,
            Status = 'New',
            breg_Workitem_Number__c = 'WI-001',
            breg_Form_Configuration__c = formConfig.Id,
            breg_Form_Code__c = 'DC-1'
        );
        insert testCase;

        Test.startTest();
        List<BREGPortalUtils.CaseWithdrawalDataWrapper> wrapperResults = BREGPortalUtils.getCasesForWithdrawal(new List<Id>{ testCase.Id });
        Test.stopTest();

        Assert.isNotNull(wrapperResults, 'Wrapper result should be returned for a valid case id.');
        Assert.areEqual(1, wrapperResults.size(), 'A single requested case should return a single wrapper.');
        BREGPortalUtils.CaseWithdrawalDataWrapper wrapperResult;
        for (BREGPortalUtils.CaseWithdrawalDataWrapper wrapper : wrapperResults) {
            if (wrapper.parentCaseId == testCase.Id) {
                wrapperResult = wrapper;
                break;
            }
        }

        Assert.isNotNull(wrapperResult, 'Wrapper should be found by matching parent case id.');
        Assert.areEqual(testCase.Id, wrapperResult.parentCaseId, 'Parent case id should be included in wrapper for client-side matching.');
        Assert.areEqual('Withdrawal Test', wrapperResult.entityName, 'Entity name should be mapped from case.');
        Assert.areEqual('WI-001', wrapperResult.workitemNumber, 'Workitem number should be mapped from case.');
        Assert.areEqual('DC-1', wrapperResult.formCode, 'Form code should be mapped from case.');
        Assert.areEqual('Articles of Incorporation', wrapperResult.formName, 'Form name should be mapped from case.');
    }

    @isTest
    static void testGetFormConfigurationTenParamOverload() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'CFG-10P',
            breg_Business_Process__c = 'New Business',
            breg_Business_Location__c = null,
            breg_Business_Structure__c = null,
            breg_Profit_Type__c = null,
            breg_Registration_Type__c = null,
            breg_Corporation_Type__c = null,
            breg_Cooperative_Type__c = null,
            breg_Stock_Type__c = null,
            breg_Partnership_Type__c = null,
            breg_Suffix_Code__c = 'X9'
        );
        insert formConfig;

        BREGPortalUtils.FormConfiguration result;
        Test.startTest();
        System.runAs(BREGTestDataFactory.getTestCommunityUser()) {
            result = BREGPortalUtils.getFormConfiguration(
                'New Business',
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            );
        }
        Test.stopTest();

        Assert.isNotNull(result, '10-param overload should return a matching configuration.');
    }

    @isTest
    static void testGetFormConfigurationWithConfigItems() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'CFG-ITEMS',
            breg_Suffix_Code__c = 'T1'
        );
        insert formConfig;

        insert new breg_Form_Configuration_Item__c(
            breg_Form_Configuration__c = formConfig.Id,
            breg_Component_Name__c = 'Company Name',
            breg_Order__c = 1,
            breg_Is_Internal_Only__c = false
        );

        BREGPortalUtils.FormConfiguration result;
        Test.startTest();
        System.runAs(BREGTestDataFactory.getTestCommunityUser()) {
            result = BREGPortalUtils.getFormConfiguration(formConfig.Id);
        }
        Test.stopTest();

        Assert.areEqual(1, result.elements.size(), 'One non-internal config item should produce one FormElement.');
        Assert.areEqual('Company Name', result.elements[0].name, 'FormElement name should match the component name.');
    }

    @isTest
    static void testGetFormConfigurationSkipsInternalOnlyItems() {
        breg_Form_Configuration__c formConfig = new breg_Form_Configuration__c(
            Name = 'CFG-INTERNAL',
            breg_Suffix_Code__c = 'I1'
        );
        insert formConfig;

        insert new breg_Form_Configuration_Item__c(
            breg_Form_Configuration__c = formConfig.Id,
            breg_Component_Name__c = 'Company Name',
            breg_Order__c = 1,
            breg_Is_Internal_Only__c = true
        );
        insert new breg_Form_Configuration_Item__c(
            breg_Form_Configuration__c = formConfig.Id,
            breg_Component_Name__c = 'Address',
            breg_Order__c = 2,
            breg_Is_Internal_Only__c = false
        );

        BREGPortalUtils.FormConfiguration result;
        Test.startTest();
        System.runAs(BREGTestDataFactory.getTestCommunityUser()) {
            result = BREGPortalUtils.getFormConfiguration(formConfig.Id);
        }
        Test.stopTest();

        Assert.isTrue(result.elements.size() >= 1, 'At least the visible item should be in elements.');
    }
}