force-app/main/default/objects/breg_Account_Affiliation__c/breg_Account_Affiliation__c.object-meta.xml
<CustomObject>
    <description>Aalta BREG-59</description>
    <label>Account Affiliation</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Account Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta Breg-59</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>BREG Case</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Account Affiliations</relationshipLabel>
    <relationshipName>Account_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Entity_Name__c</fullName>
    <label>Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_First_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Role__c.field-meta.xml
<CustomField>
    <fullName>breg_Role__c</fullName>
    <description>Aalta Breg-59</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Assignor</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>New Applicant</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>General Partner</fullName>
            </value>
            <value>
                <fullName>Incorporator</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Officer</fullName>
            </value>
            <value>
                <fullName>Officer/Director</fullName>
            </value>
            <value>
                <fullName>Organizer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Registrant</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Transferee</fullName>
            </value>
            <value>
                <fullName>Merging Entity</fullName>
            </value>
            <value>
                <fullName>Surviving Entity</fullName>
            </value>
            <value>
                <fullName>Recipient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_TN_TM_SM__c.field-meta.xml
<CustomField>
    <fullName>breg_TN_TM_SM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TN/TM/SM</label>
    <referenceTo>breg_TN_TM_SM__c</referenceTo>
    <relationshipLabel>Account Affiliations</relationshipLabel>
    <relationshipName>breg_Account_Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Account_Affiliation__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-59</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
                <label>Commercial Registered Agent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/breg_TN_TM_SM__c.object-meta.xml
<CustomObject>
    <label>TN/TM/SM</label>
    <nameField>
        <label>TN/TM/SM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TN/TM/SM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Registrant_First_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Registrant_First_Name__c</fullName>
    <label>Registrant First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Registrant_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Registrant_Last_Name__c</fullName>
    <label>Registrant Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Registrant_Name__c.field-meta.xml
<CustomField>
    <fullName>breg_Registrant_Name__c</fullName>
    <label>Registrant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Registrant_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Registrant_Type__c</fullName>
    <label>Registrant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>CRA</fullName>
                <label>Commercial Registered Agent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-61</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Name</fullName>
            </value>
            <value>
                <fullName>Trademark</fullName>
            </value>
            <value>
                <fullName>Service Mark</fullName>
            </value>
            <value>
                <fullName>Publicity Rights Name</fullName>
            </value>
            <value>
                <fullName>TNTMSM Assignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BREGCaseStatusHandlerTNTMSMRegNameChange.cls
/**
 * Handler for the TNTMSM Registrant Name Change form (T-5, TN-RNC)
 */
public with sharing class BREGCaseStatusHandlerTNTMSMRegNameChange extends BREGCaseStatusHandlerBase {
    public override void handleStatusChange(List<Case> cases, String newStatus, Boolean performValidation, Boolean performActions) {
        if (performValidation) {
            super.handleStatusChange(cases, newStatus, true, false);
            performValidation(cases, newStatus);
        }

        if (performActions) {
            super.handleStatusChange(cases, newStatus, false, true);
            performActions(cases, newStatus);
        }
    }

    private void performValidation(List<Case> cases, String newStatus) {
        // add specific validation for different statuses
        // switch on newStatus {
        //     when 'Approved' {
        //     }
        //     when else {
        //         // do nothing
        //     }
        // }
    }

    private void performActions(List<Case> cases, String newStatus) {
        // add specific actions for different statuses
        switch on newStatus {
            when 'Approved' {
                updateTNTMSMs(cases);
            }
            when else {
                // do nothing
            }
        }
    }

    private void updateTNTMSMs(List<Case> cases) {
        List<breg_TN_TM_SM__c> tnTmSmsToUpdate = new List<breg_TN_TM_SM__c>();
        Map<Id, breg_Account_Affiliation__c> caseIdToAccAffsMap = getCaseIdToAccAffsMap(getCaseIds(cases));
        for (Case c : cases) {
            if (c.breg_TN_TM_SM__c != null) {
                breg_TN_TM_SM__c tnTmSm = new breg_TN_TM_SM__c();
                tnTmSm.Id = c.breg_TN_TM_SM__c;

                breg_Account_Affiliation__c accAff = caseIdToAccAffsMap.containsKey(c.Id)
                    ? caseIdToAccAffsMap.get(c.Id)
                    : null;
                if (accAff != null && accAff.breg_Role__c == 'Applicant' && accAff.breg_TN_TM_SM__c == tnTmSm.Id) {
                    if (accAff.breg_Type__c == 'Entity') {
                        tnTmSm.breg_Registrant_Type__c = 'Entity';
                        tnTmSm.breg_Registrant_Name__c = accAff.breg_Entity_Name__c;
                        tnTmSm.breg_Registrant_First_Name__c = null;
                        tnTmSm.breg_Registrant_Last_Name__c = null;
                        tnTmSmsToUpdate.add(tnTmSm);
                    } else if (accAff.breg_Type__c == 'Individual') {
                        tnTmSm.breg_Registrant_Type__c = 'Individual';
                        tnTmSm.breg_Registrant_Name__c = null;
                        tnTmSm.breg_Registrant_First_Name__c = accAff.breg_First_Name__c;
                        tnTmSm.breg_Registrant_Last_Name__c = accAff.breg_Last_Name__c;
                        tnTmSmsToUpdate.add(tnTmSm);
                    }
                }
            }
        }
        if (!tnTmSmsToUpdate.isEmpty()) {
            update tnTmSmsToUpdate;
        }
    }

    private Map<Id, breg_Account_Affiliation__c> getCaseIdToAccAffsMap(Set<Id> caseIds) {
        Map<Id, breg_Account_Affiliation__c> caseIdToAccAffsMap = new Map<Id, breg_Account_Affiliation__c>();

        List<breg_Account_Affiliation__c> accAffs = [
            SELECT Id, breg_Type__c, breg_Entity_Name__c, breg_First_Name__c, breg_Last_Name__c, breg_Role__c, breg_Case__c, breg_TN_TM_SM__c
            FROM breg_Account_Affiliation__c
            WHERE breg_Case__c IN :caseIds AND breg_Role__c = 'Applicant' AND breg_TN_TM_SM__c != null LIMIT 1
        ];

        if (accAffs.size() > 0 && !caseIdToAccAffsMap.containsKey(accAffs[0].breg_Case__c)) {
            caseIdToAccAffsMap.put(accAffs[0].breg_Case__c, accAffs[0]);
        }

        return caseIdToAccAffsMap;
    }
}