force-app/main/default/objects/Field_Filter__c/Field_Filter__c.object-meta.xml
<CustomObject>
    <label>Field Filter</label>
    <nameField>
        <displayFormat>FFN-{00000000}</displayFormat>
        <label>Field Filter No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Filter__c/fields/Affected_Field_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Affected_Field_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affected Field Meta Data</label>
    <referenceTo>Field_Meta_Data__c</referenceTo>
    <relationshipLabel>Affected Field Meta Data</relationshipLabel>
    <relationshipName>Target_Field</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <formula>Affected_Field_Meta_Data__r.Card_Meta_Data__r.Application_Meta_Data__r.Name</formula>
    <label>Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Controlling_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Field_Name__c</fullName>
    <label>Controlling Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Controlling_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Field_Value__c</fullName>
    <label>Controlling Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Field_attribute_to_be_updated__c.field-meta.xml
<CustomField>
    <fullName>Field_attribute_to_be_updated__c</fullName>
    <label>Field attribute to be updated</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Read_Only</fullName>
            </value>
            <value>
                <fullName>Values</fullName>
            </value>
            <value>
                <fullName>Popover_Help</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Hidden__c.field-meta.xml
<CustomField>
    <fullName>Hidden__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hidden (Override)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label (Override)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Parent_Field_Filter__c.field-meta.xml
<CustomField>
    <fullName>Parent_Field_Filter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Field Filter</label>
    <referenceTo>Field_Filter__c</referenceTo>
    <relationshipLabel>Combination field filter</relationshipLabel>
    <relationshipName>Field_Filters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Placeholder__c</fullName>
    <label>Placeholder (Override)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Popover_Help__c.field-meta.xml
<CustomField>
    <fullName>Popover_Help__c</fullName>
    <description>If this field is populated, mouse over help will display on the control</description>
    <inlineHelpText>If this field is populated, mouse over help will display on the control</inlineHelpText>
    <label>Popover Help (Override)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify if the fields is for read only</description>
    <label>Read Only (Override)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required (Override)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Filter__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/Field_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains UI information for each field</description>
    <label>Field Meta Data</label>
    <nameField>
        <label>Field Meta Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Meta_Data__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Placeholder__c</fullName>
    <label>Placeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Popover_Help__c.field-meta.xml
<CustomField>
    <fullName>Popover_Help__c</fullName>
    <description>If this field is populated, mouse over help will display on the control</description>
    <inlineHelpText>If this field is populated, mouse over help will display on the control</inlineHelpText>
    <label>Popover Help</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify if the fields is for read only</description>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/sc_FieldFilterSelector.cls
public class sc_FieldFilterSelector {
    public static List<Field_Filter__c> getFieldFiltersByAppName(String appName) {
        return [Select Id, Controlling_Field_Name__c, Controlling_Field_Value__c, Affected_Field_Meta_Data__c,
            Field_attribute_to_be_updated__c, Hidden__c, Label__c, Placeholder__c, Values__c,
            Popover_Help__c, Read_Only__c, Required__c, Affected_Field_Meta_Data__r.Name__c,
            (select Id,  Controlling_Field_Name__c, Controlling_Field_Value__c from Field_Filters__r) 
            from Field_Filter__c where Application_Name__c =: appName  and Parent_Field_Filter__c = null];
    }
}