force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Course</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Address2__c.field-meta.xml
<CustomField>
    <fullName>Address2__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Address 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseId__c.field-meta.xml
<CustomField>
    <fullName>CourseId__c</fullName>
    <formula>IF(
NOT(ISBLANK(ExternalId__c)), 
ExternalId__c, 
IF(TEXT(Subject__r.Area__c) == &apos;Continuing Education&apos;, &apos;C&apos; + RIGHT(Name, 5), IF (TEXT(Subject__r.Area__c) == &apos;Prelicense&apos;, &apos;P&apos; + RIGHT(Name, 5), &apos;&apos;)))</formula>
    <label>CourseId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/InstructorName__c.field-meta.xml
<CustomField>
    <fullName>InstructorName__c</fullName>
    <formula>Instructor__r.InstructorName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instructor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Island__c.field-meta.xml
<CustomField>
    <fullName>Island__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Island</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oahu</fullName>
            </value>
            <value>
                <fullName>Molokai</fullName>
            </value>
            <value>
                <fullName>Lanai</fullName>
            </value>
            <value>
                <fullName>Kauai</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Maui</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>PacPoint-KN08122020-Created for PVL CE and INS</description>
    <formula>TEXT(Subject__r.Medium__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medium</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>USStates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <description>PacPoint-KN08112020-Created for PVL CE and INS Portal</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrelicenseCEEnrollment__c/PrelicenseCEEnrollment__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT080719- Created for PVL phase 1</description>
    <label>Prelicense / CE Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Continuing Education Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelicense / CE Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PrelicenseCEEnrollment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prelicense / CE Enrollment</relationshipLabel>
    <relationshipName>Prelicense_Continuing_Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrelicenseCEEnrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <description>PacPoint-08202020-Created for PVL CE and INS Portal</description>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Prelicense / CE Enrollment</relationshipLabel>
    <relationshipName>PrelicenseCEEnrollment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PrelicenseCEEnrollment__c/fields/EnrolleeName__c.field-meta.xml
<CustomField>
    <fullName>EnrolleeName__c</fullName>
    <formula>IF(

NOT(ISBLANK( License__c )),
License__r.LicenseeNameFormula__c,

IF(
NOT(ISBLANK(Account__c)),
Account__r.FirstName + &quot; &quot; + Account__r.LastName ,
FirstName__c + &quot; &quot; + LastName__c

)
 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrollee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrelicenseCEEnrollment__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT080719- Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Prelicense / CE Enrollment</relationshipLabel>
    <relationshipName>Continuing_Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrelicenseCEEnrollment__c/fields/MakeUpCredit__c.field-meta.xml
<CustomField>
    <fullName>MakeUpCredit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-KN09142020-Created for PVL CE and INS Portal</description>
    <label>Make Up Credit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PrelicenseCEEnrollment__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-KN08202020-Created for PVL CE and INS Portal</description>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipName>Prelicense_Continuing_Education</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT080920- Created for PVL phase 1</description>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>PacPoint-FT080920- Created for PVL phase 1</description>
    <label>Medium</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CECourseRosterController.cls
/*
 * ___________________________________________________________________________________
 * Description Controller for CECourseRoster VF Page
 * Covered by: CECourseRosterControllerTest
 * __________________________________________________________________________________
 * PacPoint-CL03242021 - Created for DCCA Portal
 * __________________________________________________________________________________
 * Initial implementation
 * 
 * @author chris.loyola@pacificpointcorp.com
 * 
 * @created 3/24/2021
 * __________________________________________________________________________________
 */
public class CECourseRosterController {
    public String courseId;

    public CECourseRosterController() {
        courseId = System.currentPageReference()
                .getParameters()
                .get('q');
    }

    public Data getCourse() {
        Data result = new Data();

        List<Course__c> c = [
                SELECT
                        Id,
                        Account__r.Name,
                        Account__r.ProviderSchoolID__c,
                        Subject__r.Name,
                        Medium__c,
                        CourseId__c,
                        StartDate__c,
                        StartTime__c,
                        Address__c,
                        Address2__c,
                        City__c,
                        Island__c,
                        State__c,
                        ZipCode__c,
                        InstructorName__c,
                        (SELECT
                                 Id,
                                 Account__r.Name,
                                 EnrolleeName__c,
                                 License__r.LicenseType__r.LicensePrefix__c,
                                 License__r.LicenseNumberFormula__c,
                                 MakeUpCredit__c
                        FROM PrelicenseCEEnrollment__r order by EnrolleeName__c)
                FROM Course__c
                WHERE Id =:courseId
        ];

        if (!c.isEmpty()) {
            result.course = c[0];
            if (result.course.StartTime__c != null) {
                Datetime tmpStartTime = Datetime.newInstance(Date.today(), result.course.StartTime__c);
                result.displayTime = tmpStartTime.format('hh:mm a');
            }

            String loc = String.isNotEmpty(result.course.Address__c) ? result.course.Address__c + ' ' : '';
            loc += String.isNotEmpty(result.course.Address2__c) ? result.course.Address2__c + ' ' : '';
            loc += String.isNotEmpty(result.course.City__c) ? result.course.City__c + ' ' : '';
            loc += String.isNotEmpty(result.course.Island__c) ? result.course.Island__c + ' ' : '';
            loc += String.isNotEmpty(result.course.State__c) ? result.course.State__c + ' ' : '';
            loc += String.isNotEmpty(result.course.ZipCode__c) ? result.course.ZipCode__c : '';
            result.displayLocation = loc;
        }

        return result;
    }

    public class Data{
        public Course__c course{
            get;set;
        }

        public String displayTime{
            get;set;
        }

        public String displayLocation{
            get;set;
        }
    }
}