force-app/main/default/objects/Filing__c/Filing__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC100518 - Created for BREG phase 1</description>
    <label>Filing</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Filing__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC0100518 - Created for BREG phase 1</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Accounts that are set as SEB/SEC accounts can be selected.</errorMessage>
        <filterItems>
            <field>Account.SEBSEC__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Filing</relationshipLabel>
    <relationshipName>Filing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <description>PacPoint-JB102418 - Created for BREG phase 1For display on page</description>
    <formula>CASE( RecordType.DeveloperName, &apos;Brokerdealer&apos;, &apos;Broker Dealer&apos;, &apos;ByQualification&apos;, &apos;By Qualification&apos;, &apos;Franchise&apos;, &apos;Franchise&apos;, &apos;IssuerDealer&apos;, &apos;Issuer-Dealer&apos;, &apos;InvestmentAdvisor&apos;, &apos;Investment Advisor&apos;, &apos;ModelAccreditedInvestor&apos;, &apos;Model Accredited Investor&apos;, &apos;MutualFund&apos;, &apos;Mutual Fund&apos;, &apos;RegulationA&apos;, &apos;Regulation A&apos;, &apos;RegulationD&apos;, &apos;Regulation D&apos;, &apos;SmallCompanyOfferingRegistrationSCOR&apos;, &apos;Small Company Offering Registration (SCOR)&apos;, &apos;Unknown&apos;)</formula>
    <label>Filing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-IC100918 - Created for BREG phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Filing Received</fullName>
            </value>
            <value>
                <fullName>Assigned for Review</fullName>
            </value>
            <value>
                <fullName>Review in Progress</fullName>
            </value>
            <value>
                <fullName>Deficiency Letter Sent</fullName>
            </value>
            <value>
                <fullName>Deficiency Response Received</fullName>
            </value>
            <value>
                <fullName>Reviewing Deficiency Response</fullName>
            </value>
            <value>
                <fullName>Filing Completed</fullName>
            </value>
            <value>
                <fullName>Filing Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Filings</relationshipLabel>
    <relationshipName>Filings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <description>PacPoint-CL092818 - Created for phase 1</description>
    <formula>IF( TEXT(TransactionGroup__r.Status__c)  = &apos;Completed&apos;, 0, (TotalAmount__c - TotalRefundAmount__c)-  PaymentAmount__c +  OverPaymentAmount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The net outstanding balance owned on this Transaction.  This is the Total Amount of the Transaction minus the Payment Amount (the amount that has already been paid) less any Refunds.</inlineHelpText>
    <label>Amount Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC101018 - Created for BREG phase 1</description>
    <label>Filing</label>
    <referenceTo>Filing__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <inlineHelpText>The Total Amount of the Transaction.  This is the Sum of all the Amounts on the Transaction Lines.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionGroup__c.field-meta.xml
<CustomField>
    <fullName>TransactionGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082618 - Created for phase 1</description>
    <label>Transaction Group</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Grouped Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SecurityPortalTransactionsHelperTest.cls
@isTest
private class SecurityPortalTransactionsHelperTest {
    @TestSetup
    static void makeData(){
        Account acc = new Account();
        acc.Name = 'Test 02282023';
        acc.SEBSEC__c = true;
        insert acc;

        Contact contct = new Contact();
        contct.FirstName = 'Test 02282023';
        contct.LastName = 'Test 02282023';
        contct.AccountId = acc.Id;
        insert contct;

        for(Integer x=0; x<3; x++){
            Filing__c filingApp = new Filing__c();
            filingApp.Name = 'Test Filing ' + x;
            filingApp.Account__c = acc.Id;
            insert filingApp;

            Transaction__c transactApp = new Transaction__c();
            transactApp.Description__c = 'Test Transaction ' + x;
            transactApp.Account__c = acc.Id;
            transactApp.Filing__c = filingApp.Id;
            transactApp.TotalAmount__c = 100;
            insert transactApp;
        }

        pymt__Settings__c ps = new pymt__Settings__c();
        ps.Name = 'Test Payment Connect Settings';
        insert ps;

        pymt__Processor_Connection__c pc = new pymt__Processor_Connection__c();
        pc.Name = 'Credit Card (Authorize.Net)';
        pc.pymt__PaymentConnect_Setup__c = ps.Id;
        insert pc;
    }

    @isTest
    private static void testUserAccount() {
        Test.startTest();
        User usr =  [Select Id, Name FROM User WHERE Profile.Name = 'DCCA BREG - CustomerCommunityLogin' limit 1];
        Id accId = SecurityPortalTransactionsHelper.getUserAccountId(usr.Id);
        Test.stopTest();
    }

    @isTest
    private static void testAccountFilings() {
        Test.startTest();
        User usr =  [Select Id, Name FROM User WHERE Profile.Name = 'DCCA BREG - CustomerCommunityLogin' limit 1];
        Id accId = SecurityPortalTransactionsHelper.getUserAccountId(usr.Id);
        List <Transaction__c> trans = [
            SELECT Id 
            FROM Transaction__c 
            WHERE (Filing__r.Account__c =: accId OR Filing__r.CreatedById =: usr.Id)
            AND Status__c != 'Completed'
            AND Filing__r.Status__c != 'Filing Withdrawn'
            AND TransactionGroup__r.Status__c != 'Completed'
            AND TransactionType__c != 'Group'
            AND AmountOutstanding__c > 0
        ];

        List<Transaction__c> accTransactions = SecurityPortalTransactionsHelper.getUserTransactions(usr.Id, accId, 'Name', 'ASC');
        Test.stopTest();

        System.assertEquals(trans.size(), accTransactions.size(), 'The same amount of outputs should have been returned as the amount of inputs');
    }

    @isTest
    private static void testGroupPayments() {
        Test.startTest();
        Account acc =  [Select Id, Name from Account WHERE Name = 'Test 02282023' limit 1];
        List <Transaction__c> trans = [Select Id, TotalAmount__c from Transaction__c WHERE Account__c =: acc.Id];

        List<Id> transactIds = new List<Id>();
        Decimal totalAmount = 0.00;
        for(Transaction__c tran: trans){
            transactIds.add(tran.Id);
            totalAmount += tran.TotalAmount__c;
        }

        sObject groupTrans = SecurityPortalTransactionsHelper.groupTransactions(transactIds, acc.Id, totalAmount);
        Test.stopTest();
    }
}