force-app/main/default/objects/Filing__c/Filing__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC100518 - Created for BREG phase 1</description>
    <label>Filing</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Filing__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <description>PacPoint-JB102418 - Created for BREG phase 1For display on page</description>
    <formula>CASE( RecordType.DeveloperName, &apos;Brokerdealer&apos;, &apos;Broker Dealer&apos;, &apos;ByQualification&apos;, &apos;By Qualification&apos;, &apos;Franchise&apos;, &apos;Franchise&apos;, &apos;IssuerDealer&apos;, &apos;Issuer-Dealer&apos;, &apos;InvestmentAdvisor&apos;, &apos;Investment Advisor&apos;, &apos;ModelAccreditedInvestor&apos;, &apos;Model Accredited Investor&apos;, &apos;MutualFund&apos;, &apos;Mutual Fund&apos;, &apos;RegulationA&apos;, &apos;Regulation A&apos;, &apos;RegulationD&apos;, &apos;Regulation D&apos;, &apos;SmallCompanyOfferingRegistrationSCOR&apos;, &apos;Small Company Offering Registration (SCOR)&apos;, &apos;Unknown&apos;)</formula>
    <label>Filing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Filings</relationshipLabel>
    <relationshipName>Filings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC101018 - Created for BREG phase 1</description>
    <label>Filing</label>
    <referenceTo>Filing__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <inlineHelpText>The Total Amount of the Transaction.  This is the Sum of all the Amounts on the Transaction Lines.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionGroup__c.field-meta.xml
<CustomField>
    <fullName>TransactionGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082618 - Created for phase 1</description>
    <label>Transaction Group</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Grouped Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Franchise_CheckoutController.cls
public without sharing class Franchise_CheckoutController {
    // definetion
	public Id paymentId       {get;set;}
	public String overrideDesc     {get;set;}
    public Integer groupFiling     {get;set;}
	
    //construction
    public Franchise_CheckoutController() {
        
        overrideDesc = '';
        paymentId = apexpages.currentpage().getparameters().get('pid');
        
        // Get Transaction ID from Payment Record
        pymt__PaymentX__c payment = [
            SELECT Id, Transaction__c, Transaction__r.TransactionType__c
            FROM pymt__PaymentX__c 
            WHERE id =: paymentId
        ];
        
        if(payment != null && payment.Transaction__c != null){
            // Get Filing Name of Transaction 
            String transactionId = payment.Transaction__c;
            
            if(payment.Transaction__r.TransactionType__c == 'Group'){
                groupFiling = 1;
                
                // If Transaction Type is "Group", get Filing Name of related Transactions
                List<Transaction__c> transactions = [
                    SELECT Id, TotalAmount__c, Filing__r.Name
               		FROM Transaction__c 
                    WHERE TransactionGroup__c =: transactionId
                ];
                
                overrideDesc += '<table width=\'100%\'>';
                for(Transaction__c transact: transactions){
                    overrideDesc += '<tr>';
                    overrideDesc += '<td>' + transact.Filing__r.Name + '</td>';
                    overrideDesc += '<td class=\'currency_column\'>$' + transact.TotalAmount__c + ' USD</td>';
                    overrideDesc += '</tr>';
                }
                
				overrideDesc += '</table>';               
            } else {
                groupFiling = 0;
                
                // If Transaction Type is "Payment", get Filing Name
                Transaction__c transact = [
                    SELECT Id, Filing__r.Name
               		FROM Transaction__c 
                    WHERE id =: transactionId
                ];
                
                if(transact != null && transact.Filing__r.Name != null){
                    overrideDesc = transact.Filing__r.Name;
                }
            }
        }
    }
}