force-app/main/default/objects/Application_Meta_Data__c/Application_Meta_Data__c.object-meta.xml
<CustomObject>
    <label>Application Meta Data</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Meta_Data__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <displayFormat>A-{000000}</displayFormat>
    <label>Application ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/Card_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains the section data for each card on an application</description>
    <label>Card Meta Data</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Meta_Data__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the Card to its application</description>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Card Meta Data</relationshipLabel>
    <relationshipName>Card_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Used to separate the different type for card display.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salary Table</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shared by children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/Field_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains UI information for each field</description>
    <label>Field Meta Data</label>
    <nameField>
        <label>Field Meta Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Meta_Data__c/fields/Card_Dependend_Value__c.field-meta.xml
<CustomField>
    <fullName>Card_Dependend_Value__c</fullName>
    <inlineHelpText>If the Field = Card Dependent Value, the Dependent Cards criteria will be triggered</inlineHelpText>
    <label>Card Dependent Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Card_Dependent_Action__c.field-meta.xml
<CustomField>
    <fullName>Card_Dependent_Action__c</fullName>
    <label>Card Dependent Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>hide</fullName>
            </value>
            <value>
                <fullName>show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Card_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Card_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link Field to its card</description>
    <label>Card Meta Data</label>
    <referenceTo>Card_Meta_Data__c</referenceTo>
    <relationshipLabel>Field Meta Data</relationshipLabel>
    <relationshipName>Field_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Client_Email_Response_Field__c.field-meta.xml
<CustomField>
    <fullName>Client_Email_Response_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field is checked, an email response will be send to this address</description>
    <inlineHelpText>If this field is checked, an email response will be send to this address</inlineHelpText>
    <label>Client Email Response Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Default_value_field__c.field-meta.xml
<CustomField>
    <fullName>Default_value_field__c</fullName>
    <description>Used for default field value prepopulate</description>
    <inlineHelpText>Used for pre populate user info to Lodging Card Info</inlineHelpText>
    <label>Default value field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/DependAction__c.field-meta.xml
<CustomField>
    <fullName>DependAction__c</fullName>
    <inlineHelpText>This specifies what is to be done to the dependend target control</inlineHelpText>
    <label>Depent Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>show</fullName>
            </value>
            <value>
                <fullName>hide</fullName>
            </value>
            <value>
                <fullName>set value</fullName>
            </value>
            <value>
                <fullName>show and set value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/DependendCards__c.field-meta.xml
<CustomField>
    <fullName>DependendCards__c</fullName>
    <inlineHelpText>The cards that will be affected if the Field Value = Depend Card Value. To be entered in the format: Card Name1=on,Card name2=off...</inlineHelpText>
    <label>Dependent Cards</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/DependField__c.field-meta.xml
<CustomField>
    <fullName>DependField__c</fullName>
    <inlineHelpText>The depended  target field to be affected when the depended value is matched</inlineHelpText>
    <label>Depent Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Inline_Label__c.field-meta.xml
<CustomField>
    <fullName>Inline_Label__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Styling: Inline Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>The target object to create when this application is submitted</inlineHelpText>
    <label>Target Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/ObjectField__c.field-meta.xml
<CustomField>
    <fullName>ObjectField__c</fullName>
    <inlineHelpText>The Target field on the Target Object to populate with the value from this field</inlineHelpText>
    <label>Target Object Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Parent_Object_Field_for_Input_Table__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Field_for_Input_Table__c</fullName>
    <description>This field will have the Field for the Parent to the related children object in the Multi Input Table as well as for File uploads</description>
    <inlineHelpText>This field will have the Field for the Parent to the related children object in the Multi Input Table as well as for File uploads</inlineHelpText>
    <label>Parent Object Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Placeholder__c</fullName>
    <label>Placeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to specify if the fields is for read only</description>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Target_Fields_For_Input_Table__c.field-meta.xml
<CustomField>
    <fullName>Target_Fields_For_Input_Table__c</fullName>
    <description>The corresponding Target field for each input table field. Note: the target object must point to the object containing these fields.</description>
    <inlineHelpText>The corresponding Target field for each input table field. Note: the target object must point to the object containing these fields.</inlineHelpText>
    <label>Target Fields For Input Table</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Target_Object_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Record_Type__c</fullName>
    <description>The DeveloperName of the record type of the object that this field will submit to.</description>
    <inlineHelpText>The DeveloperName of the record type of the object that this field will submit to.</inlineHelpText>
    <label>Target Object Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>textarea</fullName>
            </value>
            <value>
                <fullName>picklist</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>rich text</fullName>
            </value>
            <value>
                <fullName>inputtable</fullName>
            </value>
            <value>
                <fullName>radio</fullName>
            </value>
            <value>
                <fullName>multicheckbox</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>multiPicklist</fullName>
            </value>
            <value>
                <fullName>file</fullName>
            </value>
            <value>
                <fullName>table</fullName>
            </value>
            <value>
                <fullName>clm-file</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_ABN_Number__c.field-meta.xml
<CustomField>
    <fullName>Validation_ABN_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to validate the number for ABN</description>
    <label>Validation: ABN Number</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Date__c.field-meta.xml
<CustomField>
    <fullName>Validation_Date__c</fullName>
    <description>Used to validate date</description>
    <label>Validation(Date)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Email_Only__c.field-meta.xml
<CustomField>
    <fullName>Validation_Email_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation: Email Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Length__c.field-meta.xml
<CustomField>
    <fullName>Validation_Length__c</fullName>
    <label>Validation: Max Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Min_Length__c.field-meta.xml
<CustomField>
    <fullName>Validation_Min_Length__c</fullName>
    <label>Validation: Min Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_No_Space__c.field-meta.xml
<CustomField>
    <fullName>Validation_No_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation: No Space</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Numeric_greater_than_zero__c.field-meta.xml
<CustomField>
    <fullName>Validation_Numeric_greater_than_zero__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation: Numeric greater than zero</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Numeric_Only__c.field-meta.xml
<CustomField>
    <fullName>Validation_Numeric_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation: Numeric Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Phone_Only__c.field-meta.xml
<CustomField>
    <fullName>Validation_Phone_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation: Phone Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Regression__c.field-meta.xml
<CustomField>
    <fullName>Validation_Regression__c</fullName>
    <description>Used to specify the regression to validate if the string is meet the requirement, if it is meet, it will throw an error message</description>
    <label>Validation Regression</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Validation_Special_Chars__c.field-meta.xml
<CustomField>
    <fullName>Validation_Special_Chars__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation: No Special Characters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/sc_FieldMetaDataSelector.cls
public without sharing class sc_FieldMetaDataSelector {
    public static List<Field_Meta_Data__c> getFieldMetaDataByAppId(String appId){
        return [select Id, label__c, Name__c, Validation_Date__c, Name, Type__c, Card_Meta_Data__r.Name,Object__c,  ObjectField__c, Client_Email_Response_Field__c,
            Card_Meta_Data__r.Label__c, Card_Meta_Data__r.Application_Meta_Data__c, Default_value_field__c,Validation_Regression__c,
            Card_Meta_Data__r.Application_Meta_Data__r.Application_Id__c from Field_Meta_Data__c 
            where Card_Meta_Data__r.Application_Meta_Data__c =:appId];
    }
    
    public static List<Field_Meta_Data__c> getFieldMetaDataByAppIdToReview(String appId){
        return [select Id, label__c, Name__c, Validation_Date__c, Name, Type__c, Card_Meta_Data__r.Name,Object__c,  ObjectField__c, Client_Email_Response_Field__c,
            Card_Meta_Data__r.Label__c, Card_Meta_Data__r.Application_Meta_Data__c, Default_value_field__c, Validation_Regression__c,
            Card_Meta_Data__r.Application_Meta_Data__r.Application_Id__c from Field_Meta_Data__c 
            where Card_Meta_Data__r.Application_Meta_Data__c =:appId and Type__c != 'info' and Object__c != 'NA' ];
    }

    public static List<Field_Meta_Data__c> getFieldMetaDataByAppIdToReview(String appId, String cardMetaDataName) {
        return [select Id, label__c, Name__c, Validation_Date__c, Name, Type__c, Card_Meta_Data__r.Name,Object__c,  ObjectField__c, Client_Email_Response_Field__c,
            Card_Meta_Data__r.Label__c, Card_Meta_Data__r.Application_Meta_Data__c, Default_value_field__c, Validation_Regression__c,
            Card_Meta_Data__r.Application_Meta_Data__r.Application_Id__c from Field_Meta_Data__c 
            where Card_Meta_Data__r.Application_Meta_Data__c =:appId and Card_Meta_Data__r.Name =: cardMetaDataName and Type__c != 'info' and Object__c != 'NA' ];
    }

    public static List<Field_Meta_Data__c> getFieldMetaDataByAppIds(List<String> appIds){
        return [select Id, Name__c,Label__c,Validation_Date__c, Type__c,Object__c, Card_Meta_Data__r.Application_Meta_Data__c, Card_Meta_Data__c, Placeholder__c,Required__c,sort_order__c, Name, Values__c, Validation_numeric_only__c,Validation_Length__c, 
           Validation_Special_Chars__c, Validation_Email_Only__c,Validation_Phone_Only__c,Validation_ABN_Number__c,Read_Only__c, Validation_Numeric_greater_than_zero__c, 
           Parent_Object_Field_for_Input_Table__c, Target_Fields_For_Input_Table__c, Target_Object_Record_Type__c, Card_Meta_Data__r.Name, Validation_Regression__c,
           Validation_No_Space__c,Default_Value__c, Card_Dependent_Action__c,Validation_Min_Length__c,Card_Dependend_Value__c,DependendCards__c,Inline_Label__c, Client_Email_Response_Field__c,
           DependAction__c,DependField__c, DependValue__c,Hidden__c,Dependent_Value_to_be_set__c,input_table_cols__c, input_table_Field_types__c,Popover_Help__c, File_Upload_Holder_Object_Input_Table__c, 
           PicklistValues__c,Default_value_field__c, Use_Picklist_Values_From_SF__c, ObjectField__c from Field_Meta_Data__c where Active__c = true 
            and Card_Meta_Data__r.Application_Meta_Data__c in:appIds order by sort_order__c asc
        ];
    }
    
    public static List<Field_Meta_Data__c> getFieldMetaDataByAppName(String appName){
        return [select Id, Name__c,Label__c,Validation_Date__c,Type__c,Object__c,Card_Meta_Data__c, Placeholder__c,Required__c,sort_order__c, Name, Values__c, Validation_numeric_only__c,Validation_Length__c, 
           Validation_Special_Chars__c, Validation_Email_Only__c,Validation_Phone_Only__c,Validation_ABN_Number__c,Read_Only__c, Validation_Numeric_greater_than_zero__c, 
           Parent_Object_Field_for_Input_Table__c, Target_Fields_For_Input_Table__c, Target_Object_Record_Type__c, Validation_Regression__c,
           Validation_No_Space__c,Default_Value__c, Card_Dependent_Action__c,Validation_Min_Length__c,Card_Dependend_Value__c,DependendCards__c,Inline_Label__c, Client_Email_Response_Field__c,
           DependAction__c,DependField__c, DependValue__c,Hidden__c,Dependent_Value_to_be_set__c,input_table_cols__c, input_table_Field_types__c,Popover_Help__c, File_Upload_Holder_Object_Input_Table__c, 
           PicklistValues__c,Default_value_field__c, Use_Picklist_Values_From_SF__c, ObjectField__c from Field_Meta_Data__c where Active__c = true 
            and Card_Meta_Data__r.Application_Meta_Data__r.Name =:appName order by sort_order__c asc
        ];
    }

}