force-app/main/default/objects/Application_Meta_Data__c/Application_Meta_Data__c.object-meta.xml
<CustomObject>
    <label>Application Meta Data</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Meta_Data__c/fields/AppMetaId__c.field-meta.xml
<CustomField>
    <fullName>AppMetaId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>AppMetaId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/Card_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains the section data for each card on an application</description>
    <label>Card Meta Data</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Meta_Data__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the Card to its application</description>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Card Meta Data</relationshipLabel>
    <relationshipName>Card_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/CardMetaId__c.field-meta.xml
<CustomField>
    <fullName>CardMetaId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Used for export purpose</description>
    <externalId>true</externalId>
    <inlineHelpText>Used for export purpose</inlineHelpText>
    <label>CardMetaId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Footer__c.field-meta.xml
<CustomField>
    <fullName>Footer__c</fullName>
    <label>Footer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/NextActions__c.field-meta.xml
<CustomField>
    <fullName>NextActions__c</fullName>
    <label>Next Actions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Show_on_Initial_Load__c.field-meta.xml
<CustomField>
    <fullName>Show_on_Initial_Load__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show on Initial Load</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Used to separate the different type for card display.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salary Table</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shared by children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sc_CardMetaDataSelector.cls
public without sharing class sc_CardMetaDataSelector {
    public static List<Card_Meta_Data__c> getCardsByAppId(String appMetaDataId){
        return [SELECT Application_Meta_Data__c, Label__c, APPLICATION_META_DATA__R.APPMETAID__C, Name, CardMetaId__c,
            Footer__c, Header__c, Show_on_Initial_Load__c, Sort_Order__c, Type__c, NextActions__c FROM Card_Meta_Data__c where Application_Meta_Data__c=: appMetaDataId order by Sort_Order__c];
    }
    public static List<Card_Meta_Data__c> getCardsByAppIdAndName(String appMetaDataId, String cardMetaDataName){
        return [SELECT Application_Meta_Data__c, Label__c, APPLICATION_META_DATA__R.APPMETAID__C, Name, CardMetaId__c,
            Footer__c, Header__c, Show_on_Initial_Load__c, Sort_Order__c, Type__c, NextActions__c FROM Card_Meta_Data__c where Application_Meta_Data__c=: appMetaDataId and Name =: cardMetaDataName 
            order by Sort_Order__c];
    }
    public static List<Card_Meta_Data__c> getCardsAndFieldsByAppId(String appName){
        return [select id, Name, Header__c,Footer__c,sort_order__c,Label__c, Show_on_Initial_Load__c, Application_Meta_Data__c, NextActions__c
            from Card_Meta_Data__c where Application_Meta_Data__r.Name =: appName order by sort_order__c asc];
    }
    
    public static List<Card_Meta_Data__c> getCardsAndFieldsByAppName(String appName){
        return [select Id, Name, Header__c,Footer__c,sort_order__c,Label__c, Show_on_Initial_Load__c, Application_Meta_Data__c, Type__c, NextActions__c
            from Card_Meta_Data__c where Application_Meta_Data__r.Name =: appName order by sort_order__c asc];
    }
}