force-app/main/default/objects/Application_Meta_Data__c/Application_Meta_Data__c.object-meta.xml
<CustomObject>
    <label>Application Meta Data</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Meta_Data__c/Card_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains the section data for each card on an application</description>
    <label>Card Meta Data</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Meta_Data__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the Card to its application</description>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Card Meta Data</relationshipLabel>
    <relationshipName>Card_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Used to separate the different type for card display.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salary Table</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shared by children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/Field_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains UI information for each field</description>
    <label>Field Meta Data</label>
    <nameField>
        <label>Field Meta Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Meta_Data__c/fields/Card_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Card_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link Field to its card</description>
    <label>Card Meta Data</label>
    <referenceTo>Card_Meta_Data__c</referenceTo>
    <relationshipLabel>Field Meta Data</relationshipLabel>
    <relationshipName>Field_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>textarea</fullName>
            </value>
            <value>
                <fullName>picklist</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>rich text</fullName>
            </value>
            <value>
                <fullName>inputtable</fullName>
            </value>
            <value>
                <fullName>radio</fullName>
            </value>
            <value>
                <fullName>multicheckbox</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>multiPicklist</fullName>
            </value>
            <value>
                <fullName>file</fullName>
            </value>
            <value>
                <fullName>table</fullName>
            </value>
            <value>
                <fullName>clm-file</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/sc_CardMetaDataService.cls
public class sc_CardMetaDataService {
    
    /****
     * Description: get list of cards and fields by applicaiton name
     * Used by : by sc_onboardingController.getCard
     *           Revenue_ApplicationController.getMyObjects
     *  
    *****/
    public static List<sc_CardFeed> getCardsAndFieldsByAppName(String appName){
        List<Card_Meta_Data__c> cardMetaData 
            = sc_CardMetaDataSelector.getCardsAndFieldsByAppName(appName);
        List<Field_Meta_Data__c> fieldMetaData 
            = sc_FieldMetaDataSelector.getFieldMetaDataByAppName(appName);
        
        Map<String, List<Field_Meta_Data__c>> fieldMeta 
            = (new sc_FieldMetaDataDomain(fieldMetaData)).getCardToFieldsMap();
        List<Card_Meta_Data__c> filterCards = (List<Card_Meta_Data__c>)(new sc_CardMetaDataDomain(cardMetaData)).filterRecords('Type__c', 'Shared by children');
        filterCards = (List<Card_Meta_Data__c>)(new sc_CardMetaDataDomain(filterCards)).filterRecords('Type__c', 'Hidden');
        return (new sc_CardMetaDataDomain(filterCards)).updateCardWithFields(fieldMeta);
    }
    
    /***
        Description: get cards from the application metadata Id
        Used By: sc_ApplicationCacheService.getCardFeeds
    ****/
    public static List<sc_CardFeed> getCardToFields(String appMetaId) {
        List<Card_Meta_Data__c> cards = sc_CardMetaDataSelector.getCardsByAppId(appMetaId);
        return getCardFeeds(appMetaId, cards);
    }
    /***
        Description: get cards from the application metadata Id and Cards
        Used By: CardMetaDataService.getSharedCards
    ****/
    public static List<sc_CardFeed> getCardFeeds(String appMetaId, List<Card_Meta_Data__c> cardMetaData) {
        List<Field_Meta_Data__c> fields = sc_FieldMetaDataSelector.getFieldMetaDataByAppIds((new List<String>{appMetaId}));
        Map<String, List<Field_Meta_Data__c>> fieldMeta 
            = (new sc_FieldMetaDataDomain(fields)).getCardToFieldsMap();
        return (new sc_CardMetaDataDomain(cardMetaData)).updateCardWithFields(fieldMeta);    
    }

    /****
     * Description: get list of cards and fields by applicaiton name
     * Used by : by sc_onboardingController.getCard
     *           Revenue_ApplicationController.getMyObjects
     *  
    *****/
    public static List<sc_CardFeed> getCards(String appName){
        
        List<Card_Meta_Data__c> cardMetaData 
            = sc_CardMetaDataSelector.getCardsAndFieldsByAppName(appName);
        List<Card_Meta_Data__c> cards = new List<Card_Meta_Data__c>();
        for(Card_Meta_Data__c card: cardMetaData ) {
            cards.add(card);
        }

        List<Field_Meta_Data__c> fieldMetaData 
            = sc_FieldMetaDataSelector.getFieldMetaDataByAppName(appName);
            
        // List<Field_Meta_Data__c> extrafieldMetaData 
        //     = FieldMetaDataSelector.getFieldMetaDataByAppName(extraCardMeta.Application_Meta_Data__r.Name);
        // fieldMetaData.addAll(extrafieldMetaData);     
        Map<String, List<Field_Meta_Data__c>> fieldMeta 
            = (new sc_FieldMetaDataDomain(fieldMetaData)).getCardToFieldsMap();
        List<Card_Meta_Data__c> filterCards = (List<Card_Meta_Data__c>)(new sc_CardMetaDataDomain(cards)).filterRecords('Type__c', 'Hidden');
        return (new sc_CardMetaDataDomain(filterCards)).updateCardWithFields(fieldMeta);
    }
    
    public static void getFieldByAppName(String appName) {
                
    }
    
}