force-app/main/default/objects/CustomLog__c/CustomLog__c.object-meta.xml
<CustomObject>
    <description>create records of this type in apex or other process when wanting to store error messages or info in the database</description>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomLog__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Name of Apex Class</description>
    <inlineHelpText>Name of Apex Class</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomLog__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <defaultValue>1</defaultValue>
    <description>1-9. 1 is highest priority log, 9 is lowest priority log.</description>
    <inlineHelpText>number in range [1-9]. 1 is highest priority log (e.g. exceptions), 9 is lowest priority log (e.g. info).</inlineHelpText>
    <label>Log Level</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message or Info Message. Says what went wrong or what is happening.</description>
    <inlineHelpText>Exception Message or Info Message. Says what went wrong or what is happening.</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomLog__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Name of Apex method</description>
    <inlineHelpText>Name of Apex method</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomLog__c/fields/Occured__c.field-meta.xml
<CustomField>
    <fullName>Occured__c</fullName>
    <description>Exact Date/Time that this log event occured. Useful since some logs will be created in @future method.</description>
    <inlineHelpText>Exact Date/Time that this log event occured</inlineHelpText>
    <label>Occured</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomLog__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>any additional data/parameters that would be helpful to have</description>
    <inlineHelpText>any additional data/parameters that would be helpful to have (e.g. failing record id)</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>where in the code this log occurred</description>
    <inlineHelpText>where in the code this log occurred (retrieved from exception.getStackTraceString() for exceptions)</inlineHelpText>
    <label>Stack Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomLogEvent__e/CustomLogEvent__e.object-meta.xml
<CustomObject>
    <description>this event is published in apex code when we want to log an error to the CustomLog__c object, and still throw the error.</description>
    <label>Custom Log Event</label>
    <pluralLabel>Custom Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomLogEvent__e/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomLogEvent__e/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>LogLevel</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomLogEvent__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomLogEvent__e/fields/Occured__c.field-meta.xml
<CustomField>
    <fullName>Occured__c</fullName>
    <label>Occured</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomLogEvent__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomLogLevelSettings__c/CustomLogLevelSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Add a Number field for each apex class. If value = 0, log nothing. If value is between 1 and 9 (inclusive), log everything with log level &lt;= value. (e.g. if value is 4, log everything with log level 1, 2, 3, or 4)</description>
    <label>Custom Log Level Settings</label>
</CustomObject>

force-app/main/default/classes/CustomLogger.cls
/**
 * @author Mike Ceryak
 * @since 10/11/2021
 * 
 * Test Class: CustomLoggerTest
 * Description: Utilize this class to create CustomLog__c records for Errors or Info based on CustomLogLevelSettings__c custom setting.
 */
public without sharing class CustomLogger {

    public static Boolean alwaysAsync = false;
    // PUBLIC METHODS

    public static void log(String className, String methodName, String message, String parameters, String stackTrace, Integer logLevel) {
        if (validateLogLevelSettings(className, logLevel)) { 
            createLog(className, methodName, parameters, stackTrace, message, logLevel); 
        }
    }

    public static void logException(Exception e, String className, String methodName, String parameters) {
        if (validateLogLevelSettings(className, 1)) {
            logImmediately(className, methodName, parameters, e.getStackTraceString(), e.getMessage(), 1);
        }
    }


    // PRIVATE METHODS

    // Determines if log record should be created based on CustomLogLevelSettings__c custom setting.If the logLevel <= the value in the custom setting, return true. Else, return false. 
    // Default to true if no custom setting field is found for this class name.
    private static Boolean validateLogLevelSettings(String className, Integer logLevel) {
        if (logLevel < 1 || logLevel > 9) {
            throw new CustomLogException('logLevel must be in range [1, 9]. Given: ' + logLevel);
        }
        String fieldName = className + '__c';
        if (Schema.SObjectType.CustomLogLevelSettings__c.fields.getMap().containsKey(fieldName.toLowercase())) { 
            return logLevel <= Integer.valueOf(CustomLogLevelSettings__c.getInstance(UserInfo.getUserId()).get(fieldName));
        }
        return true;
    }

    // Publishes a log event immediately so that an error can still be thrown without rolling back the creation of the log record, which happens in a platform event-triggered flow
    public static void logImmediately(String className, String methodName, String parameters, String stackTrace, String message, Integer logLevel) {
        CustomLogEvent__e logEvent = new CustomLogEvent__e(
            Class__c = className,
            Method__c = methodName,
            Message__c = StringUtil.shortenedTo(255, message),
            StackTrace__c = StringUtil.shortenedTo(255, stackTrace),
            Parameters__c = parameters,
            LogLevel__c = logLevel,
            Occured__c = System.now()
        );
        Eventbus.publish(logEvent);
    }

    private static void createLog(String className, String methodName, String parameters, String stackTrace, String message, Integer logLevel) {
        CustomLog__c log = new CustomLog__c(
            Class__c = className,
            Method__c = methodName,
            Message__c = StringUtil.shortenedTo(255, message),
            StackTrace__c = StringUtil.shortenedTo(255, stackTrace),
            Parameters__c = stackTrace + '\n' + parameters,
            LogLevel__c = logLevel,
            Occured__c = System.now()
        );
        if (alwaysAsync || (!System.isBatch() && !System.isFuture())) {
            insertLogFuture(JSON.serialize(log));
        } else {
            handleLogInsert(log);
        }
    }

    @TestVisible
    private static void handleLogInsert(CustomLog__c log) {
        try {
            insert log;
        } catch (Exception e) {
            System.debug('failed to insert custom log because of exception: ' + e.getMessage() + ', ' + e.getStackTraceString());
        }
    }

    @future
    private static void insertLogFuture(String jsonLog) {
        CustomLog__c log = (CustomLog__c)JSON.deserialize(jsonLog, CustomLog__c.class);
        handleLogInsert(log);
    }

    public class CustomLogException extends Exception {}

}