force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicense__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Entities</relationshipLabel>
    <relationshipName>AssociatedEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>EmploymentStatus__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending Employment</fullName>
                <isActive>false</isActive>
                <label>Pending Employment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/ThisLicenseRenewed__c.field-meta.xml
<CustomField>
    <fullName>ThisLicenseRenewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>This License Renewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint KN080819 - Created for PVL</description>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/Licensee__c.field-meta.xml
<CustomField>
    <fullName>Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The account that this license belongs too.</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/ThisLicenseRenewed__c.field-meta.xml
<CustomField>
    <fullName>ThisLicenseRenewed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, prevents license from being renewed through MyPVL.</inlineHelpText>
    <label>This License Renewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>Active / Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/AutoForfeitureStatus__c.field-meta.xml
<CustomField>
    <fullName>AutoForfeitureStatus__c</fullName>
    <description>PacPoint-KN081619 - Created for PVL Phase 1</description>
    <label>Auto Forfeiture Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LicenseStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suspense__c/Suspense__c.object-meta.xml
<CustomObject>
    <label>Suspense</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Suspense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspense</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Suspense__c/fields/Historical__c.field-meta.xml
<CustomField>
    <fullName>Historical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Historical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/InsuranceType__c.field-meta.xml
<CustomField>
    <fullName>InsuranceType__c</fullName>
    <description>PacPoint-KN08062020 - Created for PVL Phase 1 Sprint 6</description>
    <label>Insurance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Insurance_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Suspense</relationshipLabel>
    <relationshipName>Suspense</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/SuspenseDueDate__c.field-meta.xml
<CustomField>
    <fullName>SuspenseDueDate__c</fullName>
    <label>Suspense Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Suspense__c/fields/SuspenseStatus__c.field-meta.xml
<CustomField>
    <fullName>SuspenseStatus__c</fullName>
    <description>PacPoint-KN08072020-Created for PVL Phase 1 Sprint 6</description>
    <label>Suspense Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LicenseStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Insurance_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BD - Bond</fullName>
    </customValue>
    <customValue>
        <fullName>BX - Bond Exemption (All Boards)</fullName>
    </customValue>
    <customValue>
        <fullName>D - Employee Dishonesty Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>EX - Exemption</fullName>
    </customValue>
    <customValue>
        <fullName>FS - Pre-Need Funeral Service Trust</fullName>
    </customValue>
    <customValue>
        <fullName>GM - Perpetual Care (Ground Maintenance) Trust</fullName>
    </customValue>
    <customValue>
        <fullName>LC - Line of Credit</fullName>
    </customValue>
    <customValue>
        <fullName>LI - Liability</fullName>
    </customValue>
    <customValue>
        <fullName>LP - Liability / Property Damage</fullName>
    </customValue>
    <customValue>
        <fullName>PI - Pre-Need Interment (Burial) Services Trust</fullName>
    </customValue>
    <customValue>
        <fullName>SI - Exclusion from Workers Comp.</fullName>
    </customValue>
    <customValue>
        <fullName>SL - Self-Insured for W/C (Entity OK&apos;d By Labor Dept)</fullName>
    </customValue>
    <customValue>
        <fullName>SM - No HI Employees - Submit Workers Comp Prior to Hiring</fullName>
    </customValue>
    <customValue>
        <fullName>SW - Workers Comp Thru Leasing Co.</fullName>
    </customValue>
    <customValue>
        <fullName>SX - Exemption No Longer Allowed</fullName>
    </customValue>
    <customValue>
        <fullName>T1 - Client Trust Account #1</fullName>
    </customValue>
    <customValue>
        <fullName>T2 - Client Trust Account #2</fullName>
    </customValue>
    <customValue>
        <fullName>T3 - Client Trust Account #3</fullName>
    </customValue>
    <customValue>
        <fullName>T4 - Client Trust Account #4</fullName>
    </customValue>
    <customValue>
        <fullName>T5 - Client Trust Account #5</fullName>
    </customValue>
    <customValue>
        <fullName>TC - Charter Tour</fullName>
    </customValue>
    <customValue>
        <fullName>WC - Workers Compensation</fullName>
    </customValue>
    <customValue>
        <fullName>WP - Submit Prior to Hiring Hi Empl - Evidence of WC Not Submitted</fullName>
    </customValue>
    <masterLabel>Insurance Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AssociatedApplicationSuspenseCheckTest.cls
@isTest
private class AssociatedApplicationSuspenseCheckTest {
    @TestSetup
    static void makeData(){
        Account acc = TestDataFactory.createAccountUnit('Test Account 1', '222222');
        insert acc;
        List<LicenseType__c> licenseTypes 
            = TestDataFactory.createLicenseTypes(new List<String>{'AMD', 'MD'});
        for(LicenseType__c lt: licenseTypes) {
            lt.AutoForfeitureStatus__c = 'C - Current, Valid & In Good Standing';
        }
        update licenseTypes;
        List<License__c> licenses = new List<License__c>();
        Set<String> entityTypes = new Set<String>{'MD'};
        for(LicenseType__c licenseType: licenseTypes) {
            License__c lic = new License__c();
            lic.Name = licenseType.Name + '-1';
            lic.Licensee__c = acc.Id;
            lic.LicenseType__c = licenseType.Id;
            lic.ActiveInactive__c  = 'Active';
            lic.LicenseType__r = licenseType;
            if(entityTypes.contains(licenseType.Name) ) {
                lic.Status__c = 'CM - Current, Valid & In Good Standing/Maint. Requirement Due';
            } else {
                lic.Status__c = 'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due';
            }
            lic.ThisLicenseRenewed__c = true;
            if(!entityTypes.contains(licenseType.Name)) {
                License__c clonedRecord = lic.clone();
                licenses.add(clonedRecord);
            }
            licenses.add(lic);
        }
        
        insert licenses;
        for(License__c record: licenses) {
            if(entityTypes.contains(record.LicenseType__r.Name) ) {
                record.Status__c = 'CM - Current, Valid & In Good Standing/Maint. Requirement Due';
            } else {
                record.Status__c = 'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due';
            }
        }
        update licenses;
        String recordId;
        List<AssociatedLicense__c> assLicenses = new List<AssociatedLicense__c>();
        List<License__c> entityLicenses = [Select Id from License__c where LicenseType__r.Name in: entityTypes];
        for(License__c license: licenses) {
            if(license.LicenseType__r.Name =='AMD') {
                for(License__c entityLicense: entityLicenses) {
                    AssociatedLicense__c al = new AssociatedLicense__c();
                    al.EmployeeLicense__c = license.Id;
                    al.EntityLicense__c = entityLicense.Id;
                    al.EmploymentStatus__c = 'Employed';
                    assLicenses.add(al);
                    recordId = license.Id;
                }
                break;
            }
        }
        if(assLicenses.size() > 0){
            insert assLicenses;
        }
        Suspense__c suspense = new Suspense__c();
        suspense.License__c = recordId;
        suspense.InsuranceType__c = 'BD - Bond';
        suspense.SuspenseDueDate__c = System.today() + 10;
        suspense.Historical__c = false;
        suspense.SuspenseStatus__c = 'C - Current, Valid & In Good Standing';
        suspense.MaintenanceType__c = 'NFRM - RME WITHOUT EMPLOYMENT' ;
        insert suspense;
    }

    @isTest
    static void testExecute() {
        Set<String> entityTypes = new Set<String>{'MD'};
        List<AssociatedApplicationSuspenseCheck.Input> inputs = new List<AssociatedApplicationSuspenseCheck.Input>();
        License__c license = [Select Id from License__c where LicenseType__r.Name in: entityTypes limit 1];
        
        AssociatedApplicationSuspenseCheck.Input i = new AssociatedApplicationSuspenseCheck.Input();
        i.license = license;
        inputs.add(i);
        
        Test.startTest();
        AssociatedApplicationSuspenseCheck.execute(inputs);
        Test.stopTest();
    }

}