force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicense__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Entities</relationshipLabel>
    <relationshipName>AssociatedEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicenseStatus__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicenseStatus__c</fullName>
    <description>Pac Point-DN010820 - Created for PVL Sprint 3 Phase 1</description>
    <formula>TEXT(EmployeeLicense__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee License Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicenseType__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicenseType__c</fullName>
    <description>Pac Point-DN010820 - Created for PVL Sprint 3 Phase 1</description>
    <formula>EmployeeLicense__r.LicenseType__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee License Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>EmploymentStatus__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending Employment</fullName>
                <isActive>false</isActive>
                <label>Pending Employment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicenseStatus__c.field-meta.xml
<CustomField>
    <fullName>EntityLicenseStatus__c</fullName>
    <description>Pac Point-DN010820 - Created for PVL Sprint 3 Phase 1</description>
    <formula>TEXT(EntityLicense__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity License Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACR - AUCTIONEER (MOTOR VEHICLE INDUSTRY)</fullName>
            </value>
            <value>
                <fullName>AMD - PHYSICIAN&apos;S ASSISTANT (MEDICAL)</fullName>
            </value>
            <value>
                <fullName>AP - APPRENTICE (COSMETOLOGY BEAUTY APPRENTICE)</fullName>
            </value>
            <value>
                <fullName>BAR - BARBER</fullName>
            </value>
            <value>
                <fullName>BEO - BEAUTY OPERATOR</fullName>
            </value>
            <value>
                <fullName>BIC - BROKER-IN-CHARGE (REAL ESTATE COMMISSION)</fullName>
            </value>
            <value>
                <fullName>BO - BRANCH OFFICE</fullName>
            </value>
            <value>
                <fullName>CBA - MOTOR VEHICLE BROKER AGENT</fullName>
            </value>
            <value>
                <fullName>CDH - COMMUNITY SERVICE DENTAL HYGIENIST</fullName>
            </value>
            <value>
                <fullName>CDT - COMMUNITY SERVICE DENTIST</fullName>
            </value>
            <value>
                <fullName>CPA - CERTIFIED PUBLIC ACCOUNTANT</fullName>
            </value>
            <value>
                <fullName>CS - MOTOR VEHICLE SALESPERSON (MOTOR VEHICLE INDUSTRY BOARD)</fullName>
            </value>
            <value>
                <fullName>DHT - TEMPORARY DENTAL HYGIENIST</fullName>
            </value>
            <value>
                <fullName>DRP - DISTRIBUTOR REPRESENTATIVE (MOTOR VEHICLE INDUSTRY)</fullName>
            </value>
            <value>
                <fullName>DTT - TEMPORARY DENTIST</fullName>
            </value>
            <value>
                <fullName>EIC - SALES AGENT EMPLOYEE/INDEPENDENT CONTRACTOR (TIME SHARE)</fullName>
            </value>
            <value>
                <fullName>EMP - EMPLOYMENT AGENCY PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>FR - FIELD REPRESENTATIVE (PEST CONTROL)</fullName>
            </value>
            <value>
                <fullName>FRP - FACTORY REPRESENTATIVE (MOTOR VEHICLE INDUSTRY)</fullName>
            </value>
            <value>
                <fullName>GVT - PHYSICIAN % GOVERNMENT (MEDICAL)</fullName>
            </value>
            <value>
                <fullName>I - INACTIVE</fullName>
            </value>
            <value>
                <fullName>ITR - INSTRUCTORS</fullName>
            </value>
            <value>
                <fullName>MAT - MASSAGE THERAPIST</fullName>
            </value>
            <value>
                <fullName>MC - CERTIFIED MECHANIC</fullName>
            </value>
            <value>
                <fullName>MOP - MANAGING OPERATOR (COSMETOLOGY)</fullName>
            </value>
            <value>
                <fullName>MRC - REGISTERED CERTIFIED MECHANIC</fullName>
            </value>
            <value>
                <fullName>MR - REGISTERED MECHANIC</fullName>
            </value>
            <value>
                <fullName>MS - SOLICITOR (MORTGAGE BROKERS)</fullName>
            </value>
            <value>
                <fullName>OPC - OUTSIDE PUBLIC CONTACT (TIME SHARE)</fullName>
            </value>
            <value>
                <fullName>PA - PUBLIC ACCOUNTANT (CHANGED &quot;PA&quot; FROM &quot;PRINCIPAL AGENT&quot; FOR EMP TO &quot;PUBLIC ACCOUNTANT&quot; FOR ACCOUNTANCY BOARD PER 12/9/10 ICSD MTG)</fullName>
            </value>
            <value>
                <fullName>PB - PRINCIPAL BROKER (REAL ESTATE COMMISSION)</fullName>
            </value>
            <value>
                <fullName>SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/PositionStatus__c.field-meta.xml
<CustomField>
    <fullName>PositionStatus__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D - DESIGNATED</fullName>
            </value>
            <value>
                <fullName>P - PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>T - TEMPORARY (REAL ESTATE)</fullName>
            </value>
            <value>
                <fullName>X - EXTEND TEMPORARY (REAL ESTATE)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint KN080819 - Created for PVL</description>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/EffectiveExpireDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveExpireDate__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The date the license expires</inlineHelpText>
    <label>Effective Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Ins_Expire_Cancel_Date__c.field-meta.xml
<CustomField>
    <fullName>Ins_Expire_Cancel_Date__c</fullName>
    <label>Ins Expire/Cancel Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
            <value>
                <fullName>ZI - Automatically Forfeited Due To Insurance Loss (60 Days to Restore)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssociatedLicenseSelector.cls
public class AssociatedLicenseSelector {
    public static List<AssociatedLicense__c> getAssociatedLicenses(List<Id> entityLicenseIds) {
       return [
           Select Id, EndDate__c, EmploymentStatus__c, EntityLicense__c, EmployeeLicense__c, EntityLicense__r.EffectiveExpireDate__c from AssociatedLicense__c WHERE EntityLicense__c IN: entityLicenseIds
       ];
    }
    public static List<AssociatedLicense__c> getAssociatedEmployeeLicenses(List<Id> licenseIds) {
        return [
            Select Id, EmploymentStatus__c, EntityLicense__c, EmployeeLicense__c,  EmployeeLicense__r.EffectiveExpireDate__c from AssociatedLicense__c 
            WHERE EmployeeLicense__c IN: licenseIds and EmploymentStatus__c = 'Employed'
        ];
     }

     public static List<AssociatedLicense__c> getActiveBSHEntityLicenses(List<String> licenseIds) {
        return [
            Select Id, EmploymentStatus__c, EntityLicense__c, EmployeeLicense__c,  EmployeeLicense__r.EffectiveExpireDate__c from AssociatedLicense__c 
            WHERE EmployeeLicense__c IN: licenseIds and EmploymentStatus__c = 'Employed' and EmployeeLIcense__r.ActiveInactive__c = 'Active' 
            and (EndDate__c > today or EndDate__c = null) and EntityLicense__r.LicenseType__r.Name = 'BSH'
            and ((Position__c = 'BEO - BEAUTY OPERATOR' and PositionStatus__c = 'D - Designated' ) or Position__c = 'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)')  
        ];
     }

     public static List<AssociatedLicense__c> getActiveBASEntityLicenses(List<String> licenseIds) {
        return [
            Select Id, EmploymentStatus__c, EntityLicense__c, EmployeeLicense__c,  EmployeeLicense__r.EffectiveExpireDate__c from AssociatedLicense__c 
            WHERE EmployeeLicense__c IN: licenseIds and EmploymentStatus__c = 'Employed' and (EndDate__c > today or EndDate__c = null) and EntityLicense__r.LicenseType__r.Name = 'BAS'
            and ((Position__c = 'BAR - BARBER' and PositionStatus__c = 'D - Designated' ) or Position__c = 'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)')  
        ];
     }
     // 00026663
     public static List<AssociatedLicense__c> getActiveEmployerLicenses(Set<Id> recordIds) {
        return [
            Select Id, EmploymentStatus__c, EntityLicense__c, EmployeeLicense__c,  EmployeeLicense__r.EffectiveExpireDate__c from AssociatedLicense__c 
            WHERE EmploymentStatus__c = 'Terminated' and EmployeeLicense__c in: recordIds order by LastModifiedDate desc
        ];
     }
     // 00026663
     public static List<AssociatedLicense__c> getTerminatedEmployerLicenses(Set<Id> recordIds) {
        return [
            Select Id, EmploymentStatus__c, EmployeeLicense__r.LicenseType__r.AutoForfeitureStatus__c, 
            EntityLicense__r.Status__c, EntityLicense__c, EmployeeLicense__c, 
            EntityLicense__r.Ins_Expire_Cancel_Date__c,
            EmployeeLicense__r.EffectiveExpireDate__c from AssociatedLicense__c 
            WHERE EmploymentStatus__c = 'Terminated' and EmployeeLicense__c in: recordIds order by EndDate__c
        ];
     }

    //add for case 7697
    public static List<AssociatedLicense__c> getEmployedAssociatedLicenses(List<Id> entityLicenseIds) {
        return [
            Select Id, EntityLicense__c, EmployeeLicense__c from AssociatedLicense__c WHERE EntityLicense__c IN: entityLicenseIds 
                AND EmploymentStatus__c = 'Employed' 
                AND EmployeeLicense__c != null 
                AND (EmployeeLicense__r.Status__c = 'C - Current, Valid & In Good Standing' 
                OR EmployeeLicense__r.Status__c = 'CM - Current, Valid & In Good Standing/Maint. Requirement Due'
                OR EmployeeLicense__r.Status__c = 'R - Valid Thru Expiration Date, Subject To Renewal'
                OR EmployeeLicense__r.Status__c = 'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due')
                AND EmployeeLicense__r.ActiveInactive__c = 'Active'
        ];
    }  

    public static List<AssociatedLicense__c> getEmployedAssociatedLicensesForCheck(List<Id> entityLicenseIds) {
        return [
            Select Id, EntityLicense__c, EmployeeLicense__c from AssociatedLicense__c WHERE EntityLicense__c IN: entityLicenseIds 
                AND EmploymentStatus__c = 'Employed' 
                AND EmployeeLicense__c != null 
                And ( EndDate__c > today OR EndDate__c = null)
                AND (EmployeeLicense__r.Status__c = 'CM - Current, Valid & In Good Standing/Maint. Requirement Due'
                OR EmployeeLicense__r.Status__c = 'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due')
        ];
    }  

    public static List<AggregateResult> getEntityLicenseCount(List<String> employeeLicenseIds) {
        return [
            Select Count(Id) numCount, EmployeeLicense__c from AssociatedLicense__c
            where EmployeeLicense__c in: employeeLicenseIds and (EndDate__c > today or EndDate__c = null) 
            and EmploymentStatus__c = 'Employed' and EntityLicense__r.ActiveInactive__c <> 'Inactive'
            and (EntityLicense__r.Status__c = 'C - Current, Valid & In Good Standing' 
            OR EntityLicense__r.Status__c = 'CR - Current/Next Renewal Paid' 
            OR EntityLicense__r.Status__c = 'CP - Current Pending' 
            OR EntityLicense__r.Status__c = 'CM - Current, Valid & In Good Standing/Maint. Requirement Due'
            OR EntityLicense__r.Status__c = 'R - Valid Thru Expiration Date, Subject To Renewal'
            OR EntityLicense__r.Status__c = 'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due'
            OR EntityLicense__r.Status__c = 'Z - Current & Valid, But Subject To Disciplinary Requirement' 
            OR EntityLicense__r.Status__c = 'ZI - Automatically Forfeited Due To Insurance Loss (60 Days to Restore)' 
            OR EntityLicense__r.Status__c = 'ZM - Current & Valid, But Subject To Disciplinary/Maintenance Requirement' )
            group by EmployeeLicense__c
        ];
    }

    public static List<AssociatedLicense__c> getPrincipalAssociatedLicenses(Set<String> licenseIds) {
        return [
            Select Id, EntityLicense__c 
            from AssociatedLicense__c 
            where EntityLicense__c in: licenseIds 
            and (
                (
                    EntityLicense__r.LicenseType__r.Name != 'RB - Entity'
                    AND (
                        (PositionStatus__c = 'P - PRINCIPAL' AND EntityLicense__r.LicenseType__r.TypeofPositionStatus__c  = 'P - PRINCIPAL')
                        OR (PositionStatus__c = 'D - DESIGNATED' AND EntityLicense__r.LicenseType__r.TypeofPositionStatus__c  = 'D - DESIGNATED')
                    )
                )
                or (EntityLicense__r.LicenseType__r.Name = 'RB - Entity' AND PositionStatus__c = 'PB - PRINCIPAL BROKER (REAL ESTATE COMMISSION)')
            )
            and EmploymentStatus__c = 'Employed'];
    }
    public static List<AssociatedLicense__c> getEntityAssociatedLicenses(Set<String> licenseIds) {
        return [Select Id, EntityLicense__c, EntityLicense__r.EffectiveExpireDate__c from AssociatedLicense__c where EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed'];
    }

    public static List<AssociatedLicense__c> getSoleOwnerLicenses (List<String> licenseIds) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c from AssociatedLicense__c where EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing'
            and (PositionStatus__c = 'D - Designated' or Position__c = 'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)') 
            and EmployeeLicense__r.ActiveInactive__c = 'Active' and 
            (EmployeeLicenseType__c = 'MRC' or EmployeeLicenseType__c = 'MR' or EmployeeLicenseType__c = 'MC') ];
    }

    public static List<AssociatedLicense__c> getUnSoleOwnerLicenses (List<String> licenseIds) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c from AssociatedLicense__c where EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing'
            and PositionStatus__c = 'D - Designated'  
            and EmployeeLicense__r.ActiveInactive__c = 'Active' and 
            (EmployeeLicenseType__c = 'MRC' or EmployeeLicenseType__c = 'MR' or EmployeeLicenseType__c = 'MC') ];
    }

    public static List<AssociatedLicense__c> getActiveAssociatedLicenses(List<String> licenseIds) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c 
            from AssociatedLicense__c where EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing'
            and (EmployeeLicenseType__c = 'MRC' or EmployeeLicenseType__c = 'MR' or EmployeeLicenseType__c = 'MC') ];
    }

    public static List<AssociatedLicense__c> getActiveAssociatedLicenses(List<String> licenseIds, Set<String> licenseTypes) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c 
            from AssociatedLicense__c where EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EmployeeLicenseType__c in: licenseTypes ];
    }


    public static List<AssociatedLicense__c> getAssociatedLicensesForEntityLicenseBSC(List<String> licenseIds) {
        return [Select Id, EntityLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c 
            from AssociatedLicense__c where EmployeeLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EntityLicenseStatus__c = 'R - Valid Thru Expiration Date, Subject To Renewal'
            and EmployeeLicense__r.ActiveInactive__c != 'Inactive'
            and EntityLicenseType__c = 'BSC'];
    }

    public static List<AssociatedLicense__c> getAssociatedLicensesForEmployeeLicenseIAndIds(Set<String> licenseIds, List<String> ids) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c, EntityLicense__r.LicenseType__r.Name, PositionStatus__c
            from AssociatedLicense__c where (EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing'
            and EmployeeLicense__r.ActiveInactive__c != 'Inactive'
            and EmployeeLicenseType__c = 'I') or Id in: ids];
    }

    public static List<AssociatedLicense__c> getAssociatedLicensesForEmployeeLicenseI(List<String> licenseIds) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c , PositionStatus__c
            from AssociatedLicense__c where EntityLicense__c in: licenseIds and EmploymentStatus__c = 'Employed' and 
            (EndDate__c = null or EndDate__c = Today) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing'
            and EmployeeLicense__r.ActiveInactive__c != 'Inactive'
            and EmployeeLicenseType__c = 'I'];
    }

    public static List<AssociatedLicense__c> getAssociatedBEO(Set<String> applicantIds) {
        return [Select Id, EmployeeLicense__r.LicenseType__r.Name, EntityLicense__c, EmployeeLicense__c 
            from AssociatedLicense__c where EntityLicense__r.Licensee__c in: applicantIds
            and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing'
            and EmployeeLicense__r.ActiveInactive__c != 'Inactive'
            and EmployeeLicenseType__c = 'BEO'];
    }

    public static List<AssociatedLicense__c> getAssociatedLicensesWWoSoleOwner(List<String> soleOwnerLicenseIds, List<String> unSoleOwnerLicenseIds, String employeeLicenseType) {
        return [Select Id, EntityLicense__c from AssociatedLicense__c where EmploymentStatus__c = 'Employed' and EmployeeLicense__r.ActiveInactive__c = 'Active' 
            and (EndDate__c > today or EndDate__c = null) and EmployeeLicense__r.Status__c = 'C - Current, Valid & In Good Standing' 
            and EmployeeLicense__r.LicenseType__r.Name =: employeeLicenseType
            and ((EntityLicense__c in: soleOwnerLicenseIds and (PositionStatus__c = 'D - Designated' or Position__c = 'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)')) 
            or (EntityLicense__c in: unSoleOwnerLicenseIds and PositionStatus__c = 'D - Designated'))];
    }
    public static List<AssociatedLicense__c> getAMDEntityAssociatedLicenses(List<String> licenseIds) {
        return [Select Id, EntityLicense__c, EmployeeLicense__c from AssociatedLicense__c where EmploymentStatus__c = 'Employed' 
            and (EndDate__c > today or EndDate__c = null) and EntityLicenseStatus__c = 'C - Current, Valid & In Good Standing' 
            and EmployeeLicense__c in: licenseIds 
            and EntityLicense__r.LicenseType__r.Name in ('MD', 'DOS')];
    }
    public static List<AssociatedLicense__c> getCPAEmployeeAssociatedLicenses(List<String> licenseIds) {
        return [Select Id, EntityLicense__c from AssociatedLicense__c where EmploymentStatus__c = 'Employed' 
            and (EndDate__c > today or EndDate__c = null) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing' 
            and EmployeeLicense__r.LicenseType__r.Name = 'CPA'
            and EmployeeLicense__r.Privilege__c = 'P - Permit to Practice'
            and EntityLicense__c in: licenseIds 
            and ((EntityLicense__r.LicenseType__r.Name = 'FPTP' and Position__c = 'CPA - CERTIFIED PUBLIC ACCOUNTANT' and PositionStatus__c = 'P - PRINCIPAL') or (
                EntityLicense__r.LicenseType__r.Name = 'FPTP - Sole Proprietor' and (Position__c = 'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)' or PositionStatus__c = 'P - PRINCIPAL')
            ))];
    }

    public static List<AssociatedLicense__c> getPHEmployeeAssociatedLicenses(List<String> licenseIds) {
        return [Select Id, EntityLicense__c from AssociatedLicense__c where EmploymentStatus__c = 'Employed' 
            and (EndDate__c > today or EndDate__c = null) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing' 
            and EmployeeLicense__r.LicenseType__r.Name = 'PH'
            and EntityLicense__c in: licenseIds 
            and (Position__c = 'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)' or  PositionStatus__c= 'D - Designated')];
    }

    public static List<AssociatedLicense__c> getPestControlByEmployee(List<String> licenseIds, List<String> relatedLicenseTypes) {
        return [Select Id, EntityLicense__c, EmployeeLicense__c, PositionStatus__c from AssociatedLicense__c where EmploymentStatus__c = 'Employed' 
            and (EndDate__c > today or EndDate__c = null) and EntityLicenseStatus__c = 'C - Current, Valid & In Good Standing' 
            and EntityLicense__r.LicenseType__r.Name in: relatedLicenseTypes
            and EmployeeLicense__c in: licenseIds and EntityActiveInactive__c = 'Active'];
    }

    public static List<AssociatedLicense__c> getPestControlByEntity(List<String> licenseIds, List<String> relatedLicenseTypes) {
        return [Select Id, EntityLicense__c, EmployeeLicense__c, PositionStatus__c from AssociatedLicense__c where EmploymentStatus__c = 'Employed' 
            and (EndDate__c > today or EndDate__c = null) and EmployeeLicenseStatus__c = 'C - Current, Valid & In Good Standing' 
            and EmployeeLicense__r.LicenseType__r.Name in: relatedLicenseTypes
            and EntityLicense__c in: licenseIds and EmployeeActiveInactive__c = 'Active'];
    }

    public static List<AssociatedLicense__c> getPDGByEntity(List<String> licenseIds, List<String> relatedLicenseTypes, String extraConditions) {
        String query = 'Select Id, EntityLicense__c, EntityLicenseType__c, EntityLicenseStatus__c, EmployeeLicense__c, EmployeeLicenseStatus__c, PositionStatus__c from AssociatedLicense__c where EmploymentStatus__c = \'Employed\' '
            + ' and (EndDate__c > today or EndDate__c = null) '
            + ' and EntityLicense__c in: licenseIds and EmployeeActiveInactive__c = \'Active\' ';
        if(relatedLicenseTypes != null ) {
            query += ' and EmployeeLicense__r.LicenseType__r.Name in: relatedLicenseTypes ';
        }
            
        query += extraConditions;
        return Database.query(query);
    }

    public static List<AssociatedLicense__c> getPDGByEmployee(List<String> licenseIds, List<String> relatedLicenseTypes, String extraConditions) {
        String query = 'Select Id, EntityLicense__c, EntityLicenseType__c, EntityLicenseStatus__c, EmployeeLicense__c, EmployeeLicenseStatus__c, PositionStatus__c from AssociatedLicense__c where EmploymentStatus__c = \'Employed\' '
           + ' and (EndDate__c > today or EndDate__c = null) '
           + ' and EmployeeLicense__c in: licenseIds and EntityActiveInactive__c = \'Active\' ';
        if(relatedLicenseTypes != null) {
            query += ' and EntityLicense__r.LicenseType__r.Name in: relatedLicenseTypes '; 
        }
        query += extraConditions;
        return Database.query(query);
    }

    public static List<AssociatedLicense__c> getAssociatedLicensesByEntity(List<String> licenseIds, List<String> relatedLicenseTypes, String extraConditions) {
        String query = 'Select Id, EntityLicense__c, EmployeeLicense__c, PositionStatus__c from AssociatedLicense__c where EmploymentStatus__c = \'Employed\' '
            + ' and (EndDate__c > today or EndDate__c = null) '
            + ' and EntityLicense__c in: licenseIds and EmployeeActiveInactive__c = \'Active\' ';
        if(relatedLicenseTypes != null ) {
            query += ' and EmployeeLicense__r.LicenseType__r.Name in: relatedLicenseTypes ';
        }
            
        query += extraConditions;
        return Database.query(query);
    }

    public static List<AssociatedLicense__c> getAssociatedLicensesByEmployee(List<String> licenseIds, List<String> relatedLicenseTypes, String extraConditions) {
        String query = 'Select Id, EntityLicense__c, EmployeeLicense__c, PositionStatus__c from AssociatedLicense__c where EmploymentStatus__c = \'Employed\' '
            + ' and (EndDate__c > today or EndDate__c = null) '
            + ' and EmployeeLicense__c in: licenseIds and EmployeeActiveInactive__c = \'Active\' ';
        if(relatedLicenseTypes != null ) {
            query += ' and EmployeeLicense__r.LicenseType__r.Name in: relatedLicenseTypes ';
        }
            
        query += extraConditions;
        return Database.query(query);
    }

    public static List<AssociatedLicense__c> getAssociatedLicensesForEmployerAddressUpdate(String extraConditions) {
        String query = 'Select Id, EmployeeLicense__c, EntityLicense__c, EffectiveDate__c from AssociatedLicense__c ';
        if(extraConditions != null) query += extraConditions;
        return Database.query(query);
     }
}