force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationRequirement__c/ApplicationRequirement__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application Requirement</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationRequirement__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Requirements</relationshipLabel>
    <relationshipName>Application_Deficiencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV081919 - Created for PVL phase 1</description>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>Application Requirements</relationshipLabel>
    <relationshipName>Application_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FixRequirementBatch.cls
public class FixRequirementBatch implements Database.Batchable<SObject>, Database.Stateful{
    private String query = 'Select Id from Application__c where Name in: appNames';
    public List<String> appNames = new List<String>();
    public FixRequirementBatch(List<String> appNames) {
        this.appNames = appNames;
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Application__c> records = (List<Application__c>) scope;
        List<String> appIds = (new ApplicationDomain(records)).getIds();
        List<ApplicationRequirement__c> requirements = [Select Id, Requirement__c, Application__c from ApplicationRequirement__c where Application__c in: appIds and CreatedBy.name like '%Guest%' ];
        ApplicationRequirementService.createChildrenApplicationRequirements(requirements);
        
    }

    public void finish(Database.BatchableContext bc) {}
   
}