force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint-KN091319 - Created for PVL Phase 1</description>
    <inlineHelpText>Shows if the application is Active or Inactive.</inlineHelpText>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/ApplicationReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ApplicationReceivedDate__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>When the application was created in Salesforce</inlineHelpText>
    <label>Application Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/DependentLicenseType__c.field-meta.xml
<CustomField>
    <fullName>DependentLicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <formula>DependentLicense__r.LicenseType__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dependent License Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/RenewingPermittoPractice__c.field-meta.xml
<CustomField>
    <fullName>RenewingPermittoPractice__c</fullName>
    <description>Used for Accounting Renewal Questions for License Type CPA/PA</description>
    <inlineHelpText>Will you be renewing your Permit to Practice with this license renewal?</inlineHelpText>
    <label>Renewing Permit to Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/RNEWRSTRDate__c.field-meta.xml
<CustomField>
    <fullName>RNEWRSTRDate__c</fullName>
    <formula>IF(
TEXT(Type__c)  = &apos;RNEW - Renewal&apos;,
 LicenseType__r.NextLicensePeriodExpireDate__c , 

IF(

OR(
TEXT(Type__c) = &apos;RSTR - Restore - No A/I Status&apos;,
TEXT(Type__c) = &apos;RSTRA - Restore Active&apos;

),

LicenseType__r.LicenseTypeExpireDate__c,  
null)


)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RNEW/RSTR Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADDC - Additional Class</fullName>
            </value>
            <value>
                <fullName>ADDP - Additional Special Privilege</fullName>
            </value>
            <value>
                <fullName>AMEND - Amendment</fullName>
            </value>
            <value>
                <fullName>APPR - Apprentice or Appraiser Trainee or Intern</fullName>
            </value>
            <value>
                <fullName>BAP - Apprentice Barber</fullName>
            </value>
            <value>
                <fullName>BEP - Beauty Apprentice</fullName>
            </value>
            <value>
                <fullName>CCNM - Change BP Name</fullName>
            </value>
            <value>
                <fullName>CONV - Conversion</fullName>
            </value>
            <value>
                <fullName>CVN - Converted License Type</fullName>
            </value>
            <value>
                <fullName>DELQ - Deliquent Failure to Renew</fullName>
            </value>
            <value>
                <fullName>DP - Applying for Designated Principal</fullName>
            </value>
            <value>
                <fullName>DUAL - Dual (Sole/RME or RME/RME or RME/Sole)</fullName>
            </value>
            <value>
                <fullName>EVA - Apprentice Elevator Mechanic</fullName>
            </value>
            <value>
                <fullName>EXPER - Experience Certificate</fullName>
            </value>
            <value>
                <fullName>GDS2O - GD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>LICC - New License after Cancelation/Close Business</fullName>
            </value>
            <value>
                <fullName>LICF - New License after Forfeiture</fullName>
            </value>
            <value>
                <fullName>LICN - New License</fullName>
            </value>
            <value>
                <fullName>MAP - Apprentice Massage Therapist</fullName>
            </value>
            <value>
                <fullName>PD2SO - PD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>PDREL - Preliminary Decision: Real Estate Salesperson or Broker</fullName>
            </value>
            <value>
                <fullName>PHA - Assistant Pharmacist</fullName>
            </value>
            <value>
                <fullName>R2DBA - RME to Sole Owner</fullName>
            </value>
            <value>
                <fullName>RB2SO - RB to Sole Owner</fullName>
            </value>
            <value>
                <fullName>REAC - Reactivation</fullName>
            </value>
            <value>
                <fullName>RECOG - Temporary Recognition for Real Estate Appraisers</fullName>
            </value>
            <value>
                <fullName>RELOC - Business Site Relocation</fullName>
            </value>
            <value>
                <fullName>RNEW - Renewal</fullName>
            </value>
            <value>
                <fullName>RSTR - Restore - No A/I Status</fullName>
            </value>
            <value>
                <fullName>RSTRA - Restore Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-KN081619 - Created for PVL Phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RME</fullName>
            </value>
            <value>
                <fullName>Broker In Charge</fullName>
            </value>
            <value>
                <fullName>Mechanic In Charge</fullName>
            </value>
            <value>
                <fullName>Barber Operator-In-Charge</fullName>
            </value>
            <value>
                <fullName>Beauty Operator-In-Charge</fullName>
            </value>
            <value>
                <fullName>Principal RME</fullName>
            </value>
            <value>
                <fullName>Pharmacist-in-Charge</fullName>
            </value>
            <value>
                <fullName>Principal Massage Therapist</fullName>
            </value>
            <value>
                <fullName>Principal Agent</fullName>
            </value>
            <value>
                <fullName>Principal Detective</fullName>
            </value>
            <value>
                <fullName>Principal Guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint KN080819 - Created for PVL</description>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/RenewingPermittoPractice__c.field-meta.xml
<CustomField>
    <fullName>RenewingPermittoPractice__c</fullName>
    <label>Renewing Permit to Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>Active / Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/DependentLicenseType__c.field-meta.xml
<CustomField>
    <fullName>DependentLicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-KN112619-Created for PVL Sprint 2 Phase 1</description>
    <inlineHelpText>Which License Type is this License Type Dependent on?</inlineHelpText>
    <label>Dependent License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>License Types</relationshipLabel>
    <relationshipName>License_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/X2ndDependencyRequired__c.field-meta.xml
<CustomField>
    <fullName>X2ndDependencyRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint - KN01152019-Created for PVL Phase 1 Sprint  3</description>
    <label>2nd Dependency Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/X2ndDependentLicenseType__c.field-meta.xml
<CustomField>
    <fullName>X2ndDependentLicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-KN01152019-Created for Phase 1 Sprint 3</description>
    <label>2nd Dependent License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>License Types (2nd Dependent License Type)</relationshipLabel>
    <relationshipName>License_Types2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PVL_RenewalDependencyFlowHelper.cls
public with sharing class PVL_RenewalDependencyFlowHelper {
    @InvocableMethod(
        label='Get Related Multidependency Application' 
        description='Returns a list of applications declared as 2nd Dependency Required for this application' 
        category='License'
    )
    public static List<Result> getRelatedMultidependentApplications(List<License__c> licenses){
        Map<Id, Result> applicationsToReturn = new Map<Id, Result>();
        Set<Application__c> uniqueApplicationsToReturn = new Set<Application__c>();
        Set<Id> licenseTypeIds = new Set<Id>();
        for(License__c thisLicense : licenses){
            applicationsToReturn.put(thisLicense.Id, new Result(thisLicense));
            licenseTypeIds.add(thisLicense.LicenseType__c);
        }
        Map<Id, LicenseType__c> licenseTypes = new Map<Id, LicenseType__c>([SELECT Id, DependentLicenseType__c, X2ndDependentLicenseType__c FROM LicenseType__c WHERE X2ndDependencyRequired__c = true AND (DependentLicenseType__c IN :licenseTypeIds OR X2ndDependentLicenseType__c IN :licenseTypeIds)]);
        if(licenseTypes.isEmpty()){
            return applicationsToReturn.values();
        }
        for(License__c dependentLicenses : [SELECT (SELECT Id, CurrentLicense__c, RNEWRSTRDate__c, ActiveInactive__c, RenewingPermittoPractice__c, Type__c, ApplicationReceivedDate__c, Status__c, LicenseType__c, Phase__c FROM Applications1__r WHERE Status__c = 'D1 - Awaiting Dependency Review'), (SELECT EmployeeLicense__c FROM AssociatedEmployee__r WHERE EmployeeLicense__c IN :applicationsToReturn.keySet()) FROM License__c WHERE LicenseType__c IN :licenseTypes.keySet() AND Id IN (SELECT EntityLicense__c FROM AssociatedLicense__c WHERE EmployeeLicense__c IN :applicationsToReturn.keySet())]){
            for(AssociatedLicense__c associatedLicense : dependentLicenses.AssociatedEmployee__r){
                applicationsToReturn.get(associatedLicense.EmployeeLicense__c)?.dependentApplications.addAll(dependentLicenses.Applications1__r);
            }
        }
        return applicationsToReturn.values();
    }

    public class Result{
        @InvocableVariable (label='License' description='The license that associated to this result')
        public License__c ivokingLicense;

        @InvocableVariable (label='Dependent Applications' description='The dependent applications related to this license')
        public List<Application__c> dependentApplications;

        public Result(){
            
        }
        public Result(License__c license){
            this.ivokingLicense = license;
            this.dependentApplications = new List<Application__c>();
        }
    }
}