force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicense__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Entities</relationshipLabel>
    <relationshipName>AssociatedEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>EmploymentStatus__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending Employment</fullName>
                <isActive>false</isActive>
                <label>Pending Employment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicenseType__c.field-meta.xml
<CustomField>
    <fullName>EntityLicenseType__c</fullName>
    <description>Pac Point-DN010820 - Created for PVL Sprint 3 Phase 1</description>
    <formula>EntityLicense__r.LicenseType__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity License Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/ThisLicenseRenewed__c.field-meta.xml
<CustomField>
    <fullName>ThisLicenseRenewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>This License Renewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseTypeName__c.field-meta.xml
<CustomField>
    <fullName>LicenseTypeName__c</fullName>
    <description>PacPoint-IC021920- Created for PVL phase 1</description>
    <formula>LicenseType__r.Name</formula>
    <label>License Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/ThisLicenseRenewed__c.field-meta.xml
<CustomField>
    <fullName>ThisLicenseRenewed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, prevents license from being renewed through MyPVL.</inlineHelpText>
    <label>This License Renewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RbEntityRbBrokerRnewalDependency.cls
/*
 * -----------------------------------------------------------------------------------
 * Description
 * https://lucid.app/lucidchart/aaa20ac0-4780-4bce-9904-0a8391f2a01d/edit?invitationId=inv_13fa9641-cba6-4bf9-b4fc-51b6f257e626&page=-EZZCIEv3uyM#
 * -----------------------------------------------------------------------------------
 * Covered by: RbEntityRbBrokerRnewalDependencyTest
 * -----------------------------------------------------------------------------------
 * PacPoint-CL10202022 - Created for case 00025296
 * -----------------------------------------------------------------------------------
 * Initial implementation
 *
 * @author chris.loyola@pacificpointcorp.com
 *
 * @created 10/20/2022
 * -----------------------------------------------------------------------------------
 * Changes
 * -----------------------------------------------------------------------------------
 */
public without sharing class RbEntityRbBrokerRnewalDependency {

    @InvocableMethod
    public static void runRenewalDependency(List<Input>inputs) {
        License__c inputLicense = inputs[0].inputLicense;
        Application__c inputApplication = inputs[0].inputApplication;

        if (inputLicense.LicenseTypeName__c == 'RB - Broker') {
            doRbBroker(inputLicense, inputApplication);
        }

        if (inputLicense.LicenseTypeName__c == 'RB - Entity') {
            doRbEntity(inputLicense, inputApplication);
        }
    }

    private static void doRbEntity(License__c inputLicense, Application__c inputApplication) {
        //find associated RBOs
        List<AssociatedLicense__c> rbEntityRboAssoc = [
            SELECT
                Id,
                EntityLicense__c,
                EntityLicense__r.Status__c,
                EntityLicense__r.ThisLicenseRenewed__c
            FROM AssociatedLicense__c
            WHERE EmployeeLicense__c = :inputLicense.Id
            AND EmploymentStatus__c = 'Employed'
            AND (EndDate__c = null OR EndDate__c > TODAY)
            AND EntityLicenseType__c = 'RBO'
        ];

        if (rbEntityRboAssoc.isEmpty()) {
            return;
        }

        Set<Id> rboLicenseIds = new Set<Id>();
        for (AssociatedLicense__c al : rbEntityRboAssoc) {
            rboLicenseIds.add(al.EntityLicense__c);
        }

        //find applications
        List<Application__c> rboApplications = [
            SELECT
                Id,
                CurrentLicense__c,
                CurrentLicense__r.LicenseTypeNextExpire__c,
                LicenseType__r.NextLicensePeriod__c,
                LicensePeriodRNEW__c
            FROM Application__c
            WHERE CurrentLicense__c IN :rboLicenseIds
            AND Status__c = 'D1 - Awaiting Dependency Review'
            AND (Type__c = 'RNEW - Renewal' OR Type__c = 'RSTR - Restore - No A/I Status')
        ];

        if (rboApplications.isEmpty()) {
            return;
        }

        List<Application__c> d1RboApplications = new List<Application__c>();
        for (Application__c a : rboApplications) {
            if (a.LicensePeriodRNEW__c == a.LicenseType__r.NextLicensePeriod__c) {
                d1RboApplications.add(a);
            }
        }

        if (d1RboApplications.isEmpty()) {
            return;
        }

        //find BIC RB Broker licenses
        List<AssociatedLicense__c> rbEntityRbBrokerAssoc = [
            SELECT
                Id,
                EmployeeLicense__c,
                EmployeeLicense__r.Status__c,
                EmployeeLicense__r.ThisLicenseRenewed__c
            FROM AssociatedLicense__c
            WHERE EntityLicense__c = :inputLicense.Id
            AND EmploymentStatus__c = 'Employed'
            AND (EndDate__c = null OR EndDate__c > TODAY)
            AND Position__c ='BIC - BROKER-IN-CHARGE (REAL ESTATE COMMISSION)'
        ];

        Set<Id> rbBrokerLicenseIds = new Set<Id>();
        Boolean foundRenewedRbBroker = false;

        for (AssociatedLicense__c al : rbEntityRbBrokerAssoc) {
            if (al.EmployeeLicense__r.ThisLicenseRenewed__c && al.EmployeeLicense__r.Status__c == 'C - Current, Valid & In Good Standing') {
                foundRenewedRbBroker = true;
                break;
            }

            rbBrokerLicenseIds.add(al.EmployeeLicense__c);
        }

        if (!foundRenewedRbBroker) {
            return;
        }

        List<License__c> rboLicensesToUpdate = new List<License__c>();
        for (Application__c a : d1RboApplications) {
            a.Status__c = 'HC - Application Completed';
            a.Phase__c = 'H - License Generation';

            License__c l = new License__c();
            l.Id = a.CurrentLicense__c;
            l.Status__c = 'C - Current, Valid & In Good Standing';
            l.EffectiveExpireDate__c = a.CurrentLicense__r.LicenseTypeNextExpire__c;
            rboLicensesToUpdate.add(l);
        }

        update rboLicensesToUpdate;
        update d1RboApplications;
    }

    private static void doRbBroker(License__c inputLicense, Application__c inputApplication) {
        //find associated entities
        List<AssociatedLicense__c> rbBrokerAssociatedEntities = [
            SELECT
                Id,
                EntityLicense__c,
                EntityLicense__r.Status__c,
                EntityLicense__r.ThisLicenseRenewed__c
            FROM AssociatedLicense__c
            WHERE EmployeeLicense__c = :inputLicense.Id
            AND EmploymentStatus__c = 'Employed'
            AND (EndDate__c = null OR EndDate__c > TODAY)
            AND EntityLicenseType__c = 'RB - Entity'
            AND Position__c = 'BIC - BROKER-IN-CHARGE (REAL ESTATE COMMISSION)'
            AND EntityLicense__r.Status__c = 'C - Current, Valid & In Good Standing'
            AND EntityLicense__r.ThisLicenseRenewed__c = true
        ];

        if (rbBrokerAssociatedEntities.isEmpty()) {
            return;
        }

        Set<Id> entityLicenseIds = new Set<Id>();

        for (AssociatedLicense__c al : rbBrokerAssociatedEntities) {
            entityLicenseIds.add(al.EntityLicense__c);
        }

        //find associated RBOs
        List<AssociatedLicense__c> rbEntityRboAssoc = [
            SELECT
                Id,
                EntityLicense__c,
                EntityLicense__r.Status__c,
                EntityLicense__r.ThisLicenseRenewed__c
            FROM AssociatedLicense__c
            WHERE EmployeeLicense__c IN :entityLicenseIds
            AND EmploymentStatus__c = 'Employed'
            AND (EndDate__c = null OR EndDate__c > TODAY)
            AND EntityLicenseType__c = 'RBO'
        ];

        if (rbEntityRboAssoc.isEmpty()) {
            return;
        }

        Set<Id> rboLicenseIds = new Set<Id>();

        for (AssociatedLicense__c al : rbEntityRboAssoc) {
            rboLicenseIds.add(al.EntityLicense__c);
        }

        List<Application__c> rboApplications = [
            SELECT
                Id,
                CurrentLicense__c,
                CurrentLicense__r.LicenseTypeNextExpire__c,
                LicenseType__r.NextLicensePeriod__c,
                LicensePeriodRNEW__c
            FROM Application__c
            WHERE CurrentLicense__c IN :rboLicenseIds
            AND Status__c = 'D1 - Awaiting Dependency Review'
            AND (Type__c = 'RNEW - Renewal' OR Type__c = 'RSTR - Restore - No A/I Status')
        ];

        List<Application__c> rboApplicationsForUpdate = new List<Application__c>();
        List<License__c> rboLicensesForUpdate = new List<License__c>();

        for (Application__c a : rboApplications) {
            if (a.LicensePeriodRNEW__c == a.LicenseType__r.NextLicensePeriod__c) {
                a.Phase__c = 'H - License Generation';
                a.Status__c = 'HC - Application Completed';
                rboApplicationsForUpdate.add(a);

                License__c l = new License__c();
                l.Id = a.CurrentLicense__c;
                l.Status__c = 'C - Current, Valid & In Good Standing';
                l.EffectiveExpireDate__c = a.CurrentLicense__r.LicenseTypeNextExpire__c;
                rboLicensesForUpdate.add(l);
            }
        }

        if (rboApplicationsForUpdate.isEmpty()) {
            return;
        }

        update rboLicensesForUpdate;
        update rboApplicationsForUpdate;
    }

    public class Input {
        @InvocableVariable(required = true)
        public License__c inputLicense;

        @InvocableVariable(required = true)
        public Application__c inputApplication;
    }
}