force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LicensePeriod__c.field-meta.xml
<CustomField>
    <fullName>LicensePeriod__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <inlineHelpText>This can be changed to choose if the license will be issued in this license period or the next.</inlineHelpText>
    <label>License Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>This License Period</fullName>
                <default>true</default>
                <label>This License Period</label>
            </value>
            <value>
                <fullName>Next License Period</fullName>
            </value>
            <value>
                <fullName>This License Period + Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A - Application Received</fullName>
                <default>true</default>
                <label>A - Application Received</label>
            </value>
            <value>
                <fullName>E - Executive Officer Review</fullName>
            </value>
            <value>
                <fullName>B - Board Review</fullName>
            </value>
            <value>
                <fullName>C - Consultant Review</fullName>
            </value>
            <value>
                <fullName>X - Exam Phase</fullName>
            </value>
            <value>
                <fullName>O - 2nd Board Review - Oral Interview</fullName>
            </value>
            <value>
                <fullName>D - Dependency Review</fullName>
            </value>
            <value>
                <fullName>L - License Review</fullName>
            </value>
            <value>
                <fullName>H - License Generation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicensePeriod__c/LicensePeriod__c.object-meta.xml
<CustomObject>
    <label>License Period</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>License Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LicensePeriod__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Previous License Period</fullName>
            </value>
            <value>
                <fullName>Current License Period</fullName>
            </value>
            <value>
                <fullName>Next License Period</fullName>
            </value>
            <value>
                <fullName>Future License Period</fullName>
            </value>
            <value>
                <fullName>Historical License Periods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <description>PacPoint-CL092818 - Created for phase 1</description>
    <formula>IF( TEXT(TransactionGroup__r.Status__c)  = &apos;Completed&apos;, 0, (TotalAmount__c - TotalRefundAmount__c)-  PaymentAmount__c +  OverPaymentAmount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The net outstanding balance owned on this Transaction.  This is the Total Amount of the Transaction minus the Payment Amount (the amount that has already been paid) less any Refunds.</inlineHelpText>
    <label>Amount Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionDomain.cls
/*
* ─────────────────────────────────────────────────────────
* Used for the single unit of  logic around
* Transaction records
* ─────────────────────────────────────────────────────────
* PacPoint-AZ210819 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Alvin Zhou - PacificPointCorp
* @created      2019-08-21
* ───────────────────────────────────────────────────────────
* Changes
*
*
* ───────────────────────────────────────────────────────────
*/
public without sharing class TransactionDomain extends SObjectDomain{
    public TransactionDomain(List<Transaction__c> transactions) {
        super(transactions);
    }
    
    public Map<String, Transaction__c> getApp2Transaction() {
        Map<String, Transaction__c> app2Transaction = new Map<String, Transaction__c>();
        for (Transaction__c record : (List<Transaction__c> ) this.records) {
			if (record.Application__c != null) {
				app2Transaction.put(record.Application__c, record);
			}
		}
        return app2Transaction;
    }

    //case 00032255
    public List<Transaction__c> getTransactionsForDelete() {
        List<Transaction__c> transactionsForDelete = new List<Transaction__c>();
        for (Transaction__c record : (List<Transaction__c>) this.records) {
            if (record.Description__c.startsWith('Renewal Fees') && record.Application__r.LicensePeriod__c == 'This License Period') {
                transactionsForDelete.add(record);
            }
        }
        return transactionsForDelete;
    }

    // 00008048
    public List<Transaction__c> getTransactionForLicenseFees() {
        List<Transaction__c> filteredTransactions = new List<Transaction__c>();
        Map<String, Transaction__c> app2Transaction = new Map<String, Transaction__c>();
        for(Transaction__c record : (List<Transaction__c>) records) {
            // Commented based on the cae 8249
            if (record.Description__c != null
                && (record.Description__c.startsWith('License Fees') || record.Description__c.startsWith('License + Renewal Fees'))
                && record.Application__r != null && record.Application__r.Phase__c == 'L - License Review') {
                // filteredTransactions.add(record);
                app2Transaction.put(record.Application__c, record);
            }
            if(record.Description__c != null
                && (record.Description__c.startsWith('Application Fees') || record.Description__c.startsWith('Application + Renewal Fees'))
                && record.Application__r != null && record.Application__r.Phase__c == 'A - Application Received') {
                // filteredTransactions.add(record);
                app2Transaction.put(record.Application__c, record);
            }
        }
        filteredTransactions = app2Transaction.values();
        return filteredTransactions;
    }
    public void updateStatus(String status) {
        for(Transaction__c record: (List<Transaction__c> )records) {
            record.Status__c = status;
        }
        
    }
    // Used to get the Amount Outstanding sum per applications.
    public Map<String, Decimal> getSumAmtPerApp() {
        Map<String, Decimal> sumAmtPerApp = new Map<String, Decimal>();
        for(SObject record: records) {
            Transaction__c tran = (Transaction__c) record;
            String appId = tran.Application__c;
            Decimal amt = 0;
            if(appId != null && sumAmtPerApp.containsKey(appId)) {
                amt = sumAmtPerApp.get(appId);
            }
            if(tran.AmountOutstanding__c != null) {
                amt += tran.AmountOutstanding__c;
            }
            sumAmtPerApp.put(appId, amt);
        }
        return sumAmtPerApp;
    }
    
}