force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/GenerateCheckoutForm__c.field-meta.xml
<CustomField>
    <fullName>GenerateCheckoutForm__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-MV112719 - Created for PVL phase 1</description>
    <label>Generate Checkout Form</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/OnlineApplicationType__c.field-meta.xml
<CustomField>
    <fullName>OnlineApplicationType__c</fullName>
    <label>Online Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online Renewal/Restore</fullName>
            </value>
            <value>
                <fullName>Online New Application (LICN)</fullName>
            </value>
            <value>
                <fullName>Online New Application (LICF)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/OnlineRenewalClasses__c.field-meta.xml
<CustomField>
    <fullName>OnlineRenewalClasses__c</fullName>
    <label>Online Renewal Classes</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/OnlineRenewalEmployment__c.field-meta.xml
<CustomField>
    <fullName>OnlineRenewalEmployment__c</fullName>
    <label>Online Renewal Employment</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/OnlineRenewalInsurance__c.field-meta.xml
<CustomField>
    <fullName>OnlineRenewalInsurance__c</fullName>
    <label>Online Renewal Insurance</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/PopulateOnlineRenewalFields__c.field-meta.xml
<CustomField>
    <fullName>PopulateOnlineRenewalFields__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Populate Online Renewal Fields</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationHandler.cls
/*
* ─────────────────────────────────────────────────────────
* class for the Application Handller used to handle 
* Application trigger
* ─────────────────────────────────────────────────────────
* PacPoint-AZ130619 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Alvin Zhou - PacificPointCorp 
* @created      2019-06-13
* ───────────────────────────────────────────────────────────
* Changes
*
* 05-20-2020 PacPoint:RdG - Case# 8363 - Validation Check: License to have Insurances w/ valid term dates before an Application can be updated to HC
* 10-06-2023 PacPoint:EA - Case# 30984 - Create a New Visualforce Email Templates for ADDP Approved Letter Email and New Apex Trigger to Send the Email
*
* ───────────────────────────────────────────────────────────
*/
public with sharing class ApplicationHandler implements ITrigger{
    public static Boolean bypassInsuranceValidation = false;
    public ApplicationHandler() {}

    public void bulkBefore() {
        if(Trigger.isUpdate) {
            List<Application__c> appForRenewalSnapshot = new List<Application__c>();
            List<Application__c> newApps = (List<Application__c>) Trigger.new;
            Map<Id, Application__c> oldAppMap = (Map<Id, Application__c>) Trigger.oldMap;
            Set<String> statusFilter = new Set<String>{
                    'D1 - Awaiting Dependency Review',
                    'D2 - Continuing Education Missing',
                    'HC - Application Completed'
                    };

            for (Application__c app : newApps) {
                if ((statusFilter.contains(app.Status__c) &&
                                app.OnlineApplicationType__c == 'Online Renewal/Restore' &&
                                app.OnlineRenewalClasses__c == null &&
                                app.OnlineRenewalInsurance__c == null &&
                                app.OnlineRenewalEmployment__c == null &&
                                oldAppMap.get(app.Id).Status__c != app.Status__c) ||
                        (app.PopulateOnlineRenewalFields__c)) {
                    app.PopulateOnlineRenewalFields__c = false;
                    appForRenewalSnapshot.add(app);
                }
            }

            if (!appForRenewalSnapshot.isEmpty()) {
                ApplicationService.takeRenewalSnapshot(appForRenewalSnapshot);
            }
            ApplicationService.captureLicenseRecord(newApps);

        }
    }

    public void beforeUpdate(List<SObject> newlstObj,List<SObject> oldlstObj,Map<Id,SObject> newMapObj, Map<Id,SObject> oldMapObj) {}
    public void beforeInsert(List<SObject> newlstObj) {}
    public void bulkAfter() {
        if(Trigger.isUpdate) {
            List<String> applicationIdsForCheckOutFormGeneration = new List<String>();
            for (Application__c app : (List<Application__c>) Trigger.new) {
                if (app.GenerateCheckoutForm__c) {
                    applicationIdsForCheckOutFormGeneration.add(app.Id);
                }
            }

            if (!applicationIdsForCheckOutFormGeneration.isEmpty()) {
                //case 00020872
                ApplicationService.generateCheckoutForm(applicationIdsForCheckOutFormGeneration);
            }
        }
    }
    public void beforeInsert(SObject so) {
        //00005043 capture applicaiton if phase is L - License Review
        ApplicationService.captureLLicenseReview(so);
        ApplicationService.ensureRenewByPermitToPracticeValue(so);
    }

    public void afterInsert(SObject so) {
        // 00003563: Application Type "LICN" or "RNEW", Create Application requirements based on LicenseTypeRequirements
        ApplicationService.captureLicenseTypeCheck(so);
        // 00003450: Trigger on Application to mark Application Classification Records that are not on Dependent License or Dependent Applicaiton
        ApplicationService.updateApplicationClassification(so);
        // 00005439: On Application Type: "REAC - Reactivation", Created Related Application Requirements based on CurrentLicense__c
        ApplicationService.populateLicenseRequirements(so);
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        //PacPoint:RdG - Case# 8363 - Validation Check: License to have Insurances w/ valid term dates before an Application can be updated to HC
        if(!bypassInsuranceValidation) ApplicationService.validationLicenseRenew(oldSo, so);  
        //00005043 capture applicaiton if phase is L - License Review
        ApplicationService.captureLLicenseReview(oldSo, so);
        // Case id 00005902 Dymatic Create PDF 
        ApplicationService.PDFGeneration(oldSo, so);
        // 00014255
        ApplicationService.generateOnlineRenewalCopy(oldSo, so);
        ApplicationService.ensureRenewByPermitToPracticeValue(so);
        

        // 00029513
        ApplicationService.captureSendApprovedForExamLetterEmail(oldSo, so);

        // 00030984
        ApplicationService.captureSendADDPApprovedLetterEmail(oldSo, so);
    }

    public void beforeUnDelete(SObject so) {} 
    public void afterUpdate(SObject oldSo, SObject so) {
        // 00003563: Application Type "LICN" or "RNEW", Create Application Requirements based on LicenseTypeRequirements
        ApplicationService.captureLicenseTypeCheck(oldSo, so);
        // 00003450: Trigger on Application to mark Application Classification Records that are not on Dependent License or Dependent Applicaiton
        ApplicationService.updateApplicationClassification(oldSo, so);
        // 00008048
        ApplicationService.captureLicensePeriodChange(oldSo, so);
        
    }

    public void beforeDelete(SObject so){} 
    public void afterDelete(SObject so) {} 
    public void afterUnDelete(SObject so) {} 
    public void andFinally() {
        ApplicationService.runFinally(Trigger.new);
    }
}