force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/OnlineApplicationType__c.field-meta.xml
<CustomField>
    <fullName>OnlineApplicationType__c</fullName>
    <label>Online Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online Renewal/Restore</fullName>
            </value>
            <value>
                <fullName>Online New Application (LICN)</fullName>
            </value>
            <value>
                <fullName>Online New Application (LICF)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADDC - Additional Class</fullName>
            </value>
            <value>
                <fullName>ADDP - Additional Special Privilege</fullName>
            </value>
            <value>
                <fullName>AMEND - Amendment</fullName>
            </value>
            <value>
                <fullName>APPR - Apprentice or Appraiser Trainee or Intern</fullName>
            </value>
            <value>
                <fullName>BAP - Apprentice Barber</fullName>
            </value>
            <value>
                <fullName>BEP - Beauty Apprentice</fullName>
            </value>
            <value>
                <fullName>CCNM - Change BP Name</fullName>
            </value>
            <value>
                <fullName>CONV - Conversion</fullName>
            </value>
            <value>
                <fullName>CVN - Converted License Type</fullName>
            </value>
            <value>
                <fullName>DELQ - Deliquent Failure to Renew</fullName>
            </value>
            <value>
                <fullName>DP - Applying for Designated Principal</fullName>
            </value>
            <value>
                <fullName>DUAL - Dual (Sole/RME or RME/RME or RME/Sole)</fullName>
            </value>
            <value>
                <fullName>EVA - Apprentice Elevator Mechanic</fullName>
            </value>
            <value>
                <fullName>EXPER - Experience Certificate</fullName>
            </value>
            <value>
                <fullName>GDS2O - GD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>LICC - New License after Cancelation/Close Business</fullName>
            </value>
            <value>
                <fullName>LICF - New License after Forfeiture</fullName>
            </value>
            <value>
                <fullName>LICN - New License</fullName>
            </value>
            <value>
                <fullName>MAP - Apprentice Massage Therapist</fullName>
            </value>
            <value>
                <fullName>PD2SO - PD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>PDREL - Preliminary Decision: Real Estate Salesperson or Broker</fullName>
            </value>
            <value>
                <fullName>PHA - Assistant Pharmacist</fullName>
            </value>
            <value>
                <fullName>R2DBA - RME to Sole Owner</fullName>
            </value>
            <value>
                <fullName>RB2SO - RB to Sole Owner</fullName>
            </value>
            <value>
                <fullName>REAC - Reactivation</fullName>
            </value>
            <value>
                <fullName>RECOG - Temporary Recognition for Real Estate Appraisers</fullName>
            </value>
            <value>
                <fullName>RELOC - Business Site Relocation</fullName>
            </value>
            <value>
                <fullName>RNEW - Renewal</fullName>
            </value>
            <value>
                <fullName>RSTR - Restore - No A/I Status</fullName>
            </value>
            <value>
                <fullName>RSTRA - Restore Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanRenewApplicationJobTest.cls
@isTest
private class CleanRenewApplicationJobTest {
    @TestSetup
    static void makeData(){
        Application__c app = TestDataFactory.createDummyApplication();
        app.Type__c = 'RNEW - Renewal';
        app.Status__c = 'AP - Application Pending Submittal by Applicant/Licensee';
        app.OnlineApplicationType__c = 'Online Renewal/Restore';
        insert app;
        TestDataFactory.createDummyChargebackPayment();
        List<Transaction__c> trans = [Select Id, Application__c from Transaction__c];
        for(Transaction__c tran: trans) {
            tran.Application__c = app.Id;
        }
        
        update trans;
    }
    @isTest
    private static void testBatch() {
        Test.startTest();
        Datetime dt = System.now();
        dt.addHours(1);
        Database.executeBatch(new CleanRenewApplicationJob(dt), 100);
        Test.stopTest();
        //System.assert([Select id from Transaction__c].size() == 0);
        //System.assert([Select id from Application__c].size() > 0);
    }
}