force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The account that this application belongs too</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A - Application Received</fullName>
                <default>true</default>
                <label>A - Application Received</label>
            </value>
            <value>
                <fullName>E - Executive Officer Review</fullName>
            </value>
            <value>
                <fullName>B - Board Review</fullName>
            </value>
            <value>
                <fullName>C - Consultant Review</fullName>
            </value>
            <value>
                <fullName>X - Exam Phase</fullName>
            </value>
            <value>
                <fullName>O - 2nd Board Review - Oral Interview</fullName>
            </value>
            <value>
                <fullName>D - Dependency Review</fullName>
            </value>
            <value>
                <fullName>L - License Review</fullName>
            </value>
            <value>
                <fullName>H - License Generation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/PositionStatus__c.field-meta.xml
<CustomField>
    <fullName>PositionStatus__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D - DESIGNATED</fullName>
            </value>
            <value>
                <fullName>P - PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>T - TEMPORARY (REAL ESTATE)</fullName>
            </value>
            <value>
                <fullName>X - EXTEND TEMPORARY (REAL ESTATE)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Licensee__c.field-meta.xml
<CustomField>
    <fullName>Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The account that this license belongs too.</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BarberingCosRenewalPushThru.cls
global class BarberingCosRenewalPushThru extends ApplicationRenewalPushThru {
    global BarberingCosRenewalPushThru() {
        super(new List<String> {'BAS', 'BSH', 'BSC', 'I'}, new List<String> {'R - Valid Thru Expiration Date, Subject To Renewal'});
    }

    global override void processRecords(List<Application__c> records) {
        // Check next step: 
        // BSC
        List<Application__c> bscApps = (new ApplicationDomain(records)).filterAppByLicenseTypes(new Set<String>{'BSC'});
        if(!bscApps.isEmpty()) captureRenewApp(bscRenewCheck(bscApps));
        // I
        List<Application__c> iApps = (new ApplicationDomain(records)).filterAppByLicenseTypes(new Set<String>{'I'});
        if(!iApps.isEmpty()) captureRenewApp(iRenewCheck(iApps));
        
        // BAS
        List<Application__c> basApps = (new ApplicationDomain(records)).filterAppByLicenseTypes(new Set<String>{'BAS'});
        if(!basApps.isEmpty()) captureRenewApp(BarberingCosmetologyRenewal.basBshRenewCheck(basApps, 'BAR'));
        // BSH
        List<Application__c> bshApps = (new ApplicationDomain(records)).filterAppByLicenseTypes(new Set<String>{'BSH'});
        if(!bshApps.isEmpty()) captureRenewApp(BarberingCosmetologyRenewal.basBshRenewCheck(bshApps, 'BEO'));

        //  get all that I applications that are going for renew.
        List<Application__c> iApplications = (new ApplicationDomain(appMap.values())).filterAppByLicenseTypes(new Set<String> {'I'});
        if(!iApplications.isEmpty()) captureRenewApp(extraBSCAppRenew(iApplications));
    }

    private void captureRenewApp(List<Application__c> records) {
        for(Application__c app: records) {
            appMap.put(app.Id, app);
        }
    }
    public List<Application__c>  iRenewCheck(List<Application__c> records) {
        List<String> applicantIds = (List<String>) (new ApplicationDomain(records)).getFieldValues('Applicant__c');
        
        List<License__c> beoLicenseRecords = LicenseSelector.getLicenseByLicenseTypeStatusAndLicensee('BEO', applicantIds, 'C - Current, Valid & In Good Standing');
        List<String> beoLicenseeIds = (List<String>) new LicenseDomain(beoLicenseRecords).getFieldValues('Licensee__c');
        Set<String> beoIdSet = new Set<String>();
        beoIdSet.addAll(beoLicenseeIds);

        List<Application__c> appsForUpdate =  new List<Application__c>();
        for(Application__c app: records) {
            if(beoIdSet.contains(app.Applicant__c)) {
                app.Status__c = 'HC - Application Completed';
                app.Phase__c = 'H - License Generation';
                appsForUpdate.add(app);
            }
        }
        return appsForUpdate;
    }

    public static List<Application__c> bscRenewCheck(List<Application__c> records) {
        List<String> bcsLicenseIds = (List<String>) (new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> bscAssociatedLicenses = AssociatedLicenseSelector.getAssociatedLicensesForEmployeeLicenseI(bcsLicenseIds);
        Map<String, List<AssociatedLicense__c>> bscAssociatedLicensesMap = (new AssociatedLicenseDomain(bscAssociatedLicenses)).getEntityId2Records();
        //  Check for the if size is more than 2
        // Query Associated License;
        List<Application__c> bscApplicationsFurtherCheck = (new ApplicationDomain(records)).filterApplicationOnAssociatedLicenseSize(bscAssociatedLicensesMap);
        List<AssociatedLicense__c> bscFilteredAssociatedLicenses = (new ApplicationDomain(bscApplicationsFurtherCheck)).getAllAssociatedLicenses(bscAssociatedLicensesMap);
        Set<String> bscLicenseIds = new Set<String>();
        for(AssociatedLicense__c associatedLicense: bscAssociatedLicenses) {
            if(associatedLicense.PositionStatus__c == 'D - Designated') {
                bscLicenseIds.add(associatedLicense.EntityLicense__c);
            }
        }

        List<Application__c> appsForUpdate =  new List<Application__c>();
        for(Application__c app: bscApplicationsFurtherCheck) {
            if(bscLicenseIds.contains(app.CurrentLicense__c)) {
                app.Status__c = 'HC - Application Completed';
                app.Phase__c = 'H - License Generation';
                appsForUpdate.add(app);
            }
        }
        return appsForUpdate;

    }

    public static List<Application__c> extraBSCAppRenew(List<Application__c> iApplications) {
        
        List<Application__c> iApplicationsTobeRenewed = (new ApplicationDomain(iApplications)).filterRecordByStatus('HC - Application Completed');
        // For all the I applications, we need to do a reverse check to find the bsc applications
        List<String> iLicenseIds 
            = (List<String> ) (new ApplicationDomain(iApplicationsTobeRenewed)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> associatedLicenseBSC 
            = AssociatedLicenseSelector.getAssociatedLicensesForEntityLicenseBSC(iLicenseIds);
        List<String> associatedIds = (new AssociatedLicenseDomain(associatedLicenseBSC)).getIds();
        
        Map<String, List<AssociatedLicense__c>> bscAssociatedLicensesMap = (new AssociatedLicenseDomain(associatedLicenseBSC)).getEntityId2Records();
        List<Application__c> applicationForBSC = ApplicationSelector.getRenewalApplicationsByLicenseIds(new List<String>(bscAssociatedLicensesMap.keySet()));

        List<AssociatedLicense__c> bscAssociatedLicenses = AssociatedLicenseSelector.getAssociatedLicensesForEmployeeLicenseIAndIds(bscAssociatedLicensesMap.keySet(), associatedIds);
        bscAssociatedLicensesMap = (new AssociatedLicenseDomain(bscAssociatedLicenses)).getEntityId2Records();

        List<Application__c> bscApplicationsFurtherCheck = (new ApplicationDomain(applicationForBSC)).filterApplicationOnAssociatedLicenseSize(bscAssociatedLicensesMap);
        List<AssociatedLicense__c> bscFilteredAssociatedLicenses = (new ApplicationDomain(bscApplicationsFurtherCheck)).getAllAssociatedLicenses(bscAssociatedLicensesMap);
        Set<String> bscLicenseIds = new Set<String>();
        for(AssociatedLicense__c associatedLicense: bscAssociatedLicenses) {
            if(associatedLicense.PositionStatus__c == 'D - Designated') {
                bscLicenseIds.add(associatedLicense.EntityLicense__c);
            }
        }

        List<Application__c> appsForUpdate =  new List<Application__c>();
        for(Application__c app: bscApplicationsFurtherCheck) {
            if(bscLicenseIds.contains(app.CurrentLicense__c)) {
                app.Status__c = 'HC - Application Completed';
                app.Phase__c = 'H - License Generation';
                appsForUpdate.add(app);
            }
        }
        return appsForUpdate;
    }


    
}