force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CompleteApplicationBy__c.field-meta.xml
<CustomField>
    <fullName>CompleteApplicationBy__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The date on which the Application must be completed or else it will be considered Abandoned.</inlineHelpText>
    <label>Complete Application By</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CompleteExamBy__c.field-meta.xml
<CustomField>
    <fullName>CompleteExamBy__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The Applicant has until this date to complete the Exam</inlineHelpText>
    <label>Complete Exam By</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/IsApplicationTerminated__c.field-meta.xml
<CustomField>
    <fullName>IsApplicationTerminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Application Terminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/NoticeofFeesSentDate__c.field-meta.xml
<CustomField>
    <fullName>NoticeofFeesSentDate__c</fullName>
    <description>PacPoint-MV082219 - Created for PVL phase 1</description>
    <label>Notice of Fees Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A - Application Received</fullName>
                <default>true</default>
                <label>A - Application Received</label>
            </value>
            <value>
                <fullName>E - Executive Officer Review</fullName>
            </value>
            <value>
                <fullName>B - Board Review</fullName>
            </value>
            <value>
                <fullName>C - Consultant Review</fullName>
            </value>
            <value>
                <fullName>X - Exam Phase</fullName>
            </value>
            <value>
                <fullName>O - 2nd Board Review - Oral Interview</fullName>
            </value>
            <value>
                <fullName>D - Dependency Review</fullName>
            </value>
            <value>
                <fullName>L - License Review</fullName>
            </value>
            <value>
                <fullName>H - License Generation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADDC - Additional Class</fullName>
            </value>
            <value>
                <fullName>ADDP - Additional Special Privilege</fullName>
            </value>
            <value>
                <fullName>AMEND - Amendment</fullName>
            </value>
            <value>
                <fullName>APPR - Apprentice or Appraiser Trainee or Intern</fullName>
            </value>
            <value>
                <fullName>BAP - Apprentice Barber</fullName>
            </value>
            <value>
                <fullName>BEP - Beauty Apprentice</fullName>
            </value>
            <value>
                <fullName>CCNM - Change BP Name</fullName>
            </value>
            <value>
                <fullName>CONV - Conversion</fullName>
            </value>
            <value>
                <fullName>CVN - Converted License Type</fullName>
            </value>
            <value>
                <fullName>DELQ - Deliquent Failure to Renew</fullName>
            </value>
            <value>
                <fullName>DP - Applying for Designated Principal</fullName>
            </value>
            <value>
                <fullName>DUAL - Dual (Sole/RME or RME/RME or RME/Sole)</fullName>
            </value>
            <value>
                <fullName>EVA - Apprentice Elevator Mechanic</fullName>
            </value>
            <value>
                <fullName>EXPER - Experience Certificate</fullName>
            </value>
            <value>
                <fullName>GDS2O - GD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>LICC - New License after Cancelation/Close Business</fullName>
            </value>
            <value>
                <fullName>LICF - New License after Forfeiture</fullName>
            </value>
            <value>
                <fullName>LICN - New License</fullName>
            </value>
            <value>
                <fullName>MAP - Apprentice Massage Therapist</fullName>
            </value>
            <value>
                <fullName>PD2SO - PD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>PDREL - Preliminary Decision: Real Estate Salesperson or Broker</fullName>
            </value>
            <value>
                <fullName>PHA - Assistant Pharmacist</fullName>
            </value>
            <value>
                <fullName>R2DBA - RME to Sole Owner</fullName>
            </value>
            <value>
                <fullName>RB2SO - RB to Sole Owner</fullName>
            </value>
            <value>
                <fullName>REAC - Reactivation</fullName>
            </value>
            <value>
                <fullName>RECOG - Temporary Recognition for Real Estate Appraisers</fullName>
            </value>
            <value>
                <fullName>RELOC - Business Site Relocation</fullName>
            </value>
            <value>
                <fullName>RNEW - Renewal</fullName>
            </value>
            <value>
                <fullName>RSTR - Restore - No A/I Status</fullName>
            </value>
            <value>
                <fullName>RSTRA - Restore Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/EffectiveCheckDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveCheckDate__c</fullName>
    <formula>EffectiveExpireDate__c +  LicenseType__r.RenewalWindowInDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Effective Check Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ApplicationBatchJob.cls
/*
* ─────────────────────────────────────────────────────────
* Used for Application Batch Job
* Application records
* ─────────────────────────────────────────────────────────
* PacPoint-CZ050919 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Chris Zhuang - PacificPointCorp
* @created      2019-09-05
* ───────────────────────────────────────────────────────────
* Changes
* 00005003 - Creation of a batch job that will Set Application to AW when Complete By Date is reached during A Phase
* 00005344 - Creation of batch job to set the status to HD on the Application
* 00005654 - Update Batch Job of case 5003
* ───────────────────────────────────────────────────────────
*/
global with sharing class ApplicationBatchJob implements schedulable, Database.Batchable<SObject> {
    /* variables */
    public String objectType;
    public String filterCriteria;
    public String selectFields;
    
    /* construction */
    global ApplicationBatchJob() {
        /* default settings */
        Date today120 = System.today() - 120;
        Datetime localDate = Datetime.newInstance(today120.year(), today120.month(), today120.day(), 00, 00, 00);
        String gmtDate = localDate.format('yyyy-MM-dd', 'GMT');

        objectType = 'Application__c';
        // Change due to the case 000012287
        // filterCriteria = '((Phase__c <> \'H - License Generation\' AND CompleteApplicationBy__c = YESTERDAY) OR (Phase__c <> \'H - License Generation\' AND NoticeofFeesSentDate__c <= ' + gmtDate + ') OR CompleteExamBy__c = YESTERDAY) AND IsApplicationTerminated__c = False';
        // filterCriteria = '(Phase__c <> \'H - License Generation\' '
        //  + ' AND ((Type__c != \'RNEW - Renewal\' and CompleteApplicationBy__c <= YESTERDAY) '
        //  + ' OR (Type__c = \'RNEW - Renewal\' and CurrentLicense__r.EffectiveCheckDate__c <= YESTERDAY)))';
        // filterCriteria = '(Phase__c <> \'H - License Generation\')';
        // Change due to the case 00015503
        filterCriteria = 'Type__c <> \'RSTR - Restore - No A/I Status\' and ' 
            +' (Status__c = \'A1 - Application Submitted, Awaiting Review\''
            + ' or  Status__c = \'A2 - Deficient, Awaiting Notice\' or '
            + ' Status__c = \'A3 - Deficiency Notice Sent\' or '
            + ' Status__c = \'D1 - Awaiting Dependency Review\''
            + ' OR Status__c = \'D2 - Continuing Education Missing\')'
            + ' AND ((Type__c != \'RNEW - Renewal\' and CompleteApplicationBy__c <= YESTERDAY) '
         + ' OR (Type__c = \'RNEW - Renewal\' and CurrentLicense__r.EffectiveCheckDate__c <= YESTERDAY))';
        selectFields = 'Id, Name, Status__c, BoardProgramName__c,  ActiveInactive__c, Phase__c, CurrentLicense__c, CurrentLicense__r.Id, CurrentLicense__r.Status__c, CompleteExamBy__c, CompleteApplicationBy__c, NoticeofFeesSentDate__c, IsApplicationTerminated__c';
    }

    /* batch start class */
    global DataBase.QueryLocator Start(Database.BatchableContext context) {
        return ApplicationSelector.getApplicationsQueryLocator(objectType, selectFields, filterCriteria);
    }

    /* batch execute class */
    global void execute(Database.BatchableContext context, List<SObject> scope) {
        /* process the records */
        // Change due to the case 000012287
        List<Application__c> applications = (List<Application__c>) scope;
        List<Application__c> applicationsForTerminate = (new ApplicationDomain(applications)).terminateApplication();
        List<Application__c> applicationsDReviewsForTerminate = (new ApplicationDomain(applications)).terminateHDApplicationForDReview();
        List<Application__c> applicationForRealstateCommission = (new ApplicationDomain(applications)).terminateHDApplicationForRealstateCommission();
        List<Application__c> appsForUpdate = new List<Application__c> ();
        appsForUpdate.addAll(applicationsDReviewsForTerminate);
        appsForUpdate.addAll(applicationsForTerminate);
        // 1)  We need to update the Application.ActiveInactive__c = Inactive AND SAVE
        appsForUpdate.addAll(applicationForRealstateCommission);
        Database.update(appsForUpdate, true);
        
        // 2)  Then we need to set the Application.Status__c = HC and save again. 
        (new ApplicationDomain(applicationForRealstateCommission)).updateToHCApplicationCompleted();
        Database.update(applicationForRealstateCommission, true);
        // Update current license status to TX - Terminated and Refunded
        Database.update((new ApplicationDomain(applicationsDReviewsForTerminate
            )).updateCurrentLicenseToTerminatedAndRefunded(), true);
    }

    /* batch finish class */
    global void finish(Database.BatchableContext context) {
        /* To send confirmation emails or execute post-processing operations. */
    }

    /* method to execute the schedulable context */
    global void execute(SchedulableContext context) {
        /* process loan account records in batches of 1000 records.  The job will produce on file per 1000 loan__Loan_Disbursal_Transaction__c */
        Database.executeBatch(new ApplicationBatchJob(), 100);
    }
}