force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A - Application Received</fullName>
                <default>true</default>
                <label>A - Application Received</label>
            </value>
            <value>
                <fullName>E - Executive Officer Review</fullName>
            </value>
            <value>
                <fullName>B - Board Review</fullName>
            </value>
            <value>
                <fullName>C - Consultant Review</fullName>
            </value>
            <value>
                <fullName>X - Exam Phase</fullName>
            </value>
            <value>
                <fullName>O - 2nd Board Review - Oral Interview</fullName>
            </value>
            <value>
                <fullName>D - Dependency Review</fullName>
            </value>
            <value>
                <fullName>L - License Review</fullName>
            </value>
            <value>
                <fullName>H - License Generation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicense__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Entities</relationshipLabel>
    <relationshipName>AssociatedEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CommercialEmploymentRenewal.cls
public class CommercialEmploymentRenewal {
    private static Set<String> appIdsForRenew = new Set<String>();
    public static Map<String, Application__c> renewApps = new Map<String, Application__c>();
    @InvocableMethod(
        label='Commercial Employment Renewal'
        description='Renew application with license types EMA, EMA - Sole Proprietor and EMP'
        category='License__c'
        )
    public static List <Results> execute (List<Input> inputs) {
        List<String> appIds = new List<String>();
        for(Input inp: inputs) {
            appIds.add(inp.record.Id);
        }
        List<Application__c> applications = ApplicationSelector.getApplicationsByIds(appIds);
        List<Application__c> appsForCustom = (new ApplicationDomain(applications)).filterApplicationsNotForInactiveRenew();
        appIdsForRenew.addAll((new ApplicationDomain(appsForCustom)).getIds());
        List<Application__c> emaApps = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'EMA'});
        if(!emaApps.isEmpty()) captureRenewApp(processEMAApps(emaApps));

        List<Application__c> emaSoleApps = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'EMA - Sole Proprietor'});
        if(!emaSoleApps.isEmpty()) captureRenewApp(processEMASoleProprietorApps(emaSoleApps));
        
        List<Application__c> empApps = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'EMP'});
        if(!empApps.isEmpty()) captureRenewApp(processEMPApps(empApps));

        (new ApplicationDomain(renewApps.values())).renewApplication();

        List<Application__c> d1Update = (new ApplicationDomain(appsForCustom)).filterRecordsByIds(renewApps.keySet());
        Map<String, Application__c> appsForUpdate = new Map<String, Application__c>();
        appsForUpdate.putAll(renewApps);

        for(Application__c record: d1Update) {
            if(!appsForUpdate.containsKey(record.Id)) {
                record.Status__c = 'D1 - Awaiting Dependency Review';
                record.Phase__c = 'D - Dependency Review';
                appsForUpdate.put(record.Id, record);
            }
        }
        List<License__c> renewLicenses = (new ApplicationDomain(appsForUpdate.values())).renewLicenses();
        
        
        // update applications
        update appsForUpdate.values();

        // update licenses
        update renewLicenses;

        BarberingCosmetologyRenewal.checkToCreateLicenseHistory(appsForUpdate.values());

        List<Application__c> appsForInactive = (new ApplicationDomain(applications)).filterApplicationsForInactiveRenew();

        for(Application__c record: appsForInactive) {
            BarberingCosmetologyRenewal.lanchRenewingInactiveFlow(record);
        }

        List<Results> responseWrapper= new List<Results>();
        for(Input inp: inputs) {
            Results re = new Results();
            re.operationOutcome = 'Success';
            responseWrapper.add(re);
        }
        return responseWrapper;
    }

    public static List<Application__c> processEMAApps(List<Application__c> records) {
        List<String> emaLicenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> empAssociatedLicenses = AssociatedLicenseSelector.getPDGByEntity(emaLicenseIds, new List<String>{'EMP'}, '');
        List<String> empLicenseIds = (List<String>) new AssociatedLicenseDomain(empAssociatedLicenses).getFieldValues('EmployeeLicense__c');
        List<Application__c> empRNApps = ApplicationSelector.getRNApplicationsByLicenseIds(empLicenseIds);
        List<String> empRNLicenses = (List<String>)new ApplicationDomain(empRNApps).getFieldValues('CurrentLicense__c');
        Set<String> empRNLicenseSet = new Set<String>();
        empRNLicenseSet.addAll(empRNLicenses);

        Set<String> emaLicenseIdSet = new Set<String>();
        for(AssociatedLicense__c record: empAssociatedLicenses) {
            if(empRNLicenseSet.contains(record.EmployeeLicense__c)) {
                emaLicenseIdSet.add(record.EntityLicense__c);
            }
        }

        List<Application__c> renewalApplications = (new ApplicationDomain(records)).filterApplicationByLicenseIds(emaLicenseIdSet);
        
        List<String> emaLicenses = new List<String>();
        emaLicenses.addAll(emaLicenseIds);


        renewalApplications.addAll(empRNApps);

        return renewalApplications;
    }

    public static List<Application__c> processEMASoleProprietorApps(List<Application__c> records) {
        List<String> emaLicenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> empAssociatedLicenses = AssociatedLicenseSelector.getPDGByEntity(emaLicenseIds, new List<String>{'EMP'}, ' and Position__c =\'SO - INDIVIDUAL (SOLE OWNER) (ALL BOARDS)\' ');
        List<String> empLicenseIds = (List<String>) new AssociatedLicenseDomain(empAssociatedLicenses).getFieldValues('EmployeeLicense__c');
        List<Application__c> empRNApps = ApplicationSelector.getRNApplicationsByLicenseIds(empLicenseIds);

        List<String> empRNLicenses = (List<String>)new ApplicationDomain(empRNApps).getFieldValues('CurrentLicense__c');
        Set<String> empRNLicenseSet = new Set<String>();
        empRNLicenseSet.addAll(empRNLicenses);

        Set<String> emaLicenseIdSet = new Set<String>();
        for(AssociatedLicense__c record: empAssociatedLicenses) {
            if(empRNLicenseSet.contains(record.EmployeeLicense__c)) {
                emaLicenseIdSet.add(record.EntityLicense__c);
            }
        }

        List<Application__c> renewalApplications = (new ApplicationDomain(records)).filterApplicationByLicenseIds(emaLicenseIdSet);
        
        List<String> emaLicenses = new List<String>();
        emaLicenses.addAll(emaLicenseIds);

        List<AssociatedLicense__c> empEAssociatedLicenses = AssociatedLicenseSelector.getPDGByEmployee(emaLicenses, new List<String>{'EMP'}, '');
        List<String> empEntityLicenseIds = (List<String>) (new AssociatedLicenseDomain(empEAssociatedLicenses)).getFieldValues('EntityLicense__c');
        
        List<Application__c> empRenewalApplications = ApplicationSelector.getRNApplicationsByLicenseIds(empEntityLicenseIds);

        renewalApplications.addAll(empRNApps);
        renewalApplications.addAll(empRenewalApplications);

        return renewalApplications;
    }
    
    public static List<Application__c> processEMPApps(List<Application__c> records) {
        List<String> licenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> associatedLicenses = AssociatedLicenseSelector.getPDGByEmployee(licenseIds, new List<String>{'EMA', 'EMA - Sole Proprietor'}, '');
        List<String> entityLicenseIds = (List<String>)new AssociatedLicenseDomain(associatedLicenses).getFieldValues('EntityLicense__c');
        List<Application__c> emRNApps = ApplicationSelector.getRNApplicationsByLicenseIds(entityLicenseIds);
        List<String> emRNLicenses = (List<String>)new ApplicationDomain(emRNApps).getFieldValues('CurrentLicense__c');
        Set<String> emRNLicenseSet = new Set<String>();
        emRNLicenseSet.addAll(emRNLicenses);

        Set<String> emaLicenseIdSet = new Set<String>();
        for(AssociatedLicense__c record: associatedLicenses) {
            if(emRNLicenseSet.contains(record.EntityLicense__c)) {
                emaLicenseIdSet.add(record.EmployeeLicense__c);
            }
        }

        List<Application__c> renewalApplications = (new ApplicationDomain(records)).filterApplicationByLicenseIds(emaLicenseIdSet);
        

        List<AssociatedLicense__c> empEAssociatedLicenses = AssociatedLicenseSelector.getPDGByEntity(emRNLicenses, new List<String>{'EMP'}, '');
        List<String> empEmployeeLicenseIds = (List<String>) (new AssociatedLicenseDomain(empEAssociatedLicenses)).getFieldValues('EmployeeLicense__c');
        
        List<Application__c> empRenewalApplications = ApplicationSelector.getRNApplicationsByLicenseIds(empEmployeeLicenseIds);

        renewalApplications.addAll(emRNApps);
        renewalApplications.addAll(empRenewalApplications);

        return renewalApplications;
    }

    public static void captureRenewApp(List<Application__c> records) {
        for(Application__c app: records) {
            if(app.Status__c != 'HC - Application Completed'
                 || (appIdsForRenew.contains(app.Id) && app.Status__c == 'HC - Application Completed')) {
                renewApps.put(app.Id, app);
            }
        }
    }

    public class Input {
        @InvocableVariable(label='Application Record for Input' description='Input Application' required=true)
        public Application__c record;
    }
    public class Results {
        @InvocableVariable(label='Records for Output' description='Output Renewals' required=true)
        public String operationOutcome;
    }
}