force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/ApplicationClassifications__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application Classifications</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Application Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationClassifications__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Classifications</relationshipLabel>
    <relationshipName>Application_Classifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.LicenseType__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.LicenseType__c</field>
            <operation>equals</operation>
            <valueField>Classification__c.LicenseType__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Application Classifications</relationshipLabel>
    <relationshipName>Application_Classifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Application Classifications</relationshipLabel>
    <relationshipName>Application_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CW - Class Withdrawn by Applicant</fullName>
            </value>
            <value>
                <fullName>H - Class Deferred by Board</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>NE - No Exam Required--Class to be Licensed</fullName>
            </value>
            <value>
                <fullName>P - Passed Exam--Class to be Licensed</fullName>
            </value>
            <value>
                <fullName>U - Class No Longer Needed Due To Upgrade To Higher Class</fullName>
            </value>
            <value>
                <fullName>W - Awaiting Approval/Exam</fullName>
            </value>
            <value>
                <fullName>NA - No Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Classifications</relationshipLabel>
    <relationshipName>Classifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061219 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1
Used to specify if the license type is used for &quot;Business Account&quot; or &quot;Person Account&quot;</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/recordTypes/PVL.recordType-meta.xml
<RecordType>
    <fullName>PVL</fullName>
    <active>true</active>
    <label>PVL</label>
</RecordType>

force-app/main/default/objects/PVLSettings__mdt/PVLSettings__mdt.object-meta.xml
<CustomObject>
    <description>PacPoint-MV090319 - Created for PVL phase 1</description>
    <label>PVL Settings</label>
    <pluralLabel>PVL Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PVLSettings__mdt/fields/WizardApplicationType__c.field-meta.xml
<CustomField>
    <fullName>WizardApplicationType__c</fullName>
    <defaultValue>&quot;LICN - New License&quot;</defaultValue>
    <description>PacPoint-MV090319 - Created for PVL phase 1</description>
    <inlineHelpText>Use to  default the &quot;Type&quot; field on the application when using the wizard</inlineHelpText>
    <label>Wizard Application Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationRecordsCreation.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Controller for the Application Record Create component
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* @author       Alvin Zhou - PacificPointCorp
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
public with sharing class ApplicationRecordsCreation {
    
    
    //Case: 5473 - Method reads custom metadata and returns value to populate Type for 
    //ApplicationCreation Component
    @AuraEnabled
    public static String licenseApplicationType() {
        //default license type for Application
            return [SELECT WizardApplicationType__c 
                                FROM  PVLSettings__mdt LIMIT 1].WizardApplicationType__c;
                
    }
    
    @AuraEnabled
    public static List<String> getRecordTypesBySobjectType() {
        List<String> recordTypeNames = new List<String>();
        Schema.DescribeSObjectResult d = Schema.SObjectType.Application__c;
        Map<Id,Schema.RecordTypeInfo> rtMapById = d.getRecordTypeInfosById();
        
        for(Schema.RecordTypeInfo recordT: rtMapById.values()) {
            if(recordT.isAvailable()) {
                recordTypeNames.add(recordT.getName());
            }
        }
        return recordTypeNames;
    }
    
    @AuraEnabled
    public static string getLicenseTypes(String accountId){
        String accountType = null;
        if(accountId != null) {
            List<Account> accounts = [Select Id, IsPersonAccount from Account where Id =: accountId];
            if(!accounts.isEmpty()) {
                if(accounts[0].IsPersonAccount) {
                    accountType = 'Person Account';
                } else {
                    accountType = 'Business Account';
                }
            }
        }
        List<String> recordTypes = getRecordTypesBySobjectType();
        List<LicenseType__c> licenseTypes = new List<LicenseType__c>();
        // 00011599
        // if(accountType == null )
            licenseTypes = LicenseTypeSelector.getLicenseTypes(recordTypes);
        // else 
        //     licenseTypes = LicenseTypeSelector.getLicenseTypes(recordTypes, accountType);
        if(accountType != null ) {
            for(LicenseType__c licenseRecord: licenseTypes) {
                licenseRecord.AccountType__c = accountType;
            }
        }
        // End
        List<PVLSettings__mdt> settings = PVLSettingsSelector.getSettingsByName('PVL Settings');    
        PVLSettings__mdt setting = new PVLSettings__mdt();
        if(settings!= null ) {
            setting = settings.get(0);
        }
        (new LicenseTypeDomain(licenseTypes)).updateWithDefaultPageLayout(setting);
        return JSON.serialize(licenseTypes);
    }
    
    @AuraEnabled
    public static String getClassifications(String licenseTypeId){
        List<Classification__c> classifications = [Select Id, Name, Description__c,
            LicenseType__c from Classification__c where Status__c = 'Active' and LicenseType__c =: licenseTypeId order by Name];
        return JSON.serialize(classifications);
    }
    @AuraEnabled
    public static String getApplicationRecordTypes(String recordTypeName){
        List<RecordType> recordTypes = [Select Id, Name 
                                        from RecordType where Name=: recordTypeName and SObjectType='Application__c'];
        return JSON.serialize(recordTypes);
    }
    @AuraEnabled
    public static String getFieldSetByName(String fieldSetName) {
        return JSON.serialize(AccountRecordsSearchCreate.getFieldSet(fieldSetName, 'License__c'));
    }
    @AuraEnabled
    public static String checkDuplicateLicense(String record, String fieldSetName) {
        Application__c application = (Application__c)JSON.deserialize(record, Application__c.class);
        String applicantId = application.Applicant__c;
        String licenseTypeId = application.LicenseType__c;
        List<AccountRecordsSearchCreate.Option> fieldAPISet = AccountRecordsSearchCreate.getFieldSet(fieldSetName, 'License__c');
        List<String> fieldApiNames = new List<String>();
        for(AccountRecordsSearchCreate.Option fieldAPI: fieldAPISet) {
            fieldApiNames.add(fieldAPI.name);
        }

        String fieldString = String.join(fieldApiNames, ',') ;
        List<String> statusList = new List<String>();
        statusList.add('C - Current, Valid & In Good Standing');
        statusList.add('CM - Current, Valid & In Good Standing/Maint. Requirement Due');
        statusList.add('CR - Current/Next Renewal Paid", "DM - Forfeited/Maintenance Requirement Due');
        statusList.add('R - Valid Thru Expiration Date, Subject To Renewal');
        statusList.add('RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due');
        statusList.add('Z - Current & Valid, But Subject To Disciplinary Requirement');
        statusList.add('ZI - Automatically Forfeited Due To Insurance Loss (60 Days to Restore)');
        statusList.add('ZM - Current & Valid, But Subject To Disciplinary/Maintenanc');
        List<License__c> licenses = LicenseSelector.getLicensesByLicenseTypeAndLicenseeAndStatus(licenseTypeId, applicantId, statusList);
        List<String> licenseIds = (new LicenseDomain(licenses)).getIds();
        List<License__c> generatedLicenses = (List<License__c>) (new PVL_Selector()).getSObjectRecordsByField('License__c', fieldApiNames, 
            (List<Id>)licenseIds, 'CreatedDate').getSObjectList();
        return JSON.serialize(generatedLicenses);
    }
    @AuraEnabled 
    public static String getContactRecord(String accountId) {
        return JSON.serialize([Select Id, PersonContact.MailingStreet, PersonContact.MailingCity, 
                PersonContact.MailingCountry, PersonContact.MailingState,PersonContact.MailingStateCode, 
                PersonContact.MailingPostalCode from Account where Id=: accountId]);
    }
    @AuraEnabled
    public static String createApplicationRecord(String record, String classificationsStr) {
        // Call CustomRecordCreate to create Application record
        system.debug('record>>>>  ' + record);
        
        String response = CustomRecordCreate.SaveRecord('Application__c', record, null);
        Map<String, String> resultMap = (Map<String, String> )JSON.deserialize(response, Map<String, String>.class);
        if(resultMap.get('status') == 'OK') {
            String recordId = resultMap.get('id');
            // select License Type Id
            Application__c application = ApplicationSelector.getApplications(new List<String>{recordId}).get(0);
            List<Classification__c> classifications = (List<Classification__c>) JSON.deserialize(
                classificationsStr, List<Classification__c>.class);
            List<ApplicationClassifications__c> records = new List<ApplicationClassifications__c> ();
            for(Classification__c classification: classifications) {
                ApplicationClassifications__c appClassRecord = new ApplicationClassifications__c ();
                if(application.LicenseType__r.DefaultClassStatus__c != null) {
                    appClassRecord.Status__c = application.LicenseType__r.DefaultClassStatus__c;
                }
                 
                appClassRecord.Classification__c  = classification.Id;
                appClassRecord.Application__c   = recordId;
                records.add(appClassRecord);
            }
            insert records;
        } else {
            String errorMessage = resultMap.get('message');
            System.debug('error message' + errorMessage);
            // AuraHandledException auExp = new AuraHandledException(errorMessage);
            // auExp.setMessage(errorMessage);
            // throw auExp;
        }
        return response;
    }
}