force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint-KN091319 - Created for PVL Phase 1</description>
    <inlineHelpText>Shows if the application is Active or Inactive.</inlineHelpText>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/DependencyRequired__c.field-meta.xml
<CustomField>
    <fullName>DependencyRequired__c</fullName>
    <description>PacPoint-CZ100319 - Created for PVL phase 1</description>
    <formula>LicenseType__r.DependencyRequired__c</formula>
    <label>Dependency Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADDC - Additional Class</fullName>
            </value>
            <value>
                <fullName>ADDP - Additional Special Privilege</fullName>
            </value>
            <value>
                <fullName>AMEND - Amendment</fullName>
            </value>
            <value>
                <fullName>APPR - Apprentice or Appraiser Trainee or Intern</fullName>
            </value>
            <value>
                <fullName>BAP - Apprentice Barber</fullName>
            </value>
            <value>
                <fullName>BEP - Beauty Apprentice</fullName>
            </value>
            <value>
                <fullName>CCNM - Change BP Name</fullName>
            </value>
            <value>
                <fullName>CONV - Conversion</fullName>
            </value>
            <value>
                <fullName>CVN - Converted License Type</fullName>
            </value>
            <value>
                <fullName>DELQ - Deliquent Failure to Renew</fullName>
            </value>
            <value>
                <fullName>DP - Applying for Designated Principal</fullName>
            </value>
            <value>
                <fullName>DUAL - Dual (Sole/RME or RME/RME or RME/Sole)</fullName>
            </value>
            <value>
                <fullName>EVA - Apprentice Elevator Mechanic</fullName>
            </value>
            <value>
                <fullName>EXPER - Experience Certificate</fullName>
            </value>
            <value>
                <fullName>GDS2O - GD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>LICC - New License after Cancelation/Close Business</fullName>
            </value>
            <value>
                <fullName>LICF - New License after Forfeiture</fullName>
            </value>
            <value>
                <fullName>LICN - New License</fullName>
            </value>
            <value>
                <fullName>MAP - Apprentice Massage Therapist</fullName>
            </value>
            <value>
                <fullName>PD2SO - PD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>PDREL - Preliminary Decision: Real Estate Salesperson or Broker</fullName>
            </value>
            <value>
                <fullName>PHA - Assistant Pharmacist</fullName>
            </value>
            <value>
                <fullName>R2DBA - RME to Sole Owner</fullName>
            </value>
            <value>
                <fullName>RB2SO - RB to Sole Owner</fullName>
            </value>
            <value>
                <fullName>REAC - Reactivation</fullName>
            </value>
            <value>
                <fullName>RECOG - Temporary Recognition for Real Estate Appraisers</fullName>
            </value>
            <value>
                <fullName>RELOC - Business Site Relocation</fullName>
            </value>
            <value>
                <fullName>RNEW - Renewal</fullName>
            </value>
            <value>
                <fullName>RSTR - Restore - No A/I Status</fullName>
            </value>
            <value>
                <fullName>RSTRA - Restore Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Classifications</relationshipLabel>
    <relationshipName>Classifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Classification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061219 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint KN080819 - Created for PVL</description>
    <label>Active/Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/DependencyRequired__c.field-meta.xml
<CustomField>
    <fullName>DependencyRequired__c</fullName>
    <description>PACIFICPoint-AZ20200908- 00010823</description>
    <formula>LicenseType__r.DependencyRequired__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dependency Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseClassification__c/LicenseClassification__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Classification</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>License Classifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseClassification__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>License Classifications</relationshipLabel>
    <relationshipName>LicenseClassifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/ActiveInactive__c.field-meta.xml
<CustomField>
    <fullName>ActiveInactive__c</fullName>
    <description>PacPoint-IC080519- Created for PVL phase 1</description>
    <label>Active / Inactive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/DependencyRequired__c.field-meta.xml
<CustomField>
    <fullName>DependencyRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-KN092719 - Created for PVL Phase 1</description>
    <label>Dependency Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/recordTypes/PVL.recordType-meta.xml
<RecordType>
    <fullName>PVL</fullName>
    <active>true</active>
    <label>PVL</label>
</RecordType>

force-app/main/default/classes/LicenseCurrentAndValidFinderTest.cls
@isTest
public with sharing class LicenseCurrentAndValidFinderTest {
    private static testMethod void testExecute() {
        // create transactions
        // Data setup
		Account acc = new Account();
        acc.Name = 'Test 398624';
        insert acc;
     
        Contact cnt = new Contact();
        cnt.AccountId = acc.Id;
        cnt.LastName = 'Test 375734';
        insert cnt;

        LicenseType__c licenseTypeRecord = new LicenseType__c();
        licenseTypeRecord.Name = 'Test LT';
        licenseTypeRecord.DependencyRequired__c = true;
        insert licenseTypeRecord;

        License__c licenseRecord = new License__c();
		licenseRecord.Name = 'License A';
		licenseRecord.ActiveInactive__c = 'Active';
		licenseRecord.LicenseType__c = licenseTypeRecord.Id;
        licenseRecord.Status__c = 'CP - Current Pending';
        Id CTEntityRecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('PVL - CT - Entity').getRecordTypeId();
        licenseRecord.RecordTypeId = CTEntityRecordTypeId;
        insert licenseRecord;

        Application__c dependentApplication = new Application__c();
        dependentApplication.Applicant__c = acc.Id;
        dependentApplication.LicenseType__c = licenseTypeRecord.Id;
        dependentApplication.Type__c = 'LICN - New License';
        dependentApplication.Phase__c = 'A - Application Received';
        insert dependentApplication;

        Application__c applicationRecord = new Application__c();
        applicationRecord.Applicant__c = acc.Id;
        applicationRecord.LicenseType__c = licenseTypeRecord.Id;
        applicationRecord.Type__c = 'LICN - New License';
        applicationRecord.Phase__c = 'A - Application Received';
        insert applicationRecord;

        Classification__c classificationRecord = new Classification__c();
		classificationRecord.Status__c = 'Active';
		classificationRecord.Name = 'Classification Record';
		classificationRecord.LicenseType__c = licenseTypeRecord.Id;
		insert classificationRecord;

        LicenseClassification__c licenseClassificationRecord = new LicenseClassification__c();
		licenseClassificationRecord.Status__c = 'C - Current, Valid & In Good Standing';
        licenseClassificationRecord.License__c = licenseRecord.id;
        licenseClassificationRecord.Classification__c = classificationRecord.Id;
        insert licenseClassificationRecord;

        Test.startTest();
        List<License__c> records = [SELECT Id, Status__c FROM License__c ];
        (new LicenseCurrentAndValidFinderScheduler()).execute(null, records);
        Database.executeBatch(new LicenseCurrentAndValidFinderScheduler(), 100);
        Test.stopTest();
    }
   
}