force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADDC - Additional Class</fullName>
            </value>
            <value>
                <fullName>ADDP - Additional Special Privilege</fullName>
            </value>
            <value>
                <fullName>AMEND - Amendment</fullName>
            </value>
            <value>
                <fullName>APPR - Apprentice or Appraiser Trainee or Intern</fullName>
            </value>
            <value>
                <fullName>BAP - Apprentice Barber</fullName>
            </value>
            <value>
                <fullName>BEP - Beauty Apprentice</fullName>
            </value>
            <value>
                <fullName>CCNM - Change BP Name</fullName>
            </value>
            <value>
                <fullName>CONV - Conversion</fullName>
            </value>
            <value>
                <fullName>CVN - Converted License Type</fullName>
            </value>
            <value>
                <fullName>DELQ - Deliquent Failure to Renew</fullName>
            </value>
            <value>
                <fullName>DP - Applying for Designated Principal</fullName>
            </value>
            <value>
                <fullName>DUAL - Dual (Sole/RME or RME/RME or RME/Sole)</fullName>
            </value>
            <value>
                <fullName>EVA - Apprentice Elevator Mechanic</fullName>
            </value>
            <value>
                <fullName>EXPER - Experience Certificate</fullName>
            </value>
            <value>
                <fullName>GDS2O - GD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>LICC - New License after Cancelation/Close Business</fullName>
            </value>
            <value>
                <fullName>LICF - New License after Forfeiture</fullName>
            </value>
            <value>
                <fullName>LICN - New License</fullName>
            </value>
            <value>
                <fullName>MAP - Apprentice Massage Therapist</fullName>
            </value>
            <value>
                <fullName>PD2SO - PD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>PDREL - Preliminary Decision: Real Estate Salesperson or Broker</fullName>
            </value>
            <value>
                <fullName>PHA - Assistant Pharmacist</fullName>
            </value>
            <value>
                <fullName>R2DBA - RME to Sole Owner</fullName>
            </value>
            <value>
                <fullName>RB2SO - RB to Sole Owner</fullName>
            </value>
            <value>
                <fullName>REAC - Reactivation</fullName>
            </value>
            <value>
                <fullName>RECOG - Temporary Recognition for Real Estate Appraisers</fullName>
            </value>
            <value>
                <fullName>RELOC - Business Site Relocation</fullName>
            </value>
            <value>
                <fullName>RNEW - Renewal</fullName>
            </value>
            <value>
                <fullName>RSTR - Restore - No A/I Status</fullName>
            </value>
            <value>
                <fullName>RSTRA - Restore Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PVLProcess__e/PVLProcess__e.object-meta.xml
<CustomObject>
    <description>PacPoint-AZ011920 - Created for PVL phase 1</description>
    <label>PVL Process</label>
    <pluralLabel>PVL Processes</pluralLabel>
</CustomObject>

force-app/main/default/objects/PVLProcess__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-AZ011920 - Created for PVL phase 1
Used to specify the type of the platform events</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PVLProcessFlowTest.cls
@isTest
private class PVLProcessFlowTest {
    @isTest
    static void testDependencyFlow() {
        TestDataFactory.createLicense();
        Account acc = [Select Id from Account limit 1];
        Set<Id> recordIds = new Set<Id>();
        List<Application__c> apps = new List<Application__c>();
        for(License__c record: [Select Id, LicenseType__c from License__c]) {
            recordIds.add(record.Id);
            Application__c app = new Application__c();
            app.Name = 'app';
            app.Status__c = 'D1 - Awaiting Dependency Review';
            app.LicenseType__c = record.LicenseType__c;
            app.Applicant__c = acc.Id;
            app.CurrentLicense__c = record.Id;
            app.Type__c = 'RNEW - Renewal';
            apps.add(app);
        }

        Test.startTest();
        insert apps;

        
        PVLProcess__e process = new PVLProcess__e();
        process.Type__c = 'DependencyFlow';
        process.Payload__c = JSON.serialize(recordIds);
        EventBus.publish(process);
        Test.stopTest();
    }
    @isTest
    static void testMultiDependencyFlow() {
        TestDataFactory.prepareAssociatedLicenses();
        List<LicenseType__c> licenseTypes = [Select Id, X2ndDependencyRequired__c from LicenseType__c ];
        for(LicenseType__c record: licenseTypes) {
            record.X2ndDependencyRequired__c = true;
        }
        update licenseTypes;
        List<License__c> records = [Select Id, LicenseType__c from License__c ];
        Test.startTest();
        PVLProcess__e process = new PVLProcess__e();
        process.Type__c = 'MultiDependencyFlow';
        process.Payload__c = JSON.serialize(records);
        EventBus.publish(process);
        Test.stopTest();
        
    }
}