force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationRequirement__c/ApplicationRequirement__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application Requirement</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationRequirement__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Requirements</relationshipLabel>
    <relationshipName>Application_Deficiencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/IsDeficient__c.field-meta.xml
<CustomField>
    <fullName>IsDeficient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Is the Applicant Deficient on this?  Is so, please check the box.</inlineHelpText>
    <label>Is Deficient?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AppDeficiencyEmailAppReqsControllerTest.cls
/*
 * ___________________________________________________________________________________
 * Test class for AppDeficiencyEmailAppReqsController
 * __________________________________________________________________________________
 * PacPoint-CL03032020 - Created for Phase #
 * __________________________________________________________________________________
 * Initial implementation
 * 
 * @author chris.loyola@pacificpointcorp.com
 * 
 * @created 3/3/2020
 * __________________________________________________________________________________
 */
@IsTest
private class AppDeficiencyEmailAppReqsControllerTest {
    @TestSetup
    static void setup() {
        Application__c app = new Application__c();
        insert app;

        ApplicationRequirement__c requirement = new ApplicationRequirement__c();
        requirement.Application__c = app.Id;
        requirement.IsDeficient__c = true;
        insert requirement;
    }

    @IsTest
    static void testGetApplicationRequirements() {
        AppDeficiencyEmailAppReqsController controller = new AppDeficiencyEmailAppReqsController();
        controller.applicationId = [SELECT Id FROM Application__c].Id;
        List<ApplicationRequirement__c> apps = controller.getApplicationRequirements();
    }
}