force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADDC - Additional Class</fullName>
            </value>
            <value>
                <fullName>ADDP - Additional Special Privilege</fullName>
            </value>
            <value>
                <fullName>AMEND - Amendment</fullName>
            </value>
            <value>
                <fullName>APPR - Apprentice or Appraiser Trainee or Intern</fullName>
            </value>
            <value>
                <fullName>BAP - Apprentice Barber</fullName>
            </value>
            <value>
                <fullName>BEP - Beauty Apprentice</fullName>
            </value>
            <value>
                <fullName>CCNM - Change BP Name</fullName>
            </value>
            <value>
                <fullName>CONV - Conversion</fullName>
            </value>
            <value>
                <fullName>CVN - Converted License Type</fullName>
            </value>
            <value>
                <fullName>DELQ - Deliquent Failure to Renew</fullName>
            </value>
            <value>
                <fullName>DP - Applying for Designated Principal</fullName>
            </value>
            <value>
                <fullName>DUAL - Dual (Sole/RME or RME/RME or RME/Sole)</fullName>
            </value>
            <value>
                <fullName>EVA - Apprentice Elevator Mechanic</fullName>
            </value>
            <value>
                <fullName>EXPER - Experience Certificate</fullName>
            </value>
            <value>
                <fullName>GDS2O - GD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>LICC - New License after Cancelation/Close Business</fullName>
            </value>
            <value>
                <fullName>LICF - New License after Forfeiture</fullName>
            </value>
            <value>
                <fullName>LICN - New License</fullName>
            </value>
            <value>
                <fullName>MAP - Apprentice Massage Therapist</fullName>
            </value>
            <value>
                <fullName>PD2SO - PD to Sole Owner</fullName>
            </value>
            <value>
                <fullName>PDREL - Preliminary Decision: Real Estate Salesperson or Broker</fullName>
            </value>
            <value>
                <fullName>PHA - Assistant Pharmacist</fullName>
            </value>
            <value>
                <fullName>R2DBA - RME to Sole Owner</fullName>
            </value>
            <value>
                <fullName>RB2SO - RB to Sole Owner</fullName>
            </value>
            <value>
                <fullName>REAC - Reactivation</fullName>
            </value>
            <value>
                <fullName>RECOG - Temporary Recognition for Real Estate Appraisers</fullName>
            </value>
            <value>
                <fullName>RELOC - Business Site Relocation</fullName>
            </value>
            <value>
                <fullName>RNEW - Renewal</fullName>
            </value>
            <value>
                <fullName>RSTR - Restore - No A/I Status</fullName>
            </value>
            <value>
                <fullName>RSTRA - Restore Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-KN081619 - Created for PVL Phase 1</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RME</fullName>
            </value>
            <value>
                <fullName>Broker In Charge</fullName>
            </value>
            <value>
                <fullName>Mechanic In Charge</fullName>
            </value>
            <value>
                <fullName>Barber Operator-In-Charge</fullName>
            </value>
            <value>
                <fullName>Beauty Operator-In-Charge</fullName>
            </value>
            <value>
                <fullName>Principal RME</fullName>
            </value>
            <value>
                <fullName>Pharmacist-in-Charge</fullName>
            </value>
            <value>
                <fullName>Principal Massage Therapist</fullName>
            </value>
            <value>
                <fullName>Principal Agent</fullName>
            </value>
            <value>
                <fullName>Principal Detective</fullName>
            </value>
            <value>
                <fullName>Principal Guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/EffectiveExpireDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveExpireDate__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The date the license expires</inlineHelpText>
    <label>Effective Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseTypeEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>LicenseTypeEffectiveDate__c</fullName>
    <description>PacPoint-KN06172020-Created for PVL Phase 1 Sprint 6</description>
    <formula>LicenseType__r.LicenseTypeEffectiveDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Type Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/AbleToInactivate__c.field-meta.xml
<CustomField>
    <fullName>AbleToInactivate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint KN081419 - Created for PVL</description>
    <inlineHelpText>Is this License Type able to hold an Inactive Status?</inlineHelpText>
    <label>Able To Inactivate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/DurationofLicenseInMonths__c.field-meta.xml
<CustomField>
    <fullName>DurationofLicenseInMonths__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1
PacPoint-KN081419 - Modified for PVL Phase 1</description>
    <inlineHelpText>The number of months of the License Period</inlineHelpText>
    <label>Duration of License (In Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseTypeEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>LicenseTypeEffectiveDate__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <inlineHelpText>The effective start date of the license type</inlineHelpText>
    <label>License Type Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/PreviousLicensePeriodExpireDate__c.field-meta.xml
<CustomField>
    <fullName>PreviousLicensePeriodExpireDate__c</fullName>
    <label>Previous License Period Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/StartofRenewalPeriod__c.field-meta.xml
<CustomField>
    <fullName>StartofRenewalPeriod__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Start of Renewal Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RealEstateLicensesInactivatorBatchTest.cls
/*
 * -----------------------------------------------------------------------------------
 * Description
 * -----------------------------------------------------------------------------------
 * PacPoint-CL10192022 - Created for
 * -----------------------------------------------------------------------------------
 * Initial implementation
 *
 * @author chris.loyola@pacificpointcorp.com
 *
 * @created 10/19/2022
 * -----------------------------------------------------------------------------------
 * Changes
 * -----------------------------------------------------------------------------------
 */
@IsTest
private class RealEstateLicensesInactivatorBatchTest {
    @TestSetup
    static void setup() {
        Date licTypeEffectiveDate = Date.today().toStartOfMonth();
        Date licTypeEffectiveExpireDate = licTypeEffectiveDate.addMonths(1).addDays(-1);

        LicenseType__c licTypeRbEntity = new LicenseType__c();
        licTypeRbEntity.Name = 'RB - Entity';
        licTypeRbEntity.StartofRenewalPeriod__c = Date.today().addDays(-10);
        licTypeRbEntity.PreviousLicensePeriodExpireDate__c = Date.today().addDays(100);
        licTypeRbEntity.LicenseTypeEffectiveDate__c = licTypeEffectiveDate;
        licTypeRbEntity.DurationofLicenseInMonths__c = 1;
        licTypeRbEntity.AbleToInactivate__c = true;

        LicenseType__c licTypeRbBroker = new LicenseType__c();
        licTypeRbBroker.Name = 'RB - Broker';
        licTypeRbBroker.StartofRenewalPeriod__c = Date.today().addDays(-10);
        licTypeRbBroker.PreviousLicensePeriodExpireDate__c = Date.today().addDays(100);
        licTypeRbBroker.LicenseTypeEffectiveDate__c = licTypeEffectiveDate;
        licTypeRbBroker.DurationofLicenseInMonths__c = 1;
        licTypeRbBroker.AbleToInactivate__c = true;

        insert new List<LicenseType__c>{licTypeRbEntity, licTypeRbBroker};

        License__c licRbEntity = new License__c();
        licRbEntity.LicenseType__c = licTypeRbEntity.Id;
        licRbEntity.EffectiveExpireDate__c = licTypeEffectiveExpireDate;

        License__c licRbEntity2 = new License__c();
        licRbEntity2.LicenseType__c = licTypeRbEntity.Id;
        licRbEntity2.EffectiveExpireDate__c = licTypeEffectiveExpireDate;

        License__c licRbEntity3 = new License__c();
        licRbEntity3.LicenseType__c = licTypeRbEntity.Id;
        licRbEntity3.EffectiveExpireDate__c = licTypeEffectiveExpireDate;

        License__c licRbBroker = new License__c();
        licRbBroker.LicenseType__c = licTypeRbBroker.Id;
        licRbBroker.EffectiveExpireDate__c = licTypeEffectiveExpireDate;

        License__c licRbBroker2 = new License__c();
        licRbBroker2.LicenseType__c = licTypeRbBroker.Id;
        licRbBroker2.EffectiveExpireDate__c = licTypeEffectiveExpireDate;

        License__c licRbBroker3 = new License__c();
        licRbBroker3.LicenseType__c = licTypeRbBroker.Id;
        licRbBroker3.EffectiveExpireDate__c = licTypeEffectiveExpireDate;


        insert new List<License__c>{licRbEntity, licRbEntity2, licRbEntity3, licRbBroker, licRbBroker2, licRbBroker3};

        licRbEntity.Status__c = 'R - Valid Thru Expiration Date, Subject To Renewal';
        licRbEntity.ActiveInactive__c = 'Active';

        licRbEntity2.Status__c = 'Z - Current & Valid, But Subject To Disciplinary Requirement';
        licRbEntity2.ActiveInactive__c = 'Active';

        licRbEntity3.Status__c = 'R - Valid Thru Expiration Date, Subject To Renewal';
        licRbEntity3.ActiveInactive__c = 'Active';

        licRbBroker.Status__c = 'C - Current, Valid & In Good Standing';
        licRbBroker.ActiveInactive__c = 'Active';

        licRbBroker2.Status__c = 'R - Valid Thru Expiration Date, Subject To Renewal';
        licRbBroker2.ActiveInactive__c = 'Active';

        licRbBroker3.Status__c = 'R - Valid Thru Expiration Date, Subject To Renewal';
        licRbBroker3.ActiveInactive__c = 'Active';

        update new List<License__c>{licRbEntity, licRbEntity2, licRbEntity3, licRbBroker, licRbBroker2, licRbBroker3};

        AssociatedLicense__c rbEntityAssoc = new AssociatedLicense__c();
        rbEntityAssoc.EntityLicense__c = licRbEntity.Id;
        rbEntityAssoc.EmployeeLicense__c = licRbBroker.Id;
        rbEntityAssoc.EmploymentStatus__c = 'Employed';

        AssociatedLicense__c rbEntity2Assoc = new AssociatedLicense__c();
        rbEntity2Assoc.EntityLicense__c = licRbEntity2.Id;
        rbEntity2Assoc.EmployeeLicense__c = licRbBroker2.Id;
        rbEntity2Assoc.EmploymentStatus__c = 'Employed';

        AssociatedLicense__c rbEntity3Assoc = new AssociatedLicense__c();
        rbEntity3Assoc.EntityLicense__c = licRbEntity2.Id;
        rbEntity3Assoc.EmployeeLicense__c = licRbBroker3.Id;
        rbEntity3Assoc.EmploymentStatus__c = 'Employed';

        AssociatedLicense__c rbEntity4Assoc = new AssociatedLicense__c();
        rbEntity4Assoc.EntityLicense__c = licRbEntity3.Id;
        rbEntity4Assoc.EmployeeLicense__c = licRbBroker.Id;
        rbEntity4Assoc.EmploymentStatus__c = 'Employed';

        insert new List<AssociatedLicense__c>{rbEntityAssoc, rbEntity2Assoc, rbEntity3Assoc, rbEntity4Assoc};

        String appLicensePeriodRnew = String.valueOf(licTypeEffectiveDate.month()) + '/' +
            String.valueOf(licTypeEffectiveDate.day()) + '/' +
            String.valueOf(licTypeEffectiveDate.year()) + ' - ' +
            String.valueOf(licTypeEffectiveExpireDate.month()) + '/' +
            String.valueOf(licTypeEffectiveExpireDate.day()) + '/' +
            String.valueOf(licTypeEffectiveExpireDate.year());

        Id appPvlRnewRtId = APplication__c.getSObjectType()
            .getDescribe()
            .getRecordTypeInfosByDeveloperName()
            .get('PVLRNEW')
            .getRecordTypeId();

        Application__c appRbEntity = new Application__c();
        appRbEntity.CurrentLicense__c = licRbEntity.Id;
        appRbEntity.Type__c = 'RNEW - Renewal';
        appRbEntity.LicenseType__c = licTypeRbEntity.Id;
        appRbEntity.Status__c = 'D1 - Awaiting Dependency Review';
        appRbEntity.Phase__c = 'D - Dependency Review';
        appRbEntity.LicensePeriodRNEW__c = appLicensePeriodRnew;
        appRbEntity.RecordTypeId = appPvlRnewRtId;

        Application__c appRbEntity3 = new Application__c();
        appRbEntity3.CurrentLicense__c = licRbEntity3.Id;
        appRbEntity3.Type__c = 'RNEW - Renewal';
        appRbEntity3.LicenseType__c = licTypeRbEntity.Id;
        appRbEntity3.Status__c = 'D2 - Continuing Education Missing';
        appRbEntity3.Phase__c = 'D - Dependency Review';
        appRbEntity3.LicensePeriodRNEW__c = appLicensePeriodRnew;
        appRbEntity3.RecordTypeId = appPvlRnewRtId;

        Application__c appRbBroker2 = new Application__c();
        appRbBroker2.CurrentLicense__c = licRbBroker2.Id;
        appRbBroker2.Type__c = 'RNEW - Renewal';
        appRbBroker2.LicenseType__c = licTypeRbBroker.Id;
        appRbBroker2.Status__c = 'D2 - Continuing Education Missing';
        appRbBroker2.Phase__c = 'D - Dependency Review';
        appRbBroker2.LicensePeriodRNEW__c = appLicensePeriodRnew;
        appRbBroker2.RecordTypeId = appPvlRnewRtId;

        Application__c appRbBroker3 = new Application__c();
        appRbBroker3.CurrentLicense__c = licRbBroker3.Id;
        appRbBroker3.Type__c = 'RNEW - Renewal';
        appRbBroker3.LicenseType__c = licTypeRbBroker.Id;
        appRbBroker3.Status__c = 'D1 - Awaiting Dependency Review';
        appRbBroker3.Phase__c = 'D - Dependency Review';
        appRbBroker3.LicensePeriodRNEW__c = appLicensePeriodRnew;
        appRbBroker3.RecordTypeId = appPvlRnewRtId;

        insert new List<Application__c>{appRbEntity, appRbEntity3, appRbBroker2, appRbBroker3};
    }

    @IsTest
    static void batchTest() {
        Test.startTest();
        (new RealEstateLicensesInactivatorBatch()).execute(null);
        Test.stopTest();
    }
}