force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/LicensePeriodRNEW__c.field-meta.xml
<CustomField>
    <fullName>LicensePeriodRNEW__c</fullName>
    <description>Used for MyPVL Portal Online Renewal History</description>
    <label>License Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicense__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Entities</relationshipLabel>
    <relationshipName>AssociatedEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/PositionStatus__c.field-meta.xml
<CustomField>
    <fullName>PositionStatus__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D - DESIGNATED</fullName>
            </value>
            <value>
                <fullName>P - PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>T - TEMPORARY (REAL ESTATE)</fullName>
            </value>
            <value>
                <fullName>X - EXTEND TEMPORARY (REAL ESTATE)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseTypeName__c.field-meta.xml
<CustomField>
    <fullName>LicenseTypeName__c</fullName>
    <description>PacPoint-IC021920- Created for PVL phase 1</description>
    <formula>LicenseType__r.Name</formula>
    <label>License Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/NumberofActiveEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberofActiveEmployees__c</fullName>
    <description>PacPoint-KN11052020-Created for PVL Phase 1</description>
    <label>Number of Active Employees</label>
    <summaryFilterItems>
        <field>AssociatedLicense__c.EmploymentStatus__c</field>
        <operation>equals</operation>
        <value>Employed</value>
    </summaryFilterItems>
    <summaryForeignKey>AssociatedLicense__c.EntityLicense__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CtEntitySolePrmePushThroughBatch.cls
/*
 * -----------------------------------------------------------------------------------
 * Description
 *
 * -----------------------------------------------------------------------------------
 * Covered by: ContractorRenewalPushThroughBatchTest
 * -----------------------------------------------------------------------------------
 * PacPoint-CL09142022 - Created for case 00024031
 * -----------------------------------------------------------------------------------
 * Initial implementation
 *
 * @author chris.loyola@pacificpointcorp.com
 *
 * @created 09/14/2022
 * -----------------------------------------------------------------------------------
 * Changes
 * -----------------------------------------------------------------------------------
 */
public class CtEntitySolePrmePushThroughBatch implements Schedulable, Database.Batchable<SObject>, Database.Stateful{
    public Set<String> licenseTypeFilter = new Set<String>{
        'CT - RME',
        'CT - Sole Proprietor',
        'CT - Entity'
        };

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<License__c> licenses = (List<License__c>)scope;
        Map<Id, License__c> licensesMap = new Map<Id, License__c>(licenses);
        Map<Id, Id> ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap = new Map<Id, Id>();
        Map<Id, Id> ctEntityAssociatedEmployeeLicenseIdLicenseIdMap = new Map<Id, Id>();
        Map<Id, Id> ctRmeAssociatedEntityLicenseIdLicenseIdMap = new Map<Id, Id>();
        Set<Id> licenseIdsToComplete = new Set<Id>();
        Set<Id> licenseIdsWithoutAssoc = new Set<Id>();
        Set<Id> assocLicenseIds = new Set<Id>();

        for (License__c l : licenses) {
            if (l.LicenseTypeName__c == 'CT - Sole Proprietor') {
                if (l.NumberofActiveEmployees__c > 1) {
                    if (!l.AssociatedEmployee__r.isEmpty()) {
                        for (AssociatedLicense__c al : l.AssociatedEmployee__r) {
                            if (al.EmployeeLicense__c != null) {
                                ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap.put(al.EmployeeLicense__c, l.Id);
                                assocLicenseIds.add(al.EmployeeLicense__c);
                            }
                        }
                    } else {
                        licenseIdsWithoutAssoc.add(l.Id);
                    }
                } else {
                    licenseIdsToComplete.add(l.Id);
                }
                continue;
            }

            if (l.LicenseTypeName__c == 'CT - Entity') {
                if (!l.AssociatedEmployee__r.isEmpty()) {
                    for (AssociatedLicense__c al : l.AssociatedEmployee__r) {
                        if (al.EmployeeLicense__c != null && (al.PositionStatus__c == 'P - PRINCIPAL')) {
                            ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.put(al.EmployeeLicense__c, l.Id);
                            assocLicenseIds.add(al.EmployeeLicense__c);
                        }
                    }

                    if (!ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.values().contains(l.Id)) {
                        licenseIdsWithoutAssoc.add(l.Id);
                    }
                } else {
                    licenseIdsWithoutAssoc.add(l.Id);
                }
                continue;
            }

            if (l.LicenseTypeName__c == 'CT - RME') {
                if (!l.AssociatedEntities__r.isEmpty()) {
                    for (AssociatedLicense__c al : l.AssociatedEntities__r) {
                        if (al.EntityLicense__c != null && (al.PositionStatus__c == 'P - PRINCIPAL')) {
                            ctRmeAssociatedEntityLicenseIdLicenseIdMap.put(al.EntityLicense__c, l.Id);
                            assocLicenseIds.add(al.EntityLicense__c);
                        }
                    }
                }
            }
        }

        //find associated applications
        List<Application__c> associatedApplications = [
            SELECT
                Id,
                CurrentLicense__c,
                LicensePeriodRNEW__c,
                LicenseType__r.PreviousLicensePeriod__c
            FROM Application__c
            WHERE CurrentLicense__c IN :assocLicenseIds
            AND Type__c = 'RNEW - Renewal'
            AND (Phase__c = 'D - Dependency Review' OR Phase__c = 'H - License Generation')
            AND (Status__c = 'D1 - Awaiting Dependency Review' OR Status__c = 'HC - Application Completed')
        ];

        //collect valid applications
        Set<Id> assocLicenseIdsWithValidApplication = new Set<Id>();

        for (Application__c a : associatedApplications) {
            if (a.LicensePeriodRNEW__c != a.LicenseType__r.PreviousLicensePeriod__c) {
                continue;
            }

            assocLicenseIdsWithValidApplication.add(a.CurrentLicense__c);

            if (ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.containsKey(a.CurrentLicense__c)) {
                licenseIdsToComplete.add(ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.get(a.CurrentLicense__c));
                continue;
            }

            if (ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap.containsKey(a.CurrentLicense__c)) {
                licenseIdsToComplete.add(ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap.get(a.CurrentLicense__c));
                continue;
            }

            if (ctRmeAssociatedEntityLicenseIdLicenseIdMap.containsKey(a.CurrentLicense__c)) {
                licenseIdsToComplete.add(ctRmeAssociatedEntityLicenseIdLicenseIdMap.get(a.CurrentLicense__c));
                continue;
            }
        }

        //find remaining licences for RM
        assocLicenseIds.removeAll(assocLicenseIdsWithValidApplication);
        for (Id i : assocLicenseIds) {
            if (ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.containsKey(i) &&
                !licenseIdsToComplete.contains(ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.get(i))) {
                licenseIdsWithoutAssoc.add(ctEntityAssociatedEmployeeLicenseIdLicenseIdMap.get(i));
                continue;
            }

            if (ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap.containsKey(i) &&
                !licenseIdsToComplete.contains(ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap.get(i))) {
                licenseIdsWithoutAssoc.add(ctSolePropAssociatedEmployeeLicenseIdLicenseIdMap.get(i));
                continue;
            }

            if (ctRmeAssociatedEntityLicenseIdLicenseIdMap.containsKey(i) &&
                !licenseIdsToComplete.contains(ctRmeAssociatedEntityLicenseIdLicenseIdMap.get(i))) {
                licenseIdsWithoutAssoc.add(ctRmeAssociatedEntityLicenseIdLicenseIdMap.get(i));
                continue;
            }
        }


        List<License__c> licensesToUpdate = new List<License__c>();
        for (Id licId : licenseIdsWithoutAssoc) {
            License__c l = new License__c();
            l.Id = licId;
            l.Status__c = 'RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due';
            licensesToUpdate.add(l);
        }

        if (!licenseIdsToComplete.isEmpty()) {
            List<Application__c> applicationsToUpdate = new List<Application__c>();
            //find applications to update
            List<Application__c> applications = [
                SELECT
                    Id,
                    LicensePeriodRNEW__c,
                    LicenseType__r.PreviousLicensePeriod__c
                FROM Application__c
                WHERE CurrentLicense__c IN :licenseIdsToComplete
                AND Type__c = 'RNEW - Renewal'
            ];

            for (Application__c a : applications) {
                if (a.LicensePeriodRNEW__c != a.LicenseType__r.PreviousLicensePeriod__c) {
                    continue;
                }

                a.Phase__c = 'H - License Generation';
                a.Status__c = 'HC - Application Completed';
                applicationsToUpdate.add(a);
            }

            Database.update(applicationsToUpdate, false);

            for (Id licId : licenseIdsToComplete) {
                License__c l = new License__c();
                l.Id = licId;
                l.Status__c = 'C - Current, Valid & In Good Standing';
                l.EffectiveExpireDate__c = licensesMap.get(licId).LicenseType__r.LicenseTypeExpireDate__c;
                licensesToUpdate.add(l);
            }
        }

        Database.update(licensesToUpdate, false);
    }

    public void finish(Database.BatchableContext bc) {
        BatchJobFinishNotification notification = new BatchJobFinishNotification('CT Entity/Sole/PRME Push Through');
        notification.sendEmail();
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String associatedLicenseEntitiesSubQuery = '(SELECT Id, EmployeeLicense__c, PositionStatus__c ' +
            'FROM AssociatedEmployee__r ' +
            'WHERE EmploymentStatus__c = \'Employed\' ' +
            'AND (EndDate__c = null OR EndDate__c > TODAY) ' +
            'AND (EmployeeLicenseStatus__c = \'C - Current, Valid & In Good Standing\' ' +
            'OR EmployeeLicenseStatus__c = \'R - Valid Thru Expiration Date, Subject To Renewal\') ' +
            'AND EmployeeActiveInactive__c= \'Active\') ';

        String associatedLicenseEmployeesSubQuery = '(SELECT Id, EntityLicense__c, PositionStatus__c ' +
            'FROM AssociatedEntities__r ' +
            'WHERE EmploymentStatus__c = \'Employed\'' +
            'AND (EndDate__c = null OR EndDate__c > TODAY) ' +
            'AND (EntityLicenseStatus__c = \'C - Current, Valid & In Good Standing\' ' +
            'OR EntityLicenseStatus__c = \'R - Valid Thru Expiration Date, Subject To Renewal\') ' +
            'AND EntityActiveInactive__c = \'Active\') ';

        return Database.getQueryLocator('SELECT Id, Name, ' +
            'NumberofActiveEmployees__c, ' +
            'LicenseType__r.NextLicensePeriodExpireDate__c, ' +
            'LicenseType__r.LicenseTypeExpireDate__c, ' +
            'LicenseTypeName__c, ' +
            associatedLicenseEmployeesSubQuery + ', ' +
            associatedLicenseEntitiesSubQuery +
            'FROM License__c ' +
            'WHERE LicenseTypeName__c IN :licenseTypeFilter ' +
            'AND Status__c = \'R - Valid Thru Expiration Date, Subject To Renewal\'' +
            'AND ThisLicenseRenewed__c = true');
    }

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new CtEntitySolePrmePushThroughBatch());
    }
}