force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Select the Type of License you are applying for:</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Classifications</relationshipLabel>
    <relationshipName>Classifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/recordTypes/PVL.recordType-meta.xml
<RecordType>
    <fullName>PVL</fullName>
    <active>true</active>
    <label>PVL</label>
</RecordType>

force-app/main/default/classes/ApplicationRecordsCreationTest.cls
@isTest
public with sharing class ApplicationRecordsCreationTest {
    public static testMethod void testCheckDuplicateLicense() {
        Application__c record = TestDataFactory.createDummyApplication();
        insert record;
        ApplicationRecordsCreation.checkDuplicateLicense(JSON.serialize(record), 'WizardMatchingRecords');
    }
    public static testMethod void testCreateApplicationRecord() {
        Classification__c classification = TestDataFactory.createClasifications();
        Application__c record = TestDataFactory.createDummyApplication();
        ApplicationRecordsCreation.createApplicationRecord(JSON.serialize(record), JSON.serialize(new List<Classification__c>{classification}));
    }
    public static testMethod void testgetRecordTypesBySobjectType() {
        insert TestDataFactory.createBusinessAccount();
        
        Classification__c classification = TestDataFactory.createClasifications();
        ApplicationrecordsCreation.getRecordTypesBySobjectType();
        Account record = [Select Id from Account];
        ApplicationrecordsCreation.getLicenseTypes(record.Id);
        
        
        ApplicationRecordsCreation.getClassifications(classification.LicenseType__c);
    }

    public static testMethod void testGetFieldSetByName() {
        ApplicationRecordsCreation.getFieldSetByName('WizardMatchingRecords');
        ApplicationRecordsCreation.getApplicationRecordTypes('PVL - ACU');
    }
    
}