force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/ApplicationClassifications__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application Classifications</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Application Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationClassifications__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.LicenseType__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.LicenseType__c</field>
            <operation>equals</operation>
            <valueField>Classification__c.LicenseType__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Application Classifications</relationshipLabel>
    <relationshipName>Application_Classifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ApplicationClassifications__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CW - Class Withdrawn by Applicant</fullName>
            </value>
            <value>
                <fullName>H - Class Deferred by Board</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>NE - No Exam Required--Class to be Licensed</fullName>
            </value>
            <value>
                <fullName>P - Passed Exam--Class to be Licensed</fullName>
            </value>
            <value>
                <fullName>U - Class No Longer Needed Due To Upgrade To Higher Class</fullName>
            </value>
            <value>
                <fullName>W - Awaiting Approval/Exam</fullName>
            </value>
            <value>
                <fullName>NA - No Application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061219 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseClassification__c/LicenseClassification__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Classification</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>License Classifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseClassification__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>License Classifications</relationshipLabel>
    <relationshipName>LicenseClassifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LicenseClassification__c/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The date the Classification was added to the License</inlineHelpText>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LicenseClassification__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>License Classifications</relationshipLabel>
    <relationshipName>LicenseClassifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ApplicationClassificationsDomain.cls
/*
* ─────────────────────────────────────────────────────────
* Used for the single unit of  logic around 
* ApplicationClassifications records
* ─────────────────────────────────────────────────────────
* PacPoint-AZ140619 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Alvin Zhou - PacificPointCorp 
* @created      2019-06-14
* ───────────────────────────────────────────────────────────
* Changes
*
*
* ───────────────────────────────────────────────────────────
*/
public class ApplicationClassificationsDomain extends SObjectDomain {
    public ApplicationClassificationsDomain(List<ApplicationClassifications__c> applicationClassifications){
        super(applicationClassifications);
    }

    // Used to Convert to license classification List from Application Classifications
    // Used by 
    public List<LicenseClassification__c> convertToLicenseClassifications(License__c license) {
        List<LicenseClassification__c> licenseClassifications = new List<LicenseClassification__c>();
        for(SObject record: records) {
            ApplicationClassifications__c appClassification = (ApplicationClassifications__c) record;
            LicenseClassification__c licenseClassificationRecord = new LicenseClassification__c();
            licenseClassificationRecord.License__c = license.Id;
            licenseClassificationRecord.Classification__c = appClassification.Classification__c;
            licenseClassificationRecord.EffectiveStartDate__c = appClassification.EffectiveStartDate__c;
            licenseClassificationRecord.Status__c = 'C - CURRENT, VALID & IN GOOD STANDING';
            licenseClassifications.add(licenseClassificationRecord);
        }
        return licenseClassifications;
    }
    public Map<String, Set<String>> getAppClassificationMap(){
        Map<String, Set<String>> appClassificationIds = new Map<String, Set<String>>();
        for(SObject record: records) {
            ApplicationClassifications__c appClassification = (ApplicationClassifications__c) record;
            Set<String> classificationIds = appClassificationIds.get(appClassification.Application__c);
            if(classificationIds == null ) {
                classificationIds = new Set<String>();
            }
            classificationIds.add(appClassification.Classification__c);
            appClassificationIds.put(appClassification.Application__c, classificationIds);
        }
        return appClassificationIds;
    }

    public Map<String, List<ApplicationClassifications__c>> getAppClassifications(){
        Map<String, List<ApplicationClassifications__c>> appClassifications = new Map<String, List<ApplicationClassifications__c>>();
        for(SObject record: records) {
            ApplicationClassifications__c appClassification = (ApplicationClassifications__c) record;
            List<ApplicationClassifications__c> classifications = appClassifications.get(appClassification.Application__c);
            if(classifications == null ) {
                classifications = new List<ApplicationClassifications__c>();
            }
            classifications.add(appClassification);
            appClassifications.put(appClassification.Application__c, classifications);
        }
        return appClassifications;
    }

    public Map<String, List<Classification__c>> getClassifications(){
        Map<String, List<Classification__c>> appClassifications = new Map<String, List<Classification__c>>();
        for(SObject record: records) {
            ApplicationClassifications__c appClassification = (ApplicationClassifications__c) record;
            List<Classification__c> classifications = appClassifications.get(appClassification.Application__c);
            if(classifications == null ) {
                classifications = new List<Classification__c>();
            }
            classifications.add(appClassification.Classification__r);
            appClassifications.put(appClassification.Application__c, classifications);
        }
        return appClassifications;
    }
}