force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A - Application Received</fullName>
                <default>true</default>
                <label>A - Application Received</label>
            </value>
            <value>
                <fullName>E - Executive Officer Review</fullName>
            </value>
            <value>
                <fullName>B - Board Review</fullName>
            </value>
            <value>
                <fullName>C - Consultant Review</fullName>
            </value>
            <value>
                <fullName>X - Exam Phase</fullName>
            </value>
            <value>
                <fullName>O - 2nd Board Review - Oral Interview</fullName>
            </value>
            <value>
                <fullName>D - Dependency Review</fullName>
            </value>
            <value>
                <fullName>L - License Review</fullName>
            </value>
            <value>
                <fullName>H - License Generation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AP - Application Pending Submittal by Applicant/Licensee</fullName>
            </value>
            <value>
                <fullName>A0 - Flag Incoming Application</fullName>
            </value>
            <value>
                <fullName>A1 - Application Submitted, Awaiting Review</fullName>
                <default>true</default>
                <label>A1 - Application Submitted, Awaiting Review</label>
            </value>
            <value>
                <fullName>A2 - Deficient, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A3 - Deficiency Notice Sent</fullName>
            </value>
            <value>
                <fullName>A4 - Rejected, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>A5 - Rejected, Notice Sent</fullName>
            </value>
            <value>
                <fullName>A6 - Flagged by Tax; Renewal Deficiency Notice Sent.</fullName>
            </value>
            <value>
                <fullName>A9 - Past Time Limit To Respond To Deficiency</fullName>
            </value>
            <value>
                <fullName>AW - Application Withdrawal</fullName>
            </value>
            <value>
                <fullName>B1 - To Board Awaiting Review</fullName>
            </value>
            <value>
                <fullName>B6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>B7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>BH - Board Deferral</fullName>
            </value>
            <value>
                <fullName>BW - Board Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>C1 - To Board, Awaiting Review</fullName>
            </value>
            <value>
                <fullName>C6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>C7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>C9 - Past Time Limit To Apply For License</fullName>
            </value>
            <value>
                <fullName>D1 - Awaiting Dependency Review</fullName>
            </value>
            <value>
                <fullName>D2 - Continuing Education Missing</fullName>
            </value>
            <value>
                <fullName>DW - Dependency Review Phase Withdrawal</fullName>
            </value>
            <value>
                <fullName>E1 - To Executive Officer Awaiting Review</fullName>
            </value>
            <value>
                <fullName>E2 - Flagged By Tax; Renewal Appl. Sent To Exec</fullName>
            </value>
            <value>
                <fullName>E3 - Executive Officer Requests Add&apos;l Information</fullName>
            </value>
            <value>
                <fullName>E6 - Denied, Awaiting Notice</fullName>
            </value>
            <value>
                <fullName>E7 - Denial Letter Sent</fullName>
            </value>
            <value>
                <fullName>EW - Application Withdrawn After</fullName>
            </value>
            <value>
                <fullName>EY - Cease Processing</fullName>
            </value>
            <value>
                <fullName>F1 - To Executive Secretary Awaiting Review</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicense__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Entities</relationshipLabel>
    <relationshipName>AssociatedEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EmployeeLicenseStatus__c.field-meta.xml
<CustomField>
    <fullName>EmployeeLicenseStatus__c</fullName>
    <description>Pac Point-DN010820 - Created for PVL Sprint 3 Phase 1</description>
    <formula>TEXT(EmployeeLicense__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee License Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicenseStatus__c.field-meta.xml
<CustomField>
    <fullName>EntityLicenseStatus__c</fullName>
    <description>Pac Point-DN010820 - Created for PVL Sprint 3 Phase 1</description>
    <formula>TEXT(EntityLicense__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity License Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The application related to this license.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MotorVehicleIndustryRenewal.cls
public class MotorVehicleIndustryRenewal {
    private static Set<String> appIdsForRenew = new Set<String>();
    public static Map<String, Application__c> renewApps = new Map<String, Application__c>();
    public static Boolean forPushThrough = false;

    @InvocableMethod(
        label='Motor Vehicle Industry Renewal'
        description='Renew application with license types MVD, CS, MVB and MVD - Sole'
        category='License__c'
        )
    public static List <Results> execute (List<Input> inputs) {
        List<String> appIds = new List<String>();
        for(Input inp: inputs) {
            appIds.add(inp.record.Id);
        }
        List<Application__c> applications = ApplicationSelector.getApplicationsByIds(appIds);
        List<Application__c> appsForCustom = (new ApplicationDomain(applications)).filterApplicationsNotForInactiveRenew();
        appIdsForRenew.addAll((new ApplicationDomain(appsForCustom)).getIds());
        List<Application__c> mvdApps = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'MVD'});
        if(!mvdApps.isEmpty()) captureRenewApp(processMVDApps(mvdApps));

        List<Application__c> csApps = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'CS'});
        if(!csApps.isEmpty()) captureRenewApp(processCSApps(csApps));
        
        List<Application__c> mvbApps = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'MVB'});
        if(!mvbApps.isEmpty()) captureRenewApp(processMVBApps(mvbApps));

        List<Application__c> mvdSoleApp = (new ApplicationDomain(appsForCustom)).filterAppByLicenseTypes(new Set<String> {'MVD - Sole Proprietor'});
        if(!mvdSoleApp.isEmpty()) captureRenewApp(processMVDSoleProprietor(mvdSoleApp));

        (new ApplicationDomain(renewApps.values())).renewApplication();

        List<Application__c> d1Update = (new ApplicationDomain(appsForCustom)).filterRecordsByIds(renewApps.keySet());
        Map<String, Application__c> appsForUpdate = new Map<String, Application__c>();
        appsForUpdate.putAll(renewApps);

        for(Application__c record: d1Update) {
            if(!appsForUpdate.containsKey(record.Id)) {
                record.Status__c = 'D1 - Awaiting Dependency Review';
                record.Phase__c = 'D - Dependency Review';
                appsForUpdate.put(record.Id, record);
            }
        }
        List<License__c> renewLicenses = (new ApplicationDomain(appsForUpdate.values())).renewLicenses();
        
        
        // update applications
        Database.update(appsForUpdate.values(), false);

        // update licenses
        Database.update(renewLicenses, false);

        BarberingCosmetologyRenewal.checkToCreateLicenseHistory(appsForUpdate.values());

        List<Application__c> appsForInactive = (new ApplicationDomain(applications)).filterApplicationsForInactiveRenew();

        for(Application__c record: appsForInactive) {
            BarberingCosmetologyRenewal.lanchRenewingInactiveFlow(record);
        }

        List<Results> responseWrapper= new List<Results>();
        for(Input inp: inputs) {
            Results re = new Results();
            re.operationOutcome = 'Success';
            responseWrapper.add(re);
        }
        return responseWrapper;
    }

    public static List<Application__c> processMVDApps(List<Application__c> records) {
        List<String> licenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        System.debug('########licenseIds#size#####' + licenseIds.size());

        List<Application__c> renewalApplications = new List<Application__c>();
        List<AssociatedLicense__c> cAssociatedLicenses = AssociatedLicenseSelector.getPDGByEntity(licenseIds, new List<String>{'CS'}, ' and EmployeeLicenseStatus__c = \'C - Current, Valid & In Good Standing\'');
        List<String> ccsLicenseIds = new List<String>();
        if(forPushThrough)ccsLicenseIds.addAll((List<String>) new AssociatedLicenseDomain(cAssociatedLicenses).getFieldValues('EntityLicense__c'));
        renewalApplications.addAll(new ApplicationDomain(records).filterApplicationByLicenseIds(new Set<String>(ccsLicenseIds)));

        List<AssociatedLicense__c> associatedLicenses = AssociatedLicenseSelector.getPDGByEntity(licenseIds, new List<String>{'CS'}, '');
        System.debug('########associatedLicenses#size#####' + associatedLicenses.size());
        List<String> csLicenseIds = (List<String>) new AssociatedLicenseDomain(associatedLicenses).getFieldValues('EmployeeLicense__c');
        System.debug('########csLicenseIds#size#####' + csLicenseIds.size());
        List<Application__c> csRNApps = !forPushThrough ? ApplicationSelector.getRNApplicationsByLicenseIds(csLicenseIds) : ApplicationSelector.getPrevRNApplicationsByLicenseIds(csLicenseIds);
        System.debug('########csRNApps#size#####' + csRNApps.size());
        List<String> csRNLicenses = (List<String>)new ApplicationDomain(csRNApps).getFieldValues('CurrentLicense__c');
        System.debug('########csRNLicenses#size#####' + csRNLicenses.size());

        Set<String> mvdLicenseIdSet = new Set<String>();
        for(AssociatedLicense__c record: associatedLicenses) {
            if(
                csRNLicenses.contains(record.EmployeeLicense__c)
                && !ccsLicenseIds.contains(record.EntityLicense__c)
            ) {
                mvdLicenseIdSet.add(record.EntityLicense__c);
            }
        }
        System.debug('########mvdLicenseIdSet#size#####' + mvdLicenseIdSet.size());
        renewalApplications.addAll(new ApplicationDomain(records).filterApplicationByLicenseIds(mvdLicenseIdSet));
        System.debug('########renewalApplications#size#####' + renewalApplications.size());
        List<String> mvdRNLicenses = new List<String>();
        mvdRNLicenses.addAll(mvdLicenseIdSet);
        mvdRNLicenses.addAll(ccsLicenseIds);
        System.debug('####mvdRNLicenses#size####' + mvdRNLicenses.size());

        List<AssociatedLicense__c> mvbsAssociatedLicenses = AssociatedLicenseSelector.getPDGByEmployee(mvdRNLicenses, new List<String>{'MVB'}, '');
        System.debug('####mvbsAssociatedLicenses#size####' + mvbsAssociatedLicenses.size());
        List<String> mvbEntityLicenseIds = (List<String>) (new AssociatedLicenseDomain(mvbsAssociatedLicenses)).getFieldValues('EntityLicense__c');
        System.debug('####mvbEntityLicenseIds#size####' + mvbEntityLicenseIds.size());
        List<Application__c> mvbRenewalApplications = !forPushThrough ? ApplicationSelector.getRNApplicationsByLicenseIds(mvbEntityLicenseIds) : ApplicationSelector.getPrevRNApplicationsByLicenseIds(mvbEntityLicenseIds);
        System.debug('####mvbRenewalApplications#size####' + mvbRenewalApplications.size());
        renewalApplications.addAll(csRNApps);
        renewalApplications.addAll(mvbRenewalApplications);
        System.debug('####renewalApplications#size####' + renewalApplications.size());

        return renewalApplications;
    }

    public static List<Application__c> processCSApps(List<Application__c> records) {
        List<String> licenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> associatedLicenses = AssociatedLicenseSelector.getPDGByEmployee(licenseIds, new List<String>{'MVD', 'MVD - Sole Proprietor'}, '');
        
        List<String> rawMVDLicenseIds = (List<String>) new AssociatedLicenseDomain(associatedLicenses).getFieldValues('EntityLicense__c');
        List<Application__c> renewalApplications = !forPushThrough ? ApplicationSelector.getRNApplicationsByLicenseIds(rawMVDLicenseIds) : ApplicationSelector.getPrevRNApplicationsByLicenseIds(rawMVDLicenseIds);
        List<String> mvdLicenseIds = (List<String>) new ApplicationDomain(renewalApplications).getFieldValues('CurrentLicense__c');
        
        Set<String> licenseIdSet = new Set<String>();
        for(AssociatedLicense__c record: associatedLicenses) {
            if(mvdLicenseIds.contains(record.EntityLicense__c) || record.EntityLicenseStatus__c == 'C - Current, Valid & In Good Standing') {
                licenseIdSet.add(record.EmployeeLicense__c);
            }
        }

        List<Application__c> csApplications = (new ApplicationDomain(records)).filterApplicationByLicenseIds(licenseIdSet);
        
        List<AssociatedLicense__c>  mVBs = AssociatedLicenseSelector.getPDGByEmployee(mvdLicenseIds, new List<String> {'MVB'}, '');
        List<String> mVBIds = (List<String>) (new AssociatedLicenseDomain(mVBs)).getFieldValues('EntityLicense__c');
        List<Application__c> mVBApps = !forPushThrough ? ApplicationSelector.getRNApplicationsByLicenseIds(mVBIds) : ApplicationSelector.getPrevRNApplicationsByLicenseIds(mVBIds);

        renewalApplications.addAll(mVBApps);
        renewalApplications.addAll(csApplications);
        return renewalApplications;
    }
    
    public static List<Application__c> processMVBApps(List<Application__c> records) {
        List<String> licenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> associatedLicenses = AssociatedLicenseSelector.getPDGByEntity(licenseIds, new List<String>{'MVD', 'MVD - Sole Proprietor'}, ' and EmployeeLicenseStatus__c =\'C - Current, Valid & In Good Standing\' ');
        System.debug('####associatedLicenses#size####' + associatedLicenses.size());
        List<String> entityLicenseIds = (List<String>)new AssociatedLicenseDomain(associatedLicenses).getFieldValues('EntityLicense__c');
        System.debug('####entityLicenseIds#size####' + entityLicenseIds.size());
        Set<String> entityLicenseSet = new Set<String>();
        entityLicenseSet.addAll(entityLicenseIds);

        
        List<Application__c> renewalApplications = (new ApplicationDomain(records)).filterApplicationByLicenseIds(entityLicenseSet);
        System.debug('####renewalApplications#size####' + renewalApplications.size());
        return renewalApplications;
    }

    public static List<Application__c> processMVDSoleProprietor(List<Application__c> records) {
        List<String> licenseIds = (List<String>)(new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> associatedLicesnes = AssociatedLicenseSelector.getPDGByEntity(licenseIds, new List<String>{'CS'}, '');
        List<String> employeeLicenseIds = (List<String>)(new AssociatedLicenseDomain(associatedLicesnes)).getFieldValues('EmployeeLicense__c');
        List<Application__c> csApps = !forPushThrough ? ApplicationSelector.getRNApplicationsByLicenseIds(employeeLicenseIds) : ApplicationSelector.getPrevRNApplicationsByLicenseIds(employeeLicenseIds);
        List<Application__c> csD1Apps = !forPushThrough ? ApplicationSelector.getD1RNApplicationsByLicenseIds(employeeLicenseIds) : ApplicationSelector.getPrevD1RNApplicationsByLicenseIds(employeeLicenseIds);
   
        List<Application__c> renewalApplications = new ApplicationDomain(records).filterApplicationByLicenseIds(new Set<String>(licenseIds));
        renewalApplications.addAll(csD1Apps);

        if(!csD1Apps.isEmpty() || Test.isRunningTest()){            
            List<AssociatedLicense__c> mvbAssociatedLicenses = AssociatedLicenseSelector.getPDGByEmployee(licenseIds, new List<String>{'MVB'}, '');
            List<String> mvbLicenseIds = (List<String>)new AssociatedLicenseDomain(mvbAssociatedLicenses).getFieldValues('EntityLicense__c');
            List<Application__c> mvbRNApps = !forPushThrough ? ApplicationSelector.getRNApplicationsByLicenseIds(mvbLicenseIds) : ApplicationSelector.getPrevRNApplicationsByLicenseIds(mvbLicenseIds); 
            renewalApplications.addAll(mvbRNApps);
        }

        return renewalApplications;
    }

    public static void captureRenewApp(List<Application__c> records) {
        for(Application__c app: records) {
            if(app.Status__c != 'HC - Application Completed'
                 || (appIdsForRenew.contains(app.Id) && app.Status__c == 'HC - Application Completed')) {
                renewApps.put(app.Id, app);
            }
        }
    }

    public class Input {
        @InvocableVariable(label='Application Record for Input' description='Input Application' required=true)
        public Application__c record;
    }
    public class Results {
        @InvocableVariable(label='Records for Output' description='Output Renewals' required=true)
        public String operationOutcome;
    }
}