force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CurrentLicense__c.field-meta.xml
<CustomField>
    <fullName>CurrentLicense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071519- Created for PVL phase 1</description>
    <inlineHelpText>When a License is generated for this Application, the License Number will show up here.</inlineHelpText>
    <label>Current License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Applications (Current License)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssociatedLicense__c/AssociatedLicense__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Associated License</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Associated License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssociatedLicense__c/fields/EntityLicense__c.field-meta.xml
<CustomField>
    <fullName>EntityLicense__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Entity License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Associated Employees</relationshipLabel>
    <relationshipName>AssociatedEmployee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountancyRenewalPushThru.cls
global class AccountancyRenewalPushThru extends ApplicationRenewalPushThru {
    global AccountancyRenewalPushThru() {
        super(new List<String> {'FPTP', 'FPTP - Sole Proprietor'}, new List<String> {'R - Valid Thru Expiration Date, Subject To Renewal'});
    }

    global override void processRecords(List<Application__c> records) {
        List<String> licenseIds = (List<String>) (new ApplicationDomain(records)).getFieldValues('CurrentLicense__c');
        List<AssociatedLicense__c> associatedLicenses = AssociatedLicenseSelector.getCPAEmployeeAssociatedLicenses(licenseIds);
        List<String> entityLicenseIds = (List<String>) (new AssociatedLicenseDomain(associatedLicenses)).getFieldValues('EntityLicense__c');
        Set<String> entityLicenseIdsSet = new Set<String>(entityLicenseIds);
        List<Application__c> recordsForUpdate = (new ApplicationDomain(records)).filterApplicationByLicenseIds(entityLicenseIdsSet);
        this.appMap = new Map<Id, Application__c> (recordsForUpdate);
    }
    
}