force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationRequirement__c/ApplicationRequirement__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application Requirement</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Application Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationRequirement__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Requirements</relationshipLabel>
    <relationshipName>Application_Deficiencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/IsDeficient__c.field-meta.xml
<CustomField>
    <fullName>IsDeficient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>Is the Applicant Deficient on this?  Is so, please check the box.</inlineHelpText>
    <label>Is Deficient?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/ParentApplicationRequirement__c.field-meta.xml
<CustomField>
    <fullName>ParentApplicationRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Parent Application Requirement</label>
    <referenceTo>ApplicationRequirement__c</referenceTo>
    <relationshipLabel>Application Requirements</relationshipLabel>
    <relationshipName>ApplicationRequirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV081919 - Created for PVL phase 1</description>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>Application Requirements</relationshipLabel>
    <relationshipName>Application_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/RequirementLongDescription__c.field-meta.xml
<CustomField>
    <fullName>RequirementLongDescription__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>This is the text that will show up on the deficiency letter.  you can edit and save the text if needed</inlineHelpText>
    <label>Requirement Long Description</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApplicationRequirement__c/fields/RequirementShortDescription__c.field-meta.xml
<CustomField>
    <fullName>RequirementShortDescription__c</fullName>
    <description>PacPoint-MV010419 - Created for PVL phase 1</description>
    <label>Requirement Short Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Requirements__c/Requirements__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC072419- Created for PVL phase 1</description>
    <label>Requirement</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirements__c/fields/ParentRequirement__c.field-meta.xml
<CustomField>
    <fullName>ParentRequirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC072419- Created for PVL phase 1</description>
    <label>Parent Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requirements__c/fields/RequirementLongDescription__c.field-meta.xml
<CustomField>
    <fullName>RequirementLongDescription__c</fullName>
    <description>PacPoint-IC072419- Created for PVL phase 1</description>
    <label>Requirement Long Description</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Requirements__c/fields/RequirementShortDescription__c.field-meta.xml
<CustomField>
    <fullName>RequirementShortDescription__c</fullName>
    <description>PacPoint-MV081919 - Created for PVL phase 1</description>
    <label>Requirement Short Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RequirementsDomain.cls
/*
* ─────────────────────────────────────────────────────────
* class for manage unit record logic for the Requirement
* ─────────────────────────────────────────────────────────
* PacPoint-AZ210919 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Alvin Zhou - PacificPointCorp 
* @created      2019-09-21
* ───────────────────────────────────────────────────────────
*
* ───────────────────────────────────────────────────────────
*/
public class RequirementsDomain extends SObjectDomain {
    public RequirementsDomain(List<Requirements__c> requirements) {
        super(requirements);
    }

    // 00003563 used to generate Parent Requirement Id => Requirements
    public Map<String, List<Requirements__c>> getChildren() {
        Map<String, List<Requirements__c>> children = new Map<String, List<Requirements__c>>();
        for(Sobject record: records) {
            Requirements__c requirement = (Requirements__c) record;
            if(requirement.ParentRequirement__c == null ) {
                continue;
            }
            List<Requirements__c> requirements = new List<Requirements__c>();
            if(children.containsKey(requirement.ParentRequirement__c)) {
                requirements = children.get(requirement.ParentRequirement__c);
            }
            requirements.add(requirement);
            children.put(requirement.ParentRequirement__c, requirements);
        }
        return children;
    }
    // 0003563 used to generate Application Requirement records
    public List<ApplicationRequirement__c> getChildrenApplicationRequirements(ApplicationRequirement__c parentRecord) {
        List<ApplicationRequirement__c> appReqlist = new List<ApplicationRequirement__c>();
        for(SObject record: records) {
            Requirements__c childRecord = (Requirements__c)record;
            ApplicationRequirement__c applicationRequirement = new ApplicationRequirement__c();
            applicationRequirement.Application__c = parentRecord.Application__c;
            applicationRequirement.ParentApplicationRequirement__c = parentRecord.Id;
            // Changes to move License Type Requirement Matching to Requirements
            // Case: 00003563
            applicationRequirement.Requirement__c = childRecord.Id;
            applicationRequirement.RequirementLongDescription__c 
                = childRecord.RequirementLongDescription__c;
            applicationRequirement.RequirementShortDescription__c 
                = childRecord.RequirementShortDescription__c;
            applicationRequirement.IsDeficient__c = false;
            appReqlist.add(applicationRequirement);
        }
        return appReqlist;
    }
}