force-app/main/default/objects/DocGeneratorSettings__c/DocGeneratorSettings__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT10179 - Created for PVL phase 1</description>
    <label>Doc Generator Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doc Generator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocGeneratorSettings__c/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>PacPoint-MV101719 - Created for PVL phase 1</description>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Word</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/FileEngines__c.field-meta.xml
<CustomField>
    <fullName>FileEngines__c</fullName>
    <description>PacPoint-AZ011119 - Created for PVL phase 1. To be used to populate the name of  the Doc generator Settings that has the document we want to create.</description>
    <label>File Engines</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/License__c/fields/GenerateEntityLosesRMENotification__c.field-meta.xml
<CustomField>
    <fullName>GenerateEntityLosesRMENotification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-FT031420 - Created for PVL phase 1</description>
    <label>Generate Entity Loses RME Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License__c/fields/GenerateRMELosesEntityNotification__c.field-meta.xml
<CustomField>
    <fullName>GenerateRMELosesEntityNotification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-FT031420 - Created for PVL phase 1</description>
    <label>Generate RME Loses Entity Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Licensee__c.field-meta.xml
<CustomField>
    <fullName>Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The account that this license belongs too.</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The type of license</inlineHelpText>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>The current status of the license.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C - Current, Valid &amp; In Good Standing</fullName>
            </value>
            <value>
                <fullName>CM - Current, Valid &amp; In Good Standing/Maint. Requirement Due</fullName>
            </value>
            <value>
                <fullName>CP - Current Pending</fullName>
            </value>
            <value>
                <fullName>DA - Delinquent Restoration Subject To Approval/Maint. May Be Due</fullName>
            </value>
            <value>
                <fullName>D - Forfeited; Needs to Restore</fullName>
            </value>
            <value>
                <fullName>DM - Forfeited/Maintenance Requirement Due</fullName>
            </value>
            <value>
                <fullName>DN - Downgraded License Type</fullName>
            </value>
            <value>
                <fullName>EX - Exempt From CMA Registration</fullName>
            </value>
            <value>
                <fullName>FA - Forfeited, Restoration Subject To Approval and Maybe Maintenance/Disciplinary/Conditional Regent Due</fullName>
            </value>
            <value>
                <fullName>FM - Terminated/Maintenance Requirement Due; Needs To Reapply</fullName>
            </value>
            <value>
                <fullName>F - Terminated; Needs to Reapply</fullName>
            </value>
            <value>
                <fullName>HC - Application Completed</fullName>
            </value>
            <value>
                <fullName>H - History</fullName>
            </value>
            <value>
                <fullName>LP - Law Repealed/Changed</fullName>
            </value>
            <value>
                <fullName>NL - No License</fullName>
            </value>
            <value>
                <fullName>NS - No Status Or Status Not Applicable</fullName>
            </value>
            <value>
                <fullName>RM - Valid Thru Exp Date, Subject To Renwl/Maint Reqmt Due</fullName>
            </value>
            <value>
                <fullName>R - Valid Thru Expiration Date, Subject To Renewal</fullName>
            </value>
            <value>
                <fullName>SC - Sole Owner License Cancelled, Corporation/Partnership License Issued</fullName>
            </value>
            <value>
                <fullName>TC - Voluntary Request To Cancel/Terminate</fullName>
            </value>
            <value>
                <fullName>TD - Deceased</fullName>
            </value>
            <value>
                <fullName>TE - &quot;Employer Releases An Employee&quot; Or &quot;Temporary/Limited Status Has Expired&quot;</fullName>
            </value>
            <value>
                <fullName>TF - Forfeited Due To Loss Of Principal Or Failure To Maintain Any Other License Requirements</fullName>
            </value>
            <value>
                <fullName>TI - Inactive</fullName>
            </value>
            <value>
                <fullName>TN - Licensing No Longer Required</fullName>
            </value>
            <value>
                <fullName>TR - Rescinded License</fullName>
            </value>
            <value>
                <fullName>TS - Forfeited Due To Nonpayment Of CT Special Assessment</fullName>
            </value>
            <value>
                <fullName>TX - Terminated And Refunded</fullName>
            </value>
            <value>
                <fullName>TZ - Revocation Vacated</fullName>
            </value>
            <value>
                <fullName>UP - Upgraded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License__c/fields/StatusDuetoLossofDependent__c.field-meta.xml
<CustomField>
    <fullName>StatusDuetoLossofDependent__c</fullName>
    <formula>Text(LicenseType__r.StatusDuetoLossofDependent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Due to Loss of Dependent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-KN111419-Created for PVL Sprint 2 Phase 1</description>
    <inlineHelpText>Populate this field when there is a dependency on this License Type.</inlineHelpText>
    <label>Entity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/EntityLosesRMENotification__c.field-meta.xml
<CustomField>
    <fullName>EntityLosesRMENotification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-KN03162020-Created for PVL Phase 1 Sprint 3</description>
    <label>Entity Loses RME Notification</label>
    <referenceTo>DocGeneratorSettings__c</referenceTo>
    <relationshipLabel>License Types (Entity Loses RME Notification)</relationshipLabel>
    <relationshipName>License_TypeskdLc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/RMELosesEntityNotification__c.field-meta.xml
<CustomField>
    <fullName>RMELosesEntityNotification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-KN03162020-Created for PVL Phase 1 Sprint 3</description>
    <label>RME Loses Entity Notification</label>
    <referenceTo>DocGeneratorSettings__c</referenceTo>
    <relationshipLabel>License Types (RME Loses Entity Notification)</relationshipLabel>
    <relationshipName>License_TypeskdLm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/StartofRenewalPeriod__c.field-meta.xml
<CustomField>
    <fullName>StartofRenewalPeriod__c</fullName>
    <description>PacPoint-IC071619- Created for PVL phase 1</description>
    <label>Start of Renewal Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-MV061119 - Created for PVL phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/StatusDuetoLossofDependent__c.field-meta.xml
<CustomField>
    <fullName>StatusDuetoLossofDependent__c</fullName>
    <description>PacPoint-FT110519- Created for PVL phase 1</description>
    <label>Status Due to Loss of Dependent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LicenseStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/StatusDuetoNonRenewal__c.field-meta.xml
<CustomField>
    <fullName>StatusDuetoNonRenewal__c</fullName>
    <description>PacPoint-FT110519- Created for PVL phase 1</description>
    <label>Status Due to Non-Renewal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LicenseStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/DocGeneratorSettings__c.field-meta.xml
<CustomField>
    <fullName>DocGeneratorSettings__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Doc Generator Settings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>License</label>
    <referenceTo>License__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PACIFICPOINT-AZ20200902 case 00009192</description>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentGeneratorProcessBatchTest.cls
@isTest
public with sharing class DocumentGeneratorProcessBatchTest {
    @TestSetup
    static void makeData(){
        Date todaysDate = Date.today();

		Account dummyAccount = new Account();
		dummyAccount.Name = 'Account Name';
        insert dummyAccount;
        
        DocGeneratorSettings__c  setting = new DocGeneratorSettings__c ();
        setting.Name = 'test';
        setting.DocumentType__c = 'Word';
        insert setting;
        LicenseType__c dummyLT = new LicenseType__c();
		dummyLT.StartofRenewalPeriod__c = todaysDate;
        dummyLT.StatusDuetoNonRenewal__c = 'D - Forfeited; Needs to Restore';
        dummyLT.StatusDuetoLossofDependent__c = 'CM - Current, Valid & In Good Standing/Maint. Requirement Due';
         dummyLT.Entity__c = true;
         dummyLT.RMELosesEntityNotification__c  = setting.Id;
         dummyLt.EntityLosesRMENotification__c  = setting.Id;
		dummyLT.Status__c = 'Active';
		dummyLT.Name = 'Dummy License Type';
		insert dummyLT;
        
        
        License__c dummyEmployeeLicense = new License__c();
		dummyEmployeeLicense.Status__c = 'C - Current, Valid & In Good Standing';
        dummyEmployeeLicense.GenerateRMELosesEntityNotification__c = true;
		dummyEmployeeLicense.LicenseType__c = dummyLT.Id;
		dummyEmployeeLicense.Licensee__c = dummyAccount.Id;
        insert dummyEmployeeLicense;
        License__c dummyEmployeeLicense2 = new License__c();
		dummyEmployeeLicense2.Status__c = 'C - Current, Valid & In Good Standing';
        dummyEmployeeLicense2.GenerateEntityLosesRMENotification__c = true;
		dummyEmployeeLicense2.LicenseType__c = dummyLT.Id;
		dummyEmployeeLicense2.Licensee__c = dummyAccount.Id;
        insert dummyEmployeeLicense2;
        Notification__c record = new Notification__c();
        record.RecordId__c = dummyLT.Id;
        insert record;
    }
    public static testMethod void testGeneration() {
        
        LicenseType__c licenseType = [Select Id from LicenseType__c limit 1];
        Notification__c  notification = [Select Id from Notification__c limit 1];
        DocGeneratorSettings__c docGeneratorSetting = [Select Id, Name from DocGeneratorSettings__c limit 1];
        Database.executeBatch(new DocumentGeneratorProcessBatch(licenseType.Id, notification.Id, docGeneratorSetting.Name));
        DocumentGeneratorProcessBatch batch = new DocumentGeneratorProcessBatch(licenseType.Id, notification.Id, docGeneratorSetting.Name, true);
        List<License__c> licenses = [Select Id, FileEngines__c from License__c ];
        batch.execute(null, licenses);


    }
    
}