force-app/main/default/objects/DocGeneratorSettings__c/DocGeneratorSettings__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT10179 - Created for PVL phase 1</description>
    <label>Doc Generator Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doc Generator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocGeneratorSettings__c/fields/DocumentTemplateName__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateName__c</fullName>
    <description>PacPoint-MV101719 - Created for PVL phase 1</description>
    <label>Document Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/DocGeneratorSettings__c.field-meta.xml
<CustomField>
    <fullName>DocGeneratorSettings__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Doc Generator Settings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/DocumentTemplateName__c.field-meta.xml
<CustomField>
    <fullName>DocumentTemplateName__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Document Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/SendtoPrinter__c.field-meta.xml
<CustomField>
    <fullName>SendtoPrinter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PacPoint-KN07132020 - Created for PVL Phase 1 Sprint 6</description>
    <label>Send to Printer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint: AZ00008158PVL2</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendLetterToPrinterBatchJobTest.cls
@isTest
public with sharing class SendLetterToPrinterBatchJobTest {
    public static testMethod void testBatch() {
        Notification__c record = new Notification__c();
        record.Status__c = 'Scheduled';
        record.SendtoPrinter__c = true;
        record.Scheduled__c = true;
        record.DocGeneratorSettings__c = 'Test Doc';
        record.DocumentTemplateName__c = 'test Doc';

        insert record;
        //Create File Attached
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.VersionData = Blob.valueOf('test');
        cv.Title = record.DocumentTemplateName__c + '.txt';
        cv.PathOnClient = record.DocumentTemplateName__c + '.txt';
        insert cv;
                    
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.LinkedEntityId = record.Id;
        cdl.ShareType = 'I';
        insert cdl;
        SendLetterToPrinterBatchJob job = new SendLetterToPrinterBatchJob();
        Database.executeBatch(job);
        List<Notification__c> records = NotificationSelector.getNotifications(record.Id);
        List<Id> contentDocumentIds = new List<Id>();
        contentDocumentIds.add(cdl.ContentDocumentId);
        job.execute(null, records);
        job.sendEmails(contentDocumentIds);
        SendLetterToPrinterBatchJob.ContentDocumentAsAttachement(contentDocumentIds);
    }
}