force-app/main/default/objects/breg_Fee__c/breg_Fee__c.object-meta.xml
<CustomObject>
    <description>Aalta BREG-933</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Fee__c/fields/breg_Form_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Form_Code__c</fullName>
    <label>Form Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CashierCode__c/CashierCode__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <nameField>
        <label>Cashier Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cashier Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CashierCode__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <description>Aalta BREG-424</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Form Fees</fullName>
            </value>
            <value>
                <fullName>Expedite Fees</fullName>
            </value>
            <value>
                <fullName>Archive Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Cashier Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-FT053018 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FeeCode__c.field-meta.xml
<CustomField>
    <fullName>FeeCode__c</fullName>
    <description>PacPoint-FT082218 - Created for phase 1

Code used by BREG to associate Cashier Codes for transaction line items.</description>
    <label>Fee Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CashierCode__c/fields/FormDescription__c.field-meta.xml
<CustomField>
    <fullName>FormDescription__c</fullName>
    <label>Form Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/breg_Entity__c.field-meta.xml
<CustomField>
    <fullName>breg_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta BREG-4059</description>
    <label>Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Entity)</relationshipLabel>
    <relationshipName>breg_PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BREG</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>DFI</fullName>
            </value>
            <value>
                <fullName>HPEAP</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>OCP</fullName>
            </value>
            <value>
                <fullName>OAH</fullName>
            </value>
            <value>
                <fullName>PUC</fullName>
            </value>
            <value>
                <fullName>PVL</fullName>
            </value>
            <value>
                <fullName>RICO</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>PVL Real Estate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/AmountOverride__c.field-meta.xml
<CustomField>
    <fullName>AmountOverride__c</fullName>
    <label>Amount Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/breg_Fee__c.field-meta.xml
<CustomField>
    <fullName>breg_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee</label>
    <referenceTo>breg_Fee__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/breg_Type__c.field-meta.xml
<CustomField>
    <fullName>breg_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NBR Form</fullName>
            </value>
            <value>
                <fullName>TNTMSM Form</fullName>
            </value>
            <value>
                <fullName>Change Form</fullName>
            </value>
            <value>
                <fullName>Annual Form</fullName>
            </value>
            <value>
                <fullName>Name Reservation Form</fullName>
            </value>
            <value>
                <fullName>CRA Registration Form</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Entity List</fullName>
            </value>
            <value>
                <fullName>Agent Search List</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Withdrawal Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/breg_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>breg_Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/CashierCode__c.field-meta.xml
<CustomField>
    <fullName>CashierCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Cashier Code</label>
    <referenceTo>CashierCode__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>TEXT( CashierCode__r.Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Form_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD-1</fullName>
    </customValue>
    <customValue>
        <fullName>ADD</fullName>
    </customValue>
    <customValue>
        <fullName>ADD-MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>ADD-TNTMSM</fullName>
    </customValue>
    <customValue>
        <fullName>AG-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-AG-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-CONS-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-DC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-DNP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FLLC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FLLP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-FLP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-GP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-LLC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-LLP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-LP-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-PC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-SBC-1</fullName>
    </customValue>
    <customValue>
        <fullName>ANN-SOLE-1</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CONS-1</fullName>
    </customValue>
    <customValue>
        <fullName>DC-1</fullName>
    </customValue>
    <customValue>
        <fullName>DC-10</fullName>
    </customValue>
    <customValue>
        <fullName>DC-12</fullName>
    </customValue>
    <customValue>
        <fullName>DC-13</fullName>
    </customValue>
    <customValue>
        <fullName>DC-2</fullName>
    </customValue>
    <customValue>
        <fullName>DC-3</fullName>
    </customValue>
    <customValue>
        <fullName>DC-4</fullName>
    </customValue>
    <customValue>
        <fullName>DC-5</fullName>
    </customValue>
    <masterLabel>Form Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BREGCreateTransaction.cls
public without sharing class BREGCreateTransaction {
    private static Date getOrgDateByUserTimezone() {
        Datetime nowUtc = System.now();
        TimeZone tz = UserInfo.getTimeZone();
        Integer offset = tz.getOffset(nowUtc) / 1000;
        Datetime orgNow = nowUtc.addSeconds(offset);
        return orgNow.date();
    }

    @AuraEnabled
    public static TransactionWrapper initTransaction(Id recordId) {
        /*User cUser = [SELECT Division__c FROM User WHERE Id = :UserInfo.getUserId()];
        string division = cUser.Division__c;
        if (division != null && division.contains(';')) {
            division = division.split(';')[0];
        }*/
        TransactionWrapper toReturn = new TransactionWrapper(recordId /*, division*/);

        return toReturn;
    }

    @AuraEnabled
    public static List<PicklistVal> getSelectOptions(string objName, string fieldName) {
        List<PicklistVal> picklistValues = new List<PicklistVal>();
        SObjectType objectType = Schema.getGlobalDescribe().get(objName);
        List<Schema.PicklistEntry> pick_list_values = objectType.getDescribe().fields.getMap().get(fieldName).getDescribe().getPickListValues();
        for (Schema.PicklistEntry aPickListValue : pick_list_values) {
            picklistValues.add(new PicklistVal(aPickListValue));
        }
        return picklistValues;
    }

    @AuraEnabled
    public static Id saveTransaction(Transaction__c trns, string lines) {
        upsert trns;
        trns = [SELECT Id, breg_Case__r.breg_Form_Code__c FROM Transaction__c WHERE Id = :trns.Id];
        Map<Id, TransactionLine__c> trLinesMap = new Map<Id, TransactionLine__c>([SELECT Id FROM TransactionLine__c WHERE Transaction__c = :trns.Id]);
        List<TransactionLine__c> xlines = (List<TransactionLine__c>) JSON.deserialize(lines, List<TransactionLine__c>.class);
        List<TransactionLine__c> trlinesToInsert = new List<TransactionLine__c>();
        String formCategory = BREGUtils.checkFormCategory(trns.breg_Case__r?.breg_Form_Code__c);
        String transactionType;
        if (String.isNotBlank(formCategory)) {
            transactionType = formCategory + ' Form';
        }
        for (TransactionLine__c line : xlines) {
            if (!trLinesMap.containsKey(line.Id)) {
                System.debug('Amount ====> ' + line.Amount__c);
                System.debug('Amount Override ====> ' + line.AmountOverride__c);
                if (line.AmountOverride__c != null && line.AmountOverride__c != 0) {
                    line.Amount__c = line.AmountOverride__c;
                    line.AmountOverride__c = null;
                }
                line.breg_Unit_Price__c = line.Amount__c;
                line.breg_Case__c = trns.breg_Case__c;
                line.breg_Type__c = transactionType;
                line.Transaction__c = trns.Id;
                trlinesToInsert.add(line);
            }
        }

        Set<Id> cashierCodeIds = new Set<Id>();
        for (TransactionLine__c lineToInsert : trlinesToInsert) {
            if (lineToInsert.breg_Fee__c == null && lineToInsert.CashierCode__c != null) {
                cashierCodeIds.add(lineToInsert.CashierCode__c);
            }
        }

        if (!cashierCodeIds.isEmpty()) {
            Map<Id, Id> feeIdByCashierCodeId = BREGPaymentController.getCashierCodeIdToFeeId(cashierCodeIds);

            for (TransactionLine__c lineToInsert : trlinesToInsert) {
                if (lineToInsert.breg_Fee__c == null && lineToInsert.CashierCode__c != null) {
                    if (feeIdByCashierCodeId.containsKey(lineToInsert.CashierCode__c)) {
                        lineToInsert.breg_Fee__c = feeIdByCashierCodeId.get(lineToInsert.CashierCode__c);
                    }
                }
            }
        }

        insert trlinesToInsert;
        List<TransactionLine__c> TrLines = [
            SELECT Id, CashierCode__c, CashierCode__r.Division__c, CashierCode__r.Name, Amount__c
            FROM TransactionLine__c
            WHERE Transaction__c = :trns.Id
        ];
        for (TransactionLine__c tl : TrLines) {
            trns.Division__c = tl.CashierCode__r.Division__c;
            tl.Description__c = tl.CashierCode__r.Name;
            System.debug('Amount ====> ' + tl.Amount__c);
        }
        update trns;
        update TrLines;
        return trns.Id;
    }

    @AuraEnabled
    public static List<CashierCode__c> getCashierCodes() {
        User myUser = [SELECT Division__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<string> divisions = new List<string>();
        if (myuser.Division__c != null)
            divisions = myUser.Division__c.split(';');
        return [
            SELECT Id, Name, FeeCode__c, Amount__c, FormDescription__c, Description__c, Division__c, Category__c, CashierCode__c
            FROM CashierCode__c
            WHERE Division__c IN :divisions
            ORDER BY Division__c
        ];
    }

    public class TransactionWrapper {
        @AuraEnabled
        public Transaction__c trns { get; set; }
        @AuraEnabled
        public List<TransactionLine__c> lines { get; set; }
        @AuraEnabled
        public TransactionLine__c exampleLine { get; set; }

        public TransactionWrapper(Id recordId /*, string division*/) {
            Date orgDate = getOrgDateByUserTimezone();

            if (recordId.getSobjectType() == Schema.Account.SObjectType) {
                trns = new Transaction__c();
                trns.Account__c = recordId;
                trns.Date__c = orgDate;
                trns.Status__c = 'New';
                //trns.DCCASection__c = division;
                trns.TransactionType__c = '';

                lines = new List<TransactionLine__c>();

                exampleLine = new TransactionLine__c();
            } else if (recordId.getSobjectType() == Schema.Case.SObjectType) {
                trns = new Transaction__c();
                trns.breg_Case__c = recordId;
                trns.Date__c = orgDate;
                trns.Status__c = 'New';
                //trns.DCCASection__c = division;
                trns.TransactionType__c = '';

                Case relatedCase = [
                    SELECT Id, Origin, breg_Workitem_ID__c, RecordType.DeveloperName,
                        breg_Entity__c, Contact.AccountId, Contact.Account.IsPersonAccount
                    FROM Case
                    WHERE Id = :recordId
                    LIMIT 1
                ];

                if (relatedCase.RecordType != null
                    && relatedCase.RecordType.DeveloperName == 'BREG_Case'
                    && relatedCase.Origin != 'Web') {
                    trns.WorkitemID__c = relatedCase.breg_Workitem_ID__c;
                    trns.Account__c = relatedCase.breg_Entity__c;

                    if (relatedCase.breg_Entity__c == null
                        && relatedCase.Contact != null
                        && relatedCase.Contact.Account != null
                        && relatedCase.Contact.Account.IsPersonAccount == true) {
                        trns.Account__c = relatedCase.Contact.AccountId;
                    }
                }

                lines = new List<TransactionLine__c>();

                exampleLine = new TransactionLine__c();
            } else {
                trns = [SELECT Id, Name, Account__c, Status__c, TransactionType__c, Date__c, Description__c FROM Transaction__c WHERE Id = :recordId];

                lines = [
                    SELECT
                        Id,
                        CashierCode__c,
                        Amount__c,
                        AmountOverride__c,
                        CashierCode__r.Name,
                        CashierCode__r.FeeCode__c,
                        CashierCode__r.Category__c,
                        CashierCode__r.FormDescription__c,
                        CashierCode__r.Division__c,
                        CashierCode__r.Description__c
                    FROM TransactionLine__c
                    WHERE Transaction__c = :recordId
                ];
                exampleLine = new TransactionLine__c();
            }
        }
    }

    public class PicklistVal {
        @AuraEnabled
        public string value { get; set; }
        @AuraEnabled
        public string label { get; set; }

        public PicklistVal(Schema.PicklistEntry pe) {
            value = pe.getValue();
            label = pe.getLabel();
        }
    }
}