force-app/main/default/objects/Card_Cache__c/Card_Cache__c.object-meta.xml
<CustomObject>
    <description>Form Builder App - Stores temp JSON</description>
    <label>Card Cache</label>
    <nameField>
        <label>Card Cache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Cache</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Cache__c/fields/Card_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Card_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Meta Data</label>
    <referenceTo>Card_Meta_Data__c</referenceTo>
    <relationshipLabel>Card Cache</relationshipLabel>
    <relationshipName>Card_Cache</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Cache__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/Card_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains the section data for each card on an application</description>
    <label>Card Meta Data</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Used to separate the different type for card display.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salary Table</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Shared by children</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/Field_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains UI information for each field</description>
    <label>Field Meta Data</label>
    <nameField>
        <label>Field Meta Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Meta_Data__c/fields/Card_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Card_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link Field to its card</description>
    <label>Card Meta Data</label>
    <referenceTo>Card_Meta_Data__c</referenceTo>
    <relationshipLabel>Field Meta Data</relationshipLabel>
    <relationshipName>Field_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>The target object to create when this application is submitted</inlineHelpText>
    <label>Target Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/ObjectField__c.field-meta.xml
<CustomField>
    <fullName>ObjectField__c</fullName>
    <inlineHelpText>The Target field on the Target Object to populate with the value from this field</inlineHelpText>
    <label>Target Object Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>textarea</fullName>
            </value>
            <value>
                <fullName>picklist</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>rich text</fullName>
            </value>
            <value>
                <fullName>inputtable</fullName>
            </value>
            <value>
                <fullName>radio</fullName>
            </value>
            <value>
                <fullName>multicheckbox</fullName>
            </value>
            <value>
                <fullName>decimal</fullName>
            </value>
            <value>
                <fullName>multiPicklist</fullName>
            </value>
            <value>
                <fullName>file</fullName>
            </value>
            <value>
                <fullName>table</fullName>
            </value>
            <value>
                <fullName>clm-file</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <label>Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FieldMetaDataDomain.cls
public class FieldMetaDataDomain extends SObjectDomain {
    public FieldMetaDataDomain(List<Field_Meta_Data__c> fieldMetaData){
        super(fieldMetaData);
    }
    // Summary the fields to be Object Name => List Field Names
    public Map<String, List<String>> getObj2FieldList() {
        Map<String, List<String>> obj2FieldList = new Map<String, List<String>>();
        for(Field_Meta_Data__c record: (List<Field_Meta_Data__c> )records) {
            List<String> fieldList = new List<String>();
            if(obj2FieldList.containsKey(record.Object__c)) {
                fieldList = obj2FieldList.get(record.Object__c);
            }
            fieldList.add(record.ObjectField__c);
            obj2FieldList.put(record.Object__c, fieldList);
        }
        return obj2FieldList;
    }
    // Summary the fields to be Card Meta Data => List Fields
    public Map<String, List<Field_Meta_Data__c>> getCardId2FieldList() {
        Map<String, List<Field_Meta_Data__c>> cardId2FieldList = new Map<String, List<Field_Meta_Data__c>>();
        for(Field_Meta_Data__c record: (List<Field_Meta_Data__c> )records) {
            List<Field_Meta_Data__c> fieldList = new List<Field_Meta_Data__c>();
            if(cardId2FieldList.containsKey(record.Card_Meta_Data__c)) {
                fieldList = cardId2FieldList.get(record.Card_Meta_Data__c);
            }
            fieldList.add(record);
            cardId2FieldList.put(record.Card_Meta_Data__c, fieldList);
        }
        return cardId2FieldList;
    }

    public Map<String, SObject> generateRecord(Card_Cache__c cache, Map<String, SObject> objMap) {
        for(Field_Meta_Data__c record: (List<Field_Meta_Data__c>) records) {
            if(record.Type__c != 'info' && record.Type__c != 'table') {
                String apiName = record.Name__c;
                String values = cache.Values__c;
                String fieldName = record.ObjectField__c;
                String objName = record.Object__c;
                if(fieldName == 'NA' || fieldName == 'Files') continue;
                Map<String, String> valueMap = (Map<String, String>) JSON.deserialize(values, Map<String, String>.class);
                if(valueMap.containsKey(apiName)) {
                    String value = valueMap.get(apiName);
                    if(value != 'null' && value != null && value != '') {
                        if(!Schema.getGlobalDescribe().containsKey(objName)) continue;
                        SObject obj = Schema.getGlobalDescribe().get(objName).newSObject();
                        if(objMap.containsKey(objName)) {
                            obj = objMap.get(objName);
                        }
                        try{
                            if(record.Type__c == 'date') {
                                obj.put(fieldName, Date.valueOf(value));
                            } else if(record.Type__c == 'checkbox') {
                                obj.put(fieldName, value == 'true');
                            } else {
                                obj.put(fieldName, value);    
                            }
                            objMap.put(objName, obj);
                            
                        } catch(Exception ex) {
                            try{
                                if(record.Type__c == 'picklist') {
                                    if(value == 'Yes') {
                                        obj.put(fieldName, true);
                                    } else {
                                        System.debug('#####Field objName#####' + objName + '#####Field api Name#####' + fieldName + '#####Field Label#####' + record.Label__c + '#####Field Type#####' + record.Type__c + '#####Field value#####' + value);    
                                    }
                                } else {
                                    System.debug('#####Field objName#####' + objName + '#####Field api Name#####' + fieldName + '#####Field Label#####' + record.Label__c + '#####Field Type#####' + record.Type__c + '#####Field value#####' + value);
                                }
                                
                            } catch (Exception ex1) {
                                System.debug('#####Field objName#####' + objName + '#####Field api Name#####' + fieldName + '#####Field Label#####' + record.Label__c + '#####Field Type#####' + record.Type__c + '#####Field value#####' + value);
                            }
                            
                        }
                        
                    }
                }
            }
        }
        return objMap;
    }

    public Map<String, List<SObject>> generateTables(Card_Cache__c cache, Map<String, List<SObject>> recordsMaps) {
        for(Field_Meta_Data__c record: (List<Field_Meta_Data__c>) records) {
            if(record.Type__c == 'table') {
                String apiName = record.Name__c;
                String values = cache.Values__c;
                String objName = record.Object__c;
                Map<String, String> valueMap = (Map<String, String>) JSON.deserialize(values, Map<String, String>.class);
                
                if(valueMap.containsKey(apiName)) {
                    String value = valueMap.get(apiName);
                    if(String.isBlank(value)) {
                        continue;
                    }
                    List<SObject> records = (List<SObject>) JSON.deserialize(value, List<SObject>.class);
                    List<SObject> allRecords = new List<SObject>();
                    if(recordsMaps.containsKey(objName)) {
                        allRecords = recordsMaps.get(objName);
                    }
                    allRecords.addAll(records);
                    recordsMaps.put(objName, allRecords);
                }
            }
        }
        return recordsMaps;
    }

    public Map<String, List<String>> generateFiles(Card_Cache__c cache, Map<String, List<String>> fileMaps) {
        for(Field_Meta_Data__c record: (List<Field_Meta_Data__c>) records) {
            if(record.Type__c == 'clm-file') {
                String apiName = record.Name__c;
                String values = cache.Values__c;
                String objName = record.Object__c;
                Map<String, String> valueMap = (Map<String, String>) JSON.deserialize(values, Map<String, String>.class);
                
                if(valueMap.containsKey(apiName)) {
                    String value = valueMap.get(apiName);
                    if(String.isBlank(value)) continue;
                    System.debug('####test value###' + value);
                    List<Map<String, String>> fMaps = (List<Map<String, String>>) JSON.deserialize(value,
                         List<Map<String, String>>.class);
                    for(Map<String, String> fMap: fMaps ) {
                        String fileUrl = fMap.get('fileUrl');
                        List<String> fileUrls = new List<String>();
                        if(fileMaps.containsKey(objName)) {
                            fileUrls = fileMaps.get(objName);
                        }
                        fileUrls.add(fileUrl);
                        fileMaps.put(objName, fileUrls);
                    }
                }
            }
        }
        return fileMaps;
    }
}