force-app/main/default/objects/SpringCLMSetting__mdt/SpringCLMSetting__mdt.object-meta.xml
<CustomObject>
    <label>Spring CLM Setting</label>
    <pluralLabel>Spring CLM Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SpringCLMSetting__mdt/fields/API_URL__c.field-meta.xml
<CustomField>
    <fullName>API_URL__c</fullName>
    <label>API URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpringCLMSetting__mdt/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SpringCMApiEnvironment.cls
public class SpringCMApiEnvironment {
    public static String getEnvironmentPrefix() {
        String environmentPrefix = '';
        String hostname = URL.getOrgDomainURL().toExternalForm();
        Organization org = [SELECT IsSandbox FROM Organization LIMIT 1];
        if (hostname.contains('sandbox')) {
            environmentPrefix = 'UAT';
        } else if (org.IsSandbox) {
            environmentPrefix = 'DEV';
        } else {
            environmentPrefix = 'PROD';
        }
        return environmentPrefix;
    }
    public static SpringCLMSetting__mdt getApiEnvironment() {
        String environmentqueryname = getEnvironmentPrefix();
        if (Test.isRunningTest())
            environmentqueryname = 'TEST';

        return [ Select Id, Client_Id__c, Client_Secret__c, AuthEndpoint__c,API_URL__c,
        Account_Id__c from SpringCLMSetting__mdt WHERE DeveloperName =: environmentqueryname];
    }
}