force-app/main/default/objects/Account_Access_Request__c/Account_Access_Request__c.object-meta.xml
<CustomObject>
    <label>Account Access Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Account Access Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Access_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INET_Request__c/INET_Request__c.object-meta.xml
<CustomObject>
    <label>INET Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>INET_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INET_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>CATV Review</fullName>
            </value>
            <value>
                <fullName>Assigned Back</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
            <value>
                <fullName>Work Initiated</fullName>
            </value>
            <value>
                <fullName>Work Completed</fullName>
            </value>
            <value>
                <fullName>Invoice Created</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Connected to INET</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CATV_InetTriggerHandlerTest.cls
@isTest
public class CATV_InetTriggerHandlerTest {
	@testsetup static void setup(){
        Account communityDefaultAcc = CATV_TestClassUtility.createAccount('Test Account',false);
        communityDefaultAcc.Type = 'Community';
        insert communityDefaultAcc;
        
        List<Contact> conList = new List<Contact>();
        List<Account> accList = new List<Account>();
        
        Contact con = CATV_TestClassUtility.createContact('lname', 'a@b.com', communityDefaultAcc.Id, false);
        con.Type__c = 'Requestor';
        conList.add(con);
        
        Account acc = CATV_TestClassUtility.createAccount('test_acc',false);
        acc.Type = 'City';
        accList.add(acc);
        
        Account acc2 = CATV_TestClassUtility.createAccount('test_acc',false);
        acc2.Type = 'Provider';
        accList.add(acc2);
        insert accList;
        
        Contact con2 = CATV_TestClassUtility.createContact('lsname', 'aaa@b.com', acc2.Id, false);
        con2.Type__c = 'Provider';
        conList.add(con2);
        insert conList;

        INET_Request__c request = CATV_TestClassUtility.createINETRequest(acc2, con2, acc, con, true);
        
        Account_Access_Request__c aar = CATV_TestClassUtility.createAccountAccessRequest(acc.Id, con.Id, true);
        Account_Access_Request__c aar2 = CATV_TestClassUtility.createAccountAccessRequest(acc2.Id, con2.Id, true);
        
        Map<String, Object> inputObj = new Map<String, Object>();
        inputObj.put('recordId', aar.Id);
        inputObj.put('comments', 'test_comments');
        inputObj.put('targetAction', 'approveAction');
        
        Map<String, Object> inputObj2 = new Map<String, Object>();
        inputObj2.put('recordId', aar2.Id);
        inputObj2.put('comments', 'test_comments');
        inputObj2.put('targetAction', 'approveAction');

        CATV_AccessRequestController.handleRequestAction(JSON.serialize(inputObj));
        CATV_AccessRequestController.handleRequestAction(JSON.serialize(inputObj2));
    }
    
    @isTest static void inetSharingTest(){
        Account reqAcc = [SELECT Id FROM Account WHERE Type = 'City'];
        Account providerAcc = [SELECT Id FROM Account WHERE Type = 'Provider'];
        
        Contact reqCon = [SELECT Id FROM Contact WHERE Type__c = 'Requestor'];
        Contact providerCon = [SELECT Id FROM Contact WHERE Type__c = 'Provider'];
        
        User u = [SELECT Id FROM User WHERE ContactId = :reqCon.Id];
        
        INET_Request__c request = CATV_TestClassUtility.createINETRequest(providerAcc, providerCon, reqAcc, reqCon,  true);
        
        request.Status__c = 'Submitted';
        update request;
        
        system.assertEquals(request.Id != null, true);
        
    }
}