force-app/main/default/objects/Account_Access_Request__c/Account_Access_Request__c.object-meta.xml
<CustomObject>
    <label>Account Access Request</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Account Access Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Access_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Access Requests</relationshipLabel>
    <relationshipName>Account_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Access_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Access Requests</relationshipLabel>
    <relationshipName>Account_Access_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Access_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INET_Request__c/INET_Request__c.object-meta.xml
<CustomObject>
    <label>INET Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>INET_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INET_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Requestor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Island__c.field-meta.xml
<CustomField>
    <fullName>Island__c</fullName>
    <label>Island</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Kahoolawe</fullName>
            </value>
            <value>
                <fullName>Kauai</fullName>
            </value>
            <value>
                <fullName>Lanai</fullName>
            </value>
            <value>
                <fullName>Maui</fullName>
            </value>
            <value>
                <fullName>Molokai</fullName>
            </value>
            <value>
                <fullName>Niihau</fullName>
            </value>
            <value>
                <fullName>Oahu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>INET_Requests</relationshipLabel>
    <relationshipName>INET_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Provider_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Type__c</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Provider__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>INET_Requests (Provider Contact Name)</relationshipLabel>
    <relationshipName>INET_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>City, County, State, University, CATV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>INET_Requests (Requestor)</relationshipLabel>
    <relationshipName>INET_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Requestor_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Type__c</field>
            <operation>equals</operation>
            <value>Requestor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>INET_Requests (Requestor Contact Name)</relationshipLabel>
    <relationshipName>INET_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>CATV Review</fullName>
            </value>
            <value>
                <fullName>Assigned Back</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
            <value>
                <fullName>Work Initiated</fullName>
            </value>
            <value>
                <fullName>Work Completed</fullName>
            </value>
            <value>
                <fullName>Invoice Created</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Connected to INET</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INET_Request__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/INET_Request__c.field-meta.xml
<CustomField>
    <fullName>INET_Request__c</fullName>
    <label>INET Request</label>
    <referenceTo>INET_Request__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/INET_Request__c.field-meta.xml
<CustomField>
    <fullName>INET_Request__c</fullName>
    <label>INET Request</label>
    <referenceTo>INET_Request__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Provider)</relationshipLabel>
    <relationshipName>Purchase_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>City, County, State, University, CATV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/Quotes__c.object-meta.xml
<CustomObject>
    <label>Quotes</label>
    <nameField>
        <label>Quote Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotes__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/INET_Request__c.field-meta.xml
<CustomField>
    <fullName>INET_Request__c</fullName>
    <label>INET Request</label>
    <referenceTo>INET_Request__c</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>City, County, State, University, CATV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotes__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CATV_TestClassUtility.cls
/**
 * @description       : 
 * @author            : Deepanshu Jain
 * @group             : 
 * @last modified on  : 05-06-2025
 * @last modified by  : Deepanshu Jain
**/
@isTest
public with sharing class CATV_TestClassUtility {
    public static Account createAccount(String name, Boolean doInsert){
        String CATV_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('DCCA_CATV')?.getRecordTypeId();
        
        Account accRec = new Account();
        accRec.Name = name;
        accRec.RecordTypeId = CATV_RECORD_TYPE_ID;
        
        if(doInsert){
            insert accRec;
        }
        return accRec;
    }
    
    public static Contact createContact(String lastName, String email, String accId, Boolean doInsert){
        Contact con = new Contact();
        con.FirstName = 'first Name';
        con.LastName = lastName;
        con.Email = email;
        con.AccountId = accId;
        con.Title = 'Test Title';

        if( doInsert ){
            insert con;
        }
        return con;
    }
    
    public static Account_Access_Request__c createAccountAccessRequest(String accId, String conId, Boolean doInsert ){
        Account_Access_Request__c aar = new Account_Access_Request__c();
        aar.Account__c = accId;
        aar.Contact__c = conId;
        aar.Status__c = 'Pending';

        if( doInsert ){
            insert aar;
        }
        return aar;
    }
    
    public static INET_Request__c createINETRequest(Account provider, Contact providerContact, Account requestor, Contact requestorContact, Boolean doInsert ){
        INET_Request__c request = new INET_Request__c();
        request.Site_Name__c = 'Test Site';
        request.Provider__c = provider.Id;
        request.Requestor__c = requestor.Id;
        request.Requestor_Contact_Name__c = requestorContact.Id;
        request.Provider_Contact_Name__c = providerContact.Id;
        request.Status__c = 'Quote';
        request.Address__c = '6303 Cowboys Way';
        request.City__c = 'HI Pacific Uni';
        request.Island__c = 'Hawaii';
        request.Zip_Code__c = '76554';
        if( doInsert ){
            insert request;
        }
        return request;
    }
        
    public static Quotes__c createQuote(Account provider, Account requestor, INET_Request__c requestId, Boolean doInsert ){
        Quotes__c quote = new Quotes__c();
        quote.Provider__c = provider.Id;
        quote.Requestor__c = requestor.Id;
        quote.Description__c = 'Test desc';
        quote.INET_Request__c = requestId.Id;
        quote.Status__c = 'Sent';
        quote.Submitted_Date__c = System.Today();
        quote.Amount__c = 100;
        if( doInsert ){
            insert quote;
        }
        return quote;
    }
    
    public static Purchase_Order__c createPurchaseOrder(Account provider, Account requestor, INET_Request__c requestId, Boolean doInsert ){
        Purchase_Order__c  purchaseOrder = new Purchase_Order__c  ();
        purchaseOrder.Name = '1111';
        purchaseOrder.PO_Amount__c = 100;
        purchaseOrder.INET_Request__c  = requestId.Id;
        purchaseOrder.PO_Date__c = System.Today();
        purchaseOrder.Provider__c = provider.Id;
        purchaseOrder.Requestor__c = requestor.Id;
        if( doInsert ){
            insert purchaseOrder;
        }
        return purchaseOrder;
    }
    
    public static Invoice__c  createInvoice(INET_Request__c requestId, Boolean doInsert ){
        Invoice__c invoice = new Invoice__c ();
        invoice.Name = '1111';
        invoice.Invoice_Amount__c  = 100;
        invoice.INET_Request__c  = requestId.Id;
        invoice.Status__c = 'Unpaid';
        invoice.Invoice_Date__c = System.Today();
        if( doInsert ){
            insert invoice;
        }
        return invoice;
    }
    
    public static User createuser(String firtName, String lastName, String email, String profileId, String contactId, Boolean doInsert){
        String orgId = UserInfo.getOrganizationId();  
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');  
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));  
        String uniqueName = orgId + dateString + randomInt;  
        User tempUser = new User(  
            FirstName = firtName,  
            LastName = lastName,  
            Email = email,   
            Username = uniqueName + '@sfdc' + orgId + '.org',  
            EmailEncodingKey = 'ISO-8859-1',  
            Alias = uniqueName.substring(18, 23),  
            TimeZoneSidKey = 'America/Los_Angeles',  
            LocaleSidKey = 'en_US',  
            LanguageLocaleKey = 'en_US',  
            ProfileId = profileId,
            ContactId = contactId,
            IsActive = true,
            FederationIdentifier = 'abc'+System.now()+lastName
        );
        
        if( doInsert ){
            insert tempUser;
        }
        return tempUser;
    }
}