force-app/main/default/objects/breg_TN_TM_SM__c/breg_TN_TM_SM__c.object-meta.xml
<CustomObject>
    <label>TN/TM/SM</label>
    <nameField>
        <label>TN/TM/SM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TN/TM/SM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Account__c.field-meta.xml
<CustomField>
    <fullName>breg_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta BREG-61</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TN/TM/SM</relationshipLabel>
    <relationshipName>TN_TM_SM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Transaction__c.field-meta.xml
<CustomField>
    <fullName>breg_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BREG Transaction</label>
    <referenceTo>breg_Transaction__c</referenceTo>
    <relationshipLabel>TN/TM/SM</relationshipLabel>
    <relationshipName>TN_TM_SM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/breg_Transaction__c.object-meta.xml
<CustomObject>
    <description>Aalta BREG-62</description>
    <label>BREG Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BREG Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Account__c.field-meta.xml
<CustomField>
    <fullName>breg_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta BREG-62</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>breg_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Case__c.field-meta.xml
<CustomField>
    <fullName>breg_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transactions (Case)</relationshipLabel>
    <relationshipName>breg_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_TN_TM_SM__c.field-meta.xml
<CustomField>
    <fullName>breg_TN_TM_SM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TN/TM/SM</label>
    <referenceTo>breg_TN_TM_SM__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_Transaction__c/fields/breg_Transaction_Code__c.field-meta.xml
<CustomField>
    <fullName>breg_Transaction_Code__c</fullName>
    <label>Transaction Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>breg_Transaction_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BREGTransactionUtilsWithoutSharing.cls
public without sharing class BREGTransactionUtilsWithoutSharing {
    public static List<breg_Transaction__c> getExistingTransactions(
        Set<Id> caseIds,
        Set<Id> relatedRecordIds,
        Set<String> transactionCodesToSearch
    ) {
        return [
            SELECT Id, breg_Case__c, breg_Account__c, breg_TN_TM_SM__c, breg_Case__r.breg_Name_of_the_Entity__c
            FROM breg_Transaction__c
            WHERE
                breg_Case__c IN :caseIds
                AND (
                    breg_Account__c IN :relatedRecordIds
                    OR breg_TN_TM_SM__c IN :relatedRecordIds
                    OR (breg_Account__c = NULL AND breg_TN_TM_SM__c = NULL)
                )
                AND breg_Transaction_Code__c IN :transactionCodesToSearch
            ORDER BY CreatedDate DESC
        ];
    }
}