force-app/main/default/objects/breg_TN_TM_SM__c/breg_TN_TM_SM__c.object-meta.xml
<CustomObject>
    <label>TN/TM/SM</label>
    <nameField>
        <label>TN/TM/SM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TN/TM/SM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Account__c.field-meta.xml
<CustomField>
    <fullName>breg_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Aalta BREG-61</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TN/TM/SM</relationshipLabel>
    <relationshipName>TN_TM_SM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>breg_Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/breg_TN_TM_SM__c/fields/breg_Status__c.field-meta.xml
<CustomField>
    <fullName>breg_Status__c</fullName>
    <description>Aalta BREG-61</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Revoked</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BREGCaseStatusHandlerTNTMSMCancel.cls
/**
 * Handler for the TNTMSM Cancellation forms (TMSM-CANC,  TN-CANC)
 */
public with sharing class BREGCaseStatusHandlerTNTMSMCancel extends BREGCaseStatusHandlerBase {
    public override void handleStatusChange(List<Case> cases, String newStatus, Boolean performValidation, Boolean performActions) {
        if (performValidation) {
            super.handleStatusChange(cases, newStatus, true, false);
            performValidation(cases, newStatus);
        }

        if (performActions) {
            super.handleStatusChange(cases, newStatus, false, true);
            performActions(cases, newStatus);
        }
    }

    private void performValidation(List<Case> cases, String newStatus) {
        // add specific validation for different statuses
        // switch on newStatus {
        //     when 'Approved' {
        //     }
        //     when else {
        //         // do nothing
        //     }
        // }
    }

    private void performActions(List<Case> cases, String newStatus) {
        // add specific actions for different statuses
        switch on newStatus {
            when 'Completed' {
                updateTNTMSMs(cases);
            }
            when else {
                // do nothing
            }
        }
    }

    private void updateTNTMSMs(List<Case> cases) {
        Set<Id> ids = getTNTMSMIds(cases);
        Map<Id, breg_TN_TM_SM__c> tnTmSmsMap = getTNTMSMMap(ids);
        List<breg_TN_TM_SM__c> tnTmSmsToUpdate = new List<breg_TN_TM_SM__c>();
        List<Account> accountsToUpdate = new List<Account>();
        Map<Id, Case> entityToCaseMap = new Map<Id, Case>();
        Map<Id, Set<String>> accountUpdatedFieldsMap = new Map<Id, Set<String>>();
        for (Case c : cases) {
            if (tnTmSmsMap.containsKey(c.breg_TN_TM_SM__c)) {
                entityToCaseMap.put(c.breg_Entity__c, c);
                breg_TN_TM_SM__c tnTmSm = tnTmSmsMap.get(c.breg_TN_TM_SM__c);
                if (c.breg_Effective_Date__c != null) {
                    tnTmSm.breg_Cancellation_Date__c = c.breg_Effective_Date__c;
                }
                tnTmSm.breg_Status__c = 'C';
                tnTmSmsToUpdate.add(tnTmSm);

                if (tnTmSm.breg_Account__c != null) {
                    Account account = new Account();
                    account.Id = tnTmSm.breg_Account__c;
                    if (c.breg_Effective_Date__c != null) {
                        account.breg_End_Date__c = c.breg_Effective_Date__c;
                        accountUpdatedFieldsMap.put(account.Id, new Set<String>{ 'breg_End_Date__c' });
                    }
                    accountsToUpdate.add(account);
                }
            }
        }

        if (!tnTmSmsToUpdate.isEmpty()) {
            update tnTmSmsToUpdate;
        }
        if (!accountsToUpdate.isEmpty()) {
            BREGCaseStatusHandlerHelper.createBusinessInfoLogsAndUpdate(accountsToUpdate, accountUpdatedFieldsMap, entityToCaseMap);
        }
    }

    private Set<Id> getTNTMSMIds(List<Case> cases) {
        Set<Id> ids = new Set<Id>();
        for (Case c : cases) {
            if (c.breg_TN_TM_SM__c != null) {
                ids.add(c.breg_TN_TM_SM__c);
            }
        }
        return ids;
    }

    private Map<Id, breg_TN_TM_SM__c> getTNTMSMMap(Set<Id> ids) {
        return new Map<Id, breg_TN_TM_SM__c>(
            [
                SELECT Id, breg_Cancellation_Date__c, breg_Status__c, breg_Account__c
                FROM breg_TN_TM_SM__c
                WHERE Id IN :ids
            ]
        );
    }
}