force-app/main/default/objects/BoardProgram__c/BoardProgram__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Board / Program</label>
    <nameField>
        <label>Board / Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards / Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseNumberAssignments__c/LicenseNumberAssignments__c.object-meta.xml
<CustomObject>
    <description>PacPoint-MV093019 - Created for PVL phase 1</description>
    <label>License Number Assignments</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Number Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseNumberAssignments__c/fields/BoardProgram__c.field-meta.xml
<CustomField>
    <fullName>BoardProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV082119 - Created for PVL phase 1</description>
    <label>Board/Program</label>
    <referenceTo>BoardProgram__c</referenceTo>
    <relationshipLabel>License Number Assignments</relationshipLabel>
    <relationshipName>License_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseNumberAssignments__c/fields/LicenseNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenseNumber__c</fullName>
    <description>PacPoint-MV082119 - Created for PVL phase 1</description>
    <label>License Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseNumberAssignments__c/fields/LicensePrefix__c.field-meta.xml
<CustomField>
    <fullName>LicensePrefix__c</fullName>
    <formula>LicenseType__r.LicensePrefix__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Prefix</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseNumberAssignments__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-MV082119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <referenceTo>LicenseType__c</referenceTo>
    <relationshipLabel>License Number Assignments</relationshipLabel>
    <relationshipName>License_Number_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/LicenseType__c.object-meta.xml
<CustomObject>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <nameField>
        <label>License Type Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseType__c/fields/BoardProgram__c.field-meta.xml
<CustomField>
    <fullName>BoardProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>Board / Program</label>
    <referenceTo>BoardProgram__c</referenceTo>
    <relationshipLabel>License Types</relationshipLabel>
    <relationshipName>License_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicensePrefix__c.field-meta.xml
<CustomField>
    <fullName>LicensePrefix__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <inlineHelpText>This is the 2 or 3 digit code that will all licenses numbers of this type will start with.</inlineHelpText>
    <label>License Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/fields/LicenseType__c.field-meta.xml
<CustomField>
    <fullName>LicenseType__c</fullName>
    <description>PacPoint-FT070119 - Created for PVL phase 1</description>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseType__c/recordTypes/PVL.recordType-meta.xml
<RecordType>
    <fullName>PVL</fullName>
    <active>true</active>
    <label>PVL</label>
</RecordType>

force-app/main/default/classes/LicenseNumberAssignmentDomain.cls
/*
* ─────────────────────────────────────────────────────────
* Used for the single unit of  logic around
* License number assignments records
* ─────────────────────────────────────────────────────────
* PacPoint-AZ021019 - Created for PVL phase 1
* ───────────────────────────────────────────────────────────
* Initial implementation
* @author       Alvin Zhou - PacificPointCorp
* @created      2019-10-02
* ───────────────────────────────────────────────────────────
* Changes
*
*
* ───────────────────────────────────────────────────────────
*/
public with sharing class LicenseNumberAssignmentDomain extends SObjectDomain{
    public LicenseNumberAssignmentDomain(List<LicenseNumberAssignments__c> licenseNumberAssignments) {
        super(licenseNumberAssignments);
    }

    public LicenseNumberAssignments__c getLicenseNumberAssignmentByBoardProgram(String boardProgramId) {
        LicenseNumberAssignments__c selectedRecord = null;
        for(SObject record: records) {
            LicenseNumberAssignments__c licenseNumberAssignment = (LicenseNumberAssignments__c) record;
            if(licenseNumberAssignment.BoardProgram__c == boardProgramId) {
                selectedRecord = licenseNumberAssignment;
            }
        }
        return selectedRecord;
    }
    public LicenseNumberAssignments__c getLicenseNumberAssignmentByLicenseType(String licenseTypeId) {
        LicenseNumberAssignments__c selectedRecord = null;
        for(SObject record: records) {
            LicenseNumberAssignments__c licenseNumberAssignment = (LicenseNumberAssignments__c) record;
            if(licenseNumberAssignment.LicenseType__c == licenseTypeId) {
                selectedRecord = licenseNumberAssignment;
            }
        }
        return selectedRecord;
    }

    // 00011339
    public List<String> getLicenseTypePrefix() {
        List<String> licenseTypePrefix = new List<String>();
        for(LicenseNumberAssignments__c record: (List<LicenseNumberAssignments__c>)records) {
            licenseTypePrefix.add(record.LicenseType__r.LicensePrefix__c);

        }
        return licenseTypePrefix;
    }
    // 00011339
    public Map<String, LicenseNumberAssignments__c> getLicenseTypePrefixMap() {
        Map<String, LicenseNumberAssignments__c> licenseNumberAssignments = new Map<String, LicenseNumberAssignments__c> ();
        for(LicenseNumberAssignments__c record: (List<LicenseNumberAssignments__c>)records) {
            licenseNumberAssignments.put(record.LicenseType__r.LicensePrefix__c, record);

        }
        return licenseNumberAssignments;
    }
    // 00011339
    public void updateLicenseNumber(Map<String, LicenseNumberAssignments__c> licenseNumberAssignments) {
        for(LicenseNumberAssignments__c record: (List<LicenseNumberAssignments__c>)records) {
            if(licenseNumberAssignments.get(record.LicenseType__r.LicensePrefix__c) != null) {
                record.LicenseNumber__c = licenseNumberAssignments.get(record.LicenseType__r.LicensePrefix__c).LicenseNumber__c;
            }
        }
    }
}