force-app/main/default/objects/Reconciliation_Batch__c/Reconciliation_Batch__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CZ101919 - Created for 4GOV phase 1.This object will house each batched Collection Allocation records.</description>
    <label>Reconciliation Batch</label>
    <nameField>
        <displayFormat>RB-{0000000}</displayFormat>
        <label>Reconciliation Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliation Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reconciliation_Batch__c/fields/Batch_Time__c.field-meta.xml
<CustomField>
    <fullName>Batch_Time__c</fullName>
    <description>PacPoint-CZ101919 - Created for 4GOV phase 1</description>
    <label>Batch Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reconciliation_Batch__c/fields/CashierSession__c.field-meta.xml
<CustomField>
    <fullName>CashierSession__c</fullName>
    <label>Cashier Session</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reconciliation_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CZ101919 - Created for 4GOV phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Sent To 4Gov</fullName>
                <label>Sent To GL</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
                <isActive>false</isActive>
                <label>Email Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reconciliation_Batch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentAdjustmentController.cls
public with sharing class PaymentAdjustmentController {
    public class Response {
        @InvocableVariable
        public Id reconciliationBatchId;
    }

    @InvocableMethod(label='Generate Payment Adjustment')
    public static List<Response> generatePaymentAdjustment(List<String> requests) {
        // Create Reconciliation Batch
        Reconciliation_Batch__c rb = new Reconciliation_Batch__c();

        rb.Status__c = 'Pending Review';
        rb.OwnerId = UserInfo.getUserId();
        rb.Batch_Time__c = System.now();
        rb.CashierSession__c = UserInfo.getName() + ' ~ ' + System.now().format('M/d/yyyy h:mma');
        rb.Type__c = 'Adjustment';

        insert rb;

        Database.executeBatch(
            new PaymentAdjustmentBatchJob(rb.Id),
            200
        );

        Response res = new Response();
        res.reconciliationBatchId = rb.Id;

        return new List<Response>{ res };
    }
}