force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <inlineHelpText>The Total Amount of the Transaction.  This is the Sum of all the Amounts on the Transaction Lines.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionGroup__c.field-meta.xml
<CustomField>
    <fullName>TransactionGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082618 - Created for phase 1</description>
    <label>Transaction Group</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Grouped Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/WorkitemID__c.field-meta.xml
<CustomField>
    <fullName>WorkitemID__c</fullName>
    <label>Workitem ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GroupTransactions2Test.cls
/*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Test class for GroupTransaction2
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Initial implementation
* PacPoint-LC040819 - Created for DCCA phase 1
* @author       Lucian Ciobanu - PacificPointCorp
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Changes
*
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
*/
@isTest(seeAllData = false)
public class GroupTransactions2Test {
    
	@isTest 
    public static void Test1() {
        
		// Data setup
        Account acc = new Account();
        acc.Name = 'Test936844';
        acc.FileID__c = '1';
        acc.OAH_Case_Number__c = '1';
        insert acc;
        
        Transaction__c trns1 = new Transaction__c();
        trns1.Account__c = acc.Id;
        trns1.WorkitemID__c = '1';
        trns1.TotalAmount__c = 100.00;

        Transaction__c trns2 = new Transaction__c();
        trns2.Account__c = acc.Id;
        trns2.WorkitemID__c = '2';
        insert new List<Transaction__c> { trns1, trns2 };
        
		// Run the code
        Test.startTest();
        GroupTransactions2.getInitialValues();
        List<Account> accs = GroupTransactions2.searchLines1('Test', '1', '', '1', '', '', 5,1);
        List<Account> accs2 = GroupTransactions2.searchLines1('Test Name', '1', 'Test', '1', 'Test', 'Test', 5, 1);
        String saveResult = GroupTransactions2.saveNewAccount('012t0000000PLy1AAG', 'Test936845', '', '', '', '', '', '', '');
		List<Transaction__c> trans = GroupTransactions2.searchLines('Test', null, null, '2', null, null);
		List<Transaction__c> trans2 = GroupTransactions2.searchLines('Test Name', 'Test', 'Test', '2', 'Test', 'Test');
        GroupTransactions2.saveTransactions(acc.Id, new List<String> { trns1.Id, trns2.Id });
        Test.stopTest();
        
        // Verify Results
        System.assertEquals(1, trans.size());
        trns2 = [SELECT TransactionGroup__c FROM Transaction__c WHERE Id = :trns2.Id];
        System.assert(trns2.TransactionGroup__c != null);
    }
}