force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <description>PacPoint-CL092818 - Created for phase 1</description>
    <formula>IF( TEXT(TransactionGroup__r.Status__c)  = &apos;Completed&apos;, 0, (TotalAmount__c - TotalRefundAmount__c)-  PaymentAmount__c +  OverPaymentAmount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The net outstanding balance owned on this Transaction.  This is the Total Amount of the Transaction minus the Payment Amount (the amount that has already been paid) less any Refunds.</inlineHelpText>
    <label>Amount Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/MostRecentDisputedCharge__c.field-meta.xml
<CustomField>
    <fullName>MostRecentDisputedCharge__c</fullName>
    <formula>Account__r.MostRecentDisputedCharge__c</formula>
    <label>Most Recent Disputed Charge</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TempMemo__c.field-meta.xml
<CustomField>
    <fullName>TempMemo__c</fullName>
    <description>Used to store the Temp Memo value in the Transaction used for payment.</description>
    <label>Temp Memo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TempPaymentType__c.field-meta.xml
<CustomField>
    <fullName>TempPaymentType__c</fullName>
    <description>Used to capture the temp payment type.</description>
    <label>Temp Payment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLine__c/TransactionLine__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT070418 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Cashier Codes</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/AmountOutstanding__c.field-meta.xml
<CustomField>
    <fullName>AmountOutstanding__c</fullName>
    <formula>Amount__c - AmountCollected__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionLine__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PaymentTerminalController.cls
/******
 * Description: customize the payment save method in the payment terminal function
 * created By: Alvin Zhou
 * PC00011302-AZ110520
 * *** */
public class PaymentTerminalController {
    @AuraEnabled
    public static void updatePayment(String paymentStr) {
        updatePaymentAsync(paymentStr);
    }

    @future
    public static void updatePaymentAsync(String paymentStr) {
        pymt__PaymentX__c payment = (pymt__PaymentX__c) JSON.deserialize(paymentStr, pymt__PaymentX__c.class);
        Transaction__c tran = new Transaction__c();
        tran.Id = payment.Transaction__c;
        tran.TempPaymentType__c = payment.pymt__Payment_Type__c;
        update tran;
        update payment;
    }

    @AuraEnabled
    public static void updateTempPayment(String recordId, String paymentType, String memo) {
        Transaction__c record = new Transaction__c();
        record.Id = recordId;
        record.TempPaymentType__c = paymentType;
        record.TempMemo__c = memo;
        update record;
    }

    @AuraEnabled
    public static List<String> validateTransaction(String recordId){
        Transaction__c record = [Select Id, Account__c, Account__r.MostRecentBouncedCheck__c, Account__r.MostRecentDisputedCharge__c, AmountOutstanding__c, TransactionType__c, (Select Id from TransactionLines__r) from Transaction__c where Id =: recordId];
        if(record.AmountOutstanding__c == 0 || record.AmountOutstanding__c == null) {
            String error1 = 'Please make sure the outstanding amount is greater than zero before making a payment.';
            AuraHandledException ex = new AuraHandledException(error1);
            ex.setMessage(error1);
            throw ex;
        }
        if(record.TransactionType__c != 'Group' && (record.TransactionLines__r == null || record.TransactionLines__r.size() == 0)) {
            String error2 = 'Please enter at least one transaction line before making a payment.';
            AuraHandledException ex2 = new AuraHandledException(error2);
            ex2.setMessage(error2);
            throw ex2;
        }
        
        
        List<String> options;
        if(record.Account__c != null && record.Account__r.MostRecentDisputedCharge__c != null) {
            options = new List<String>();
            options.add('disputed charge');

        }else if(record.Account__c != null && record.Account__r.MostRecentBouncedCheck__c != null) {
            options = new List<String>();
            options.add('bounced check');
        } else {
            options = new List<String> {'Check', 'Credit Card', 'ECheck', 'Electronic Funds Transfer', 'Treasury Deposit (TDR)', 'Journal Voucher (JV)', 'Deposit Slipa'};
        }
        return options;
    }
}