force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-CL051618 - Created for phase1</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Transaction Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/ParentTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>ParentTotalAmount__c</fullName>
    <description>PacPoint-MC082718 - Created for phase 1

Total amount for Transactions Parent (sum of all transaction related to the parent)</description>
    <label>Parent Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <inlineHelpText>The Total Amount of the Transaction.  This is the Sum of all the Amounts on the Transaction Lines.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionGroup__c.field-meta.xml
<CustomField>
    <fullName>TransactionGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-FT082618 - Created for phase 1</description>
    <label>Transaction Group</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Grouped Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>PacPoint-CL051618 - Created for phase 1</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GroupTransactionController.cls
/********************************************************************************************************
*    Name:  GroupTransactionController.cls
*    Author: PacPoint-MC082818 - Created for phase(???)
*    Date:  8/28/2018
*    
*    TestClass: GroupTransactionControllerTest.cls
********************************************************************************************************/

public without sharing class GroupTransactionController {

    @AuraEnabled
    public static Transaction__c initTransaction() {
        // Parent Transaction initialization
        Transaction__c currentTransaction = new Transaction__c();
        currentTransaction.Date__c = Date.Today();
        currentTransaction.TransactionType__c = 'Payment';
        return currentTransaction;

    }

    @AuraEnabled
    public static List<Transaction__c> getTransactions() {
        // return all transaction to make them available for select
        return [SELECT Id, Name, Account__c, Account__r.Name, TotalAmount__c, TransactionGroup__c FROM Transaction__c WHERE TransactionType__c != 'Group' AND Account__c != null AND Status__c != 'Completed'];
    }

    @AuraEnabled
    public static Id saveTransaction(Transaction__c currenttransaction, string transactions) {
        // get all selected transactions
        List<Transaction__c> xlines = (List<Transaction__c>)JSON.deserialize(transactions, List<Transaction__c>.class);
        // asociate an Account to the parent transaction
        currenttransaction.Account__c = xlines[0].Account__c;
        // set parent transaction Type = "Group"
        currenttransaction.TransactionType__c = 'Group';
        // insert parent transaction

        insert currenttransaction;


        // iterate through all selected Transactions and add The parent Id
        Transaction__c transToUpdate = [SELECT Id, ParentTotalAmount__c FROM Transaction__c WHERE Id =:currentTransaction.Id];
        transToUpdate.ParentTotalAmount__c = 0;
        for (Transaction__c line : xlines) {
            line.TransactionGroup__c = currenttransaction.Id;
            // sum all the amounts and add the total on the parent record
            if(line.TotalAmount__c != null)
                transToUpdate.ParentTotalAmount__c += line.TotalAmount__c;
        }
        update xlines;

        update transToUpdate;
        // return parent record id (redirect to record page)
        return currenttransaction.Id;
        
    }
    
    public class TransactionWrapper {
        
        @AuraEnabled
        public Transaction__c trns { get; set; }
        @AuraEnabled
        public List<Transaction__c> lines { get; set; }
        @AuraEnabled
        public Transaction__c exampleLine { get; set; }
        
        public TransactionWrapper() {
            
            trns = new Transaction__c();
            trns.Date__c = Date.today();
            trns.Status__c = 'New';
            trns.TransactionType__c = 'Payment';
            
            lines = new List<Transaction__c>();
            
            exampleLine = new Transaction__c();
        }
        
    }
    
}