force-app/main/default/objects/BusinessAccountCounter__c/BusinessAccountCounter__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>PacPoint-MV100319 - Created for PVL phase 1</description>
    <label>Business Account Counter</label>
</CustomObject>

force-app/main/default/objects/BusinessAccountCounter__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <description>PacPoint-MV100319 - Created for PVL phase 1</description>
    <label>Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessAccountCounter__c/fields/ResetDate__c.field-meta.xml
<CustomField>
    <fullName>ResetDate__c</fullName>
    <label>Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DisplayBPIDControllerTest.cls
@isTest
private class DisplayBPIDControllerTest {
    @isTest
    static void testValidateBPID() {
        BusinessAccountCounter__c accountCounterSetting = new BusinessAccountCounter__c();
        accountCounterSetting.ResetDate__c = Date.today();
        accountCounterSetting.Counter__c = 1;
        insert accountCounterSetting;

        RecordTypeInfo businessAccountRti =
                Account.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get('BusinessAccount');

        Account acc = new Account();
        acc.Name = 'acc';
        acc.BPID__c = 'acc';
        acc.RecordTypeId = businessAccountRti.getRecordTypeId();
        insert acc;
        Account acc1 = [Select Id, BPID__c from Account  where Id =: acc.Id];
        Test.startTest();
        try {
            DisplayBPIDController.validateBPIDs(acc1.BPID__c, 'REGISTERED NURSE');
            
        } catch(Exception ex) {}
        DisplayBPIDController.getAccountInfo(acc1.BPID__c);

        Test.stopTest();
    }
}