force-app/main/default/objects/Sanction__c/Sanction__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC102218 - Created for BREG phase 1</description>
    <label>Sanction</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sanction__c/fields/Sanction__c.field-meta.xml
<CustomField>
    <fullName>Sanction__c</fullName>
    <description>PacPoint-IC102918 - Created for BREG phase 1</description>
    <label>Sanction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barred/Prohibited from Registering</fullName>
            </value>
            <value>
                <fullName>Registration Conditional</fullName>
            </value>
            <value>
                <fullName>Registration Denied</fullName>
            </value>
            <value>
                <fullName>Restitution/Rescission</fullName>
            </value>
            <value>
                <fullName>Injunction</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Registration Revocation</fullName>
            </value>
            <value>
                <fullName>Registration Suspension</fullName>
            </value>
            <value>
                <fullName>Registration Withdrawal (Formal/Informal)</fullName>
            </value>
            <value>
                <fullName>Heightened Supervision</fullName>
            </value>
            <value>
                <fullName>Investigative Costs</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sanction__c/fields/SEBCaseID__c.field-meta.xml
<CustomField>
    <fullName>SEBCaseID__c</fullName>
    <description>PacPoint-IC102918 - Created for BREG phase 1</description>
    <label>SEB Case ID</label>
    <referenceTo>SEBCase__c</referenceTo>
    <relationshipLabel>Sanctions</relationshipLabel>
    <relationshipName>Sanctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sanction__c/fields/Suspended_Amount__c.field-meta.xml
<CustomField>
    <fullName>Suspended_Amount__c</fullName>
    <description>PacPoint-YH-110923; case ref 29449</description>
    <label>Suspended Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sanction__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <label>Total Amount Paid</label>
    <summarizedField>Sanction_Payment__c.Total_Payments__c</summarizedField>
    <summaryFilterItems>
        <field>Sanction_Payment__c.Status__c</field>
        <operation>equals</operation>
        <value>Received</value>
    </summaryFilterItems>
    <summaryForeignKey>Sanction_Payment__c.Sanction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sanction__c/fields/Total_Sanction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Sanction_Amount__c</fullName>
    <description>PacPoint-YH-110923 case ref 29449</description>
    <label>Total Sanction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sanction_Payment__c/Sanction_Payment__c.object-meta.xml
<CustomObject>
    <label>Sanction Payment</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Sanction Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sanction Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sanction_Payment__c/fields/AmountDue__c.field-meta.xml
<CustomField>
    <fullName>AmountDue__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sanction_Payment__c/fields/Sanction__c.field-meta.xml
<CustomField>
    <fullName>Sanction__c</fullName>
    <label>Sanction</label>
    <referenceTo>Sanction__c</referenceTo>
    <relationshipLabel>Sanction Payments</relationshipLabel>
    <relationshipName>Sanction_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sanction_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEBCase__c/SEBCase__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC101218 - Created for BREG phase 1</description>
    <label>SEB Case</label>
    <nameField>
        <label>SEB Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEB Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEBCase__c/fields/PenaltiesAssessed__c.field-meta.xml
<CustomField>
    <fullName>PenaltiesAssessed__c</fullName>
    <description>PacPoint-IC102418 - Created for BREG phase 1</description>
    <label>Total Penalty Sanction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/PenaltiesCollected__c.field-meta.xml
<CustomField>
    <fullName>PenaltiesCollected__c</fullName>
    <defaultValue>0</defaultValue>
    <description>PacPoint-IC102418 - Created for BREG phase 1</description>
    <label>Total Penalty Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/PenaltiesSuspended__c.field-meta.xml
<CustomField>
    <fullName>PenaltiesSuspended__c</fullName>
    <defaultValue>0</defaultValue>
    <description>PacPoint-IC102418 - Created for BREG phase 1
PacPoint-RA110518 - Updated for BREG phase 1</description>
    <label>Total Penalty Suspended Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/RestitutionAssessed__c.field-meta.xml
<CustomField>
    <fullName>RestitutionAssessed__c</fullName>
    <description>PacPoint-RA110518 - Created for BREG phase 1</description>
    <label>Total Restitution/Rec Sanction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/RestitutionCollected__c.field-meta.xml
<CustomField>
    <fullName>RestitutionCollected__c</fullName>
    <description>PacPoint-RA110518 - Created for BREG phase 1</description>
    <label>Restitution Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SEBCase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-RA101218 - Created for BREG phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
                <default>true</default>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SEBCasePenaltyBatch.cls
global class SEBCasePenaltyBatch implements schedulable, Database.Batchable<SObject>, Database.Stateful {
    private String query = 'Select Id, RestitutionCollected__c, RestitutionAssessed__c, PenaltiesSuspended__c, ' 
    + ' PenaltiesAssessed__c, PenaltiesCollected__c from SEBCase__c ';

    /*
     * batch start class
     */
    global DataBase.QueryLocator Start(Database.BatchableContext context) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext context, List<SObject> scope) {
        List<SEBCase__c> records = (List<SEBCase__c>) scope;
        List<SEBCase__c> casesForUpdate = new List<SEBCase__c>();
        List<String> recordIds = new List<String>();
        for(SEBCase__c record: records) {
            recordIds.add(record.Id);
        }
        List<Sanction__c> sanctions = [Select Id, (Select Id, Status__c from Sanction_Payments__r ) from Sanction__c where SEBCaseID__c in: recordIds];
        List<String> sanctionIds = new List<String>();
        for(Sanction__c sanction: sanctions) {
            sanctionIds.add(sanction.Id);
        }
        List<SEBCase__c> penaltiesForUpdate = calculateSummalizedAmount(records, sanctionIds, 'Penalty');
        Set<Id> caseIdSet = (new Map<Id, SEBCase__c>(penaltiesForUpdate)).keySet();
        
        List<SEBCase__c> restitutionForUpdate = calculateSummalizedAmount(records, sanctionIds, 'Restitution/Rescission');
        Set<Id> restitutionIdSet = (new Map<Id, SEBCase__c>(restitutionForUpdate)).keySet();
        
        for(SEBCase__c record: records) {
            if(caseIdSet.contains(record.Id) || restitutionIdSet.contains(record.Id)) {
                casesForUpdate.add(record);
            }
        }
        
        if(!casesForUpdate.isEmpty()) {
            update casesForUpdate;
        }
        
    }

    // public Map<String, Decimal> getDecimalCalFromPayment(List<AggregateResult> results, List<AggregateResult> cancelledResults) {
    //     Map<String, Decimal> summarizedAmount = new Map<String, Decimal>();
    //     for(AggregateResult result: results) {
    //         String sebCaseId = (String) result.get('SEBCaseID__c');
    //         Decimal amountDue = (Decimal) result.get('amount');
    //         summarizedAmount.put(sebCaseId, amountDue);
    //     }
    //     for(AggregateResult result: cancelledResults) {
    //         String sebCaseId = (String) result.get('caseId');
    //         if(summarizedAmount.containsKey(sebCaseId)) {
    //             Decimal amountDue = summarizedAmount.get(sebCaseId);
    //             Decimal amountCancelled = (Decimal) result.get('amount');
    //             if(amountDue == null) amountDue = 0;
    //             if(amountCancelled == null) amountCancelled = 0;
    //             amountDue = amountDue - amountCancelled;
    //             summarizedAmount.put(sebCaseId, amountDue);
    //         } 
    //     }
    //     return summarizedAmount;

    // }
    public Map<String, Decimal> getDecimalCal(List<AggregateResult> results) {
        Map<String, Decimal> summarizedAmount = new Map<String, Decimal>();
        for(AggregateResult result: results) {
            String sebCaseId = (String) result.get('SEBCaseID__c');
            Decimal amountDue = (Decimal) result.get('amount');
            summarizedAmount.put(sebCaseId, amountDue);
        }
        return summarizedAmount;

    }


    public List<SEBCase__c> calculateSummalizedAmount(List<SEBCase__c> records, List<String> sanctionIds, String type) {
        List<SEBCase__c> casesForUpdate = new List<SEBCase__c>();    
        List<String> recordIds = new List<String>();
        for(SEBCase__c record: records) {
            recordIds.add(record.Id);
        }


        List<AggregateResult> resultsAssessed = [Select SEBCaseID__c, Sum(Total_Sanction_Amount__c) amount 
            from Sanction__c where Sanction__c =: type and SEBCaseID__c in: recordIds group by SEBCaseID__c];
        // List<AggregateResult> cancelledResultsAssessed = [Select Sanction__r.SEBCaseID__c caseId, Sum(AmountDue__c) amount 
        //     from Sanction_Payment__c where Status__c = 'Cancelled' and Sanction__r.Sanction__c =: type 
        //     and Sanction__c in: sanctionIds group by Sanction__r.SEBCaseID__c];
        Map<String, Decimal> assessedAmount = getDecimalCal(resultsAssessed);

        List<AggregateResult> resultsCollected = [Select SEBCaseID__c, Sum(Total_Amount_Paid__c) amount 
            from Sanction__c where Sanction__c =: type and SEBCaseID__c in: recordIds group by SEBCaseID__c];

        Map<String, Decimal> collectedAmount = getDecimalCal(resultsCollected);
        
        List<AggregateResult> resultsSuspended = new List<AggregateResult>();
        if(type == 'Penalty') {
            resultsSuspended = [Select SEBCaseID__c, Sum(Suspended_Amount__c) amount 
                from Sanction__c where Sanction__c =: type and Id in: sanctionIds group by SEBCaseID__c];
        }
        Map<String, Decimal> suspendedAmount = getDecimalCal(resultsSuspended);

        if(type == 'Penalty') {
            casesForUpdate = toUpdateForPenality(records, assessedAmount, collectedAmount, suspendedAmount);
        }
        else if(type == 'Restitution/Rescission') {
            casesForUpdate = toUpdateForRestitution(records, assessedAmount, collectedAmount);
        }
        return casesForUpdate;
    }
           
    public List<SEBCase__c> toUpdateForPenality(List<SEBCase__c> records, Map<String, Decimal> assessedAmount, 
        Map<String, Decimal> collectedAmount, Map<String, Decimal> suspendedAmount) {
        List<SEBCase__c> casesForUpdate = new List<SEBCase__c>();    
        for(SEBCase__c record: records) {
            Boolean toBeUpdated = false;  
            if(collectedAmount.containsKey(record.Id)  
                && record.PenaltiesCollected__c != collectedAmount.get(record.Id)) {
                record.PenaltiesCollected__c = collectedAmount.get(record.Id);
                toBeUpdated = true;
            }

            if(assessedAmount.containsKey(record.Id)  
                && record.PenaltiesAssessed__c != assessedAmount.get(record.Id)) {
                record.PenaltiesAssessed__c = assessedAmount.get(record.Id);
                toBeUpdated = true;
            }

            if(suspendedAmount.containsKey(record.Id)  
                && record.PenaltiesSuspended__c != suspendedAmount.get(record.Id)) {
                record.PenaltiesSuspended__c = suspendedAmount.get(record.Id);
                toBeUpdated = true;
            }
            if(toBeUpdated) {
                casesForUpdate.add(record);
            }
        }
        return casesForUpdate;
    }
    public List<SEBCase__c> toUpdateForRestitution(List<SEBCase__c> records, Map<String, Decimal> assessedAmount, 
        Map<String, Decimal> collectedAmount) {
        List<SEBCase__c> casesForUpdate = new List<SEBCase__c>();    
        for(SEBCase__c record: records) {
            Boolean toBeUpdated = false;
            if(collectedAmount.containsKey(record.Id) 
                && record.RestitutionCollected__c != collectedAmount.get(record.Id)) {
                record.RestitutionCollected__c = collectedAmount.get(record.Id);
                toBeUpdated = true;
            }

            if(assessedAmount.containsKey(record.Id) 
                && record.RestitutionAssessed__c != assessedAmount.get(record.Id)) {
                record.RestitutionAssessed__c = assessedAmount.get(record.Id);
                toBeUpdated = true;
            }
            if(toBeUpdated) {
                casesForUpdate.add(record);
            }
        }
        return casesForUpdate;
    }

    /*
     * batch finish class
     */
    global void finish(Database.BatchableContext context) {}

    public void execute(System.SchedulableContext context) {
        Database.executeBatch(new SEBCasePenaltyBatch(), 100);
    }
}