force-app/main/default/objects/Application_Cache__c/Application_Cache__c.object-meta.xml
<CustomObject>
    <description>Form Builder App</description>
    <label>Draft Application</label>
    <nameField>
        <label>Application Cache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Draft Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Cache__c/fields/AppDataBeforeSubmit__c.field-meta.xml
<CustomField>
    <fullName>AppDataBeforeSubmit__c</fullName>
    <description>Used to store the data before submit</description>
    <label>App Data Before Submit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Application Cache</relationshipLabel>
    <relationshipName>Application_Cache</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assessment - replica instruments</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreements</fullName>
            </value>
            <value>
                <fullName>Cancelled Transfers</fullName>
            </value>
            <value>
                <fullName>Exemption - Charitable ... bodies</fullName>
            </value>
            <value>
                <fullName>Exemption from duty</fullName>
            </value>
            <value>
                <fullName>Refund of overpayments</fullName>
            </value>
            <value>
                <fullName>Remission of interest</fullName>
            </value>
            <value>
                <fullName>Deceased estate</fullName>
            </value>
            <value>
                <fullName>Change in trustee</fullName>
            </value>
            <value>
                <fullName>Apparent purchaser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/FormData__c.field-meta.xml
<CustomField>
    <fullName>FormData__c</fullName>
    <label>Form Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Application Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exemption - Charitable ... bodies</fullName>
            </value>
            <value>
                <fullName>Correction of error</fullName>
            </value>
            <value>
                <fullName>63(1) - $50 - fixed</fullName>
            </value>
            <value>
                <fullName>63(2) - variation to trust in will / intestacy</fullName>
            </value>
            <value>
                <fullName>55(1)(a)</fullName>
            </value>
            <value>
                <fullName>55(1)(b)</fullName>
            </value>
            <value>
                <fullName>54(2)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/Sub_Type_Data__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type_Data__c</fullName>
    <description>Used to store the selections from the Application Type Selection page</description>
    <label>Sub Type Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Meta_Data__c/Application_Meta_Data__c.object-meta.xml
<CustomObject>
    <label>Application Meta Data</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Meta_Data__c/fields/FormData__c.field-meta.xml
<CustomField>
    <fullName>FormData__c</fullName>
    <label>Form Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/sc_ApplicationCacheSelector.cls
public class sc_ApplicationCacheSelector {
    public static  List<Application_Cache__c> getApplicationCacheById(String accId ) {
        return [select Id, AppDataBeforeSubmit__c, Application_Meta_Data__c, Application_Meta_Data__r.Name, Application_Meta_Data__r.Label__c, FormData__c, Status__c,
            Label__c, Name, Sub_Type_Data__c from Application_Cache__c where id=: accId];
    }
    public static  List<Application_Cache__c> getApplicationCacheByName(String name ){
        return [select Id, AppDataBeforeSubmit__c, Application_Meta_Data__c, Application_Meta_Data__r.Name, Application_Meta_Data__r.Label__c, FormData__c, Status__c,
            Label__c, Name,Application_Type__c, Sub_Type__c, Section__c, Application_Meta_Data__r.Description__c, Sub_Type_Data__c from Application_Cache__c where name =: name];
    }
}