force-app/main/default/objects/Application_Cache__c/Application_Cache__c.object-meta.xml
<CustomObject>
    <description>Form Builder App</description>
    <label>Draft Application</label>
    <nameField>
        <label>Application Cache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Draft Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Cache__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Application Cache</relationshipLabel>
    <relationshipName>Application_Cache</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Meta_Data__c/Application_Meta_Data__c.object-meta.xml
<CustomObject>
    <label>Application Meta Data</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Meta_Data__c/Field_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains UI information for each field</description>
    <label>Field Meta Data</label>
    <nameField>
        <label>Field Meta Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/sc_ApplicationCacheService.cls
/***
 * Description: Used to be the staring point for the business logics for Application Cache(Draft Application)
 * Created By: Alvin Zhou
 * Date: 25/09/2018
*****/
public without sharing class sc_ApplicationCacheService {
    private static Set<String> draftWithOwnerUpdated = new Set<String>();
    private static Set<String> submittedDraftIds = new Set<String>();
    public class CacheException extends Exception {}
    /****
     * Used by ApplicationService - getApplicationMetaData
     * @Param: appId @Type: String
     * Description: if no results, throw an expcetion.
    *****/
    public static List<Application_Cache__c> getApplicationCacheByName(String appName) {
        List<Application_Cache__c> applicationCaches 
            = sc_ApplicationCacheSelector.getApplicationCacheByName(appName);
            
        if(applicationCaches.isEmpty()) {
            throw new CacheException(sc_GlobalConstants.ERROR_APP_CACHE_NOT_FIND + appName);
        }
        return applicationCaches;
    }
   
    /****
        Used to return card name => list of field meta data records
    ***/
    public static List<sc_CardFeed> getCardFeeds (String draftAppId) {
        List<Application_Cache__c> draftApps = sc_ApplicationCacheSelector.getApplicationCacheById(draftAppId);
        if(draftApps.isEmpty()) {
            return new List<sc_CardFeed>();
        }
        Application_Cache__c record = draftApps.get(0);
        List<String> appMetaDataIds = (List<String>) (new sc_ApplicationCacheDomain(draftApps)).getFieldValues('Application_Meta_Data__c');
        return sc_CardMetaDataService.getCardToFields(appMetaDataIds.get(0));
    }
    /******
        Used to return the card name and list of Field Meta Data records
    *****/
    public static Map<String, List<Field_Meta_Data__c>> getCardToFields (String draftAppId) {
        List<Application_Cache__c> draftApps = sc_ApplicationCacheSelector.getApplicationCacheById(draftAppId);
        if(draftApps.isEmpty()) {
            return new Map<String, List<Field_Meta_Data__c>> ();
        }
        Application_Cache__c record = draftApps.get(0);
        List<String> appMetaDataIds = (List<String>) (new sc_ApplicationCacheDomain(draftApps)).getFieldValues('Application_Meta_Data__c');
        Map<String, Map<String, List<Field_Meta_Data__c>>> appMetaToFieldMeta = sc_FieldMetaDataService.getFields(appMetaDataIds);
        return appMetaToFieldMeta.get(record.Application_Meta_Data__c);
    }

}