force-app/main/default/objects/Application_Cache__c/Application_Cache__c.object-meta.xml
<CustomObject>
    <description>Form Builder App</description>
    <label>Draft Application</label>
    <nameField>
        <label>Application Cache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Draft Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Cache__c/fields/AppDataBeforeSubmit__c.field-meta.xml
<CustomField>
    <fullName>AppDataBeforeSubmit__c</fullName>
    <description>Used to store the data before submit</description>
    <label>App Data Before Submit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Cache__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Application Cache</relationshipLabel>
    <relationshipName>Application_Cache</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Meta_Data__c/Application_Meta_Data__c.object-meta.xml
<CustomObject>
    <label>Application Meta Data</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Cache__c/Card_Cache__c.object-meta.xml
<CustomObject>
    <description>Form Builder App - Stores temp JSON</description>
    <label>Card Cache</label>
    <nameField>
        <label>Card Cache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Cache</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Cache__c/fields/Application_Cache__c.field-meta.xml
<CustomField>
    <fullName>Application_Cache__c</fullName>
    <label>Application Cache</label>
    <referenceTo>Application_Cache__c</referenceTo>
    <relationshipLabel>Card Cache</relationshipLabel>
    <relationshipName>Card_Cache</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Cache__c/fields/Card_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Card_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card Meta Data</label>
    <referenceTo>Card_Meta_Data__c</referenceTo>
    <relationshipLabel>Card Cache</relationshipLabel>
    <relationshipName>Card_Cache</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Meta_Data__c/Card_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains the section data for each card on an application</description>
    <label>Card Meta Data</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Card Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Meta_Data__c/fields/Application_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Application_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the Card to its application</description>
    <label>Application Meta Data</label>
    <referenceTo>Application_Meta_Data__c</referenceTo>
    <relationshipLabel>Card Meta Data</relationshipLabel>
    <relationshipName>Card_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Meta_Data__c/Field_Meta_Data__c.object-meta.xml
<CustomObject>
    <description>Contains UI information for each field</description>
    <label>Field Meta Data</label>
    <nameField>
        <label>Field Meta Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Meta Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Meta_Data__c/fields/Card_Meta_Data__c.field-meta.xml
<CustomField>
    <fullName>Card_Meta_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link Field to its card</description>
    <label>Card Meta Data</label>
    <referenceTo>Card_Meta_Data__c</referenceTo>
    <relationshipLabel>Field Meta Data</relationshipLabel>
    <relationshipName>Field_Meta_Data1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DraftCardService.cls
public class DraftCardService {
    public static void updateCardCachies(Card_Cache__c cardCache) {
        String appCacheId = cardCache.Application_Cache__c;
        List<Application_Cache__c> appCaches = sc_ApplicationCacheSelector.getApplicationCacheById(appCacheId);
        Application_Cache__c appCache = appCaches.get(0);
        String appMetaDataId = appCache.Application_Meta_Data__c;
        String cardMetaDataName = cardCache.Name;
        Map<String, Card_Cache__c> cardMetaId2Cache = (new CardCacheDomain(new List<Card_Cache__c>{cardCache})).getCardMeta2Cache();
        List<Field_Meta_Data__c> fieldMetaDatas = sc_FieldMetaDataSelector.getFieldMetaDataByAppIdToReview(appMetaDataId, cardMetaDataName);

        Map<String, List<Field_Meta_Data__c>> cardMetaId2FieldList = (new sc_FieldMetaDataDomain(fieldMetaDatas)).getCardId2FieldList();
        
        List<Card_Meta_Data__c> cardMetas = sc_CardMetaDataSelector.getCardsByAppIdAndName(appMetaDataId, cardMetaDataName);

        Map<String, SObject> objs = new Map<String, SObject>();
        if(appCache.AppDataBeforeSubmit__c != null)
            objs = (Map<String, SObject>) JSON.deserialize(appCache.AppDataBeforeSubmit__c, 
                Map<String, SObject>.class);
        objs = (new CardMetaDataDomain(cardMetas)).convert2AppData(cardMetaId2Cache, cardMetaId2FieldList, objs);
        appCache.AppDataBeforeSubmit__c = JSON.serialize(objs);
        update appCache;

    }
    
}