force-app/main/default/objects/TravelApproval__c/TravelApproval__c.object-meta.xml
<CustomObject>
    <description>PacPoint-AC120419 - Created for DCCA Travel Approval phase 1</description>
    <label>Travel Approval</label>
    <nameField>
        <displayFormat>TA - {000000}</displayFormat>
        <label>Travel Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelApproval__c/fields/BusinessOnlyReturnDate__c.field-meta.xml
<CustomField>
    <fullName>BusinessOnlyReturnDate__c</fullName>
    <description>PacPoint-AC120919 - Created for DCCA Travel Approval phase 1</description>
    <inlineHelpText>Authorized date of return to home island.</inlineHelpText>
    <label>Business Only Return Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/Final_Report_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Final_Report_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mandatory checkbox to be checked before SOCT status can be to SOCT completed</description>
    <inlineHelpText>Final Report required to be uploaded for all Out-of-State travel</inlineHelpText>
    <label>Final Report Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/NameOfTraveler__c.field-meta.xml
<CustomField>
    <fullName>NameOfTraveler__c</fullName>
    <description>PacPoint-JW120519 - Created for DCCA Travel Approval phase 1</description>
    <label>Name of Traveler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/TravelApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>TravelApprovalStatus__c</fullName>
    <description>PacPoint-AC121319 - Created for DCCA Travel Approval phase 1</description>
    <label>Travel Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>APD Sent to Fiscal</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/TravelerEmail__c.field-meta.xml
<CustomField>
    <fullName>TravelerEmail__c</fullName>
    <description>PacPoint-AC092520 - Case# 10826 - Created for DCCA Travel Approval</description>
    <label>Traveler Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/TravelType__c.field-meta.xml
<CustomField>
    <fullName>TravelType__c</fullName>
    <description>PacPoint-AC120519 - Created for DCCA Travel Approval phase 1</description>
    <label>Travel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OCONUS (Foreign or Alaska)</fullName>
            </value>
            <value>
                <fullName>CONUS (Contiguous 48 States)</fullName>
            </value>
            <value>
                <fullName>Intra-state Same Day</fullName>
            </value>
            <value>
                <fullName>Intra-state Overnight Travel</fullName>
            </value>
            <value>
                <fullName>Intra-State</fullName>
                <isActive>false</isActive>
                <label>Intra-State</label>
            </value>
            <value>
                <fullName>Out-of-State</fullName>
                <isActive>false</isActive>
                <label>Out-of-State</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TravelApprovalValidator.cls
public class TravelApprovalValidator {
    @AuraEnabled
    public static List<TravelApproval__c> validatedTravelApprovals(String recordId){
        try {
            List<TravelApproval__c> approvals = [Select Id, Name, NameOfTraveler__c, TravelerEmail__c, Final_Report_Uploaded__c from TravelApproval__c where Id =: recordId ];
            if(!approvals.isEmpty()) {
                TravelApproval__c record = approvals.get(0);
                String travelerName = record.NameOfTraveler__c;
                String travelerEmail = record.TravelerEmail__c;
                List<TravelApproval__c> pendingApprovalRecords = [
                    Select Id, BusinessOnlyReturnDate__c, Name from TravelApproval__c 
                        where TravelType__c IN ('Out-of-State', 'OCONUS (Foreign or Alaska)', 'CONUS (Contiguous 48 States)') and NameOfTraveler__c =: travelerName and TravelerEmail__c =: travelerEmail and Final_Report_Uploaded__c = false and BusinessOnlyReturnDate__c < LAST_N_DAYS:30 AND TravelApprovalStatus__c != 'Cancelled'];
                return pendingApprovalRecords;
            }
            return new List<TravelApproval__c>();   
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string redirectURL(String recordId, String dst){
        try {
            PageReference pr = Page.dsfs__DocuSign_CreateEnvelope;
            pr.getParameters().put('SourceID', recordId);
            pr.getParameters().put('DST', dst);
            return pr.getUrl();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}