force-app/main/default/objects/FileDetails__c/FileDetails__c.object-meta.xml
<CustomObject>
    <description>PacPoint-JB103118 - Created for BREG phase 1:  Stores file header information</description>
    <label>File Details</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>File Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelApproval__c/TravelApproval__c.object-meta.xml
<CustomObject>
    <description>PacPoint-AC120419 - Created for DCCA Travel Approval phase 1</description>
    <label>Travel Approval</label>
    <nameField>
        <displayFormat>TA - {000000}</displayFormat>
        <label>Travel Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelApproval__c/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <description>PacPoint-JW120519 - Created for DCCA Travel Approval phase 1</description>
    <label>Contact Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/ContactPersonEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactPersonEmail__c</fullName>
    <description>PacPoint-CaBe02052024</description>
    <label>Contact Person Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TravelApproval__c/fields/NameOfTraveler__c.field-meta.xml
<CustomField>
    <fullName>NameOfTraveler__c</fullName>
    <description>PacPoint-JW120519 - Created for DCCA Travel Approval phase 1</description>
    <label>Name of Traveler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerTest.cls
@isTest
private class ContentDocumentLinkTriggerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createExams();
    }
    public static testmethod void testCreateContentDocumentLinks() {
        
        TravelApproval__c record = new TravelApproval__c();
        record.NameOfTraveler__c = 'test record';
        record.ContactPerson__c = 'Name 1';
        record.ContactPersonEmail__c = 'testrecord2@sample.com';
        insert record;
        dsfs__DocuSign_Status__c statusRec = new dsfs__DocuSign_Status__c();
        statusRec.TravelApproval__c = record.Id;
        insert statusRec;

        String docName = 'test.pdf';
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.VersionData = Blob.valueOf('Test Data');
        cv.Title = docName;
        cv.PathOnClient = '/'+docName;
        
        insert cv;
        
        // First get the content document Id from ContentVersion
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;

        Test.startTest();
        //Create ContentDocumentLink
        ContentDocumentLink cDe = new ContentDocumentLink();
        cDe.ContentDocumentId = conDoc;
        cDe.LinkedEntityId = statusRec.Id;
        cDe.ShareType = 'I';
        cDe.Visibility = 'AllUsers';
        insert cDe;

    }
    @isTest
    private static void testBeforeDeleteInsert() {
        Test.startTest();
        GlobalConstants.SYSTEMADMIN = 'Test Admin';
        FileDetails__c fileDetail = [Select Id from FileDetails__c];
        List<ContentDocumentLink> links = [Select ContentDocumentId, Id from ContentDocumentLink where LinkedEntityId =: fileDetail.Id];

        try{   
            delete links;
        } catch(Exception ex) {

        }
        try{
            //Create ContentDocumentLink
            ContentDocumentLink cDe = new ContentDocumentLink();
            cDe.ContentDocumentId = links.get(0).Id;
            cDe.LinkedEntityId = fileDetail.Id;
            cDe.ShareType = 'I';
            cDe.Visibility = 'AllUsers';
            insert cDe;
        } catch(Exception ex) {

        }
    }
}