force-app/main/default/objects/FileDetails__c/FileDetails__c.object-meta.xml
<CustomObject>
    <description>PacPoint-JB103118 - Created for BREG phase 1:  Stores file header information</description>
    <label>File Details</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>File Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FileDetails__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-JB111618 - Created for BREG phase 1</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>File Details</relationshipLabel>
    <relationshipName>File_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FileDetails__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>PacPoint-MV010419 - Created for BREG phase 1</description>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exam Documents</fullName>
            </value>
            <value>
                <fullName>Exam Deficiencies</fullName>
            </value>
            <value>
                <fullName>SEB Clerical</fullName>
            </value>
            <value>
                <fullName>SEB Investigation</fullName>
            </value>
            <value>
                <fullName>SEB Legal</fullName>
            </value>
            <value>
                <fullName>SEC - Broker-Dealer</fullName>
            </value>
            <value>
                <fullName>SEC - Broker-Dealer Agent</fullName>
            </value>
            <value>
                <fullName>SEC - By Qualification</fullName>
            </value>
            <value>
                <fullName>SEC - Franchise</fullName>
            </value>
            <value>
                <fullName>SEC - Investment Adviser</fullName>
            </value>
            <value>
                <fullName>SEC - Investment Adviser Representative</fullName>
            </value>
            <value>
                <fullName>SEC - Issuer Dealer</fullName>
            </value>
            <value>
                <fullName>SEC - Issuer Dealer Agent</fullName>
            </value>
            <value>
                <fullName>SEC - Model Accredited Investor</fullName>
            </value>
            <value>
                <fullName>SEC - Mutual Fund</fullName>
            </value>
            <value>
                <fullName>SEC - Regulation A</fullName>
            </value>
            <value>
                <fullName>SEC - Regulation D</fullName>
            </value>
            <value>
                <fullName>SEC - SCOR</fullName>
            </value>
            <value>
                <fullName>SEB Complaint</fullName>
            </value>
            <value>
                <fullName>SEC - Unit Investment Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FileDetails__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-JB111618 - Created for BREG phase 1</description>
    <label>Filing</label>
    <referenceTo>Filing__c</referenceTo>
    <relationshipLabel>File Details</relationshipLabel>
    <relationshipName>File_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FileDetails__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-JB110718 - Created for BREG phase 1</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accredited investor notice</fullName>
            </value>
            <value>
                <fullName>Affidavit</fullName>
            </value>
            <value>
                <fullName>Annual financial statements</fullName>
            </value>
            <value>
                <fullName>Application for Registration of Securities by Qualification</fullName>
            </value>
            <value>
                <fullName>Attorney&apos;s opinion</fullName>
            </value>
            <value>
                <fullName>Attorney Exhibits</fullName>
            </value>
            <value>
                <fullName>Attorney Work Product</fullName>
            </value>
            <value>
                <fullName>Audited financial statements</fullName>
            </value>
            <value>
                <fullName>Bank Records</fullName>
            </value>
            <value>
                <fullName>By Qualification Application Attachment</fullName>
            </value>
            <value>
                <fullName>Certified copy of Issuer&apos;s articles of organization</fullName>
            </value>
            <value>
                <fullName>Certified Corporate Resolution</fullName>
            </value>
            <value>
                <fullName>Company Notice Filing</fullName>
            </value>
            <value>
                <fullName>Complainant Documents</fullName>
            </value>
            <value>
                <fullName>Consent by accountant</fullName>
            </value>
            <value>
                <fullName>Consent by counsel</fullName>
            </value>
            <value>
                <fullName>Consent by tax adviser</fullName>
            </value>
            <value>
                <fullName>Consent to Service of Process</fullName>
            </value>
            <value>
                <fullName>Consent to Service of Process and Acknowledgement</fullName>
            </value>
            <value>
                <fullName>Consent to service of process and corporate resolution</fullName>
            </value>
            <value>
                <fullName>Consent to Service of Process By Issuer of or Dealer in Securities</fullName>
            </value>
            <value>
                <fullName>Consent w/acknowledgement</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Copy of advertising</fullName>
            </value>
            <value>
                <fullName>Copy of general announcement</fullName>
            </value>
            <value>
                <fullName>Copy of Prospectus</fullName>
            </value>
            <value>
                <fullName>Copy of resolutions by directors</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Deficiency Correction - 1</fullName>
            </value>
            <value>
                <fullName>Deficiency Correction - 2</fullName>
            </value>
            <value>
                <fullName>Memorandum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FileDetails__c/recordTypes/SEB.recordType-meta.xml
<RecordType>
    <fullName>SEB</fullName>
    <active>true</active>
    <description>PacPoint-MV010819 - Created for BREG phase 1</description>
    <label>SEB</label>
</RecordType>

force-app/main/default/objects/Filing__c/Filing__c.object-meta.xml
<CustomObject>
    <description>PacPoint-IC100518 - Created for BREG phase 1</description>
    <label>Filing</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Filing__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PacPoint-IC0100518 - Created for BREG phase 1</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Accounts that are set as SEB/SEC accounts can be selected.</errorMessage>
        <filterItems>
            <field>Account.SEBSEC__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Filing</relationshipLabel>
    <relationshipName>Filing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Filing__c.field-meta.xml
<CustomField>
    <fullName>Filing__c</fullName>
    <description>PacPoint-JB102418 - Created for BREG phase 1For display on page</description>
    <formula>CASE( RecordType.DeveloperName, &apos;Brokerdealer&apos;, &apos;Broker Dealer&apos;, &apos;ByQualification&apos;, &apos;By Qualification&apos;, &apos;Franchise&apos;, &apos;Franchise&apos;, &apos;IssuerDealer&apos;, &apos;Issuer-Dealer&apos;, &apos;InvestmentAdvisor&apos;, &apos;Investment Advisor&apos;, &apos;ModelAccreditedInvestor&apos;, &apos;Model Accredited Investor&apos;, &apos;MutualFund&apos;, &apos;Mutual Fund&apos;, &apos;RegulationA&apos;, &apos;Regulation A&apos;, &apos;RegulationD&apos;, &apos;Regulation D&apos;, &apos;SmallCompanyOfferingRegistrationSCOR&apos;, &apos;Small Company Offering Registration (SCOR)&apos;, &apos;Unknown&apos;)</formula>
    <label>Filing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/FiscalYearEnd__c.field-meta.xml
<CustomField>
    <fullName>FiscalYearEnd__c</fullName>
    <description>PacPoint-IC101118 - Created for BREG phase 1</description>
    <label>Fiscal Year End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/ShowGenericUploadButton__c.field-meta.xml
<CustomField>
    <fullName>ShowGenericUploadButton__c</fullName>
    <description>PacPoint-MV012819 - Created for BREG phase 1 to display the button on the community</description>
    <formula>IF(
   ISPICKVAL(Status__c,&quot;Deficiency Letter Sent&quot;) , 
   true, 
   false
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Show Generic Upload Button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>PacPoint-IC100918 - Created for BREG phase 1</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Filing Received</fullName>
            </value>
            <value>
                <fullName>Assigned for Review</fullName>
            </value>
            <value>
                <fullName>Review in Progress</fullName>
            </value>
            <value>
                <fullName>Deficiency Letter Sent</fullName>
            </value>
            <value>
                <fullName>Deficiency Response Received</fullName>
            </value>
            <value>
                <fullName>Reviewing Deficiency Response</fullName>
            </value>
            <value>
                <fullName>Filing Completed</fullName>
            </value>
            <value>
                <fullName>Filing Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filing__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>PacPoint-MV060519 - Created for BREG phase 1 to be used to display the name of the record type on the page layout as read-only due salesforce&apos;s bug:W-3270471</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FileDetailCreatorControllerTest.cls
/*
 * ___________________________________________________________________________________
 * Test class for FileDetailCreatorController
 * __________________________________________________________________________________
 * PacPoint-CL013019 - Created for BREG phase 1
 * __________________________________________________________________________________
 * Initial implementation
 *
 * @author Chris Loyola - PacificPointCorp
 *
 * @created 01/30/2019
 * __________________________________________________________________________________
 */
@IsTest
private class FileDetailCreatorControllerTest {
    @TestSetup
    static void setup() {
        Account acct = new Account(
            Name = 'Test Accont',
            SEBSEC__c = true
        );
        insert acct;

        Filing__c filing = new Filing__c();
        filing.FiscalYearEnd__c = Date.today().addYears(1);
        filing.Account__c = acct.Id;
        filing.Status__c = 'Deficiency Letter Sent';
        insert filing;

        RecordTypeInfo fdSeb = FileDetails__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('SEB');
        FileDetails__c fd = new FileDetails__c();
        fd.RecordTypeId = fdSeb.getRecordTypeId();
        fd.Category__c = 'SEB Clerical';
        fd.Type__c = 'Memorandum';
        insert fd;
    }

    @isTest
    static void testSaveRecords() {
        Filing__c filing = [SElECT Id, ShowGenericUploadButton__c FROM Filing__c where ShowGenericUploadButton__c = true];
        RecordTypeInfo fdSeb = FileDetails__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('SEB');
        FileDetails__c fd = new FileDetails__c();
        fd.RecordTypeId = fdSeb.getRecordTypeId();
        fd.Category__c = 'SEB Clerical';
        fd.Type__c = 'Memorandum';
        fd.Filing__c = filing.Id;

        FileDetailCreatorController.saveRecord('test', fd);
    }

    @isTest
    static void testSaveRecordsException() {
        RecordTypeInfo fdSeb = FileDetails__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('SEB');
        FileDetails__c fd = new FileDetails__c();
        fd.RecordTypeId = fdSeb.getRecordTypeId();
        fd.Category__c = 'SEB Clerical';
        fd.Type__c = 'Memorandum';
        FileDetailCreatorController.checkIfFileDetail(fd.Id);
        FileDetailCreatorController.saveRecord('test', fd);
    }

    @IsTest
    static void getAvailableRecordTypesTest() {
        List<FileDetailCreatorController.AvailableRecordType> rts =
                FileDetailCreatorController.getAvailableRecordTypes();
        List<RecordTypeInfo> rtis = FileDetails__c.sObjectType.getDescribe().getRecordTypeInfos();
        System.assertEquals(rts.size(), rtis.size() - 1);
    }

    @IsTest
    static void isVisibleTest() {
        Filing__c filing = [SElECT Id, ShowGenericUploadButton__c FROM Filing__c];

        Boolean isVisibile = FileDetailCreatorController.isVisible(filing.Id, 'ShowGenericUploadButton__c');
        System.assertEquals(filing.ShowGenericUploadButton__c, isVisibile);
    }

    @IsTest
    static void deleteTest() {
        FileDetails__c fd = [SElECT Id FROM FileDetails__c];
        FileDetailCreatorController.deleteFileDetail(fd.Id);

        List<FileDetails__c> fds = [SELECT Id FROM FileDetails__c];

        System.assert(fds.isEmpty());
    }
}